### ISSUE TITLE
Bug with submit

### ISSUE THREAD

**Issue by DSergioD** [einpraegsam/powermail#10]
Hi, we have bug with submit, if you have all stuff on form full and click on submit button this need to much before send.
This is the page: http://www.residenz-josefstadt.at/kontakt/
Do you know where is the problem ?

Tnx Sergio

**Comment by einpraegsam** [comment]
What does need to much mean?

**Comment by DSergioD** [comment]
Never mind but thanks anyway, it's fixed.
