### ISSUE TITLE
Start- and Endtime fields are broken in TYPO3 7.6

### ISSUE THREAD

**Issue by einpraegsam** [einpraegsam/powermail#101]
That is related to a change for TYPO3 8.7 in TCA configuration.
see https://github.com/einpraegsam/powermail/commit/3ad0cd3307ec8c415f43d903ebf6b97e9746c50b#commitcomment-22378836 for details

**Comment by chrisprog20** [comment]
For this I just included a working fix for the respective tables.
Here my fix for the TCA definition of the table "tx_powermail_domain_model_field"

`// fix for TYPO3 < 8: in TYPO3 7 and lower there is no renderType for ['config']['type'] = 'input'
if (\TYPO3\CMS\Core\Utility\VersionNumberUtility::convertVersionNumberToInteger(TYPO3_version) < 8000000) {
    $GLOBALS['TCA']['tx_powermail_domain_model_field']['columns']['starttime']['config']['renderType'] = '';
    $GLOBALS['TCA']['tx_powermail_domain_model_field']['columns']['endtime']['config']['renderType'] = '';
}
`

**Comment by einpraegsam** [comment]
Fixed in develop. Ready for upcoming version.

**Comment by chrisprog20** [comment]
Thank you! :)
