### ISSUE TITLE
static info tables cn_short_CODE

### ISSUE THREAD

**Issue by Naberd** [einpraegsam/powermail#105]
have site in multiple languages at a powermail country field i set language  but it seem powermail displays only official name instead of localized.

right now fixed it with code :

		$language = $GLOBALS['TSFE']->sys_language_uid;

		switch($language){
			case 1: $short = "nl";
			break;
			case 2: $short = "de";
			break;
			case 4: $short = "es";
			break;
			case 5: $short = "fr";
			break;
			case 6: $short = "it";
			break;
			case 15: $short = "ru";
			break;
			default: $short = "en";
			break;
		}
		
		if($short != ''){
			$result = $GLOBALS['TYPO3_DB']->exec_SELECTgetRows("cn_iso_3, cn_short_".$short, "static_countries", "", "", "cn_short_".$short." asc");

			foreach($result as $country){
				$iso = $country['cn_iso_3'];
				$key = "cn_short_".$short;
				$name = $country[$key];
				if($name == '') continue;
				$ctr[$iso] = $name;
			}
		}

maybe i did something wrong with setup of powermail but at version 6.x of typo3 i didn't have this problem with older version of powermail.

**Comment by einpraegsam** [comment]
Your information are not complete but I think I know what you're meaning.
If you're using powermail together with static_info_tables (and e.g. static_info_tables_de) you can use fields of type country for a list of all countries.

The related partial is originally available here: EXT:powermail/Resources/Private/Partials/Form/Field/Country.html

There you will find the select field:
```
<f:form.select
				property="{field.marker}"
				options="{vh:Form.Countries(key:'isoCodeA3',value:'officialNameLocal',sortbyField:'isoCodeA3',sorting:'asc')}"
				prependOptionLabel="{f:translate(key:'pleaseChoose')}"
				class="powermail_country {settings.styles.framework.fieldClasses} {vh:Validation.ErrorClass(field:field, class:'powermail_field_error')}"
				value="{vh:Misc.PrefillField(field:field)}"
				additionalAttributes="{vh:Validation.ValidationDataAttribute(field:field)}"
				id="powermail_field_{field.marker}" />
```

The options are given from a viewhelper:
```
{vh:Form.Countries(key:'isoCodeA3',value:'officialNameLocal',sortbyField:'isoCodeA3',sorting:'asc')}
```

As you may know now - you can set any field from the table. Default value for label field is `isoCodeA3`
