### ISSUE TITLE
An error occur when we submit the form.

### ISSUE THREAD

**Issue by sonal36** [einpraegsam/powermail#107]
Hello i faced this error when the form submitted.
> http://prntscr.com/fi3e4o

Platform used - 
typo3 version - 8.7.1
powermail version - 3.19.0

**Comment by sonal36** [comment]
And we can solved that issue by adding this line at LocalConfiguration.php file.

`'DB' => [
'Connections' => [
'Default' => [
'initCommands' => 'SET SESSION sql_mode=\'\'',
],
],
],`

**Comment by einpraegsam** [comment]
Pls see https://forge.typo3.org/issues/81043 - this seems to be a core bug together with mysql strict_mode

**Comment by sonal36** [comment]
Thank you ...
