### ISSUE TITLE
setAnswers() error while submitting mail form

### ISSUE THREAD

**Issue by jackd248** [einpraegsam/powermail#112]
Hello,

I get the following error when submitting the mail form:

![error](https://user-images.githubusercontent.com/4558190/27687565-99e79684-5cd7-11e7-9d6f-f1a37ccc14d5.png)

typo3 version - 7.6.19
powermail version - 3.19.0

**Comment by einpraegsam** [comment]
That's a bit strange. It seems that there are no answers that can be passed to the given mail. I can image some misconfiguration/bugs that are related to this but I didn't saw this message before.
Please check if there are no redirects on submit (can happen if wrong baseURL or absRefPrefix is set or if there is a redirect on serverside from http:// to https:// or so).
You should also check if the names of the fields are correct filled in HTML source - like `tx_powermail_pi1[field][markername]`.
Can you give me some feedback to this issue?

**Comment by jackd248** [comment]
There is actually no redirect configured. The HTML source seems to be valid so far. I used the built-in templates/partials and also went down to powermail version 3.0.0 with no solution. 
Do you have any other idea?

**Comment by einpraegsam** [comment]
No, nothing without seeing the page in frontend so far.

**Comment by einpraegsam** [comment]
Sorry, can't help you at the moment
