### ISSUE TITLE
<a> tag links not rendered absolute in mail

### ISSUE THREAD

**Issue by rvollebregt** [einpraegsam/powermail#114]
Currently only link tags are parsed as absolute links:

https://github.com/einpraegsam/powermail/blob/develop/ext_typoscript_setup.txt#L20

Though, <a> tags can also be present in RTE content used in emails.
https://github.com/TYPO3/TYPO3.CMS/blob/d0f87bf9f86e33aa741ab9c56172cacce86efebe/typo3/sysext/fluid_styled_content/Configuration/TypoScript/Helper/ParseFunc.txt#L24

Can I submit a PR with the suggested addition?

`lib.parseFunc_powermail.tags.a.typolink.forceAbsoluteUrl = 1`

**Comment by einpraegsam** [comment]
Of course, just offer a PR with a small description which problems are solved with this and how to reproduce a failure.
