### ISSUE TITLE
Problem with date field

### ISSUE THREAD

**Issue by lstephanws** [einpraegsam/powermail#116]
Hello,

When we use date field, we have the following error when submitting the form :
![image](https://user-images.githubusercontent.com/28351269/27906393-a5be24a2-6243-11e7-9220-2c3f62579baf.png)

If we change field type with input text, no error.

TYPO3 version - 7.6.19
powermail version - 3.8.0 (I tried update to 3.19.0 but the problem is still here)

Thanks

**Comment by einpraegsam** [comment]
I really need some more information on this issue. There is a long testparcours that have to be solved before every release. And of course date-fields are also tested (german and english). 
Please insert the HTML-source of the rendered Date-Field in the form and an example value of your dateformat. In addition I need all your TypoScript-Settings related to datefields.

**Comment by einpraegsam** [comment]
No feedback, I will close this issue
