### ISSUE TITLE
Partial for `*` on mandatory fields?

### ISSUE THREAD

**Issue by stroebjo** [einpraegsam/powermail#117]
Hello,

I changed mandatory sign, for this I copied all Field templates into my custom extension to overwrite the original ones. The only change I made in each template was to change the `<f:if condition="{field.mandatory}"><span class="mandatory">*</span></f:if>` to my needs. 

Maybe it would be a good idea to put this into an partial of it's own?

**Comment by einpraegsam** [comment]
Yes, would be a good idea.
Nevertheless - this is a breaking change and should be done in the next master version because every field partial would be related to this.
