### ISSUE TITLE
Allow selection of multiple fe_groups

### ISSUE THREAD

**Issue by crochelt** [einpraegsam/powermail#118]
The option to select a fe_group as receiver is great. It would be nice to be able to select multiple fe_groups.
Is there an easy way to do that?

**Comment by einpraegsam** [comment]
No, not at the moment. Maybe a workarround with predefined receivers could help: https://docs.typo3.org/typo3cms/extensions/powermail/ForAdministrators/BestPractice/DynamicReceiver/Index.html
