### ISSUE TITLE
Mehere Formulare führen zu Fehler

### ISSUE THREAD

**Issue by thomasherr** [einpraegsam/powermail#119]
Wenn ich es in Englisch versuchen soll, bitte eine Information

Ich benutze Typo3 7.6.20 und Powermail 3.20.0

Ich habe auf einer Seite mehrere Formulare im Einsatz. An einer (dem ersten Formular) geht alles soweit gut. Wenn ich auf weiteren Seiten mit Powermail:frontend Formulare einfüge, funktioniert die Funktion „ändern“ nicht. Ich erhalte die Fehlermeldung: The action "edit" (controller "Output") is not allowed by this plugin. Please check TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin() in your ext_localconf.php

Leider kann ich damit nichts anfangen. Was muss ich bei Powermail anders konfigurieren, damit ich mehrere Formulare benutzen kann?

Vielen Dank für die Hilfe.

**Comment by einpraegsam** [comment]
In english please. Maybe other user have the same problem.

At the moment it's not allowed to have more Pi2 plugins on the same page. Probably a `plugin.tx_powermail.callDefaultActionIfActionCantBeResolved = 1` could help (untested).

**Comment by thomasherr** [comment]
I apologize for asking the same question, but I could not find anything. And, this also in German.


Nevertheless thanks for the quick response. The tip does not work. Is it foreseeable that different forms can be used in several places in the future? It is not clear to me why I can save different forms at all.

best regards

Thomas

**Comment by einpraegsam** [comment]
You can use more then only one form on a page. But you mixed it with some Pi2 or so.
Example with more forms that will be tested automaticly before every release: http://powermail.in2code.ws/index.php?id=54

**Comment by thomasherr** [comment]
The capture is not a problem. The function change at Powermail_frontend prepares me the problem.
If I insert this a second time it comes to the error.
