### ISSUE TITLE
Every time empty last Entity (Email) in Module/List.html

### ISSUE THREAD

**Issue by olegkarun** [einpraegsam/powermail#120]
powermail/Resources/Private/Templates/Module/List.html
In template last Entity all time empty. When use <f:debug> - the same. Last  Entity in array '{mailsPage}'  has empty Email data. I see Entity in list with controls buttons. Entity count is right, but last havent data.

Default TS, Original Templates. TYPO3 8.7.1, Powermail 3.20.0

Powermail Check
Function-Test Section -- ALL GREEN

**Comment by einpraegsam** [comment]
I don't understand what's exactly the problem. What do you mean with last entity? When and where does the error come up? A screenshot could probably help me.

**Comment by olegkarun** [comment]
sure,
![powermail_module_empty_mail](https://user-images.githubusercontent.com/3882942/28454539-4e3f74ca-6e04-11e7-8ab4-5a3dfc27e44a.jpg)

**Comment by Hobokens** [comment]
I have the same problem with several mail listings on different projects.

**Comment by rpflamm** [comment]
I have the same Issue, but Its not only at the last mail.

![powermail missing field data 1](https://user-images.githubusercontent.com/4660651/28668240-37208606-72cf-11e7-832b-5ec21b88257a.png)

![powermail missing field data 2](https://user-images.githubusercontent.com/4660651/28668246-3befeaf0-72cf-11e7-8729-ea8ee852f7b4.png)

If I edit the entry with missing data I got all things to see.

In the Database all entries look the same, no differents (except user input).

An debug on the QueryResult (with filtered by form):

![powermail missing field data 3](https://user-images.githubusercontent.com/4660651/28668377-b356de32-72cf-11e7-819e-ee77ac3b19ce.png)

**Comment by Patta** [comment]
i can confirm this issue. 

sometimes mails are also sent multiply times, but i think this is a [user issue](https://github.com/einpraegsam/powermail/commit/d5ea50cdab058b7a66c9be6af1e566261dcc0711) :)

**Comment by einpraegsam** [comment]
Thx for the fix. It's merged in develop branch and ready for the upcoming release.
