### ISSUE TITLE
Make sender email of spam admin notifications configurable

### ISSUE THREAD

**Issue by cumuru** [einpraegsam/powermail#121]
This is needed if you use e.g. SMTP as mail transport and your mail server limits outgoing mails to existing addresses, maybe even to domains that are different from the domain TYPO3‘s running on.
I propose a TypoScript setting (without constant as it‘s not needed often) that simply overrides the default which stays as is.
I‘ll provide a PR which does exactly this.

**Comment by einpraegsam** [comment]
Thx for the pull request. I think this could be a useful change. I'm going to check your changes as soon as I have time for it.
Beside that: Spam detection can also be logged into a file.

**Comment by cumuru** [comment]
Thanks, no sweat! We patched the affected installation for now. I‘d just like to get rid of the patch in the long run.
File logging is a nice feature but doesn‘t help too much if you want to spot false positives promptly.

**Comment by einpraegsam** [comment]
Merged to develop branch - ready for upcoming release
