### ISSUE TITLE
Adjust main.pid via TypoScript userFunc

### ISSUE THREAD

**Issue by cweiske** [einpraegsam/powermail#123]
It would be nice if there was a way to adjust the page id under which mails get saved with own PHP code, e.g. by configuring a TypoScript userFunc.

Currently this is not supported, see https://docs.typo3.org/typo3cms/extensions/powermail/ForDevelopers/UserfuncsWithCobject/Index.html.

----

I worked around that by connecting the signal `In2code\Powermail\Controller\FormController::createActionBeforeRenderView` to a class that extends `FormController` (so that I can access the protected `$settings` property) and set `main.pid` there now. But that's not .. nice.

**Comment by einpraegsam** [comment]
Thx for your idea. At the moment I don't have time for such features.
