### ISSUE TITLE
Add signal slot to add custom variables to RTE content

### ISSUE THREAD

**Issue by maechler** [einpraegsam/powermail#124]
Please add a signal slot to easily add custom variables to the RTE field in the `VariablesViewHelper`. Currently only field labels and values can be used apart from `{powermail_all}`. We have a use case where we want to use a custom variable in the RTE, e.g. `{some_db_value}`, that is being field from the database by some custom rules.

Where to add the signal slot: 
https://github.com/einpraegsam/powermail/blob/develop/Classes/ViewHelpers/Misc/VariablesViewHelper.php#L75-L76

It would be nice to be able to add variables to the template. Similar to what we already have here: https://github.com/einpraegsam/powermail/blob/develop/Classes/Domain/Service/SendMailService.php#L391

**Comment by Patta** [comment]
@maechler maybe you can use a prefill variable with custom value from typoscript. And use this variable in a hidden field and as RTE variable.

_Sent from my OnePlus ONEPLUS A3010 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by maechler** [comment]
@Patta Thanks for your response! I already solved it with a `str_replace(...)` call on the email body in this signal slot: https://github.com/einpraegsam/powermail/blob/develop/Classes/Domain/Service/SendMailService.php#L391

This way the editor does not have to add extra fields. But I still think it would be nice to have such a signal slot to not have to use `str_replace(...)`.

**Comment by einpraegsam** [comment]
Pls change the template files and add your own Variables ViewHelper which could be extended by the original one.
