### ISSUE TITLE
Powermail_Frontend Editview: no submit possible when mandatory fields are not in list of Fields to edit

### ISSUE THREAD

**Issue by vivien-lindemann-gfz** [einpraegsam/powermail#126]
I placed the **Powermail_Frontend** plugin on the page and configured the **Editview** as follows:

I set special fields to edit, not all, that means the select box is not empty (all fields). 
In the unselected fields (Available Items) are some that are marked as mandatory.

When I try to submit the edit/update form, there are errors that these mandatory fields are required.

I could solve it by `plugin.tx_powermail.settings.setup.validation.server = 0`, but I don’t want to stop the serverside validation.

**Comment by einpraegsam** [comment]
Correct, this is a missing feature at the moment.
