### ISSUE TITLE
html code in field type check

### ISSUE THREAD

**Issue by derBoogie** [einpraegsam/powermail#129]
Hi,

sometimes it's neccessary to use html code in field type check, i.e. to confirm terms of use.
For this purpose the option value is: "I confirm that I have read and understood the <a href="http://mydomain.tld/terms-of-use.html">terms of use</a> and agree with them.

The problem is, that the html code is parsed through htmlSpecialChars in receiver email and sender email.

Is there a possibility to deactivate the htmlSpecialChars function for a specific marker or marker type "check" in the powermail_all array?

**Comment by einpraegsam** [comment]
This is already working (tested with T3 8 and powermail 3.20):

<img src="https://box.everhelper.me/attachment/1037069/84725fb7-0b3e-4c40-b52e-29d7620777bb/262407-i9dsuFHXLQfb6dEu/screen.png" />

<img src="https://box.everhelper.me/attachment/1037071/84725fb7-0b3e-4c40-b52e-29d7620777bb/262407-NHZJ945UrWA051yV/screen.png" />

**Comment by Patta** [comment]
@derBoogie i think you need this constant: `plugin.tx_powermail.settings.misc.htmlForHtmlFields = 1`

**Comment by derBoogie** [comment]
@Patta thanks for the hint, but this constant affects only the field of type html and not the field of type check.
I'm using TYPO3 6.2 and Powermail 2.25.2, which is the last Powermail version for TYPO3 6.2.

**Comment by derBoogie** [comment]
@einpraegsam sorry, but my TYPO3 version is 6.2 with Powermail 2.25.2 (the last Powermail version for TYPO3 6.2).

My current workaround is:

```
plugin.tx_powermail.settings.setup {
  manipulateVariablesInPowermailAllMarker {
    receiverMail {
      termsofuse = TEXT
      termsofuse.value = I confirm that I have read and understood the <a href="http://www.mydomain.tld/terms-of-use.html">terms of use</a> and agree with them.
    }
    senderMail {
      termsofuse = TEXT
      termsofuse.value = I confirm that I have read and understood the <a href="http://www.mydomain.tld/terms-of-use.html">terms of use</a> and agree with them.
    }
  }
}
```

Better wolud be to get the field value, like this:

```
plugin.tx_powermail.settings.setup {
  manipulateVariablesInPowermailAllMarker {
    receiverMail {
      termsofuse = TEXT
      termsofuse.data = field:value
    }
    senderMail {
      termsofuse = TEXT
      termsofuse.data = field:value
    }
  }
}
```

but this doesn't work as desired, because the value is somehow cranky.

**Comment by Patta** [comment]
@derBoogie you should update asap.
