### ISSUE TITLE
missing {settings.styles.framework.fieldClasses} in File.html

### ISSUE THREAD

**Issue by scheibome** [einpraegsam/powermail#131]
I miss the variable {settings.styles.framework.fieldClasses} in the Partials/Form/Field/File.html on line 13.

**Comment by einpraegsam** [comment]
I'm not sure if this is correct or not.
Following the instructions of bootstrap (see http://getbootstrap.com/css/#forms-example) - there is no class in the upload field.
If I add it like you wrote, the FE on my testparcours looks like:
<img src="https://box.everhelper.me/attachment/1041592/84725fb7-0b3e-4c40-b52e-29d7620777bb/262407-1AbN0pCoi7mnETPa/screen.png" />

What do you think?

**Comment by einpraegsam** [comment]
As discussed a few seconds ago. I will close this request for now.
