### ISSUE TITLE
New values from different services does not set into mail object

### ISSUE THREAD

**Issue by p2media** [einpraegsam/powermail#132]
The new services to find new values for receiver, senderName, senderMail etc. does not set into mail object after mail was sent and before mail object was updated.

**Example:**
In function _sendReceiverMail()_ after _sendMailService->sendMail()_, the mail object should be updated with new values from e.g. ReceiverMailReceiverPropertiesService.

Or define new method to update mail object with new data from _sendSenderMail()_ or _sendReceiverMail()_ in function _sendMailPreflight()_?

**Comment by p2media** [comment]
It seems it does not work, if **receiver type** is as "predefined receivers" selected. I defined "tx_powermail.flexForm.predefinedReceivers.addFieldOptions.development = Development" and selected this in powermail plugin. => No update!

I changed the receiver type back to "Email addresses" and voilá, senderName and senderMail will be updated in mail object.

**Comment by einpraegsam** [comment]
I played a bit but I can't see a problem. Pls check if your email field is marked as sender field.
<img src="https://box.everhelper.me/attachment/1063028/84725fb7-0b3e-4c40-b52e-29d7620777bb/262407-7aX2wDceD9eX5T3m/screen.png" />

My tests:
<img src="https://box.everhelper.me/attachment/1063031/84725fb7-0b3e-4c40-b52e-29d7620777bb/262407-6QCQoSskR6m6hA4h/screen.png" />

**Comment by einpraegsam** [comment]
Any feedback for me? Otherwise I will close this issue.

**Comment by p2media** [comment]
Ok, I don't set a field as email or name. I want to do this in typoscript, e.g. Webmaster<webmaster@domain.org>.
I will try it out and commit my result at the end of this week.

**Comment by einpraegsam** [comment]
I will close this issue. Pls reopen if needed.
