### ISSUE TITLE
Incorrect integer value: '' for column 'value_type' at row 1

### ISSUE THREAD

**Issue by sbarbieri** [einpraegsam/powermail#138]
Hi, I use TYPO3 v8.7.4 with powermail v3.20.0 and on submit of my form I get the following error:

Oops, an error occurred!
Incorrect integer value: '' for column 'value_type' at row 1

In the backend log I see:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1470230766: Incorrect integer value: '' for column 'value_type' at row 1 | TYPO3\CMS\Extbase\Persistence\Generic\Storage\Exception\SqlErrorException thrown in file /home/www-data/zzz/typo3_src-8.7.4/typo3/sysext/extbase/Classes/Persistence/Generic/Storage/Typo3DbBackend.php in line 158. Requested URL: http://myurl/1940-und-aelter/?tx_powermail_pi1%5Baction%5D=create&tx_powermail_pi1%5Bcontroller%5D=Form&cHash=5472c995255f74a0d723768ede153b28

(myurl above exchanged for real url)

It this a known error?

Thanks
Sandro

**Comment by einpraegsam** [comment]
This is related to https://forge.typo3.org/issues/81043 and should be fixed within the next TYPO3-versions.

**Comment by sbarbieri** [comment]
Thank you @einpraegsam ! Mentioned work-around works for the moment.
