### ISSUE TITLE
Feature Request: Prefill hidden fields from TypoScript

### ISSUE THREAD

**Issue by spawnia** [einpraegsam/powermail#139]
When prefilling a hidden field, it would be great if i were able to just take a value from typoscript and add it in, just like in the field type TypoScript. I like the way how i can simply get a value by entering a TypoScript Path.

**Comment by einpraegsam** [comment]
What's wrong the the current possibilities? See https://docs.typo3.org/typo3cms/extensions/powermail/ForAdministrators/BestPractice/PrefillField/Index.html in manual

**Comment by spawnia** [comment]
I can fill a field with a TypoScript cObject with a static value just fine. However, i have a variable in my own extension which i fill with a userFunc, stored in smth. like "lib.variable_name". I would like to use that to prefill the hidden field.

**Comment by einpraegsam** [comment]
What about the example in the manual:
```
plugin.tx_powermail.settings.setup.prefill {
        # Fill field with marker {email}
        email = TEXT
        email.value = mail@domain.org
}
```
Here you can do nearly everything with TypoScript - like userFunc, etc...
So I don't get your request!?

**Comment by spawnia** [comment]
Yeah calling the userFunc from there works, problem is i have to copy the code into multiple page templates instead of just accessing a value i already set in my own extension. If i could just enter the path to that like it is possible for field type TypoScript that would simplify setting up the multiple forms.

**Comment by einpraegsam** [comment]
There is nothing planned about it

**Comment by baden32** [comment]
@einpraegsam

Dear Alexander,

When you wrote

plugin.tx_powermail.settings.setup.prefill {
        # Fill field with marker {email}
        email = TEXT
        email.value = mail@domain.org
}
**Here you can do nearly everything with TypoScript - like userFunc, etc..**

Would it be possible to give an exemple? I Tried using COA and USER_INT but the result is not the output of my userfunc but a strange string like 

Thank you in advance for your help.
Bads

**Comment by baden32** [comment]
Dear Alexander,
Forget my previous post, I was using a much complicated coding to "load" my userFunc. It's easy in fact:

plugin.tx_powermail.settings.setup.prefill {
        # Fill field with marker {idjob}
        idjob = USER
        idjob{  
           userFunc = mywebsite\display\WebsiteFunction->GetJobId
}

Hope this helps.
Regards,
