### ISSUE TITLE
Marketing eID script does not have a cHash and results in a 404

### ISSUE THREAD

**Issue by vertexvaar** [einpraegsam/powermail#141]
When having set `pageNotFoundOnCHashError` to its default value `true` the eID script of the powermail marketing feature will result in a 404.
(This is the same problem as in einpraegsam/ipandlanguageredirect )

**Comment by einpraegsam** [comment]
It's already fixed in develop branch and waits for the upcoming release: https://github.com/einpraegsam/powermail/blob/develop/Configuration/TypoScript/Marketing/setup.txt#L8
