### ISSUE TITLE
Send mail with uploaded file fails

### ISSUE THREAD

**Issue by namano87** [einpraegsam/powermail#142]
Hello,
I've created a new form with powermail. Everything is working fine. But if someone upload a file and submit this mail, the email comes without attachment. I've got 2 upload buttons in my form. In TYPO3 at the Constant editor I activated the fields receiver und sender attachements. And I don't know how to fix that.

**Comment by einpraegsam** [comment]
Pls try this:
- Use powermail with default (TypoScript) configuration
- Add a small form with just an input and an upload field (and in addtion a submit of course)
- Clear caches
- Send the mail with this form
Are there any attachments?

**Comment by namano87** [comment]
No, nothing :/

**Comment by einpraegsam** [comment]
Did you test with different filetypes and sizes?
Did you really test with a configuration-free powermail (no TypoScript, original HTML-Templates and Partials)?

**Comment by einpraegsam** [comment]
Any feedback for me? 
BTW: Is the uploads-folder writeable?

**Comment by namano87** [comment]
Sorry, for the delay. I have to wait for the FTP server to work again. I will answer as soon as possible. maybe the folder is not writeable.

**Comment by einpraegsam** [comment]
Powermail wants to upload files to `uploads/tx_powermail/` - pls check this folder (is it existing and writable).

**Comment by einpraegsam** [comment]
Any feedback for me? Otherwise I will close this issue.

**Comment by namano87** [comment]
Hey, yes the folder ist existing and writeable. But it still doesn't work...

**Comment by einpraegsam** [comment]
I tested the functionality again on my testparcours, but it works like a charm. So I'm running out of ideas - sorry for that.
