### ISSUE TITLE
scroll issue on date field 

### ISSUE THREAD

**Issue by walma7** [einpraegsam/powermail#146]
This can be repoduced on the powermail-testpage (http://powermail.in2code.ws/index.php?id=28) with IE11 or Firefox (not with Chrome). 
Datefield has to be allready filled and then place the mousecursor over the field without click. Scrolling the mouse changes the date.

**Comment by einpraegsam** [comment]
Yes, it seems that this is a feature of the datetimepicker. 
You can also test it on https://xdsoft.net/jqplugins/datetimepicker/ (field datepicker). Of course this will not happen in Chrome, because Chrome uses his own datepicker and not the jQuery plugin.

**Comment by walma7** [comment]
OK, but it would be nice if this feature is disabled by default.
Because for the user of the form it isn't obvious.
Thx.

**Comment by nebrot** [comment]
It's configurable in datetimepicker, but not in powermail. Would be cool to have a setting for this or disable it per default. The option is called `scrollInput` and is defined here: https://github.com/einpraegsam/powermail/blob/develop/Resources/Private/JavaScripts/Libraries/jquery.datetimepicker.js#L200 and here https://github.com/einpraegsam/powermail/blob/develop/Resources/Public/JavaScripts/Libraries/jquery.datetimepicker.min.js.
Scrolling through the page could change the date without notification of the user, i would prefer to disable this option.

Option in datetimepicker: https://github.com/xdan/datetimepicker/blob/1525c130278b79c44c0f9c7f7ac4eacc5ee7374b/jquery.datetimepicker.js#L1901-L1923

**Comment by einpraegsam** [comment]
You can remove the JavaScript from powermail and add your own. But that feature is not supported at the moment. I'm still hoping that browsers like Firefox and even the IE should bring their own datepicker like Chrome does.

**Comment by nebrot** [comment]
We have fixed it temporarily with a custom javascript in footer. The settings are changed at runtime after creating the datepicker (Form.min.js).

`$(".powermail_date").datetimepicker({scrollInput: false});`
