### ISSUE TITLE
Pagination widget doesn't respect filter settings in backend module.

### ISSUE THREAD

**Issue by rpflamm** [einpraegsam/powermail#147]
Under TYPO3 8.7.3 the pagination widget of the backend module don't respect the filter settings.

If I setting the filters to reduce to one form I got 5 pages, but when I click to go to the next page I got all submits of all forms.

I'm not sure if its an powermail or an TYPO3 bug...

**Comment by einpraegsam** [comment]
I can confirm this issue. And the problem is a big larger: All filter settings are getting lost if I choose page 2.

**Comment by einpraegsam** [comment]
Fixed in develop branch. Ready for upcoming release
