### ISSUE TITLE
Multi-line content in input textarea doesn't work when confirmation page is active

### ISSUE THREAD

**Issue by rr-it** [einpraegsam/powermail#148]
powermail v3.21.1 and TYPO3 7.6

**Issue**
Multi-line content in input textarea doesn't work when confirmation page is active. The line-breaks are removed.

**Cause**
The content on the confirmation page gets passed by hidden input-elements.
TYPO3 removes line-breaks of the `value`-attribute in Fluid `f:form:hidden`
`<f:form.hidden property="{answer.field.marker}" value="{answer.value}" />`

**Workaround**
As a workaround I implemented a input `textarea` which is hidden by CSS for the original textarea-input.
See https://gist.github.com/rr-it/614a8f7752703ea2db2875aebd506f41

**Alternative fix** (for TYPO3 8.7)
Fix Fluid `f:form:hidden` to not remove line-breaks of the `value`-attribute.

**Comment by einpraegsam** [comment]
Just tested on my local testsystem with the newest powermail and on T3 7.6:

<img src="https://s.nimbus.everhelper.me/attachment/1075698/kigkfzhq2wk26evlcivl/262407-IrKydGnav76Nq0vc/screen.png" />

<img src="https://s.nimbus.everhelper.me/attachment/1075700/tky7cg6l6fo9fqu3mbr3/262407-Az425SQHlFJr4Txb/screen.png" />

Pls check if you have an UTF8 database, if you are using powermail with default templates, if there is no other extension that extends powermail, etc...

**Comment by rr-it** [comment]
Please have a look in the hidden inputs. The values are shown correctly on the confirmation page.
Clicking the "Back" or "Next" button will show the multi-line content converted to single line.

**Comment by einpraegsam** [comment]
I also tested with next, previous, next - no problems.
Browser? OS?

**Comment by rr-it** [comment]
I have ext:sourceopt activated and this is provoking the issue, so it has nothing to do with powermail.
Thank you for looking into this!
