### ISSUE TITLE
Multi-line content in input textarea is not displayed as multi-line in html mails

### ISSUE THREAD

**Issue by rr-it** [einpraegsam/powermail#149]
powermail v3.21.1 and TYPO3 7.6

**Issue**
Multi-line content in input textarea is not displayed as multi-line in html mails SenderMail and ReceiverMail. The line-breaks are not converted (nl2br). This is an issue for both {powermail_all} and lonely fileds `{uidXX}`.
It is also an issue for `{powermail_rte}` and therefore not fixable in the Fluid-templates.

**Fix**
See https://gist.github.com/rr-it/f75774698c6bd995a56655f10a0c423e

Maybe an even better solution is to add an extra `valueType` in `In2code\Powermail\Domain\Model\Answer`.
`0` for text and e.g. `5` for multi-line text.

**Comment by rr-it** [comment]
I have ext:sourceopt activated and this is provoking the issue for `{powermail_all}`.

After deactivating ext:sourceopt:
For lonely fields `{uidXX}` in Fluid-templates SenderMail and ReceiverMail it is working fine.
For lonely fields `{uidXX}` via `{powermail_rte}` the issue still persists.

**Comment by einpraegsam** [comment]
See also details on https://github.com/einpraegsam/powermail/issues/148

**Comment by kimchristiansen** [comment]
Same Issue still in TYPO3 8.7 and Powermail v. 6.0.0
Has the issue been fixed in a newer version?
Is there a workaround?

**Comment by mtness** [comment]
This issue still seems to be present in v.8.2.3 and TYPO3 v10.4.10 :/

**Comment by rico3000** [comment]
I had the same issue with TYPO3 v8.7. and powermail 6.2.0 & powermail 7.4.0 for me the provided Gist doesn't work. I found my solution with: 

```
<f:format.raw>
	<v:format.replace substring="&lt;br /&gt;" replacement="<br />" >
		<vh:Misc.Variables mail="{mail}" type="mail" function="receiver">
			{powermail_rte -> f:format.html(parseFuncTSPath:'lib.parseFunc_powermail')}
		</vh:Misc.Variables>
	</v:format.replace>
</f:format.raw>

```
for Templates/Mail/*

Ugly, I know, but it helps me and maybe some other…
