### ISSUE TITLE
Feature Request: Submission ID Number

### ISSUE THREAD

**Issue by eiranix** [einpraegsam/powermail#151]
A submission ID number, similar to a help desk ticket number or the like?
When a user submits the form, an ID number generated and optionally used in the sender/receiver emails. Would be helpful if it was the same as the email UID that was generated.

**Comment by einpraegsam** [comment]
The mail will be stored before the email templates are sent and before the thx-message will be shown. So it should be possible to use the tx_powermail_domain_model_mail.uid as unique number. 
In addition there are finisher classes or the possibility to extend templates with viewhelpers, etc... to build something own.
So there is no plan to add some feature over that.

**Comment by eiranix** [comment]
Sorry for being dense. How would I use tx_powermail_domain_model_mail.uid ?

**Comment by einpraegsam** [comment]
If you look at the email template (originally stored under EXT:powermail/Resources/Private/Templates/Mail/ReceiverMail.html) you will see a list of possible variables:
```
{powermail_rte}									Variable is filled with values from RTE in backend
{powermail_all}									Outputs all fields
{marker1}, {firstname}, etc.. 					Outputs a field
{label_marker1}, {label_firstname}, etc... 		Outputs a label to a field
{mail}											Complete Mail Object
{email}											Email Configuration
{settings}										TypoScript Settings
```
So I would say that {mail.uid} contains the mail uid

**Comment by eiranix** [comment]
Yeah, I actually tried using {mail} in the receiver template before posting here, but neither {mail} nor {mail.uid} output anything at all?

**Comment by einpraegsam** [comment]
Did you really tested it?
Nevertheless, I took the time and tested it and it is like I was writing before.
This is my testsection in EXT:powermail/Resources/Private/Templates/Mail/ReceiverMail.html:
```
<f:section name="main">
	<vh:Misc.Variables mail="{mail}" type="mail" function="receiver">
		<f:format.html parseFuncTSPath="lib.parseFunc_powermail">{powermail_rte}</f:format.html>
	</vh:Misc.Variables>

	<f:render partial="Misc/MarketingInformation" arguments="{marketingInfos : marketingInfos}" />

	uid: {mail.uid}<br />
	subject: {mail.subject}
</f:section>
```

The email is rendered like this:
```
...
uid: 11627
subject: [testparcours] Short form prefilled 
```

**Comment by eiranix** [comment]
Thanks so much for your time! I finally realised my problem was actually the path to the override template had a typo (not capitalised) and so it was just using the default. I have spent so much time wondering why the variable wasn't working! Thanks again.

**Comment by eiranix** [comment]
One Question: Why doesn't this variable work from within the Receiver Mail RTE?

**Comment by einpraegsam** [comment]
Seems to be a missing feature
