### ISSUE TITLE
Bug with UTF symbols in confirmation page and email

### ISSUE THREAD

**Issue by Pekkonen** [einpraegsam/powermail#152]
Hi!
I think that it's bug.
I paste field in form with TypoScript
in TS used Cyrillic symbols (TS it's a external file with UTF8 codepage)
If FE everything seen normal - see file pm1
After send a form I see a UTF8 codes of symbols instead of cyrillic text - see file pm2
![pm1](https://user-images.githubusercontent.com/31384473/29749233-c616ee54-8b2f-11e7-8136-b33ef3d5e09b.png)
![pm2](https://user-images.githubusercontent.com/31384473/29749234-c644958e-8b2f-11e7-9136-dada17a532cb.png)
In email to Receiver same problem with UTF8 symbols. 
I update Powermail to latest version - 3.21.1 but bug is exist
TYPO3 7.6.15

**Comment by einpraegsam** [comment]
I just tested on my testparcours and everything is fine with cyrillic characters. Pls check if you don't have UTF8 tables and fields in your database. In addition try on a poor system with powermail only (no other extensions and with default TypoScript and HTML-Templates).

**Comment by Pekkonen** [comment]
Hmm. It's strange, because I edit one label end make it on English.
See attach - it's ok
![pm3](https://user-images.githubusercontent.com/31384473/29770160-4d0d9f2c-8bf6-11e7-85c0-bdb0d898b912.png)
And again - I insert fields from TS. TS file it's separate UFT8 file with TS:
```
lib,add1 = TEXT
lib,add1.value (
	<label class="powermail_label" title="">
		Надбавки к базовой стоимости:
	</label>

	<div class="powermail_field">
		
			<div class="checkbox ">
				<label>
					<input type="hidden" name="tx_powermail_pi1[field][add]" value=""><input data-parsley-errors-container=".powermail_field_error_container_add" data-parsley-class-handler=".powermail_fieldwrap_add div:first > div" class="powermail_checkbox powermail_checkbox_6" id="powermail_field_add_1" type="checkbox" name="tx_powermail_pi1[field][add][]" data-add="55" value="Внешнеэкономическая деятельность - 55%" data-parsley-multiple="tx_powermail_pi1fieldadd">
					Внешнеэкономическая деятельность - 55%
				</label>
			</div>
...
```
In Powermail I just wrote lib.add1
You tested same method?

**Comment by einpraegsam** [comment]
It's not supported to add complete fields with the whole HTML with TypoScript only. Adding new fields should be done with a new field (see https://docs.typo3.org/typo3cms/extensions/powermail/ForDevelopers/AddNewFields/Index.html). Nevertheless, if you want to add just a few options to checkboxes, radiobuttons or selectfield dynamically, I would use "create from TypoScript" (see https://docs.typo3.org/typo3cms/extensions/powermail/ForAdministrators/BestPractice/PrefillField/Index.html#prefillorpreselectaselectfieldtyposcript)

**Comment by Pekkonen** [comment]
Yeah...
It's sad, but clear. Thanks for your help!

**Comment by Pekkonen** [comment]
Anyway - my method work, exclude wrong symbol conversion ) 
Maybe you need thinking add something about it in manual?
