### ISSUE TITLE
Powermail: Fehler beim Versenden von Mails, wenn ein Empfänger eingestellt ist

### ISSUE THREAD

**Issue by Champi85** [einpraegsam/powermail#155]
Ist die Option 'plugin.tx_powermail.settings.receiver.enable' aktiviert und eine Empfänger-Mail-Adresse im Inhalt hinterlegt, bekomme ich nach dem Absenden des Formulars den Fehler 'Failure, mail could not be sent!'

Ich verwende Typo3 8.7.3.

**Comment by einpraegsam** [comment]
First of all, please try to write in english. Maybe other users have the same issue and also need help.
Sounds to me that you have a configuration issue.
What about sending mails in Install Tool? Or sending a test mail in powermail backend module? Does that work?

**Comment by Champi85** [comment]
Yes, sending a testmail works correct.
Even the mail to sender works.
I helped me by disable the mail to the Receiver and set the receiver as cc when mailing the sender.
This works for me too.

But when activate the mail to Receiver an error occurs.

**Comment by einpraegsam** [comment]
I still think that this is a configuration issue. Probably you miss to check the "this is the email address of the sender" checkbox in field email or so.
Thx for your final feedback.

**Comment by SPHolzi** [comment]
I do have the same problem, even without having a receiver address and a receiver subject line results in the error
