### ISSUE TITLE
Powermail: Beim Erzeugen der DB-Einträge der Mails kommt es zu einem Fehler

### ISSUE THREAD

**Issue by Champi85** [einpraegsam/powermail#156]
Beim Submit des Formulars kommt es bei aktiviertem 'plugin.tx_powermail.settings.db.enable' zu folgendem Fehler. 

Oops, an error occurred!
Incorrect integer value: '' for column 'value_type' at row 1

Ich verwende Typo3 8.7.3.

**Comment by einpraegsam** [comment]
Pls write in english only.
That is a known issue in TYPO3 together with mysql strict mode - see https://forge.typo3.org/issues/81043 for details
