### ISSUE TITLE
No fonts "glyphicon" for Backend.css and Bootstrap.css

### ISSUE THREAD

**Issue by ludovichemmerch** [einpraegsam/powermail#157]
In your Backend.css and Bootstrap.css files you use glyphicons and you include the files with `src:url("../fonts/glyphicons-halflings-regular.eot?#iefix")` but there is no "fonts" folder.

**Comment by einpraegsam** [comment]
Thx for the feedback. I will fix this asap.

**Comment by einpraegsam** [comment]
Fixed in develop branch. Ready for upcoming release.
