### ISSUE TITLE
Showing Label of radio button in {powermail_all}

### ISSUE THREAD

**Issue by chequille** [einpraegsam/powermail#158]
Hi,

using Typo3 7.6.21 and latest Powermail version.

I have radio buttons defined as:
Text1 | 1
Text2 | 2
and so on.

When using {powermail_all} the value is shown, meaning 1 or 2 f.e.
But I want to show Text1 or Text2

In the partial Web.html there is {answer.value} used for displaying. 
Is there any chance to display there the label of the selected radio button?

Looking forward to hearing from you.
BR
Jürgen

**Comment by einpraegsam** [comment]
This is a feature request that's not included into powermail at the moment.
