### ISSUE TITLE
Missing redirect after submitting form

### ISSUE THREAD

**Issue by julrich** [einpraegsam/powermail#159]
Hey,

we have a problem with a missing redirect, after the form was successfully filled and submitted.

The redirect is entered inside the plugin (FlexForm), like this:
![screen shot 2017-09-04 at 17 43 38](https://user-images.githubusercontent.com/136760/30032939-a46fec0a-9198-11e7-9b80-9509e2d93036.png)

When debugging, it seems the `RedirectFinisher` seems to be missing. At least `$this->getFinisherClasses($settings)` is empty when `callFinishers` is called.

Can I supply more relevant info to you, to make debugging this easier? We're on TYPO3 7.6.21, with powermail 3.22.0.

**Comment by einpraegsam** [comment]
I tested it and everything works as expected (T3 8.7 and T3 7.6 and powermail 3.22) but without realurl.
Is your finisher included? Check in your object browser:
<img src="https://s.nimbus.everhelper.me/attachment/1098914/35zb89xbaegad2wl23od/262407-mCOpentsDLZm4tr1/screen.png" />
Do you use realurl? If so which version? Can you disable it for testing?
Btw: There is a behaviour test for redirects, that must be passed before every release :)

**Comment by julrich** [comment]
Sorry for the late reply, got caught up in work.

Indeed it was misconfiguration by us. A colleague just copied the old configuration after upgrading... ;)

Thanks for your help!
