### ISSUE TITLE
Date field not exported by the scheduler task

### ISSUE THREAD

**Issue by scherric** [einpraegsam/powermail#160]
Hi,

I'm using TYPO3 7.6.21 with powermail 3.22.1. I have a powermail form with a date type field (among others).

I scheduled a "Powermail Task: export" in xls or csv format. I didn't specify anything in fieldList. When I receive the mail with the Excel file, the date field does not appear in it.

When I use the powermail backend module > mail listings and I export in csv or xls, there's no problem, all fields are in the generated file.

There's nothing in the Administration log for the _cli_scheduler user.

Thanks for your help.
Eric

**Comment by einpraegsam** [comment]
Thx for your ticket. I pushed a fix to develop branch for this issue.
Nevertheless, you can define the fields with uid for your export - e.g.:
`./vendor/bin/typo3cms task:export --receiver-emails=alex@in2code.de --page-uid=28 --field-list=1,2,3`
