### ISSUE TITLE
Add Grid-Row support in Backend

### ISSUE THREAD

**Issue by funkyferdy** [einpraegsam/powermail#161]
To be able to define the aspect (spread) of form fields per Row (inside a Fieldset) for Backend redactors. so that you enable redactors to build "complex looking" forms with variable distribution across one row. Something like: 

[https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_input_width&stacked=h](https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_input_width&stacked=h)

Hint. The ext:form has a feature like this.

![grafik](https://user-images.githubusercontent.com/22144187/30160977-17b5d32c-93cf-11e7-9ad3-5e8253c53c0d.png)

![grafik](https://user-images.githubusercontent.com/22144187/30161217-ed8c83e2-93cf-11e7-8b98-5d8a50d13340.png)

**Comment by einpraegsam** [comment]
Thx for your note. I already pushed some changes to develop brnach that makes it possible to render fields in columns. E.g. in 2 or 3 columns. My solution is different to the solution from core and I don't want to go in a competition to the core form extension.
My solution is made for administrators at the moment. So it must be set via TypoScript.

**Comment by einpraegsam** [comment]
A small documenation is already available in FAQ-section: https://github.com/einpraegsam/powermail/blob/develop/Documentation/Faq/Index.rst#how-can-i-use-responsive-columns-in-powermail
