### ISSUE TITLE
export csv with own template

### ISSUE THREAD

**Issue by format-gmbh** [einpraegsam/powermail#162]
I've set the path for my own templates in the constants (my ext is called "ms"):

plugin.tx_powermail {
	view {
		templateRootPath = {$plugin.tx_ms.view.templateRootPath}Powermail/
	}
}

The Powermail folder contains:
Form/Form.html
Module/ExportCsv.html

Changes in the file Form/Form.html are applied (in Frontend -> the setting of the path should therefore be correct).
Changes in the file Module/ExportCsv.html are not accepted (for export).

Am I doing something wrong?

TYPO3 8.7.5 / powermail 3.22

**Comment by einpraegsam** [comment]
You know that you have to use `module.tx_extkey_plugin` for configuration of backend modules?

**Comment by format-gmbh** [comment]
How embarrassing is that. Sorry.
Now I have written the following line according to your documentation in my root-setup, but unfortunately again without success:
module.tx_powermail.view.templateRootPaths.1 = EXT:ms/Resources/Private/Templates/Powermail/
My own template is in:
typo3conf/ext/ms/Resources/Private/Templates/Powermail/Module/ExportCsv.html

**Comment by einpraegsam** [comment]
Good question - I played a bit with an additional extension and I wasn't able to overwrite the template paths. At the moment I'm running out of ideas and I have to dig a bit deeper.

**Comment by format-gmbh** [comment]
Let me know if I'm supposed to help you.

**Comment by einpraegsam** [comment]
I have no ideas at the moment sorry. In addition I have a bit less time to debug through extbase. Nevertheless I'm open for improvements or PR.
