### ISSUE TITLE
Submit doesnt work - 500 Internal Server Error

### ISSUE THREAD

**Issue by fighterii** [einpraegsam/powermail#163]
I upgraded to 3.22.0 and noticed that my powermail form stopped working. 

After that i upgraded to 3.22.1, still the same. I just tried to remove powermail completly via the EM, delete the databases and install it new.

I still experience the following behavior (minimal setup:)
A Form with:
- Name
- Email
- Submit

After i enter Name + Email and click on submit, the website seems to work a bit and after that it "redirects" me to a whole blank page:
Link seems correct: kontakt/?tx_powermail_pi1[action]=create&tx_powermail_pi1[controller]=Form&cHash=d6b38dbb753f6e148570727bead8c945#c51

The Mail is stored at the correct page (i can access it via the "Mails" in the backend), but i neither see a Thank you page nor did i receive any of the emails (to visitor and to me).

Both Mails and the Answerpage don`t have any special code or something in it, basically a minimal setup.

TestMail via FunctionCheck is working, same behavior if i disable mail sending.

I use realurl 2.2.1

Any Ideas?

**Comment by fighterii** [comment]
As i saw it in another issue, where you requested the Typoscript Object Browser:

Mine looks completly different from yours (using Typo3 7.6.x):

![objectbrowser_powermail](https://user-images.githubusercontent.com/16879286/30238922-6bcc9666-9551-11e7-94c4-288d957d1cef.PNG)

**Comment by einpraegsam** [comment]
Hello, I'm nearly sure that this is just a configuration issue. Please check in your browser console if you have any redirects on form submit (this happens mostly if websites run with the wrong baseURL/absrefprefix settings - e.g. if http:// is redirected to https://).

**Comment by fighterii** [comment]
I didn't see any redirects. All additional Info i got was an "500 Internal Server Error" as result of the POST request

baseURL is ```baseUrl = http://name.de/``` ; absrefprefix is not set

However i notice, that realUrl produces links in form of "name.de/kontakt/" (so no prefix at all). I`m actually not using any https:// at the moment.

**Comment by einpraegsam** [comment]
Ok, that message could help.
Pls write me your PHP- and TYPO3-Version. Does your TYPO3 run in composer mode?
In addition: Does the error occur on very simple forms? As you wrote, just 2-3 fields and without any special configuration (no confirmation page, no double opt-in, etc...)?
I'm asking because I want to reproduce the error on my testsystem.

**Comment by fighterii** [comment]
Typo3 7.6.11
PHP 5.6.31
No Composer Mode
Yes the errror occurs on a very simple form - name, email, submit. (No confirmation, no double opt-in, email to receiver and visitor disabled).

**Comment by mesurinna** [comment]
Had the same Issue when i used Workspaces in draft mode. The Cookie wasnt deleted after i switched back to Live mode, and still got the form error after submitting form.

**Comment by einpraegsam** [comment]
Does this help?

**Comment by fighterii** [comment]
Is this some server-side configuration i have to do?
I deleted all cookies on my client, restarted the browser and the error still occurs. Same with clients i never used before to access the webpage, so i would say: no it doesn't help.

**Comment by runde8** [comment]
Got the same error! Checked the Github, but still some errors left: 

Fatal error: Class 'In2code\Powermail\Domain\Service\SendMailService' not found in /typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 4533

Version 7.6.9

**Comment by einpraegsam** [comment]
ok, I installed an old TYPO3 7.6 without composer and created a small form (just 2 fields and a submit). There are no problems on submitting. 
What else can I do to reproduce this issue?

**Comment by fighterii** [comment]
No idea.
Do you have any idea where i can check that the trait is where it should be ``` Trait 'TYPO3Fluid\Fluid\Core\ViewHelper\Traits\CompileWithRenderStatic'```

**Comment by einpraegsam** [comment]
I just inserted `<vh:condition.isArray val="{0:1}" />` to the Form template and checked if there are problems. No Problems in TYPO3 8 (with and without composer) and TYPO3 7 (with and without composer). 
I tested with the latest 7.6 version and with PHP 7.
Sorry, but if I can't reproduce this issue, I have to close this ticket.

**Comment by fighterii** [comment]
Okay no problem, guess i`ll have to switch to an other form extension then.

**Comment by einpraegsam** [comment]
BTW: There was a discussion on slack to this issue and the final message from the user was "updating TYPO3 from 7.6.10 to 7.6.23 solved this issue"
