### ISSUE TITLE
Attachment from file upload is lost when using double opt-in

### ISSUE THREAD

**Issue by andreasmerkel** [einpraegsam/powermail#169]
Hi,

we just noticed that mail attachments are lost when using the option double opt-in.
When deselecting this option, the uploaded file will be attached to the mail again.
We think, that the uploadService class in sendMailService.php:
$uploadService = ObjectUtility::getObjectManager()->get(UploadService::class);
invokes a new instance and so all references to uploaded files are gone.

We use Typo3 8.7.6 with Powermail 3.22.1

Best, Andreas

**Comment by einpraegsam** [comment]
Hi Andreas,

this seems to be correct. I added this feature (it's really more a missing feature then a bug related to the code that has to be added) in develop branch. Ready for upcoming release.

Alex

**Comment by andreasmerkel** [comment]
Hi Alex,

thanks for your solution. We just tested it, but now it fails when confirming the optin email with the following message:

Uncaught TYPO3 Exception: #1476107295: PHP Warning: Illegal string offset 'form' in /root/ext/powermail/Classes/Domain/Factory/FileFactory.php line 134 | TYPO3\CMS\Core\Error\Exception thrown in file /local/service/www.mpi-inf.mpg.de/typo3_src-8.7.6/typo3/sysext/core/Classes/Error/ErrorHandler.php in line 112. Requested URL: https://testweb.mpi-inf.mpg.de/departments/computer-vision-and-multimodal-computing/research/vision-and-language/mpii-movie-description-dataset/request-access-to-mpii-movie-description-dataset/?tx_powermail_pi1%5Bhash%5D=1e87b4980c&tx_powermail_pi1%5Bmail%5D=821&tx_powermail_pi1%5Baction%5D=optinConfirm&tx_powermail_pi1%5Bcontroller%5D=Form&cHash=e9db27f68d1f0999515de00ce2a43f15

The returning array for method 'getArguments()' looks like this:

array (
  'hash' => '1e87b4980c',
  'mail' => '821',
  'action' => 'optinConfirm',
  'controller' => 'Form',
)

which doesn't contain any "mail"->"form" content.

Best,
Andreas

**Comment by einpraegsam** [comment]
Hi Andreas,

it seems that you're right. I think I overlooked something. Strange that I saw no errors on my tests.
Will check this as soon as I have some freetime.

Alex

**Comment by einpraegsam** [comment]
Thx for the info. Should be fixed in 4.0.1

**Comment by andreasmerkel** [comment]
Thank you very much. It seems to work now!
Best, Andreas

**Comment by Geddo** [comment]
I got the same situation with TYPO3v8.7 and PowerMail 7.3: 
- Attachments are uploaded correctly to defined path
- Attachments-Mails work even when using the confirmation-step but DOI-Mails dont work
- The SENDER gets the DOI-Mails (both, link, and the confirmation) but the RECVEIVER gets nothing
- No error in the logs :-(

Any idea?
