### ISSUE TITLE
Kein Caching für "nc_staticfilecache" möglich?

### ISSUE THREAD

**Issue by SerNerestro** [einpraegsam/powermail#17]
Einen schönen guten Tag,
wir verwenden aktuell ein TYPO3 in der Version 7.16.4 zusammen mit Powermail in der Version 3.6
Nun wollten wir, um das Frontend zu beschleunigen,  nc_staticfilecache in der aktuellen Version (3.6) verwenden. Leider sind anscheinend die Seiten, auf denen ein Powermailformular drauf ist, nicht cachebar? Ich glaube mich zu erinnern, das sind in einer älteren Powermailversion (< 3) möglich war? In der Config finde ich auch keine entsprechende Möglichkeit hierzu.

Laut nc_statiffilecache würde das Caching durch Powermail verhindert: "The page has a INTincScript: type: FUNC, userFunc: TYPO3\CMS\Extbase\Core\Bootstrap->run, extensionName: Powermail, pluginName: Pi1"

**Comment by einpraegsam** [comment]
Please write in english next time if others have the same question like you.

To your answer:
See extension manager settings of powermail (also described in manual): <img src="https://nimbus.everhelper.me/client/notes/share/674567/ly58277ix7rmayqvpt4c" />
