### ISSUE TITLE
Custom Progress Styles

### ISSUE THREAD

**Issue by Skinwalker** [einpraegsam/powermail#171]
Is there a way to add some custom progress styles to the form?
I want to add a class to the submit button which indicates the form is submitted (since its ajax based) but my problem is that the class is not removed when there are errors in the form.

I saw that in your form.js there's a progressbar which should be added to the form - but i don't find anyhting where to active that.

Any ideas how to inject into the ajax submit process, without overwriting your form.js?

**Comment by einpraegsam** [comment]
The only included solution is viewable under: http://powermail.in2code.ws/index.php?id=9
But also without a stop if there are errors

**Comment by Skinwalker** [comment]
But i don't see how you implemented the progressbar on the example page ...
Is there a chapter on the docs that i missed?
