### ISSUE TITLE
powermail bug after 6.2 to 7.6 migration

### ISSUE THREAD

**Issue by jul6art** [einpraegsam/powermail#172]
HI!

After migration from 6.2 to 7.6, it's impossible to edit a form in a page.

In a page, i click on plugin tt_content, that opens the plugin options for  this item, the form named "form 1".

Choose a Powermail Form  => i choose form named "form 2" => save

After saving, i see that form is not saved, 

In addition, parameters for form one are not display.

Does anybody know why?

**Comment by einpraegsam** [comment]
I'm not sure what your problem is. If you open a plugin and select another form and save. The old form is still chosen in plugin? Is that the problem?
What if you add a complete new plugin or a new form?

**Comment by jcgueriaud** [comment]
Hello,

The error comes from compatibility6. When you disable it, the problem was gone.
With compatibility6, the system cannot read flexform correctly (column pi_flexform in tt_content).
So the form was saved correctly but not read at all.

**Comment by einpraegsam** [comment]
Ok, good to know. I will add a note to the documentation. 
I know that this will not help you, but I don't want to support technology from a time before TYPO3 7. I was thinking about also dropping support for TYPO3 7 for powermail 4 but it is still supported.

**Comment by jul6art** [comment]
Thank you jcgueriaud 🥇

Ticket resolved

Hum need to close it on stackoverflow also, asap
