### ISSUE TITLE
Defined SignalSlots active on each powoermail form

### ISSUE THREAD

**Issue by chequille** [einpraegsam/powermail#173]
Hi Alex,
I told you, that the Signals are working now, which is good so far.

But I found, that if there is any signalslot defined, it is executed on every powermail form.

To be a little bit more detailed the following explanation.
I enhanced the existing extension bvt_powermail_pdf to attach the generated pdf to the mail. This is working now and looks pretty good.

But, another form on another page is as well attaching a file to the email now (it is named tx_powermail.dat), because the registered signals are executed on every powermail form.

Do you have any idea to fix this?

Best regards
Jürgen

**Comment by einpraegsam** [comment]
That's correct. But this is, as you may know, not a powermail issue. I would prefer such support questions ins slack, where others could also help.
Nevertheless you have to enable your attachment only for one form I think. A var_dump on $_REQUEST shows you the variables that you have. Or just be a bit creative. If you are using the signal `sendTemplateEmailBeforeSend` the third parameter is the SendMailService class itself. So you you have access to the mail property with `$sendMailService->getMail()`. And a mail should have all informations that you need (also a relation to a form).
