### ISSUE TITLE
Validation when extending Model\Field

### ISSUE THREAD

**Issue by koehnlein** [einpraegsam/powermail#175]
Hi,

I want to create an individual finisher and use an extended field configuration. To extend the model, I use the following TypoScript:

```
config.tx_extbase {
  objects.In2code\Powermail\Domain\Model\Field.className = Foo\AsaPowermail\Domain\Model\Field
  persistence.classes.Foo\AsaPowermail\Domain\Model\Field.mapping {
    tableName = tx_powermail_domain_model_field
  }
}
```

But now, I have a problem with the validator in this line:

https://github.com/einpraegsam/powermail/blob/ff312f1a65da6621b92515efd5caa2b49d1e93bf/Classes/Domain/Validator/InputValidator.php#L60

From any reason, the objects are not identical. And the comparison fails.

When I simplify the check only to only compare the `uid`, it seems to work for my form:

```php
if ($answer->getField()->getUid() === $field->getUid()) {
```

But I don't know your extension as good as you do. Maybe there is a reason for your strict comparison. That's why I do not offer a merge request, but only open this issue. I hope you can find a solution!

**Comment by einpraegsam** [comment]
I'm not totally sure what you've done so far. Did you extend the field model with new properties? What is your goal? So the input validation doesn't work any more? Why is this related to a finisher? Please give me a bit more information.

**Comment by koehnlein** [comment]
I'm creating a finisher to sync the user input to the customer's ERP system.

To give the editor the chance to map the fields correctly, I extended the TCA and the field model 
![powermail](https://user-images.githubusercontent.com/16088567/30856271-22c615cc-a2b8-11e7-8aca-5b47e65ae10c.png)

But when I overwrite your default `Model\Field` with my `Model\Field` (which extends your original) ...

```
config.tx_extbase {
  objects.In2code\Powermail\Domain\Model\Field.className = Foo\AsaPowermail\Domain\Model\Field
  persistence.classes.Foo\AsaPowermail\Domain\Model\Field.mapping {
    tableName = tx_powermail_domain_model_field
  }
}
```


```php
<?php

namespace Foo\AsaPowermail\Domain\Model;

class Field extends \In2code\Powermail\Domain\Model\Field {
```

... the validation of the form always fails. 
And without a valid validation, the form cannot be sent.

Feel free to ask more questions, if my problem is still not clear.

**Comment by einpraegsam** [comment]
Ok, now I understand your workflow. PR are welcome but please describe the problem in the commit message or simply link to this ticket.
