### ISSUE TITLE
Images inside response mail

### ISSUE THREAD

**Issue by akerssies** [einpraegsam/powermail#179]
Hello,

First of all thanks for the great plugin. I have a small problem with sending mail though.

When adding an image to response mail the recipient won't see the image. The image is inserted through the ckeditor but won't show up in the actual mail.

**Comment by einpraegsam** [comment]
Thx for the ticket. But this is still not supported. To have images in mails, I would use the mail HTML files for that.
Nevertheless: PR are welcome
