### ISSUE TITLE
Bug with Datepicker on Firefox

### ISSUE THREAD

**Issue by discotizer** [einpraegsam/powermail#180]
Using the internal datepicker is causing a strange behaviour on Firefox. All hidden input fields of the datepicker are displayed at the bottom left of the page. The input fields are not filled with placeholder values.

[Firefox](http://fs5.directupload.net/images/171004/xlwkxioz.png)

The same form renders perfect on Chrome. Also the input fields are filled with placeholder values.

[Chrome](http://fs5.directupload.net/images/171004/yeuvynsv.png)

No related bug is thrown in FF console.

Powermail 4.0.1
Typo3: 7.6.23
FF: v56 - Chrome: v61

**Comment by nebrot** [comment]
Have you included the CSS of datetimepicker? See https://docs.typo3.org/typo3cms/extensions/powermail/Faq/Index.html#the-datetimepicker-is-not-working-what-s-wrong

**Comment by discotizer** [comment]
@nebrot Thanks, that did the trick. It wasn't necessary in 2.0 so i forgot to check that.
