### ISSUE TITLE
Non-unique field-ids when using multiple powermail forms on the same page

### ISSUE THREAD

**Issue by macjohnny** [einpraegsam/powermail#181]
Due to the way a field id is generated, e.g. in 
https://github.com/einpraegsam/powermail/blob/29310446da12f26617dfecd587907ef83f0bdf6c/Resources/Private/Partials/Form/Field/Check.html#L16

the resulting id might not be unique if multiple forms exist on the same page and some fields have the same name across the forms.

**Comment by einpraegsam** [comment]
Yes that could happen. This is not only a problem of field checkbox but of every field. There is no simple solution at the moment for this.

**Comment by macjohnny** [comment]
could you please reopen this issue?
a simple solution is to generate the following id:
```
id="powermail_field_{field.marker}_{index.cycle}_{field.uid}_{ttContentData.uid}"
```

**Comment by einpraegsam** [comment]
You can overwrite the partial to your needs.

If we want to change powermail in general, I'm willing to reopen this issue. But this means, someone needs some time to refactor it. And I mean to change all id attributes in all partials. Would you like to do a PR?

**Comment by einpraegsam** [comment]
I will reopen this issue if anyone is willing to do that. I don't have time at the moment - sorry.

**Comment by macjohnny** [comment]
@einpraegsam i suggest to reopen the issue in order not to forget that it is still pending...

**Comment by einpraegsam** [comment]
I did that in the past. I kept all issues open that could be resolved any time. The result was that there were so many open tickets, that nobody kept track of it - even me. That is because there are many issues, configuration problems or feature requests in powermail.
Long story short: I will only keep issues open, that will be resolved in the near future - sorry

**Comment by MiladinBojic** [comment]
My solution was using typoscriptObjectPath:

`id="powermail_field_{field.marker}_{f:cObject(typoscriptObjectPath:'lib.powermailCounter')}" `

and then in TS:
```javascript
lib.powermailCounter = COA
lib.powermailCounter {
    10 = LOAD_REGISTER
    10 {
        Counter.cObject = TEXT
        Counter.cObject.data = register:Counter
        Counter.cObject.wrap = |+1
        Counter.prioriCalc = intval
    }
    20 = TEXT
    20 {
        dataWrap = {register: Counter}
    }
}
```

This is Typoscript counter, and by using it the id becomes unique:
id="powermail_field_myfield_1" 
id="powermail_field_myfield_2"

**Comment by eiranix** [comment]
@einpraegsam It would be very helpful if there was perhaps a prefix field in the form settings, or the form uid as a default prefix. Or even a more streamlined way of adding custom markers to each field, at the moment it seems to take a lot of clicking (Extended Tab > Checkbox > Dialog > Extended Tab again after load > Marker Field)  just to make one custom marker.
