### ISSUE TITLE
Empty "type" field in localized form field breaks frontend in TYPO3 8.7

### ISSUE THREAD

**Issue by pcworld** [einpraegsam/powermail#184]
I'm currently in the process of upgrading a TYPO3 7.6 instance to TYPO3 8.7, in which I've also upgraded powermail from 2.25.2 to 4.0.2.
In the frontend of a localized page with a form, I got the following exception:
> The Fluid template files "/www/typo3/typo3conf/ext/powermail/Resources/Private/Partials/Form/Field/.html", "/www/typo3/typo3conf/ext/powermail/Resources/Private/Partials/Form/Field/" could not be loaded.

The reason is that on 7.6, the translated records have an empty "type" field in tx_powermail_domain_model_fields. Opening the form in the 8.7 backend and saving it fixes the issue as the translated records are then assigned the "type" field from the default language parent record.

I'm not sure if this is a bug worth fixing or if it should just be mentioned in the documentation.

**Comment by einpraegsam** [comment]
Thx for the time that you spend into that issue.
The problem results in the changed localization behaviour of TYPO3 8.7.

We need something like:
* A note in the documentation
* A note in backend/frontend that there are errors
* A fixing wizard in the backend module

Or maybe it's even simpler to fix if the getType() method in the Field-Model must return a value even if there are no values in the localized record like it's already done for the marker field (see https://github.com/einpraegsam/powermail/blob/develop/Classes/Domain/Model/Field.php#L638). I will investigate some time in to that issue to get this fixed.

**Comment by einpraegsam** [comment]
I pushed a fix to develop branch. Ready for upcoming release.
