### ISSUE TITLE
Performance problem in ViewHelper string.RawAndRemoveXss

### ISSUE THREAD

**Issue by calien666** [einpraegsam/powermail#185]
Typo3 7.6 within a big Typoscript Config array has problems, because the global information ->isHtmlEnabled() isn't cached and the function getSettings always reads the complete TypoScript array.
With (temporary) returning true the parsing time minimizes with our form from 12 seconds to 0.7 seconds.

powermail 3.22.1
typo3 7.6.23 no composer
php 5.6

**Comment by einpraegsam** [comment]
At the moment I see no other simple way, but pull requests are always welcome of course.
Target: TypoScript should decide if values should be escaped or not in powermail.

**Comment by einpraegsam** [comment]
After a short discussion on twitter (slack would be the better location for future discussions) I decided to reopen this issue. It turned out that TypoScript was rendered for every single field. So on large forms there is a lot of caching possibility.

**Comment by einpraegsam** [comment]
Fixed in develop branch. Ready for an upcoming release.
