### ISSUE TITLE
New Signal slot required?

### ISSUE THREAD

**Issue by christophrunkel** [einpraegsam/powermail#186]
Hello,
I've checked the manual, but could not find a slot that is executed after the whole form process is finished.

In my project i need a signal slot that is executed after an optin mail is confirmed OR the form is submitted.

I want to export an XML structure with the form data after the sender email is validated.

Is there a slot i did not see or do i need a new slot here?

Christoph

**Comment by einpraegsam** [comment]
First of all: If you want to do something at the end of the process, a finisher seems to be the right choice - espicially for exports or connections to other interfaces.
Finishers are very easy to implement - look at the manual: https://docs.typo3.org/typo3cms/extensions/powermail/ForDevelopers/AddFinisherClasses/Index.html

Ok, next issue: How to fire the finisher only if optin is activated and if the final submit was done? Here is a quick example: 
```
$pluginVariables = GeneralUtility::_GP('tx_powermail_pi1');
$hash = $pluginVariables['hash'];
if (!empty($this->settings['main']['optin']) && OptinUtility::checkOptinHash($hash, $this->mail)) {
  // start my function
}
```

**Comment by christophrunkel** [comment]
Are you a 100% sure that a finisher is called after the optin mail is confirmed?

I tried your solution but still - the finisher is called after the first submit but not after the confirmation mail.

**Comment by einpraegsam** [comment]
As I wrote: The finisher is called twice. First after a submit and second after the confirmation link was clicked. That's why I wrote you in an example how to react only after the final click.

**Comment by christophrunkel** [comment]
This is very strange. The finisher was not called after the confirmation link was clicked.
A die(“HELLO WORLD”) function at the beginning of the finisher had no effect.

 

However what I found was a signal Slot 'optinConfirmActionBeforeRenderView' that works perfectly

 

$signalSlotDispatcher->connect(

       'In2code\Powermail\Controller\FormController',

       'optinConfirmActionBeforeRenderView',

       'In2code\Powermailextended\Controller\FormController',

       'savetoXML',

       TRUE

);

 

Thanks anyway.

 

 

 

____________________________________

christoph runkel | internetprojekte

ihr partner in sachen internet / intranet
lerchenbergstrasse 32

d-73733 esslingen

 

fon: +49 711 607 539-8

fax: +49 711 645 655-1

mail:  <mailto:dialog@christophrunkel.de> dialog@christophrunkel.de

 <http://www.christophrunkel.de> http://www.christophrunkel.de

 

 

Von: Alex Kellner [mailto:notifications@github.com] 
Gesendet: Dienstag, 24. Oktober 2017 16:37
An: einpraegsam/powermail <powermail@noreply.github.com>
Cc: christophrunkel <dialog@christophrunkel.de>; Author <author@noreply.github.com>
Betreff: Re: [einpraegsam/powermail] New Signal slot required? (#186)

 

As I wrote: The finisher is called twice. First after a submit and second after the confirmation link was clicked. That's why I wrote you in an example how to react only after the final click.

**Comment by einpraegsam** [comment]
This is really strange, because in https://github.com/einpraegsam/powermail/blob/develop/Classes/Controller/FormController.php#L257 there is a forward() to createAction() and in the createAction there is the call of the finisher.
Nevertheless, if you found a solution, I'm fine :)
