### ISSUE TITLE
Empty fields in receiver and user mail after opt-in confirmation in translated plugin

### ISSUE THREAD

**Issue by jensengelmann** [einpraegsam/powermail#187]
Sorry for the long title, but I don't know how to shorten it.

Our situation:
* Multilanguage site
* Translated contact form
* Translated plugin
* Opted for double opt-in

In the default language everything works fine. The user gets the confirmation mail, clicks the link and then the receiver as well as the user get their e-mails as aspected.

When we switch to another language the following issue occurs: The user get's the confirmation email with all the information he submitted - the {powermail_all} and all other markers work as aspected, Now the user clicks the confirmation link - the receiver gets an email but there is no information, no sender name, no sender email, just nothing. The user on the otherhand gets no email at all because the sender email field is just empty - actually the user email is sent to the default noreply@xyz address of the webserver.

I tried to track this down, but got a little lost in de debugging. Maybe someone can reproduce and confirm this behaviour...

**Comment by einpraegsam** [comment]
This is a known bug together with language_mode=strict.
At the moment there is no simple solution.
