### ISSUE TITLE
Redirect to Startpage after Form Submit

### ISSUE THREAD

**Issue by Alexander-Hagemeier** [einpraegsam/powermail#190]
Hello,

I have added the Powermail Extension (v4.1.0) to my Typo3 (v7.6.9).

I created a form and see it on the frontend. When I fill out the inputs and hit submit i get a redirect to the startpage with this additional "index.php?#c16218" in the url.

Also, in the error-log I see the following:

Validator class In2code\Powermail\Domain\Validator\UserValidator does not exist
Validator class In2code\Powermail\Domain\Validator\FormValidator does not exist
Validator class In2code\Powermail\Domain\Validator\MailValidator does not exist
Validator class In2code\Powermail\Domain\Validator\PageValidator does not exist
Validator class In2code\Powermail\Domain\Validator\FieldValidator does not exist
Validator class In2code\Powermail\Domain\Validator\AnswerValidator does not exist

All of these errors are thrown from the ValidatorResolver.php, line 118.

Unforntunately, I have no idea what the cause might be. Hopefully, someone here has an idea?

Thanks and kind regards!

**Comment by einpraegsam** [comment]
I just tested with 7.6 and the newest powermail and I can't see a problem.
The error is not related to your problem. For any reason extbase logs if there is no ModelValidator.
To your problem: Is the baseUrl/absRefPrefix correct set? If you are using realurl, can you pls test without and give me feedback?

**Comment by einpraegsam** [comment]
Any feedback for me? Otherwise I will close this issue.

**Comment by GuidoJansen** [comment]
I have the same problem.
But the problem only appears, if the powermail form is in a page which itself is in a page with RealURL settings 'Exclude from speaking Url' checked

Ex.:
```
+- Page 1 (Exclude from speaking Url is cecked)
|   +- Form (does not work)
+- Page 2 (Exclude from speaking Url is not checked)
    +- Form (works)

```

**Comment by einpraegsam** [comment]
It's always a realurl problem and not a powermail problem. E.g. if you have two pages with the same name on the same level. Pls check for duplications and conflicts in realurl first.

**Comment by GuidoJansen** [comment]
I think this is correct.
So the solution in my case was:

- Check, if you have RealURL running (maybe the same problem arises with CoolURI)
- If you do, then check if you have URL conflicts with the page your Powermail Plugin is on
  ( In my case it was a conflict between a shortcut to that page and the page itself )
- Changing the URL of either of these conflict-causing pages should resolve the problem

**Comment by robertrimke** [comment]
Currently i run into the same issue like mentioned above. Is there any other workaround available for this issue? RealUrl is disabled, Typo3 7.6.24, Powermail 4.4.0. Thanks!
