### ISSUE TITLE
overriding values using typoscript ignores conditions under 3.22.1 and 4.1.0

### ISSUE THREAD

**Issue by mediaessenz** [einpraegsam/powermail#191]
To reproduce:

Add a form with a select box "uid123" with some values. 
In the Plugin-Settings leave receiver name and email empty and add a subject of your choice.

Add this TypoScript setup to your e.g. root template:
```
plugin.tx_powermail {
	settings {
		setup {
			receiver {
				overwrite {
					email = TEXT
					email.value = name1@your-domain.de
					name = TEXT
					name.value = Your Name 2
					subject = TEXT
					subject.value = A subject
				}
			}
		}
	}
}

[globalString = GP:tx_powermail_pi1|field|uid123 = *]
plugin.tx_powermail {
	settings {
		setup {
			receiver {
				overwrite {
					email = TEXT
					email.value = name2@your-domain.de
					name = TEXT
					name.value = Your Name 2
					subject = TEXT
					subject.value = An other subject
				}
			}
		}
	}
}
[global]
```
Fill in the form an press send.

Result: the receivers email will be send to name2@your-domain.de independent what value is selected or **even** the select box is enabled. To verify, just delete or disable the form field "uid123".

To make it clear: typoscript conditions will be ignored!

In the past I used several conditions like `[globalString = GP:tx_powermail_pi1|field|uid123 = *]` to change receiver and subjects depends on the selection of the user. 
This worked until version 3.20.0 (or a little bit earlier) without problems. But now it's broken :-(

Maybe this comes with "Feature: Use default TYPO3 settings when sender name/email is empty"?

If I check my typoscript with the "Typoscript-Object-Browser" and enable the different conditions I have defined, the object tree looks as expected.

I use TYPO3 7.6.23, btw.

**Comment by einpraegsam** [comment]
uid123 seems to be wrong in my eyes. Can you please post the html source of the rendered select field?
To clearify: If the name is `tx_powermail_pi1[field][markername]` of course the TypoScript condition must be `[globalVar = GP:tx_powermail_pi1|field|markername = value]` (and maybe also globalString)

**Comment by mediaessenz** [comment]
I know, uid123 is just a random selected name for this issue.
The main problem is, that condition will be ignored at all.
To reproduce you can define **any** condition around the second override section.
Even `[globalVar = TSFE:id = 0]` will be ignored and the receiver email will become name2@your-domain.de

**Comment by einpraegsam** [comment]
thx for final feedback
