### ISSUE TITLE
[FEATURE] Don't save uploaded file on server

### ISSUE THREAD

**Issue by pniederlag** [einpraegsam/powermail#192]
In old versions there was a setting that prevented an uploaded file from being saved on the server. Is there any similar feature planned/implemented in recent versions?

Using a (frequent) cronjob to delete uploaded files is problematic as it processes files that are still processed by powermail.

**Comment by einpraegsam** [comment]
Possibles at the moment (powermail 4.x) are:
* Removing old mails (older then X days) via scheduler and after that use a second scheduler to remove unused images
* Use feature Randomize Filename: https://github.com/einpraegsam/powermail/blob/develop/Configuration/TypoScript/Main/setup.txt#L518

Everything else would be a new feature. PR are always welcome :)
