### ISSUE TITLE
Backend module Extended Search, Filter by answer fields not working

### ISSUE THREAD

**Issue by janmaennig** [einpraegsam/powermail#194]
Hello!

If I try to search emails by an answer field, zip code, for example, the filter does not work. Instead, i see all emails in the result list.

The used powermail version is 4.1.0.

Best regards!
Jan

**Comment by einpraegsam** [comment]
I tried it in my testparcours but all seems to work as expected:
<img src="https://s.nimbus.everhelper.me/attachment/1242725/ipn6nheh56hxkeswf35a/262407-A6qsRQPUgKXTbtob/screen.png" />

Are you really shure that your searchterm is not used in some other fields?

**Comment by janmaennig** [comment]
My problem is located in the "Extend Search" and the "Additional Fields". 

![screen](https://user-images.githubusercontent.com/5433846/32779428-112f97be-c93e-11e7-9998-83253aeed650.png)

**Comment by einpraegsam** [comment]
Thx, now a I can also see the problem. Will have a look at it.

**Comment by einpraegsam** [comment]
The bug was introduced on 20170828 in Revision eaeffa7f9ffe623cd187699a856e91655f49055a
I pushed a fix to develop branch - ready for upcoming release.
