### ISSUE TITLE
Documentation not up to date Signal/Slot

### ISSUE THREAD

**Issue by peterbenke** [einpraegsam/powermail#195]
Hello together,

at first  I want to thank you for your great work.

The documentation in powermail version 4.2.0 is not up to date:
https://docs.typo3.org/typo3cms/extensions/powermail/ForDevelopers/SignalSlots/Index.html

sendTemplateEmailBeforeSend:
In2code\Powermail\Domain\Service\Mail\SendMailService
instead of 
In2code\Powermail\Domain\Service\SendMailService

Also in the example below.

Thanks.

**Comment by einpraegsam** [comment]
Thx for adding the issue, I will update the documentation as soon as possible

**Comment by einpraegsam** [comment]
Pushed an update to develop branch
