### ISSUE TITLE
Changing Typo3 backend tool partials

### ISSUE THREAD

**Issue by toh82** [einpraegsam/powermail#20]
Hey, great extension 

I don't know where I can put my question best, hope here is fine.

I want to change the typo3 backend tool layout about the template    `Resources\Private\Partials\Module\ListOld.html`, yes I'm on a typo3 6.2.x version. I want to change that template in a new extension, but it seems that it is not enough to change the partials setup within the typoscript config like this:

```
plugin.tx_powermail {
    view {
        partialRootPaths.30 = EXT:powermail_bulkorder/Resources/Private/Partials/
    }
}
```

Powermail: 2.25.2
Typo3: 6.2.19

What did I forget?

Greetings
Tobias Hartmann

**Comment by einpraegsam** [comment]
It would be fine if you could write a solution for other people with the same problem, but maybe my hint on Stackoverflow helped: http://stackoverflow.com/questions/41739596/changing-typo3-backend-powermail-tools

**Comment by toh82** [comment]
@einpraegsam yes it helped a lot, thanks again.
so, the solution was indeed to change the `plugin` to `module` like
```
module.tx_powermail {
    view {
        partialRootPaths.30 = EXT:ext_name/Resources/Private/Partials/
    }
}
```
