### ISSUE TITLE
Opt In Mail confirmation date/time

### ISSUE THREAD

**Issue by omp-gluehbirne** [einpraegsam/powermail#200]
Hi,

does powermail save the time and date of the confirmation of the Opt In Mail?

I need to sort the mails by confirmation date but the timestamp of the mails does not get updated when the user confirms and shows the time the user completed the form.

Is there away to sort the mails by confirmation date?

Thanks in advance.

**Comment by einpraegsam** [comment]
No, the time is not saved when a mail was confirmed. Probably the tstamp of the mail entry could help - but this is only the last time when the mail was changed.
