### ISSUE TITLE
action overviewBe

### ISSUE THREAD

**Issue by Naberd** [einpraegsam/powermail#201]
there is something wrong with paginate widget when i click buttons nothing happens.
when i manually enter page number it does open that page.. 
this happens only at forms overview page.. when i just browse mail list i have no issue there with widget.

used console tests to see what's wrong : 

```
jQuery('.pagination.pagination-block a[title="next"]').first().click(function(){
console.log('clicked');
});
```
normal click result in log : 
VM423:2 clicked
`jQuery('.pagination.pagination-block a[title="next"]').first().trigger("click");`
VM423:2 clicked

but i remain on same page  using version 4.0.2  but don't think that it matters much

**Comment by einpraegsam** [comment]
Thx for the hint. I pushed a fix to develop branch for the upcoming release.
