### ISSUE TITLE
Microsoft Security Essentials marks powermail zip as insecure

### ISSUE THREAD

**Issue by derghostface** [einpraegsam/powermail#203]
Since a couple of weeks I am unable to download the powermail zip via the official extension repository, because Microsoft Security Essentials (on Windows 7) marks the zip archive as unsecure (download trojan), see attached screenshot.
When I do a manual scan of the powermail folder in a TYPO3 installation, there is no alert.

Tested with:
- https://extensions.typo3.org/extension/download/powermail/4.3.1/zip/
- https://extensions.typo3.org/extension/download/powermail/4.0.0/zip/
- https://extensions.typo3.org/extension/download/powermail/3.22.1/zip/

![powermail-mse](https://user-images.githubusercontent.com/991597/33611859-16d78134-d9d0-11e7-97eb-e5d881644c41.png)

**Comment by einpraegsam** [comment]
Please test some other extensions and versions and give me feedback about it.
What about the ZIP from github: https://github.com/einpraegsam/powermail/archive/4.3.1.zip
Is it also marked as insecure?

**Comment by derghostface** [comment]
The ZIP from github is also marked as insecure.

I tested following extensions which all gave no warning:
- https://extensions.typo3.org/extension/download/news/6.1.1/zip/
- https://extensions.typo3.org/extension/download/vhs/4.3.3/zip/
- https://extensions.typo3.org/extension/download/realurl/2.3.0/zip/

I also tested it on another computer here in my company network. Same problem.

If you want I can test it on my private computer (with Windows 10) in the evening.

**Comment by pixeldesu** [comment]
I tested both Github and TYPO3 downloads using the Virustotal scanner and there's not a single hit with any of the signature sources.

TYPO3: https://www.virustotal.com/de/file/80c00b57186257150ceb5448bbae8d13be92e76ade7d5b099e44a4287f0a1d84/analysis/1512484182/  

Github: https://www.virustotal.com/de/file/254faa9762fdbaf5f164ec986a32cd52bae994d362dc9625436558e74d1309dd/analysis/1512484097/

**Comment by einpraegsam** [comment]
Thx @pixeldesu - I really don't know what Microsoft did here or if some users marked the ZIP as insecure or whatever. I also have no idea how to tell Microsoft the fail here. If anyone has some information regarding on this issue, you're welcome.

**Comment by einpraegsam** [comment]
I've uploaded a file for a deeper check to https://www.microsoft.com/en-us/wdsi/filesubmission - let's wait what the result is.

**Comment by einpraegsam** [comment]
The results are ready: Nothing found (see screenshot). 
What does that mean? There is no virus in a powermail zip. But will MS sharpen their tool to allow downloads of powermail.zip in future - I have no idea.
![bildschirmfoto am 2017-12-18 um 10 11 08-fullpage](https://user-images.githubusercontent.com/89055/34098265-022828b8-e3dc-11e7-8cf7-8ae1c81ff84f.png)
