### ISSUE TITLE
Invalid argument supplied for foreach() in Validator/ForeignValidator.php line 33

### ISSUE THREAD

**Issue by Shaquille23** [einpraegsam/powermail#204]
I got the following error, even with a formular with only 1 input text field:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1: PHP  Warning: Invalid argument supplied for foreach() in  /app/web/typo3conf/ext/powermail/Classes/Domain/Validator/ForeignValidator.php  line 33 \| TYPO3\CMS\Core\Error\Exception thrown in file  /usr/src/typo3_src-7.6.23/typo3/sysext/core/Classes/Error/ErrorHandler.php  in line 111. Requested URL:  http://domain.tld/?tx_powermail_pi1%5Baction%5D=create&tx_powermail_pi1%5Bcontroller%5D=Form&cHash=c08ea103495ef0fe9ee9091c618c6879

System:
TYPO3: 7.6.23
PHP Version 7.0.22-0ubuntu0.16.04.1
nginx/1.10.3
Running on docker: https://github.com/webdevops/TYPO3-docker-boilerplate

**Comment by einpraegsam** [comment]
Thx, I never heard about this error. Nevertheless I can imagine what's the problem is. I pushed a possible fix to develop branch.
