### ISSUE TITLE
problems with SSL/https and the form action url

### ISSUE THREAD

**Issue by Toccamonium** [einpraegsam/powermail#21]
Hi,

thanks for this very useful and comprehensive form extension. We are using ssl https on our website. Problem is that the powermail url ist http which causes an error and is of course not wanted. Is there something in the config I missed? Some solutions are telling to alter templates. But is there no other way to fix this problem? Thx!

Florian

**Comment by einpraegsam** [comment]
I don't think that's related to powermail. The extension can of course handle SSL configuration. Pls check your TypoScript settings and configuration.

**Comment by Toccamonium** [comment]
Jep, you are right ;) I had to switch the protocol to https on the page settings.
