### ISSUE TITLE
Can't override templateRootPaths

### ISSUE THREAD

**Issue by Nostrabramus** [einpraegsam/powermail#210]
Hello,
I have a problem with overriding of templates root path.
I can't override it and powermail keep on using its own template ("Form.html" inside "Resources/Private/Templates/Form/")

I'm using powermail 4.3.2 on TYPO3 8.7.8

This is my typoscript setup:

```
plugin.tx_powermail {
    view {
        templateRootPaths {
            0 = EXT:itawebtoolkit/Resources/Private/Extensions/powermail/Templates/
            1 = EXT:itawebtoolkit/Resources/Private/Extensions/powermail/Templates/
        }
        partialRootPaths {
            0 = EXT:itawebtoolkit/Resources/Private/Extensions/powermail/Partials/
            1 = EXT:itawebtoolkit/Resources/Private/Extensions/powermail/Partials/
        }
        layoutRootPaths {
            0 = EXT:itawebtoolkit/Resources/Private/Extensions/powermail/Layouts/
            1 = EXT:itawebtoolkit/Resources/Private/Extensions/powermail/Layouts/
        }
    }
}
```

and this are my typoscript constants:

```
plugin.tx_powermail {
        view {
                templateRootPath = EXT:itawebtoolkit/Resources/Private/Extensions/powermail/Templates/
                partialRootPath = EXT:itawebtoolkit/Resources/Private/Extensions/powermail/Partials/
                layoutRootPath = EXT:itawebtoolkit/Resources/Private/Extensions/powermail/Layouts/
        }
}
```

Thanks for your attention

**Comment by einpraegsam** [comment]
Pls check in object brower the orderings of your TypoScript templates. Of course your TypoScript must be loaded after the TypoScript of powermail.

**Comment by Nostrabramus** [comment]
Hello, 
I already checked it. 
In my first try my typoscript was loaded after all others static templates,
in my last try (as you can see in the code above) I override all others templates, partials, and layout root path, in setup and also in constants, just to be sure, but powermail is still using its templates, I can't understand how it can do it.

I also try to delete all configurations (see the code below) but powermail still use its templates

```
plugin.tx_powermail {
    view {
        templateRootPaths >
        partialRootPaths >
        layoutRootPaths >
    }
}
```

**Comment by Nostrabramus** [comment]
Hello,
as an experiment I was able to load my templates renaming the template folder of powermail, this means that my typoscript is working properly, but powermail takes it into account only after failing loading its fallbacks.
I suspect there is some bugs in powermails

in the extension documentation I found this which could be related:
2.12.0 | 2015-10-05 | Bugfix #70237: https://forge.typo3.org/issues/70237 Wrong order for templateRootPaths

**Comment by einpraegsam** [comment]
I don't believe in a bug in powermail yet because we use it in various projects and do not have any problems with overruling the paths like
```plugin.tx_powermail {
	view {
		partialRootPaths {
			1 = EXT:in2template/Resources/Private/Partials/Powermail/
		}
		templateRootPaths {
			1 = EXT:in2template/Resources/Private/Templates/Powermail/
		}
	}
}
```
Of course you have to use the same folder structure in this paths. E.g. if you want to overwrite the Form.html, there must be a file in `EXT:in2template/Resources/Private/Templates/Powermail/Form/Form.html`

**Comment by Nostrabramus** [comment]
Thanks for your answers,

I just tried your code, so I changhed the position of templateRootPaths folder 
- from: **EXT:my-extension/Resources/Private/Extensions/powermail/Templates/Powermail/** 
- to: **EXT:my-extension/Resources/Private/Templates/Powermail/** 
but I still have exactly the same problem, powermail uses my templates **only if** I remove the original one, so I get back to my folder structure.

Instead partialRootPaths works properly, so I had no problems overriding inputs partials fluid templates using my folder structure.

At this moment my typoscript code is:
```
plugin.tx_powermail {
    view {
        templateRootPaths {
            100 = EXT:my-extension/Resources/Private/Extensions/powermail/Templates/
        }
        partialRootPaths {
            100 = EXT:my-extension/Resources/Private/Extensions/powermail/Partials/
        }
        layoutRootPaths {
            100 = EXT:my-extension/Resources/Private/Extensions/powermail/Layouts/
        }
    }
}
```
And this code is working properly if powermail don't find the file Form.html inside "Resources/Private/Templates/Form/", so I temporarly renamed the file Form.html to prevent powermail from finding it, if Form.html exists powermail uses its own template, it's not the best but it works.

I also upgraded powermail to version 4.3.4 but the problem persists. 

Right now I could not do anything better than renaming the form.html file in order to force powermail to use the one contained in my extension.

Thanks for your time.

**Comment by einpraegsam** [comment]
Can you please test on a fresh TYPO3-Installation where only powermail is installed? Maybe you've installed any other extension that hacks into template rendering of TYPO3.

**Comment by Nostrabramus** [comment]
I just test it in another TYPO3-Installation (not a fresh new one, a test one, now I don't have the time), without my extension, I did the configuration directly in set typoscript with the templates in fileadmin/ folder and I had exactly the same problem.
I will try again in fresh TYPO3-installation as soon as possible and let you know. 

Thanks

**Comment by einpraegsam** [comment]
thx, pls let me know if I can help you
