### ISSUE TITLE
Error when Mail to Receiver is deactivated

### ISSUE THREAD

**Issue by SPHolzi** [einpraegsam/powermail#212]
Since V. 4.3 it's no more possible to deactivate the mail to the receiver by leaving the subject line empty. There is always an error displayed to the user:

"Fehler die Email konnte nicht versandt werden"

This makes powermail unusable for creating db entries without sending useless mails to dead mailboxes.

**Comment by einpraegsam** [comment]
Thx, will look at it asap.

**Comment by SPHolzi** [comment]
Thanx for this - tried to disable plugin.tx_powermail.receiver.enable but the only workaround is to send a blank mail to a noreply-receiver.

**Comment by einpraegsam** [comment]
The first thing that I tested was
```
plugin.tx_powermail.settings.setup {
	receiver.enable = 0
	sender.enable = 0
}
```
This works as expected: Mails are disabled, Db entry is saved. 
Next step: Check with empty subject

**Comment by einpraegsam** [comment]
I just tested with empty subjects (receiver and sender) and all works as expected on the latest powermail version in T3 8.7.
Can you pls give me some more information (T3 version, powermail version, composer/classic mode, Are mails correctly send if subject is not empty? Are there any extensions that extend powermail?) how to reproduce this issue. Maybe a screenshot of the error would also help.

**Comment by SPHolzi** [comment]
Hi - we are working on T3 7.6.23 and just updated from 4.2 to 4.3.5 which resulted in the error. Maisl are sent by SMTP-Auth Service.

If a Receiver / Subject is given, the mails are sent correctly and the error disappears. We do use these forms with Mail to Sender activated to give the user a feedback and are using double opt in. Mails are sent correctly but the nonexisting mail to the receiver results in the named error displayed in the frontend.

You can see this in https://www.duh.de/newsletter-abo/mailings-abbestellen/ - without receiver (error
A copy of the form is on https://www.duh.de/newsletter-abo/newsletter-abbestellen/ - here I added a noreply-address as a receiver and it works perfectly.

**Comment by einpraegsam** [comment]
Ok, I tested with TYPO3 7.6 (composer mode). Adding a plugin and check `double optin`. Adding values for receiver and sender but let the subject for the receiver empty. Go to frontend and fill out the form. Mail is send to the user. Next step: I click on the confirmation link and a new tab in browser opens without an error. In addition I get an email `Danke für die Mail` with all values.
So, now I'm running out of ideas for that.
BTW: My local test environment also uses a SMTP-connection to send mails.

**Comment by einpraegsam** [comment]
What if you send a testmail from the powermail backend module? Are you sure the mail is configured correctly? Some hosters does not allow a random sender email. The sender email must be configured correctly.

**Comment by SPHolzi** [comment]
Hi - many thanks for the deep investigation. Really great job!

Sending Mails does work perfectly - we do have some forms that send mails - they work perfectly.

**Comment by einpraegsam** [comment]
Ok, so I'm sorry but I'm running out of ideas. If I can't reproduce an issue, I can't fix it. The last thing would be to debug it on your machine.

**Comment by uocnma** [comment]
Hi, einpraegsam,

I dare to open this thread again because I can reproduce and confirm this behaviour of powermail on Typo3 7 LTS. The solution was - as you already said - to set plugin.tx_powermail.settings.receiver.enable = 0 in an extension template on the form page.
But that's not too comfortable. The editor should be able to setup a powermail form without asking his t3admin for help. 

I had a look at the code and think the error message occurs because of line 180 in Classes\Controller\FormController.php

```
          if ($this->isReceiverMailEnabled()) {
                /** @noinspection PhpMethodParametersCountMismatchInspection */
                $mailPreflight = $this->objectManager->get(SendReceiverMailPreflight::class, $this->settings);
                $isSent = $mailPreflight->sendReceiverMail($mail, $hash);
                if ($isSent === false) {
                    $this->addFlashMessage(
                        LocalizationUtility::translate('error_mail_not_created'),
                        '',
                        AbstractMessage::ERROR
                    );
                    $this->messageClass = 'error';
                }
            }
```
The method isReceiverMailEnabled() returns the constant mentioned above. But - in addition - it should check the settings of the plugin CE itself. Because even if receiver.enable is set to 1 the editor might not use the receiver function in his form and leaves the flexform empty.
I guess an addition of the condition in the first line of my snippet should be enough as a sustainable solution. Although I don't know why the error message seems not to appear in t3 8 LTS.

Kind regards,
Nelson.

**Comment by einpraegsam** [comment]
I think that there must be an exception anywhere in the try block.
Can you please look into syslog and write me the exception message? Otherwise please debug $exception in line 194.

**Comment by einpraegsam** [comment]
Any feedback for me?

**Comment by uocnma** [comment]
Hi, einpraegsam,
I have to consult our server admin because I don't have access to the logs. This won't change before January. I will share any additional information here then. Thank you very much for paying attention to my post above.

Kind regards,
Nelson.

**Comment by uocnma** [comment]
Hi, einpraegsam,
I have to consult our server admin because I don't have access to the logs. This won't change before January. I will share any additional information here then. Thank you very much for paying attention to my post above.

Kind regards,
Nelson.
