### ISSUE TITLE
OnSubmit event is triggered before form validation

### ISSUE THREAD

**Issue by rdk-pmis** [einpraegsam/powermail#214]
One of our customers is tracking form submissions as and event for Google Analytics.  According to Google Analytics this needs to be added to the OnSubmit event of the form.
I had a lot of trouble encoding it, but that part worked. However I notice that the OnSubmit is also triggered when the form is validating as not fully filled in. I've set the validation to Javascript only and the onsubmit still gets triggered. I tested this with a simple console.log function for onsubmit and when I try to submit a form that isn't valid I get on screen the message that one of the fields isn't filled in properly, but the console.log function is also triggered.
Validation should take place before the form onsubmit function gets triggered and if the form doesn't validate the onsubmit event shouldn't be triggered at all.

**Comment by einpraegsam** [comment]
Hi,

as you may have seen, powermail uses the parsley.js framework for clientside validation and not an own validation. So you should have a look at http://parsleyjs.org/doc/examples/events.html for some examples how to add own events.
In addition, you could also use https://docs.typo3.org/typo3cms/extensions/powermail/Faq/Index.html#how-can-i-add-a-callback-function-on-ajax-submit if you're turned on ajax submit.

Cheers
