### ISSUE TITLE
Uncaught TYPO3 Exception: #1320830018: The given string was not appended with a valid HMAC

### ISSUE THREAD

**Issue by agendartobias** [einpraegsam/powermail#215]
Hello, does anyone know what is this problem & how to solve it:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1320830018: The given string was not appended with a valid HMAC. | TYPO3\CMS\Extbase\Security\Exception\InvalidHashException thrown in file /srv/www/typo3/typo3_source/typo3_src-7.6.23/typo3/sysext/extbase/Classes/Security/Cryptography/HashService.php in line 94. Requested URL: http://mydomain/?tx_powermail_pi1%5Baction%5D=create&tx_powermail_pi1%5Bcontroller%5D=Form&cHash=e00797583173524cdb38be236dd4d43b

**Comment by einpraegsam** [comment]
No, I don't know about that problem yet.
Pls tell me your powermail version and how to reproduce this issue.

**Comment by agendartobias** [comment]
I am using 4.3.5.

I dont really know how to reproduce this issue.

In error log i get same issue every day, but time is different.

  | **03:43:51** |   |   | [0] LIVE |   | ERROR |   | Error handler |   | Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1320830018: The given string was not appended with a valid HMAC. \| TYPO3\CMS\Extbase\Security\Exception\InvalidHashException thrown in file /srv/www/typo3/typo3_source/typo3_src-7.6.23/typo3/sysext/extbase/Classes/Security/Cryptography/HashService.php in line 94. Requested URL: http://www.agenda.si/?tx_powermail_pi1%5Baction%5D=create&tx_powermail_pi1%5Bcontroller%5D=Form&cHash=e00797583173524cdb38be236dd4d43b |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  |   | **03:29:40** |   |   | [0] LIVE |   | ERROR |   | Error handler |   | Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1320830018: The given string was not appended with a valid HMAC. \| TYPO3\CMS\Extbase\Security\Exception\InvalidHashException thrown in file /srv/www/typo3/typo3_source/typo3_src-7.6.23/typo3/sysext/extbase/Classes/Security/Cryptography/HashService.php in line 94. Requested URL: http://www.agenda.si/?tx_powermail_pi1%5Baction%5D=create&tx_powermail_pi1%5Bcontroller%5D=Form&cHash=e00797583173524cdb38be236dd4d43b |  
  |   | **01:00:06** |   |   | [0] LIVE |   | ERROR |   | Error handler |   | Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1320830018: The given string was not appended with a valid HMAC. \| TYPO3\CMS\Extbase\Security\Exception\InvalidHashException thrown in file /srv/www/typo3/typo3_source/typo3_src-7.6.23/typo3/sysext/extbase/Classes/Security/Cryptography/HashService.php in line 94. Requested URL: http://www.agenda.si/?tx_powermail_pi1%5Baction%5D=create&tx_powermail_pi1%5Bcontroller%5D=Form&cHash=e00797583173524cdb38be236dd4d43b |  
  |   | **00:46:04** |   |   | [0] LIVE |   | ERROR |   | Error handler |   | Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1320830018: The given string was not appended with a valid HMAC. \| TYPO3\CMS\Extbase\Security\Exception\InvalidHashException thrown in file /srv/www/typo3/typo3_source/typo3_src-7.6.23/typo3/sysext/extbase/Classes/Security/Cryptography/HashService.php in line 94. Requested URL: http://www.agenda.si/?tx_powermail_pi1%5Baction%5D=create&tx_powermail_pi1%5Bcontroller%5D=Form&cHash=e00797583173524cdb38be236dd4d43b |  
  |   | 00:10:28 |   |   | [0] LIVE |   | ERROR |   | Error handler |   | Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1320830018: The given string was not appended with a valid HMAC. \| TYPO3\CMS\Extbase\Security\Exception\InvalidHashException thrown in file /srv/www/typo3/typo3_source/typo3_src-7.6.23/typo3/sysext/extbase/Classes/Security/Cryptography/HashService.php in line 94. Requested URL: http://www.agenda.si/?tx_powermail_pi1%5Baction%5D=create&tx_powermail_pi1%5Bcontroller%5D=Form&cHash=e00797583173524cdb38be236dd4d43b |  
  |   | 00:09:36 |   |   | [0] LIVE |   | ERROR |   | Error handler |   | Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1320830018: The given string was not appended with a valid HMAC. \| TYPO3\CMS\Extbase\Security\Exception\InvalidHashException thrown in file /srv/www/typo3/typo3_source/typo3_src-7.6.23/typo3/sysext/extbase/Classes/Security/Cryptography/HashService.php in line 94. Requested URL: http://www.agenda.si/?tx_powermail_pi1%5Baction%5D=create&tx_powermail_pi1%5Bcontroller%5D=Form&cHash=e00797583173524cdb38be236dd4d43b

  | 03:43:51 |   |   | [0] LIVE |   | ERROR |   | Error handler |   | Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1320830018: The given string was not appended with a valid HMAC. \| TYPO3\CMS\Extbase\Security\Exception\InvalidHashException thrown in file /srv/www/typo3/typo3_source/typo3_src-7.6.23/typo3/sysext/extbase/Classes/Security/Cryptography/HashService.php in line 94. Requested URL: http://www.agenda.si/?tx_powermail_pi1%5Baction%5D=create&tx_powermail_pi1%5Bcontroller%5D=Form&cHash=e00797583173524cdb38be236dd4d43b |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  |   | 03:29:40 |   |   | [0] LIVE |   | ERROR |   | Error handler |   | Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1320830018: The given string was not appended with a valid HMAC. \| TYPO3\CMS\Extbase\Security\Exception\InvalidHashException thrown in file /srv/www/typo3/typo3_source/typo3_src-7.6.23/typo3/sysext/extbase/Classes/Security/Cryptography/HashService.php in line 94. Requested URL: http://www.agenda.si/?tx_powermail_pi1%5Baction%5D=create&tx_powermail_pi1%5Bcontroller%5D=Form&cHash=e00797583173524cdb38be236dd4d43b |  
  |   | 01:00:06 |   |   | [0] LIVE |   | ERROR |   | Error handler |   | Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1320830018: The given string was not appended with a valid HMAC. \| TYPO3\CMS\Extbase\Security\Exception\InvalidHashException thrown in file /srv/www/typo3/typo3_source/typo3_src-7.6.23/typo3/sysext/extbase/Classes/Security/Cryptography/HashService.php in line 94. Requested URL: http://www.agenda.si/?tx_powermail_pi1%5Baction%5D=create&tx_powermail_pi1%5Bcontroller%5D=Form&cHash=e00797583173524cdb38be236dd4d43b |  
  |   | 00:46:04 |   |   | [0] LIVE |   | ERROR |   | Error handler |   | Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1320830018: The given string was not appended with a valid HMAC. \| TYPO3\CMS\Extbase\Security\Exception\InvalidHashException thrown in file /srv/www/typo3/typo3_source/typo3_src-7.6.23/typo3/sysext/extbase/Classes/Security/Cryptography/HashService.php in line 94. Requested URL: http://www.agenda.si/?tx_powermail_pi1%5Baction%5D=create&tx_powermail_pi1%5Bcontroller%5D=Form&cHash=e00797583173524cdb38be236dd4d43b |  
  |   | 00:10:28 |   |   | [0] LIVE |   | ERROR |   | Error handler |   | Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1320830018: The given string was not appended with a valid HMAC. \| TYPO3\CMS\Extbase\Security\Exception\InvalidHashException thrown in file /srv/www/typo3/typo3_source/typo3_src-7.6.23/typo3/sysext/extbase/Classes/Security/Cryptography/HashService.php in line 94. Requested URL: http://www.agenda.si/?tx_powermail_pi1%5Baction%5D=create&tx_powermail_pi1%5Bcontroller%5D=Form&cHash=e00797583173524cdb38be236dd4d43b |  
  |   | 00:09:36 |   |   | [0] LIVE |   | ERROR |   | Error handler |   | Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1320830018: The given string was not appended with a valid HMAC. \| TYPO3\CMS\Extbase\Security\Exception\InvalidHashException thrown in file /srv/www/typo3/typo3_source/typo3_src-7.6.23/typo3/sysext/extbase/Classes/Security/Cryptography/HashService.php in line 94. Requested URL: http://www.agenda.si/?tx_powermail_pi1%5Baction%5D=create&tx_powermail_pi1%5Bcontroller%5D=Form&cHash=e00797583173524cdb38be236dd4d43b

**Comment by einpraegsam** [comment]
This could happen if someone do a pentest or simply try to hack your website. It's normal that there is an entry in the log if the HMAC is wrong. I would search for the request in the request-log of your apache.
I think the function of powermail is not the problem.

**Comment by olivermeckel** [comment]
hi alex, i have the same issue. i first thought this problem is created by powermail. but i think this error is caused by spam bots which try to send automatically forms with manipulated input fields.
