### ISSUE TITLE
Sender Email?

### ISSUE THREAD

**Issue by eiranix** [einpraegsam/powermail#216]
Can I send the email to the sender as well?
I have set a subject on the "Mail to user" tab but nothing comes through. I would have assumed this would automatically use the field marked as the sender email.

If I set a fixed sender email for testing on the "Mail to user" tab the form gives an error and neither email is sent...?

**Comment by einpraegsam** [comment]
Did you tell powermail in which field the email address of the sender is located?
<img src="https://s.nimbus.everhelper.me/attachment/1385676/ca5ehdcdc2giqr3kz6rf/262407-s43M0tX2Rg4P30PM/screen.png" />

**Comment by eiranix** [comment]
Yes, both sender name and email fields have the appropriate boxes checked.

**Comment by einpraegsam** [comment]
If you add a subject, a sendername and senderemail and the checkbox is set, the main configuration is correct. If there is still no mail to the sender (even in spam folder), It could happen that the mailserver needs a special configuration. Some servers accept only a defined email-address as sender address - pls ask your provider.

**Comment by eiranix** [comment]
Oh ok, thank you, I'll check. It must must be a security issue or something.
