### ISSUE TITLE
Wrong Condition in unsafetest

### ISSUE THREAD

**Issue by nebrot** [einpraegsam/powermail#218]
Because of this condition
`if (!empty($rows[0]['review_state']) && $rows[0]['review_state'] === '0')`
the unsafetest is always true in PowermailVersionNoteViewHelper.php.

This should work:
`if (isset($rows[0]['review_state']) && $rows[0]['review_state'] === 0)`

Also correct name would be `isCurrentVersionUnsafeCheck` (not Unsave).

![powermail-unsafetest](https://user-images.githubusercontent.com/6941112/34940464-ed78487e-f9ef-11e7-97c1-9bf38a01e5e3.png)

TYPO3 9.0.0
Powermail 5.0.0

**Comment by einpraegsam** [comment]
Thx for you feedback. I pushed a fix to develop branch. Ready for the upcoming release.

**Comment by nebrot** [comment]
@einpraegsam Same problem with new version 5.2.1 in non-composer-mode

![powermail-bug-tests](https://user-images.githubusercontent.com/6941112/35341744-ae4f9db2-0126-11e8-9794-ce2cc16cb7a5.png)

**Comment by einpraegsam** [comment]
Thx for the feedback. To have two different modes is really a pain in the ass.

**Comment by nebrot** [comment]
This works for us:
`if (isset($rows[0]['review_state']) && $rows[0]['review_state'] === 0)`

and 
`<f:then><f:translate key="BackendCheckComposerModeComposer">Composer Mode</f:translate></f:then>
<f:else><f:translate key="BackendCheckComposerModeComposer">Classic Mode</f:translate></f:else>`

**Comment by nebrot** [comment]
Thx for the fix, works for us 👍

**Comment by einpraegsam** [comment]
Fine, I'm going to release a bugfix version
