### ISSUE TITLE
[BUG]Additional template paths for mails are resolved poorly

### ISSUE THREAD

**Issue by rupasix** [einpraegsam/powermail#222]
We've needed to change something in powermail/Resources/Private/Template/Mail/OptinMail.html so i've added TS to extend templates sources:

```
plugin.tx_powermail {
  view {
    templateRootPaths.100 = EXT:myext/Resources/Private/Plugins/powermail/Templates
    partialRootPaths.100 = EXT:myext/Resources/Private/Plugins/powermail/Partials
    layoutRootPaths.100 = EXT:myext/Resources/Private/Plugins/powermail/Layouts
  }
}
```
...and it won't work for mail content but everything was fine with frontend rendered content (eg. form). 
Our backend guy took some time to debug it and found that:
```
array(2 items)
  0 => '/root/typo3conf/ext/powermail/Resources/Private/Templates/' (81 chars)
  1 => '/root/typo3conf/ext/myext/Resources/Private/Plugins/powermail/Templates' (96 chars)

Extbase Variable Dump

'Mail/OptinMail.html' (19 chars)
```
So: symbol '/' at the end of path is somehow important for mail templates and according to https://docs.typo3.org/typo3cms/ExtbaseFluidBook/b-ExtbaseReference/Index.html#view my paths should be just fine. Propably issue is here: https://github.com/einpraegsam/powermail/blob/develop/Classes/Utility/TemplateUtility.php#L99

If we can help you with this issue somehow than let me know. We've tested it for powermail 4.4.0 and 5.1.0 on Typo3 8.7.9

**Comment by einpraegsam** [comment]
Thx, I fixed it in current develop branch. Now partialRootPaths without trailing slashes are also accepted.
