### ISSUE TITLE
Update fails

### ISSUE THREAD

**Issue by Henry7901** [einpraegsam/powermail#223]
Hi there,

trying to update powermail from 4.4.0 to 5.0.0 (or 5.0.1, or 5.1.0) via the Extension Manager fails. I get the following error:

The given class "In2code\Powermail\Slot\ConvertTableNames" is not a registered object.

(System: Typo3 8.7.9)

Thank you :-)

**Comment by einpraegsam** [comment]
The reason is simple: The class was removed. If you clean all caches in Install Tool, there should be no button in Extension Manager to update.
The good news: You don't need to update anything in database.
