### ISSUE TITLE
PowermailVersionNoteViewHelper breaks if tx_extensionmanager_domain_model_extension is empty

### ISSUE THREAD

**Issue by georgringer** [einpraegsam/powermail#224]
The checks in `PowermailVersionNoteViewHelper` rely on the fact that the extension manager table is filled which is often - especially on composer based installations - not valid.

It breaks then with the exception 
```
array_key_exists() expects parameter 2 to be array, null given

TypeError thrown in file
/app/web/typo3conf/ext/powermail/Classes/ViewHelpers/Be/PowermailVersionNoteViewHelper.php in line 123.
```

So instead of checking $rows[0] there must be some kind of notice as result to the user as it can't be checked if the version is safe or not.

**Comment by einpraegsam** [comment]
Thx, will check this

**Comment by einpraegsam** [comment]
Thx for digging into this issue. Fixed in develop branch. Ready for upcoming release.
