### ISSUE TITLE
TypeError when using custom validators

### ISSUE THREAD

**Issue by kvonspiczak** [einpraegsam/powermail#226]
Hello,

we're using 
- powermail 5.1.0
- cleverreach 0.1.2
- TYPO3 8.7.9
- PHP 7.0.27

the cleverreach extension declares some custom validators like this:
`
plugin.tx_powermail.settings.setup.validation.customValidation.120 = WapplerSystems\Cleverreach\Powermail\Validator\OptinValidator
`

Since the powermail extension uses `declare(strict_types=1);` this results in a TypeError:
`Core: Exception handler (WEB): Uncaught TYPO3 Exception: substr() expects parameter 1 to be string, integer given | TypeError thrown in file /var/www/typo3.lab/typo3conf/ext/powermail/Classes/Tca/AddOptionsToSelection.php in line 107. Requested URL: http://t3.domain.de/typo3/index.php?ajaxID=%2Fajax%2Frecord%2Finline%2Fcreate&ajaxToken=1022e8233d4a37c2cb1d9b2187afe1d2be661b54`

What is the correct way to register custom validators? I tried changing from 
`...validation.customValidation.120 = ` to `...validation.customValidation.optin = ` but then we get an error in the backend because the validation field in `tx_powermail_domain_model_field` only accepts integers and the backend renders strings as values for the <options> (see attached screenshot).

[screen](https://imgur.com/a/XtTeN)

Kind regards
Kevin

**Comment by einpraegsam** [comment]
Hi Kevin,

that sounds possible. Sorry for the bug. We have a huge testparcours which has to be solved by behaviour tests but only for https://docs.typo3.org/typo3cms/extensions/powermail/ForDevelopers/WriteOwnValidators/ServersideValidation/Index.html and https://docs.typo3.org/typo3cms/extensions/powermail/ForDevelopers/WriteOwnValidators/ClientsideValidation/Index.html and not by extending the customvalidator at the moment.
Can you please write (or link to your github) how the validators are registered and the validator itself?

Thx, Alex

**Comment by kvonspiczak** [comment]
Hi Alex,

this is the optIn validator: https://github.com/svewap/cleverreach/blob/master/Classes/Powermail/Validator/OptinValidator.php

And this is the one for opt out: https://github.com/svewap/cleverreach/blob/master/Classes/Powermail/Validator/OptoutValidator.php

Validators are registered here: https://github.com/svewap/cleverreach/blob/master/Configuration/TypoScript/Powermail/setup.txt

And here: https://github.com/svewap/cleverreach/blob/master/Configuration/TypoScript/TsConfig/Page/powermail.ts

Sorry for the link formatting, I’m replying from my phone and I don’t know how to format them properly in the mobile version

**Comment by kvonspiczak** [comment]
For the moment we solved it by downgrading to Pomermail v4

**Comment by einpraegsam** [comment]
Thx, will check this asap

**Comment by einpraegsam** [comment]
I pushed a fix to develop branch. Can you test with this version and give me feedback?

**Comment by kvonspiczak** [comment]
I will test on monday, when I'm back in the office and report the results here asap.
Thanks for your fast response :)

**Comment by kvonspiczak** [comment]
Hey,

looks fine to me. I can see the custom validators in the powermail content element, the values of the <options> are integers and no exceptions on saving/editing the content element. Seems to be working fine. When can we expect to see this in the master, so that we can go back and use the TER/master version?

Thank you

**Comment by einpraegsam** [comment]
I just released 5.3.1 which contains the fix

**Comment by KreativeKrise** [comment]
In powermail version 8.1.1 this bug occurs again.
