### ISSUE TITLE
Column 'uid' in field list is ambiguous with activated 'ElementBrowser replaces IRRE' im EM

### ISSUE THREAD

**Issue by christophlehmann** [einpraegsam/powermail#227]
TYPO3: 8.7.9
Powermail: 5.3.1

Saving a plugin with  activated `ElementBrowser replaces IRRE` leads to the Exception `Column 'uid' in field list is ambiguous with activated`

**Comment by einpraegsam** [comment]
I just fixed the issue in develop branch

**Comment by christophlehmann** [comment]
Nice, thank you very much!
