### ISSUE TITLE
“Choose a Powermail Form” select duplicate records if you use workspaces

### ISSUE THREAD

**Issue by supercaccia** [einpraegsam/powermail#228]
If you use TYPO3 with workspaces and versionig in the “Choose a Powermail Form” select you see all records forms, not only the correct forms record for the current workspace and the “correct status”

(data[tt_content][426282][pi_flexform][data][main][lDEF][settings.flexform.main.form][vDEF])

Same problem in powermail 3/4/5.
![form-select](https://user-images.githubusercontent.com/7404955/35610832-2095c248-0663-11e8-986f-6b59f00d04a7.JPG)

**Comment by einpraegsam** [comment]
Workspaces are not supported together with powermail - sorry for that.
PR are welcome of course.
