### ISSUE TITLE
Add field "hidden" in available fields of export

### ISSUE THREAD

**Issue by georgringer** [einpraegsam/powermail#229]
I am using powermail as a newsletter subscription with its double-opt in feature. Problem is that it is currently not possible to export the field `hidden` which holds the information if the registration is completed or not (which is kind of important info).

Solution would be to add this to the template
```
<li id="hidden" class="list-group-item list-group-item-warning pointer">
   <f:translate key="LLL:EXT:powermail/Resources/Private/Language/locallang_db.xlf:LGL.hidden" />
</li>
```

**Comment by einpraegsam** [comment]
A PR is welcome for the new field :)
