### ISSUE TITLE
{f:cObject(typoscriptObjectPath:'lib.receiver')} including userFunc does not return content in receiver-field

### ISSUE THREAD

**Issue by Gregor-Agnes** [einpraegsam/powermail#23]
I have a Receiver TS-cObject as 

`{f:cObject(typoscriptObjectPath:'lib.receiver')}`

The lib.receiver is a userFunc which return one or more E-Mail-Adresses in response to some conditions.

If I look at page.5 < lib.receiver as test, I see the response. But the Receiver-Address in the Email is always empty, thus no Mails are generated. 

If i fill the lib.receiver with text like test@test.de, everything works as expected.

Seems the Class gets not loaded in this context.
Tried namespace loading as well as includeLibs TS, both don't work. 
Tried on different installations as well. 

Can anyone confirm?

**Comment by einpraegsam** [comment]
I tested it with a UserFunc and I can't find any problems.

My TypoScript:
```
lib.rec = USER
lib.rec {
  includeLibs = fileadmin/powermail/user/Receiver.php
  userFunc = In2code\PowermailReceiver\UserFunc\Receiver->getReceivers
}
```

My PHP:
```
<?php
namespace In2code\PowermailReceiver\UserFunc;

class Receiver
{
  public function getReceivers()
  {
    return 'alex@in2code.de, alex@einpraegsam.net';
  }
}
```

Please double check your configuration
Nevertheless, do you know the concept of Predefined Receivers? This is a bit more sexy then using ViewHelpers in FlexForm: https://docs.typo3.org/typo3cms/extensions/powermail/ForAdministrators/BestPractice/DynamicReceiver/Index.html

**Comment by Gregor-Agnes** [comment]
Hi and thx again for your help.

I got it to work now with your  code like and I know the problem: I used

USER_INT instead of USER. Thougt this ist the right one, since the addresses shouldn't get cached :) but it seems, that the cache gets emptied before the email are send.

If I declare it as USER, it works.  

Sorry for bothering, I should have stayed to the documentation!

**Comment by einpraegsam** [comment]
It's not possible to call a USER_INT within another USER_INT - and powermail already runs uncached.
