### ISSUE TITLE
{form.css} stays empty in Fluid

### ISSUE THREAD

**Issue by josefglatz** [einpraegsam/powermail#232]
TYPO3 8.7 latest stable
EXT:powermail 5.4.0

---

# Problem

Setting the form class selectfield to predefined value=`nolabel` – `{form.css}` Fluid variable keeps empty.

I've used the default fluid EXT:powermail static include + bootstrap includes.

**Comment by einpraegsam** [comment]
I just tested and can't see a problem
<img src="https://s.nimbus.everhelper.me/attachment/1444561/12phzlrvknkmch7ms8xt/262407-pBTcgDJTYEmTwS6e/screen.png" />

BTW: There was a new feature before two weeks that prevents showing the label in HTML if css was set to nolabel - see https://github.com/einpraegsam/powermail/commit/727191030ec8f21d3a93ad4bced59caca300183f
Maybe this is the problem in your case?

**Comment by einpraegsam** [comment]
Any feedback for me?

**Comment by einpraegsam** [comment]
If not, I'm going to close this issue

**Comment by josefglatz** [comment]
Hi Alex, plz give me time until tomorrow. I will recheck!

**Comment by josefglatz** [comment]
Thanks @einpraegsam for your time. No problems in a fresh TYPO3 composer 8.7 installation with no fancy integration stuff.

I will continue my research. I think the problem relies anywhere else in our distribution. 

If it is still a problem, I will open a ticket

Cheers!

**Comment by responseinformationsdesign** [comment]
Issue still exists in powermail 7.1.0. (TYPO3 is 8.7.24)

**Comment by responseinformationsdesign** [comment]
Changing the select field in the TYPO3-backend changes the value for column "css" in table "tx_powermail_domain_model_page" instead of "tx_powermail_domain_model_form".
If the value was manually changed in the correct table frontent rendering is as exspected.

**Comment by einpraegsam** [comment]
Sorry, I don't get it. I just tested again with original HTML-Templates in 7.1.0 in T3 9.5. If I select "layout 1" for form and "layout 2" for page and "no label" for an input field, the markup is rendered correctly:
```
<form class="powermail_form powermail_form_243 layout1 form-horizontal " >

<h3>Nolabel - Label Form</h3>
<fieldset class="powermail_fieldset powermail_fieldset_309 layout2">
<legend class="powermail_legend">Label Page</legend>

<div class="row"><div class="powermail_fieldwrap powermail_fieldwrap_type_input powermail_fieldwrap_labelinput nolabel form-group col-md-6"><div class="col-sm-10"><input ...
```

**Comment by responseinformationsdesign** [comment]
I want to hide the label for the whole form.
If I change the layout for the form data set (tx_powermail_domain_model_form) the linked page data set is updated instead (tx_powermail_domain_model_page).
Therefore for the moment I have to change the column "css" in tx_powermail_domain_model_form via phpMyAdmin directly.

**Comment by einpraegsam** [comment]
Just to get you right:  Can you pls upload a screenshot where you change the layout and in addition the html source that's rendered?

**Comment by responseinformationsdesign** [comment]
Sorry, for the moment I can´t reproduce this issue (with powermail 7.2.0). Now I was able to set the CSS class via the TYPO3 backend as exspected.
