### ISSUE TITLE
Change supported PHP version in readme

### ISSUE THREAD

**Issue by georgringer** [einpraegsam/powermail#233]
stating to support `7.x` is not a good idea as you don't know how PHP 7.10 will look like. also the core does not support that. better just use that what you test, e.g. 7.2.

**Comment by einpraegsam** [comment]
Thx for the note. Maybe you're right - especially for the composer.json - to not break future builds.

**Comment by georgringer** [comment]
so  why closing then?

**Comment by einpraegsam** [comment]
Sorry, to many tasks on my desk - seems that I forgot to answer. There is not dependency in composer.json to PHP. The only dependency is set in ext_emconf. This will not break any build processes. I'm going to keep this.
