### ISSUE TITLE
Linefeeds get lost if confirmation page is used

### ISSUE THREAD

**Issue by responseinformationsdesign** [einpraegsam/powermail#234]
Confirmation page contains the converted (to <br>) linefeeds. If you go back or submit the confirmation page linefeeds get lost.
Without confirmation page linefeeds are correctly written to the database.

**Comment by einpraegsam** [comment]
Not on my system - I just tested with a textarea with more lines (submit to confirmation, go back to form, submit again and confirm). Pls tell me your TYPO3 and powermail version.
In addition: Do you use any technic to shorten/compress your HTML source? Can you please turn it off and test again?

**Comment by Hobokens** [comment]
I'm using TYPO3 8.710 and powermail v5.4. 
I can confirm what @responseinformationsdesign described when the extension 'sourceopt' is used.
After disabling it the linefeeds are written correctly  to database.

**Comment by einpraegsam** [comment]
Thx for the feedback. Maybe someone can create an issue to the ext sourceopt

**Comment by Hobokens** [comment]
I will do it.

**Comment by einpraegsam** [comment]
@responseinformationsdesign Is your problem related to the or a sourceopt extension?

**Comment by responseinformationsdesign** [comment]
Our problem is indeed related to sourceopt. If sourceopt is deactivated everything is fine.

**Comment by einpraegsam** [comment]
Ok, thx for the final feedback. I'm going to close this issue. Pls connect the author of sourceopt.
