### ISSUE TITLE
Should the URLs to the pages with "create" and "optinConfirm" be without cHash?

### ISSUE THREAD

**Issue by benjaminpick** [einpraegsam/powermail#236]
Hi,

I was investigating a problem we have with powermail and the current realurl-Version, and I stumbled over this:

```
If you supply cHash for non-cached plugin, you will pollute TYPO3 cache with many identical entries and make the site slower. You may also make RealURL slower because under certain conditions it re-creates cHash.

Unfortunately Extbase developers decided to make cHash on by default. Thus most Extbase-based plugins incorrectly use cHash even for non-cached plugins.
```
https://github.com/dmitryd/typo3-realurl/wiki/Notes-for-Developers

Did you consider dropping the cHash parameter?
I guess one consequence of the cHash parameter is that we see the Thank-you-Text on the create-page indexed for the search (as it is saved in the cache).

**Comment by einpraegsam** [comment]
I'm not sure where chash is used in detail in powermail. The createAction() is not cached by default. Any feedback on this?

**Comment by einpraegsam** [comment]
Any feedback for me?

**Comment by benjaminpick** [comment]
As far as I know, all actions are using cHash - but I didn't have the
time to test it exhaustively yet.

**Comment by einpraegsam** [comment]
So, same here. If there is not explicit need, I will close this issue for now.
