### ISSUE TITLE
When editing form on Frontend (feedit), error: parse_str() expects parameter 1 to be string, null given

### ISSUE THREAD

**Issue by mfvetter** [einpraegsam/powermail#237]
Hello, 

When editing a content element with a powermail plugin from the fronted, I an error happens:
```
parse_str() expects parameter 1 to be string, null given
TypeError thrown in file
/var/www/dev.lasierra.edu/typo3conf/ext/powermail/Classes/Utility/BackendUtility.php in line 176.
```
I tested only with feedit extension. I didn't test with the new frontend_editing extension.

Tested on Typo3 8.7.10, Powermail 5.4.0

**Comment by einpraegsam** [comment]
Thx for the feedback. I pushed a fix to develop branch.

**Comment by einpraegsam** [comment]
Ready for the upcoming release
