### ISSUE TITLE
Numeric marker disallowed

### ISSUE THREAD

**Issue by pquerner** [einpraegsam/powermail#240]
Error:

```
Uncaught TYPO3 Exception
substr() expects parameter 1 to be string, integer given 

TypeError thrown in file
/vagrant/httpdocs/xxx/web/typo3conf/ext/powermail/Classes/Controller/AbstractController.php in line 117.

22 substr(11, 0, 2)

/vagrant/httpdocs/xxx/web/typo3conf/ext/powermail/Classes/Controller/AbstractController.php:
00115:         foreach ((array)$arguments['field'] as $marker => $value) {
00116:             // ignore internal fields (honeypod)
00117:             if (substr($marker, 0, 2) === '__') {
00118:                 continue;
00119:             }
```

Steps to reproduce

1. Create Valid form for testing. One Page and 1 Inputfield is enough.
1.1 Create "Field" type with numeric "Title" (or create custom marker with numeric input. For example "11").
2. Go to Frontend and attempt to submit the form
3. You should see the error above.

**Comment by lochmueller** [comment]
👍 please add missing "(string)" casts for $marker variable in string usage.

**Comment by einpraegsam** [comment]
Markers should not have only numbers within. I pushed a fix.

**Comment by einpraegsam** [comment]
Ready for upcoming release
