### ISSUE TITLE
FormController: get/set SettingsMain

### ISSUE THREAD

**Issue by ayesil** [einpraegsam/powermail#243]
ich möchte NoOptin Forms (nicht opt-in) nach eine Überprüfung (zB ein Checkbox true gesetzt) auf Optin ändern. 

Mein Idee ist:
Bei FormController:createActionBeforeRenderView kann ich überprüfen das Field und möchte ich "$this->settings['main']['optin']" als true überschreiben.

$this->settings ist protected und wenn möglich,können wir FormController erweitern und so zwei function hinzufügen:

```
getSettingsMain()
setSettingsMain($this->settings['main'])
```

Vielen Dank und viel Gruß,
Latif

**Comment by einpraegsam** [comment]
Pls write in english only.
You could do some magic via TypoScript. If you want to change configuration, you should have a look at the offered signals from powermail.
