### ISSUE TITLE
Flashmessage when sending of mails failed

### ISSUE THREAD

**Issue by mmunz** [einpraegsam/powermail#244]
After upgrading to 5.5 (from 4.2) i noticed, that no flashmessage is shown anymore to the user, just the usual "Thanks, we received your mail".
Before there was a funtion in FormController.php which set the flashmessage.

The flashmessage was removed with https://github.com/einpraegsam/powermail/commit/592f5e43ef909631c5c6d3d0f7d14e4754582d2a#diff-9be814694be6df5e78c712753ce34c11R196

Is there any reason for that or was it just a mistake?

**Comment by einpraegsam** [comment]
I'm not totally sure. Why do you miss the flashmessage? Can you please describe a scenario where you needed the message?

**Comment by mmunz** [comment]
@einpraegsam It ist mostly for informing the user that the mail could not be sent.

A bit more background: We delete old mails every few days from the database and therefore want to make sure no mails are lost because the mail server was unreachable or so. Informing the user that the mail was not sent is the least we can do here.

**Comment by einpraegsam** [comment]
I think we should not revert the change. There are many situations where mails should not be send (if its turned off via FlexForm or TypoScript) by default. In the past there where misleading error messages of this. Or let's say it in another way: Showing an absolute correct message in frontend if there was a real error is a missing feature at the moment.

**Comment by mmunz** [comment]
I don't agree here. It is essential for a user to have instant feedback instead of everything looking like it worked when in fact it didn't. Just re-adding the flash message shouldn't break stuff in cases where no mail is sent (from what i know from reading the code). Would it be ok to open a new ticket for this regression aka missing feature?

A more complete solution might be to also add the mailing-status (mail sent, error etc) to the table containing the mails, eventually even try to resend mails which were unable to send.
