### ISSUE TITLE
Rendering exception: Undeclared arguments passed to ViewHelper In2code\Powermail\ViewHelpers\Validation\ValidationDataAttributeViewHelper:

### ISSUE THREAD

**Issue by fgerards** [einpraegsam/powermail#245]
With TYPO3 8.7.10 + powermail 5.5.0 + PHP 7.1 we experience an exception with the original HTML/JS/CSS of powermail extension, when trying to render a form.

Exception is thrown in TYPO3Fluid\Fluid\Core\ViewHelper\Exception thrown in file
/typo3_src-8.7.10/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php in line 476.

"vhs" Extension had similar problem in TYPO3 v8: https://github.com/FluidTYPO3/vhs/issues/1100.

**Comment by fgerards** [comment]
![image](https://user-images.githubusercontent.com/1511030/37217722-93b6526a-23be-11e8-9a27-61a96638a931.png)

**Comment by fgerards** [comment]
method throwing the error in TYPO3 core states as follows:

`    /**
     * Default implementation of validating additional, undeclared arguments.
     * In this implementation the behavior is to consistently throw an error
     * about NOT supporting any additional arguments. This method MUST be
     * overridden by any ViewHelper that desires this support and this inherited
     * method must not be called, obviously.
     *
     * @throws Exception
     * @param array $arguments
     * @return void
     */
    public function validateAdditionalArguments(array $arguments)
    {
        if (!empty($arguments)) {
            throw new Exception(
                sprintf(
                    'Undeclared arguments passed to ViewHelper %s: %s. Valid arguments are: %s',
                    get_class($this),
                    implode(', ', array_keys($arguments)),
                    implode(', ', array_keys($this->argumentDefinitions))
                )
            );
        }
    }`

should it be overridden in Powermails AbstractViewHelper ?

**Comment by fgerards** [comment]
solved - system contained a custom ValidationDataAttributeViewHelper not compatible with v8

**Comment by einpraegsam** [comment]
thx for the final message

**Comment by filiperhiza** [comment]
In my case, the Powermail layouts and Partials was from one older version.
