### ISSUE TITLE
fe_typo_user Cookie

### ISSUE THREAD

**Issue by TBschen** [einpraegsam/powermail#252]
I noticed that a "fe_typo_user" Cookie is generated each time I open a page with the powermail plugin. 
Is there a reason to that? Does it save form data or something?

**Comment by einpraegsam** [comment]
Did you add the static template for marketing tracking?

**Comment by TBschen** [comment]
I only added "Main Template".  I've also disabled marketing information in the extension settings.

**Comment by einpraegsam** [comment]
Basicly there are two things, that need to store a cookie in powermail:
1) Marketing Tracking (could be added/removed in static templates)
2) Spamshield session check (could be deactivated via TypoScript)

**Comment by TBschen** [comment]
Ok, it was not the marketing tracking and spamshield also was deactivated.
Turns out it was the captcha (ext:captcha) I used. I didn't even think of that.

**Comment by einpraegsam** [comment]
thx for the final feedback
