### ISSUE TITLE
individual Optin Mail text

### ISSUE THREAD

**Issue by zabinetta** [einpraegsam/powermail#253]
could you maybe add a field in the plugin-backend-flexform where some individual double-optin-message could be placed? Like "Please confirm your registration for conference xyz"
with the best regards,
Sabine

**Comment by einpraegsam** [comment]
This feature request comes up from time to time. But there are no plans yet for an implementation. PR or sponsoring are always welcome.

**Comment by sventendo** [comment]
Option added in #350 .

**Comment by tomhatzer** [comment]
@einpraegsam could you possibly have a look at the PR from @sventendo ? There's one merge conflict in the language file though...

Thank you very much!
