### ISSUE TITLE
Viewing mail record details in backend takes very long

### ISSUE THREAD

**Issue by dlehrl** [einpraegsam/powermail#255]
Hi there,

i have a specific problem regarding editing mail records in TYPO3 backend.
When you select a mail record via **List module > 'folder' > Mails 'record'** it takes a very long time for the contents to show.

I figured that it has something to do with the high number of the stored records (>12.000 mail records & >140.000 answer records).

Is there a way to create a more performant query ?
My thought of a solution was to maybe override certain field TCAs, but until now i wasn't able to adjust the query to fit my needs.

Thanks and regards.

System:
- TYPO3 7.6.25
- Powermail 4.4.0

**Comment by einpraegsam** [comment]
What exactly takes the time? The rendering of the listview or if you open a mail record? How many children elements are related to the mail record if so?
BTW: I don't think that this issue is related to powermail but more to TYPO3 itself.

**Comment by einpraegsam** [comment]
Ok, but at the moment I see no solution for this issue. In addition it's more related to the core in my eyes and mail answers can vie seen in the backend module of powermail (which do not need IRRE) - so I will close this issue.
