### ISSUE TITLE
Attribute tabindex for input elements

### ISSUE THREAD

**Issue by chequille** [einpraegsam/powermail#256]
Hi Georg,
I currently think about having the possibility to move from input to input with tab.
You know, the issue with barrier free accesebility.

Did you ever think about it to implement this?

Best regards,
Jürgen

**Comment by einpraegsam** [comment]
No, there is nothing planned for tabindexes at the moment.
BTW: Alex, not Georg :)

**Comment by chequille** [comment]
Yes Alex :-)
Georg is "news" 
So sorry !!!
Ok, I try to implement something within the templates.

Take care
Jürgen
