### ISSUE TITLE
powermail not sending email when sender email is typoscriptObject

### ISSUE THREAD

**Issue by millemedia** [einpraegsam/powermail#257]
Hi, 
I have an issue with powermail. I generate the email address from table tt_address. When I implement {f:cObject(typoscriptObjectPath:'lib.receiver')} in reciever and in sender powermail is not sending emails.
With reciever it's working.
Best regards 
Andreas

**Comment by einpraegsam** [comment]
Can you please provide some screenshots of your FlexForm configuration? In addition it would be fine to see your TypoScript related to lib.receiver

**Comment by millemedia** [comment]
Hi Alex, 

TS:

lib.receiver = CONTENT
lib.receiver {
    table = tt_address
    select {
        # Page with tt_address records
        pidInList = 83

        where {
            # UID of the tt_address record is given in field with marker {produktgruppe}
            data = GP:tx_powermail_pi1|field|produktgruppe

            wrap = description = '|'
        }
    }
    renderObj = TEXT
    renderObj {
            field = email
    }
}
lib.receiverName = CONTENT
lib.receiverName {
    table = tt_address
    select {
        # Page with tt_address records
        pidInList = 83

        where {
            # UID of the tt_address record is given in field with marker {produktgruppe}
            data = GP:tx_powermail_pi1|field|produktgruppe

            wrap = description = '|'
        }
    }
    renderObj = TEXT
    renderObj {
            field = name
            
    }
}

Screenshot from Flexform:

![flexform_form](https://user-images.githubusercontent.com/12829123/38033976-8b6a3706-32a1-11e8-9f1d-0e79f919add6.png)
![flexform_reciever](https://user-images.githubusercontent.com/12829123/38033977-8b8f0270-32a1-11e8-91bd-daa57b344015.png)
![flexform_sender](https://user-images.githubusercontent.com/12829123/38033978-8bb04dfe-32a1-11e8-8278-a3e445249448.png)

**Comment by einpraegsam** [comment]
Because I have a different testparcours then your system, I tested with a different lib.receiver cObject function. And all works as expected. Please double check your configuration and the mail-server-requirements.

My small testcase:
```lib.rec = TEXT
lib.rec.value = email1@domain.org, email2@domain.org```

BTW: Note that most of the mail servers don't accept random sender-email-addresses any more - ask your hoster

**Comment by knarfomax** [comment]
Hello einpraegsam, 
we have exactly the same issue. typoscriptObject works fine except when we use it as sender mail address  The sender mail stays empty and the mail is not sent.
TYPO3 9.5. Powermail 7.3.0
