### ISSUE TITLE
Update 4.4.0 to 5.0.0 fails

### ISSUE THREAD

**Issue by FinMike** [einpraegsam/powermail#258]
On a TYPO3 8.7.12, this comes up:
 Error: The ViewHelper "<vh:Misc.GetFlashMessagesPartialName>" could not be resolved. Based on your spelling, the system would load the class "In2code\Powermail\ViewHelpers\Misc\GetFlashMessagesPartialNameViewHelper", however this class does not exist. (error code 1407060572).
I did follow https://docs.typo3.org/typo3cms/extensions/powermail/ForAdministrators/Upgrade/Index.html
Thanks for any hints!

Michael

**Comment by einpraegsam** [comment]
Please try again with original HTML-Templates and -Partials and cleaned cache. I'm sure that this will solve your issue.

**Comment by FinMike** [comment]
Thank you so much, original templates helped. 

Best wishes, Michael
