### ISSUE TITLE
Problem with the flexform field "settings.flexform.main.form"

### ISSUE THREAD

**Issue by xavierley** [einpraegsam/powermail#259]
Hello,

We have a problem with the field "settings.flexform.main.form" of the flexform. It displays all the forms of our instance (even from sites not configured with the tsconfig tx_powermail.flexForm.formSelection). 

After a little debugging, it seems that the problem is in the function getWhereStatement of the class In2code\Powermail\Tca\FormSelectorUserFunc, as there iare no parentesis aroud the part of the statement concerning the language, all forms that have a sys_language_uid IN (0,-1) are displayed.

A solution would be to simply add parentesis, like in the following line : 
$where = '(sys_language_uid IN (-1,0) or (l10n_parent = 0 and sys_language_uid = ' . (int)$language . '))';

instead of : 
$where = 'sys_language_uid IN (-1,0) or (l10n_parent = 0 and sys_language_uid = ' . (int)$language . ')';

Thank you very much,
Best regards

**Comment by einpraegsam** [comment]
At the moment only form titles from default languages are shown. That is a wanted behaviour.

**Comment by Cmytxy** [comment]
You misunderstand @xavierley.
He didn't wished for any other languages than default, but found a bug in your SQL that causes `and pid in (xxx)` to be infective. Due to this bug the pageTSconfig `tx_powermail.flexForm.formSelection` doesn't work.

Please read his post again!
