### ISSUE TITLE
string validation fails

### ISSUE THREAD

**Issue by daCyberpunk** [einpraegsam/powermail#261]
When I add a regex Validation to a input field, with the regex `^[A-Za-z\u00C0-\u017F]+$` as recommended in [documentation](https://docs.typo3.org/typo3cms/extensions/powermail/ForEditors/AddANewForm/FieldInput/Index.html) the validation fails with error:

> PHP Warning: preg_match(): Compilation failed: PCRE does not support \L, \l, \N{name}, \U, or \u

Unfortunately I could not find a solution to suggest and as we do not really need that validation on that fields, we just turned them of. :-) But wanted to report that.

**Comment by einpraegsam** [comment]
As far as I remember this were untested examples. Because you didn't need it and because I have a bit less spare-time for powermail, I will close this issue for now.
