### ISSUE TITLE
Drop ConfigurationUtility::isEnableTableGarbageCollectionActive()

### ISSUE THREAD

**Issue by georgringer** [einpraegsam/powermail#263]
I propose to drop the configuration `ConfigurationUtility::isEnableTableGarbageCollectionActive()` and always add the tables to the garbage collector task.

Reasons:
- Less configuration
- Easier for everybody
- Less to maintain
- Because of GDPR this will/must be more often used

**Comment by einpraegsam** [comment]
Can you please point me to the File (I can't find it in the code)?

**Comment by georgringer** [comment]
sorry checked older version of powermail, just ignore it
