### ISSUE TITLE
Problem with backend export of more than one form per sysfolder

### ISSUE THREAD

**Issue by kaispanka** [einpraegsam/powermail#264]
We use one sysfolder for the email and answer datasets of the forms, configured in the plugin field "Where to save Mails (empty = same page)". An backend export (xls or csv) without using the filter "Reduce to one form: " lost some of the data. Adding the subject as first column to identify the forms, the export contains only the subject for some forms but no data. Only the first pointing form to the sysfolder has all correct data, the later created not. If I choose a form (no matter which one) in the filter "Reduce to one form: " all data are given correctly, for all the single forms. The data are stored correctly in the given folder.

**Comment by einpraegsam** [comment]
This is correct and a side-effect of the chosen extension structure. There is no simple solution for that issue at the moment.
Please export per form.
