### ISSUE TITLE
<f:link.page> tags in email

### ISSUE THREAD

**Issue by glucka** [einpraegsam/powermail#265]
If you have <f:link.page pageUid="1" target="_blank">f.e. Privacy link</f:link.page> in checkbox field.
I think this should be removed in plain email.

**Comment by einpraegsam** [comment]
Please don't use HTML for your checkbox values. Chrome (e.g.) don't support sending html on form submit by default.
If you want to have a link in the checkbox label, please use a configuration like:
`<f:link.page pageUid="1">privacy accepted</f:link.page> | privacy accepted`

**Comment by glucka** [comment]
Thank you @einpraegsam!!!

**Comment by einpraegsam** [comment]
Please open a new issue with some screenshots of your options and some additional information like the version of powermail, the version of TYPO3, if you're using any add ons to powermail, etc...
