### ISSUE TITLE
BUG: Ignore submit button required attribute when rendering the form

### ISSUE THREAD

**Issue by zechendorf** [einpraegsam/powermail#266]
Under certain conditions submitting a form will always lead to "required field missing" validation failure.

# To reproduce
* Create a new form
* Define two input fields (for example: test / test2)
* Set field test2 as "required"
* Save the form
* Change test2 to type "submit"

# Expected result
The form should render with the input field "test" and a "submit"-button (test2). Submitting the form should succeed.

# Actual result
Submitting the form fails with "required field test2 missing" message. But in the TYPO3 backend a "submit"-button does not have the "required" attribute (so it can't be changed to "not required") *and* the editor can't even see that it is set as required.

# Solutions
* Easy: Show the required field in TCA for type submit-button
* Clean: validationConfiguration should discount "required" attribute when type=='submit'

I'm willing to provide a solution for either case. Please let me know what is preferred (or if no change is wanted at all).

**Comment by einpraegsam** [comment]
I will close this issue for now but don't hesitate to add a PR for a solution in the field model if you are still interested.
