### ISSUE TITLE
Language field missing translations for [All] and Default

### ISSUE THREAD

**Issue by npoggenburg** [einpraegsam/powermail#267]
Hello,

it looks like the TYPO3 Core Translation for [All] and Default is not shown in powermail form record.

**Screenshot from powermail:**
Project 1:
![bildschirmfoto 2018-04-30 um 14 50 04](https://user-images.githubusercontent.com/18659807/39428215-e9003c36-4c86-11e8-9611-ab4801c54433.png)

Project 2:
![bildschirmfoto 2018-04-30 um 15 08 02](https://user-images.githubusercontent.com/18659807/39428620-5b5c3086-4c88-11e8-8c16-6bd332157382.png)

**Screenshot from news (Project 2):**
![bildschirmfoto 2018-04-30 um 15 02 05](https://user-images.githubusercontent.com/18659807/39428446-a48fca02-4c87-11e8-81ba-c06e6421d694.png)

I checked two more projects, and all of them have the first two entries in the selectbox empty. 

The translations come from the TYPO3 Core lang Extension:
`'items' => 
[ ['LLL:EXT:lang/locallang_general.xml:LGL.allLanguages', -1], ['LLL:EXT:lang/locallang_general.xml:LGL.default_value', 0] ],`

**Comment by einpraegsam** [comment]
Thx, I pushed a fix to develop branch. Ready for the upcoming release.
