### ISSUE TITLE
Powermail checkbox email link

### ISSUE THREAD

**Issue by lammic77** [einpraegsam/powermail#273]
I followed the instruction in the documentation to confirm the privacy policy checkbox with a link to the terms. This works very well.

But if i want to use an email in the confirmation text rendered with <f:link.email email="abc@domain.org">abc@domain.org"></f:link.email> the crypted email breaks the code as follows:
"**ja(x)vascript:linkTo_UnCryptMailto('abcdefghijklmop123465789')**"

It doesnt matter how i configure the email spam protection. The word "javascript" even breaks with "**(x)**".` Normally brackets are used instead of the rounded ones.

**Comment by einpraegsam** [comment]
This is because of your config.spamProtectEmailAddresses settings. How should powermail work with it?

**Comment by lammic77** [comment]
You mean there is no solution to work with powermail?

**Comment by einpraegsam** [comment]
yes, I don't know a solution at the moment - sorry

**Comment by blueamerican** [comment]
Is there a possibility to exclude the "config.spamProtectEmailAddresses parsing" from powermail emails?
