### ISSUE TITLE
HTML Conform?

### ISSUE THREAD

**Issue by pprossi** [einpraegsam/powermail#274]
https://github.com/einpraegsam/powermail/blob/b79352a1883f395bff9f914821568013487e0f92/Resources/Private/Partials/Form/Field/Check.html#L9

i think this should be:
```
<label for="...">label</label>
<input type="checkbox" .../>
```
As in Powwermail dukumentation 
https://docs.typo3.org/typo3cms/extensions/powermail/ForEditors/AddANewForm/FieldCheck/Index.html#option-examples-for-checkbox

**Comment by einpraegsam** [comment]
Yes this is correct HTML. You can include input fields in label-tags or use for and an id alternatively. The documentation shows only an example.
