### ISSUE TITLE
Cannot Create new Form page since 6.0.0

### ISSUE THREAD

**Issue by bibusdax** [einpraegsam/powermail#275]
When creating a powermail form page via list mode I receive the following error:

2: SQL error: 'Unknown column '' in 'field list'' (tx_powermail_domain_model_page:NEW5afe63bcd2822322920874)

Also at first another extension crashed with the note that no $id had been set on this content element.

It is not even possible to copy existing powermail form pages as I then get the same error.

**Comment by einpraegsam** [comment]
Please do a db compare in install tool and give me feedback. In addition pls try powermail on a new typo3 instance.

**Comment by bibusdax** [comment]
Dear Alex Kellner,

We found the error and it was in a customised extension to powermail.
We removed it for now and then the bug was gone.

Sorry for the troubles.

Thank you very much, have a good start for this week and best regards,

Patrick Daxboeck
IT-Consultant

BIBUS AG Group
Allmendstrasse 26
8320 Fehraltorf
Switzerland
Direct   +41 44 877 50 34
Mobile  +41 78 781 06 48
Fax       +41 44 877 58 53
E-Mail   dax@bibus.ch
Internet www.bibus-technology.com

Von: Alex Kellner [mailto:notifications@github.com]
Gesendet: Montag, 28. Mai 2018 09:00
An: einpraegsam/powermail
Cc: Daxboeck Patrick; Author
Betreff: Re: [einpraegsam/powermail] Cannot Create new Form page since 6.0.0 (#275)


Please do a db compare in install tool and give me feedback. In addition pls try powermail on a new typo3 instance.
