### ISSUE TITLE
Add a link in a checkbox label

### ISSUE THREAD

**Issue by ingeniumdesign** [einpraegsam/powermail#276]
Hi,

my update in TYPO3 8 and PowerMail 6 works fine, but now i check this option for the Checkbox:

https://docs.typo3.org/typo3cms/extensions/powermail/ForAdministrators/Privacy/Index.html#add-a-link-in-a-checkbox-label

in the Fornted is then a Error:
> Oops, an error occurred!
> Fluid parse error in template source_69446025a6ea3476138fc3967997a71ddf7d5dbb_Standard_index_html, line 1 at character 14. Error: The ViewHelper "<f:link>" could not be resolved. Based on your spelling, the system would load the class "TYPO3Fluid\Fluid\ViewHelpers\LinkViewHelper", however this class does not exist. (error code 1407060572). Template source chunk: </f:link>
> More information regarding this error might be available online.

Thanks!

**Comment by mkoitka** [comment]
It may be due to a syntax error of the example that can be found in the documentation
See https://github.com/einpraegsam/powermail/pull/277/files

**Comment by einpraegsam** [comment]
Thx for the note - pls check this and give feedback

**Comment by einpraegsam** [comment]
Any feedback for me? Otherwise I'm going to close this issue
