### ISSUE TITLE
Labels in Partials

### ISSUE THREAD

**Issue by TBschen** [einpraegsam/powermail#279]
I noticed that the default Partial for Checkbox can cause issues with other libraries such as w3co/jcf (only noticed that in IE/Edge though). This is a combination of placing the input tag inside the label and the label not having the for-attribute. Adding the for-attribute (`<label for="powermail_field_{field.marker}_{index.cycle}">`) fixes it for me. It seems redundant but apparently there are rare cases where it helps.
It could just be added without causing problems, right?

**Comment by einpraegsam** [comment]
Changing the markup for some edge cases could always generate more problems then usage in my eyes. I'm not yet convinced for such a change - sorry.
