### ISSUE TITLE
Add Autocomplete Attribute / autocomplete=""

### ISSUE THREAD

**Issue by thomas-obernberger** [einpraegsam/powermail#281]
Modern users don't want to fill every form field on their own. Especially fields that could be filled automatically.

To get the best out of it, the browser must have to know, what content should be inside every single form field. This could be done/optimised by using the autocomplete attribute of the input tag.

This would be a great new feature!
(and also kills the verbose messages about in in Chrome)

**Comment by einpraegsam** [comment]
There is nothing planned like this in the next releases - sorry.
