### ISSUE TITLE
Double Opt-In setting with multi-language

### ISSUE THREAD

**Issue by kaesetoast** [einpraegsam/powermail#282]
Hi there,

I just noticed the following issue:

* I have a multi-language site with a powermail form
* Double Opt-In is activated for the default language
* There is a translation of that page
* For the translated Powermail-Plugin, the double Opt-In is deactivated
* Regardless of the setting in the translated element, the double Opt-In is still active

I noticed that there were similar issues report that had to do with multi-language and was wondering if this might also be a known issue which currently is hard to fix.

**Comment by einpraegsam** [comment]
It's possible that it's not possible to use different opt-in settings in different language versions, but I did not heard of this issue yet. This is probably an edge case. Because of my rare spare time I tend to close this issue - sorry.

**Comment by kaesetoast** [comment]
No worries – thanks for the quick answer :-)
