### ISSUE TITLE
Error with TypoScriptService after updating

### ISSUE THREAD

**Issue by walma7** [einpraegsam/powermail#283]
Hi!
After updating powermail to 6.0.0 i've got an error after submitting my forms.

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1289386765: Could not analyse class: "TYPO3\CMS\Core\TypoScript\TypoScriptService" maybe not loaded or no autoloader? Class TYPO3\CMS\Core\TypoScript\TypoScriptService does not exist | TYPO3\CMS\Extbase\Object\Container\Exception\UnknownObjectException thrown in file /home/vagrant/extdev/typo3_src/typo3/sysext/extbase/Classes/Object/Container/ClassInfoFactory.php in line 37.`

I'm not on the lastet 8.7 version of Typo3, but i think it have to do with 

> Important: #78650 - TypoScriptService class moved from Extbase to Core

Every use statement in powermail is defined with **TYPO3\CMS\Extbase\Service\TypoScriptService**, except of one in [\Classes\Finisher\SaveToAnyTableFinisher.php](https://github.com/einpraegsam/powermail/blob/c437480a77990c32b87b411fab66591a1ffd32ee/Classes/Finisher/SaveToAnyTableFinisher.php#L9) which already uses the new TYPO3\CMS\Core\TypoScript\TypoScriptService
If i change the line manually, everything works fine. Is it possible to change the line to the "old" definition?

**Comment by einpraegsam** [comment]
Can you please update TYPO3 to the newest bugfix version, clear all caches (in Install Tool) and try again please?

**Comment by walma7** [comment]
It's planned, but not possible that fast

**Comment by einpraegsam** [comment]
Any feedbck for me? Otherwise I'm going to close this issue.

**Comment by walma7** [comment]
Not yet, but why isn't it possible to change this one line back
I'm sure, that with the latest bugfix version it will run without error (because of #78650) ;)

**Comment by einpraegsam** [comment]
Because I don't fix issues that I can't reproduce. And believe me, there is a huge testparcours that have to be solved by automatic tests before every release.

**Comment by walma7** [comment]
I believe you, there are many tests and not all combinations can be tested.

But i will try to explain it, what i wanna point out:
In the files ConfigurationService.php, SessionUtility.php, FlexFormManipulationHook.php, CalculationCaptchaService.php, ReceiverMailReceiverPropertiesService.php, SendMailService.php, SenderMailPropertiesService.php and ReceiverMailSenderPropertiesService.php the TypoScriptService is defined using **TYPO3\CMS\Extbase\Service\TypoScriptService;**
That's ok and functional (and backward compatible), because of an alias (see https://docs.typo3.org/typo3cms/extensions/core/Changelog/8.7/Important-78650-TypoScriptServiceClassMovedFromExtbaseToCore.html)
Only in SaveToAnyTableFinisher,php is the "new" definition, which was added in commit 526611a, and so older versions of Typo3 throws an error, because they don't know **TYPO3\CMS\Core\TypoScript\TypoScriptService**
Finally this file isn't backward compatible.
And i think, any IDE will suggest the new one and not the old alias.

**Comment by einpraegsam** [comment]
Sorry for my late answer, but the last time was a bit of a busy time for me.
Nevertheless, I digged a bit into that issue.
So, the class `\TYPO3\CMS\Core\TypoScript\TypoScriptService` was introduced in https://github.com/TYPO3/TYPO3.CMS/commit/8f3659419c3c90c2fd1502c73e8952ec8ca755a6 and https://review.typo3.org/#/c/50589/ in TYPO3 and was released with 8.7.0.
So, in my eyes I should change the old use statements (as you wrote ConfigurationService, SessionUtility, etc...) to the new one (like it's already done in SaveToAnyTableFinisher).
The main question for me is: Why do you have this problem? Or do you still use TYPO3 in a version older then 8.7.0?

**Comment by walma7** [comment]
After upgrading to the latest 8.7.17 everything is ok.
It seems, that the installation used a commit before the final 8.7.0, but in the backend was 8.7.0 displayed.

**Comment by einpraegsam** [comment]
Thx, I changed the old use statements to the new one like I described in my last comment.
