### ISSUE TITLE
Feature: CSRF Protection

### ISSUE THREAD

**Issue by alexloetscher** [einpraegsam/powermail#286]
Hello,
Is it planned to include a CSRF-Protection like explained here: [Form Protection](https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/FormProtection/Index.html)?

Or can you tell me, how i implement a csrf-protection for my powermail forms?

Thanks and Greetings,
Alex

**Comment by einpraegsam** [comment]
No, not planned at the moment. Can't help because of my rare spare-time - sorry
