### ISSUE TITLE
Powermail 6.0 Double Opt-In aktiv fault

### ISSUE THREAD

**Issue by germai** [einpraegsam/powermail#289]
Hi,

after updating to version 6.0 with Typo3 8.7.15 we get the following error if the Opt-In option.

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1407060572: Fluid parse error in template Standard_action_index_5f33aad4371289e9c2ce1f4c576ca49a1f5a85cf, line 34 at character 4. Error: The ViewHelper "<vh:string.RawAndRemoveXss>" could not be resolved. Based on your spelling, the system would load the class "In2code\Powermail\ViewHelpers\String\RawAndRemoveXssViewHelper", however this class does not exist. (error code 1407060572). Template source chunk: <vh:string.RawAndRemoveXss> | TYPO3Fluid\Fluid\Core\Parser\Exception thrown in file xxxxxxx/typo3cms/typo3_src-8.7.15/vendor/typo3fluid/fluid/src/Core/Parser/TemplateParser.php in line 157. Requested URL: https://xxxxxxxxx/xxxxx/xxxxx/testversion/?tx_powermail_pi1%5Baction%5D=create&tx_powermail_pi1%5Bcontroller%5D=Form&cHash=95d159279e45a71868aa28eccffba03b

#1407060572: Fluid parse error in template Standard_action_index_5f33aad4371289e9c2ce1f4c576ca49a1f5a85cf, line 34 at character 4. Error: The ViewHelper "<vh:string.RawAndRemoveXss>" could not be resolved. Based on your spelling, the system would load the class "In2code\Powermail\ViewHelpers\String\RawAndRemoveXssViewHelper", however this class does not exist. (error code 1407060572). Template source chunk: <vh:string.RawAndRemoveXss> (More information)

TYPO3Fluid\Fluid\Core\Parser\Exception thrown in file
xxxxxxxxx/typo3cms/typo3_src-8.7.15/vendor/typo3fluid/fluid/src/Core/Parser/TemplateParser.php in line 157.

Do you have any idea?

**Comment by einpraegsam** [comment]
Yes I have. Please use original HTML-Templates and Partials from powermail and the error will be solved.

**Comment by germai** [comment]
Thanks for the tip. We forgot the modified e-mail templates. Everything else we had already switched off as a test. Sorry.
