### ISSUE TITLE
Additional field type not shown for newly created field

### ISSUE THREAD

**Issue by cweiske** [einpraegsam/powermail#29]
I defined my own field type via PageTSConfig:

    tx_powermail.flexForm.type.addFieldOptions.test = Testelement

Now I create a new form field within a form page, using the "new record after this record" button.
My custom type is not available.

Only after saving this once, the additional type is selectable in the type dropdown.

![2017-01-26 powermail custom type](https://cloud.githubusercontent.com/assets/59036/22341818/91c1848c-e3f2-11e6-94b7-2bd85ce903dc.png)

**Comment by einpraegsam** [comment]
I can't reproduce this issue on my testsystem (TYPO3 7.6 and newest powermail version). Creating a complete new form with a new page with a new field shows all field types.
Anything else what I can do to reproduce the problem?
Which powermail and TYPO3 version do you use?

**Comment by cweiske** [comment]
It happens on TYPO3 7.6.15 with latest powermail.

Steps to reproduce:
1. Create new form. Save.
2. Create page in form. Save
3. Create element in form. Save
4. Click "new record after this record" on the element.

The new second element does not have the additional field. After saving, the additional field is available.

**Comment by einpraegsam** [comment]
Yes, now I see the problem. On my testsytsem I have two additional fields:
1) Additional field added via page TSConfig in the parent page - this field is not visible (as you wrote before)
2) My second additional field is visible at once. It's a recaptcha and its TSConfig come from ext_tables.php in an additional extension. See: https://github.com/einpraegsam/powermailrecaptcha/blob/master/ext_tables.php
Seems to me that the TSConfig from the parent page is not always available in TYPO3 backend.

Nevertheless I think this is more related to the core than to powermail.
