### ISSUE TITLE
[Powermail 6.0.0] AJAX submit with mulitple uses of the same form returns no answerpage  

### ISSUE THREAD

**Issue by Merkutio** [einpraegsam/powermail#291]
If you include the same form more than once on the same page and have AJAX Submit enabled, there will be no answerpage displayed - mail sending works however.

Multiple occurences of the same value of the data-attribute "data-powermail-form" seem to be the issue here.

If you use a separat form for each powermail-element all works fine.

**Comment by macjohnny** [comment]
seems to be related to https://github.com/einpraegsam/powermail/pull/247

**Comment by einpraegsam** [comment]
It's not supported to use the same form more then only once per page at the moment. But this is not related to AJAX but to powermail itself.

**Comment by macjohnny** [comment]
@einpraegsam this feature could be achieved by merging #247, don't you think so?
