### ISSUE TITLE
Add aria-required="true"

### ISSUE THREAD

**Issue by schi** [einpraegsam/powermail#293]
Our website was testet by https://access-for-all.ch/ch/. A finding was that we have to mark required fields not only with a *.

In powermail/Classes/ViewHelpers/Validation/ValidationDataAttributeViewHelper.php
go to function addMandatoryAttributesForMultipleFields(array &$additionalAttributes, Field $field, $iteration)

and add `aria-required="true"` to required fields for better accessibility.

**Comment by einpraegsam** [comment]
Can you please provide an official documentation where the benefits of aria-required are described?

**Comment by schi** [comment]
From https://www.w3.org/Translations/WCAG20-de/#minimize-error
3.3.2 Beschriftungen (Labels) oder Anweisungen: Wenn der Inhalt eine Eingabe durch den Benutzer verlangt werden Beschriftungen (Labels) oder Anweisungen bereitgestellt. (Stufe A)

- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-required_attribute
- https://www.w3.org/TR/WCAG20-TECHS/ARIA2.html
- https://www.einfach-fuer-alle.de/wcag2.0/uebersetzungen/WCAG20-TECHS/aria/#ARIA2

Some modern screen reader understand HTML5 attribute `required`. Older doesn't but understand `aria-required`.

**Comment by schi** [comment]
Yes I'll try to do my first pull request.

**Comment by einpraegsam** [comment]
Thx for the PR. Some fixes are still needed and then I will accept it. Nevertheless I will close this issue for now (of course the PR is still open).
