### ISSUE TITLE
Preserve get-params while frontend editing

### ISSUE THREAD

**Issue by deflektor01** [einpraegsam/powermail#294]
I tried to keep some custom get-parameters in my url while using frontend editing on a page. When I save the changes with powermail's regular form submit button, the params get lost after reload of the edit page.

Adding addQueryString="TRUE" to <f:form> of fluid template Edit.html has no effect.

Are there any chances to achive that?

Thx in advance, Chris

**Comment by einpraegsam** [comment]
This is the way which I also would use and which should work. If not, I have no idea. 
`addQueryString="1"` to the form tag.
Another workarround could be to add the param to `config.linkVars` list.
Nevertheless this is not related to powermail but to TYPO3 or fluid.
