### ISSUE TITLE
Powermail Marketing eID script fails with pageNotFoundOnCHashError = true

### ISSUE THREAD

**Issue by peterkraume** [einpraegsam/powermail#295]
For `$GLOBALS['TYPO3_CONF_VARS']['FE']['pageNotFoundOnCHashError'] = true;` (which is the TYPO3 default setting currently), the eID script throws an 404 error.

How to reproduce:
1. put `$GLOBALS['TYPO3_CONF_VARS']['FE']['pageNotFoundOnCHashError'] = true;` to your AdditionalConfiguration.php
1. create a page with a basic TypoScript template and include Powermail Main Template and Powermail Marketing Information
1. open the developer tools in your browser and view the network tab
1. search for `http://domain.tld/index.php?&eID=powermailEidMarketing&tx_power....`

=> you see a 404 error for the request. If you set `pageNotFoundOnCHashError` to false, everythings works as expected.

Tested with:
- TYPO3 8.7
- EXT:powermail 6.0

**Comment by einpraegsam** [comment]
Thx Peter for your feedback. The solution would be to change the old eID script with a typenum call and disable the cHash-Check for this type. Nevertheless someone has to do it. Are you interested in doing a PR?

**Comment by peterkraume** [comment]
What do you mean with "old eID" script?

**Comment by einpraegsam** [comment]
Forget the "old".
In my the best solution would be to replace the eID script with a typeNum for the AJAX request - what do you think?

**Comment by peterkraume** [comment]
Isn't there an easier solution by disabling the cHash check within the eID script?

The rewrite is probably the better solution. But I'm not sure if I find the time for the rewrite. Nevertheless, maybe we can do a quick brainstorming, what needs to be done?

If I get you correctly, we need something like this:

TypoScript: new page object with another typeNum

```
marketingAjax = PAGE
marketingAjax {
  typeNum = 1529527964

  10 = USER
  10 {
    userFunc = TYPO3\CMS\Extbase\Core\Bootstrap->run
    extensionName = Powermail
    pluginName = Pi1
    vendorName = In2code
    controller = Form
    action = marketing
    view < plugin.tx_powermail.view
    settings < plugin.tx_powermail.settings
  }
}
```

But how do you want to disable the cHash?

**Comment by einpraegsam** [comment]
Yes, if there is an easy solution together with eID, I would also prefer this solution.
With TypeNum it's pretty simple - in your example:
```
marketingAjax = PAGE
marketingAjax {
  typeNum = 1529527964

  10 = USER
  10 {
    userFunc = TYPO3\CMS\Extbase\Core\Bootstrap->run
    extensionName = Powermail
    pluginName = Pi1
    vendorName = In2code
    controller = Form
    action = marketing
    view < plugin.tx_powermail.view
    settings < plugin.tx_powermail.settings
    features.requireCHashArgumentForActionArguments = 0
  }
}
```

**Comment by einpraegsam** [comment]
Still interested in a PR? Otherwise I will close this issue for now.

**Comment by peterkraume** [comment]
Yes, still interested. But it might take until August until I find time.

**Comment by einpraegsam** [comment]
I pushed this feature to develop branch. Will be released with the next version.
