### ISSUE TITLE
Prefill/preselect with get-Parameter

### ISSUE THREAD

**Issue by deflektor01** [einpraegsam/powermail#296]
I try to prefill a field by appending a get-parameter to url of form page. In T3 7 that worked according the extension manual, but in T3 8 it doesn't. I get this T3 error:

Page Not Found
Reason: Request parameters could not be validated (&cHash empty)

Do I miss something?

**Comment by einpraegsam** [comment]
This is a TYPO3 cHash error. You could deactivate the check by several methods (see https://github.com/einpraegsam/training/issues/2 for example).
