### ISSUE TITLE
Double Optin did not send a confirmation email

### ISSUE THREAD

**Issue by mlembach** [einpraegsam/powermail#305]
With Powermail 6.0.0 under Typo3 8.7.16 my form is submitted without any erros, but the confirmation mail cannot be received (Double Optin activated). If I submit the same form without double optin activated all mails are delivered. Our mail server did not receive any mails, if double optin is activated. If it is disabled the mail server receive the mails. Installation-Tool and function check from Powermail deliver also a mail. Tested was smtp, mail and sendmail. All results are the same.

Why can I send mails without double optin, but not if it is activated? Do you have any clues?

**Comment by einpraegsam** [comment]
The most common mistake is that there is missing configuration in FlexForm in Tab "Sender" - can you pls post a screenshot?

**Comment by mlembach** [comment]
<img width="1334" alt="setup" src="https://user-images.githubusercontent.com/41113471/42580881-cd893d1c-852b-11e8-8ad6-653b9844dbc7.png">

**Comment by einpraegsam** [comment]
Are you sure that your mailserver accepts mail from the sender @test.de? Nevertheless I still don't think that's a bug in powermail. BTW: I can't reproduce the issue on my system.

**Comment by mlembach** [comment]
I have talked to our provider, but he had no clue why no mail is sent. Neither in mail nor sendmail any sent mail is logged. If Double Optin is disabled, sending mails is working and the related mails show up in logs. We had also tested it with smtp, we've got the same behavior. 

After an update of powermail to the current version there was the same behavior as described. Next we downgraded to powermail version 4.4.0, then Double Optin worked for one day but stopped working unexpectedly without any clues.

I don`t think it is a problem with powermail but porvider related. We had also tested it with the same Typo3 and powermail version by another provider and there were no problems.

If you have any further ideas they are welcome. Otherwise you can close this issue.

**Comment by julianhofmann** [comment]
Finding the reason for not sending optin mails took me quite some time, too.

Somehow, optin mail depends on settings from the sender mail.
You have to configure _plugin.tx_powermail.settings.setup.sender.email = me@example.com_ independantly of using the sender mail.

**Comment by einpraegsam** [comment]
Thx Julian

**Comment by julianhofmann** [comment]
Öhm, Alex, I do not think, this is the solution.

It's strange, you have to set a value in the sender-mail to get the optin-mail working. Why it is not possible to set _email_ in block of optin settings? E.g. _plugin.tx_powermail.settings.setup.**optin**.email = me@example.com_ 

Or another use-case: You're using powermail without a mail to the sender (_plugin.tx_powermail.settings.setup.sender.enable = 0_), but with optin (for valid email address). Normally I would expect, I can ignore all other settings in _sender_-TS. But indeed, _sender.email_ has to be set via TS (in wrong block) or via FF.

**Comment by mkrappitz** [comment]
@einpraegsam I'm struggling with the same problem on powermail 7.0.0. and TYPO3 8.7.19. The symptons are exactly the same as @mlembach described above. 

And I also I agree with @julianhofmann that setting an arbitrary plugin.tx_powermail.settings.setup.optin.email = me@example.com to get this running is no real solution to the overall problem, that in my view the double opt in seems to be broken by default. Also setting plugin.tx_powermail.settings.setup.optin.email = me@example.com didn't fix this for us anyway.
No email is being is sent to the sender unless we uncheck the double opt in option in the plugin flexform. The email address for the double opt in confirmation email needs to be taken dynamically from the form field which has set "this is the email address of the sender" anyway. So no TS setting should be necessary  for this to work as long as powermail is able to send emails in general in the TYPO3 installation.
Powermail send mail test in backend module of powermail is successfull.
