### ISSUE TITLE
Conditions in mail to website-owner

### ISSUE THREAD

**Issue by bytesinmotion** [einpraegsam/powermail#309]
Hi,
is there a way to use conditions in the mail to receiver in Powermail? 

I habe a form where the user can fill out information for up to 4 requested rooms but the mail should only contain the values of the rooms if the part of the form is filled out. I'm not able to find out if that is possible?

**Comment by einpraegsam** [comment]
You could do everything you want in the mail templates with Fluid.

**Comment by bytesinmotion** [comment]
Oh gosh, didn't realize that.
Can I insert fluid code in the RTE in the TYPO3 backend or do I have to create a external html-template for the email?

**Comment by einpraegsam** [comment]
`<` and `>` will be htmlspecialchared in RTE but inline should work. Nevertheless you could do it in a nicer way in the mail template.
