### ISSUE TITLE
multipage export empty on some pages

### ISSUE THREAD

**Issue by shuffgy** [einpraegsam/powermail#310]
Hi! :)

I have TYPO3 8.7 installed with powermail (6.1) running and i want to export monthly all mails on every page. So i made some tasks for that. (Or is it possible to put serveral exports in one file?)

- Main Page 1
-- some subpages
-- contact <- export works
- Main Page 2
-- some subpages
-- contact <- export works
- Main Page 3
-- some subpages
-- contact <- export does not work

It doesn't matter if i use the sheduler with given ids and crdate or if i use the standard export function of powermail. 

The Export (xls or csv) looks like this:

![image](https://user-images.githubusercontent.com/17125448/43568005-d0b99216-9633-11e8-8c50-df8cc1755f00.png)

I already saw [this issue](https://github.com/einpraegsam/powermail/issues/98#issuecomment-313626888). Is there a bug or am i missing something?

**Comment by einpraegsam** [comment]
I do not know about a problem here. But I'm wondering how I can help you here. If you write it works on page A and B but not on C, I think someonw has to debug the export on C?

**Comment by einpraegsam** [comment]
Any feedback for me?

**Comment by chrisprog20** [comment]
I just had the same issue but I do not have the time to dig deeper into it.
In my case I had a simple xlsx export of the mail records of one form.
There were 7 entries. The two oldest showed old columns filled but the other 5 only had the date column filled. There were 4 test entries from the editor. After I deleted them the export worked like expected: all columns had filled entries. Maybe this helps on getting a glimpse why this behaviour happened.

**Comment by tlueder** [comment]
Powermail 4.4.0 / TYPO3 7.6.29 / PHP 7.0

Hi I'm also running into this issue.
In my case the export doesn't seem to lookup the right field set.

The Site has 2 contact forms. Both store their data in the same PID.
If I set the filter "Reduce to one form" to one of the form the export works.
But if I leave this filter empty the export seems to use only the first formset for all the mails.

**Comment by shuffgy** [comment]
Sorry, i had nothing more to say because i just did not understand the problem. But the option mentioned by @tlueder works for me. I had two forms to choose from, but each form is on a different "Main Page". 

Its been some time, but maybe i copyed it from "Main Page A" to "Main Page B", changed some labels and thats why? I dont know.

Question: If i want to include this form to the sheduler task, do i have to set some option in the sheduler so he does "reduce to one form"?

**Comment by einpraegsam** [comment]
Ok, so let's keep in mind: Export needs a "reduce to one form"
