### ISSUE TITLE
powermail_cond 5.0.0: Form not submitted with powermail 6.1.0

### ISSUE THREAD

**Issue by chrisprog20** [einpraegsam/powermail#313]
Hi Alex,

I deployed powermail 6.1.0 20 days ago and discvored that there is a bug with powermail_cond 5.0.0.
I use both extensions on TYPO3 8.7.17.

The bug is:
If the user submits the form it gets the server validated messages that some of the fields (the undisplayed ones by conditions) have not been filled out.

I switched then back to powermail 6.0.0 and after this the form was successfully submitted.

Thank you for checking this out :)

Best regards
Christian

PS: I also put this ticket under https://github.com/einpraegsam/powermail_cond/issues/21.

**Comment by PatrickPiroth** [comment]
I can confirm that, downgraded to 6.0.0 and works again.

**Comment by einpraegsam** [comment]
Hmm, ok maybe commit 00f79f88989f505ad22183c794fd87e18e63948f broke the functionality of powermail_cond. Have to dig deeper...

**Comment by simare** [comment]
Hi, is there an update on this issue? We make extensive use of conditional fields and are now bound to version 6.0.0.

Best,
Ramon

**Comment by foobar13372** [comment]
Any news here? We have this, too.

**Comment by Patta** [comment]
@foobar13372 I fixed it in that PR einpraegsam/powermail_cond#27. Can you review it?

**Comment by einpraegsam** [comment]
powermail_cond 6.0.0 will fix this issue - thx @Patta for his PR
