### ISSUE TITLE
Plain HTML output in powermail 2.25.3, htmlForHtmlFields doesn't work

### ISSUE THREAD

**Issue by stephaniestief** [einpraegsam/powermail#315]
Due to the fact that the html fields of our powermail form did only show plain html code, we investigated the issue. The parameter {settings.misc.disableRemoveXss} is called in the partial Html.html. Unfortunately, this parameter is not listed in the constants or setup TypoScript of the extension and therefore, it cannot be overwritten. If you add it manually to the contants.ts and setup.ts in the extension, it will be possible to overwrite it with your own TypoScript and the html output will work again.

**Comment by einpraegsam** [comment]
Released with 2.25.4
