### ISSUE TITLE
Powermail 4.4.0 not working with older content from version 1.5.3

### ISSUE THREAD

**Issue by manish128** [einpraegsam/powermail#318]
Powermail have problem in migrating the old data to new version.
I have setup my site into two different domains. One domain is setup with typo3 version 3.5 and powermail version 1.5.3.
I migrated this site to latest typo3 version 7.6.2 and updated the powermail version to 4.4.0 but now i am not able to use powermail as content type and not able to retrive existing powermail forms.

See attached screenshots for reference:

**Comment by einpraegsam** [comment]
There was no attachment. Nevertheless: If you update, it can happen, that there is old data in existing content elements.
What if you:
- Clear all caches in Install Tool
- Add a new content element

If the error still exists, please test on a new TYPO3 7.6.2 system.

**Comment by manish128** [comment]
Hello @einpraegsam

Thanks for your reply. but i tried with above both tricks and still the things are not working with powermail. Now i am using typo3 8.1 version and powermail 4.4.0.

**Comment by einpraegsam** [comment]
Sorry, I have no clue. Nevertheless the version is too old to be supported
