### ISSUE TITLE
current 2.x version missing on packagist.org

### ISSUE THREAD

**Issue by dwenzel** [einpraegsam/powermail#320]
The current the version 2.25.3 can not be installed from dist via `composer require in2code/powermail:^2.25.3` because packagist.org does not list this version. 

Instead it has to be installed requiring `typo3-ter/powermail:^2.25.3` which is deprecated IMHO.

Please publish the current version on packgist too.

cheers Dirk

**Comment by einpraegsam** [comment]
Powermail in the old version 2.x does not have a composer.json and so it's not loadable. I would load it over composer.typo3.org (see https://composer.typo3.org/ and search for `typo3-ter`)
