### ISSUE TITLE
Maxlength in HTML?

### ISSUE THREAD

**Issue by ursbraem** [einpraegsam/powermail#321]
The maxlength validation is output for parsley, but not as vanilla HTML `maxlength="10"` for input and textarea.
 
Is that on purpose or would it be worth a PR?

**Comment by ursbraem** [comment]
Ah, parsley supports minlength and maxlength, while in html, this is only possible for input fields (`pattern=".{5,10}"`), but not for textareas. So removing the parsley option would be a breaking change. 
What do you think about https://github.com/ursbraem/powermail/commit/059ea976ed763716e381decee0bb9d4cd5d1255b (backside: different behaviour depending on validation type)

**Comment by ursbraem** [comment]
I didn't do any testing yet. I don't think it's  best practice to have different behaviour for two modes...

**Comment by einpraegsam** [comment]
Sorry, don't get it. So what's your proposal to go on?

**Comment by ursbraem** [comment]
To close it.

**Comment by einpraegsam** [comment]
ok, anyways - thx for your time!

**Comment by ursbraem** [comment]
Can you reopen it? I'd be happy to give it another try. I think I was a bit quick

**Comment by ursbraem** [comment]
Current state

**validation.native = 0 & validation.client = 1** 
Value 100 -> <input type="text" data-parsley-length="[1, 100]" />
Value 10, 100 -> <input type="text" data-parsley-length="[10, 100]" />

**validation.native = 1 & validation.client = 0**
Value 100 -> <input type="text" />
Value 10, 100 -> <input type="text" />

**validation.native = 1 & validation.client = 1**
Value 100 -> <input type="text" data-parsley-length="[1, 100]" />
Value 10, 100 -> <input type="text" data-parsley-length="[10, 100]" />

Proposal (will be tested)

**validation.native = 0 & validation.client = 1** (same as above)
Value 100 -> <input type="text" data-parsley-length="[1, 100]" />
Value 10, 100 -> <input type="text" data-parsley-length="[10, 100]" />

**validation.native = 1 & validation.client = 0**
Value 100 -> <input type="text" maxlength="100"/>
Value 10, 100 -> <input type="text" maxlength="100"/> 

**validation.native = 1 & validation.client = 1**
Value 100 -> <input type="text" data-parsley-length="[1, 100]" maxlength="100" />
Value 10, 100 -> <input type="text" data-parsley-length="[10, 100]" maxlength="100" />
