### ISSUE TITLE
Powermail db.enable = 0 don't "work" if powermail form has Double Opt-In checked

### ISSUE THREAD

**Issue by agendartobias** [einpraegsam/powermail#323]
Hello, i have a problem with TypoScript constant plugin.tx_powermail.settings.db.enable = 0 - mails are still stored in DB.

If i uncheck my option in form "Mail must be confirmed (Double Opt-In)" then TypoScript configuration works OK, and mails are not stored in DB.

TYPO3 8.7.19
Powermail 6.1.0

**Comment by einpraegsam** [comment]
That's the wanted behaviour. Double Opt-In of course needs to save records - otherwise it would not be possible to reactivate them any time later.
