### ISSUE TITLE
mandatory checkbox keep checked on field change

### ISSUE THREAD

**Issue by vkemeter** [einpraegsam/powermail#324]
the mandatory checkbox keeps checked when switching the field type. which is not a problem at all - except when you switch to "submit" as type - then you have no chance to remove the mandatory field.

my idea: please check on fieldchange if the field has the mandatory option and if not, uncheck that field.

usecase: the editor copies fields and switches field types then.

thx and greets, volker.

**Comment by einpraegsam** [comment]
Thx, please specify what kind of problem happens. Is it the serverside validator when submitting a form in frontend?
BTW: Please write your powermail version

**Comment by vkemeter** [comment]
oh. sorry. 

first, the plugins still thinks, that the submit button is a mandatory field, so the validator stops sending the mail due to missing mandatory data.

the powermail version is 5.1.0, but the checkbox is in the dev-master branch also checked after field changes but i have at the moment not the possibility to check if the validator checks that on a submit field too.

**Comment by einpraegsam** [comment]
thx, for clarifiying

**Comment by einpraegsam** [comment]
This was already fixed in 6.1.0
