### ISSUE TITLE
Field Type Selectfield does not respect values from logged in Frontent User

### ISSUE THREAD

**Issue by cschnell** [einpraegsam/powermail#327]
When I am using a selectfield (as dropdown) and want it to be preselected with the correspnding value from fe_users table, the preselection does not work. I noticed this behaviour in all current powermail versions from 4.4.0 to 6.1.0
Example:
Table: fe_users, field gender contains the values 0,1 or 99
in the powermail field, I assigned the values like this:
`please choose ... |99`
`Female|0`
`Male|1`
and selected the field "gender" as Prefill Field - Value from logged in Frontent User

However, in the frontend, no option is preselected. 

I then tried to map the gender field to a plain text field and the value from the database (in my case "1") is inserted into the textfield, so it is working here.

**Comment by einpraegsam** [comment]
Just tested and I could not reproduce this issue.

What did I test:
- TYPO3 9.5
- powermail 6.1.0
- feusers.gender field added
- Extend the selection in TCA with pageTSConfig `tx_powermail.flexForm.feUserProperty.addFieldOptions.gender = Gender`
- Create select field with values `a` `b` and `c`
- Login with a fe_users with value `b`
- Open the form - selection is prefilled as expected

Maybe there is a problem with value 0 but I'm not sure - sorry
