### ISSUE TITLE
CompileWithRenderStatic not found FATAL ERROR

### ISSUE THREAD

**Issue by k1ngrnbz** [einpraegsam/powermail#328]
Hey Guys, 
I've got a Problem with **Powermail 4.4**. I just created a simple Form with one Checkbox and one inputfield(E-Mail). After i filled the required fields and clicked on the submit Button im getting this as Error. 

**The Error:** 
_Fatal error: Trait 'TYPO3Fluid\Fluid\Core\ViewHelper\Traits\CompileWithRenderStatic' not found in /var/www/clients/client4/web9/web/typo3conf/ext/powermail/Classes/ViewHelpers/Condition/IsArrayViewHelper.php on line 17_

I've downgradet the powermail Version but im still getting the same Error. Is there any solution for this?

**Typo3 Version:** 7.6.9
**PHP Version:** 5.6.24-0+deb8u1

**Comment by wilhelmwork** [comment]
Hi @k1ngrnbz ,

I have the exact same Problem at the moment. Can you tell me how you solved it? 

Thank you :)
