### ISSUE TITLE
[FEATURE] Counter for Mails, after X do sth.

### ISSUE THREAD

**Issue by webdev2027** [einpraegsam/powermail#331]
Hello Powermail-Team.

Maybe a good sugestion or feature for your great extension. 
Something like a counter. "How many mails can be sent via a powermail-form before it becomes unavailible". 

 X. Mails are allowed, after it there's a message (insetad of the form). "No further registrations/mails are possible" f.e. or you can enter a redirect to page xy?!

I need this feature for now and wrote an `user_func` with a redirect. That is also works fine, but it will be great for an editor to set the counter by flexform (s. screenshot).

Thank you.
Stefan

Example Flexform
![powermail_feature](https://user-images.githubusercontent.com/5501876/45691419-e9461300-bb58-11e8-83af-22ac5971674d.png)

**Comment by edekowalski** [comment]
Liebes Powermailteam,

ja das wäre ein super Feature! Das Powermail (Schweizer Taschenmesser) mit extra Feature. 

Beste Grüße
Ede

**Comment by einpraegsam** [comment]
Aktuell ist so etwas leider nicht geplant - sorry
