### ISSUE TITLE
HELP: add new attribute in File.html

### ISSUE THREAD

**Issue by agendartobias** [einpraegsam/powermail#332]
Hello, i want to add new "attribute" in ext/powermail/Resources/Private/Partials/Form/Field/File.html. Something like this:

`<vh:Form.MultiUpload
				id="file"
				property="{field.marker}"
				additionalAttributes="{vh:Validation.UploadAttributes(field:field)}"
				class="powermail_file {vh:Validation.ErrorClass(field:field, class: 'powermail_field_error')}"
data-multiple-caption="{count} files selected"
				 />` 

So i want to add data-multiple-caption="{count} files selected" - but FE wont render.
Can anyone help me?

**Comment by einpraegsam** [comment]
Shouldn't be that hard:
`<vh:Form.MultiUpload id="file" property="{field.marker}" additionalAttributes="{vh:Validation.UploadAttributes(field:field,additionalAttributes:'{data-multiple-caption:count}')}" class="powermail_file {vh:Validation.ErrorClass(field:field, class: 'powermail_field_error')}" data-multiple-caption="{count} files selected" />`

**Comment by agendartobias** [comment]
Tnx, but it dont work :( still no render in FE

**Comment by agendartobias** [comment]
Problem was {count} - i replace that in code #count# and it works tnx :D
