### ISSUE TITLE
HTML in powermail_all escaped (not from html field)

### ISSUE THREAD

**Issue by ursbraem** [einpraegsam/powermail#333]
- I have a form with a field `weblink`.
- On the confirmation page, the link should be rendered (for users to test it before submitting)
- I discovered the `manipulateVariablesInPowermailAllMarker` (thanks!) and did

```
weblink = TEXT
weblink {
    value.field = value
    typolink.parameter.field = value
}
```

The link is rendered, but output is escaped (`&lt;a href=&quot;http`...)

- `plugin.tx_powermail.settings.setup.misc.disableRemoveXss = 1` didn't help
- neither `weblink.htmlSpecialChars = 0`
- Also, I couldn't find an "escape" VH in the templates

Is that by design, or where can I turn off escaping in the powermail_all section (ideally only for that field)?

**Comment by einpraegsam** [comment]
Every value that is passed to Fluid will be htmlspecialchared by default for security reasons. At the moment it is not possible to disable only parts of the powermail_all variable but only the full output. Nevertheless I would recommand that because that would open the gates for some XSS issues.

**Comment by ursbraem** [comment]
Thanks!!
In `PowermailAll/Web.html`, I could query for the field's marker, so the risk would be reduced:

```
<f:if condition="{answer.field.marker} == 'weblink'">
    <f:then>
		<f:format.html><f:format.nl2br><vh:Misc.ManipulateValueWithTypoScript answer="{answer}" type="{type}">{answer.value}</vh:Misc.ManipulateValueWithTypoScript></f:format.nl2br></f:format.html>
		</f:then>
		<f:else>
		    <f:format.nl2br><vh:Misc.ManipulateValueWithTypoScript answer="{answer}" type="{type}">{answer.value}</vh:Misc.ManipulateValueWithTypoScript></f:format.nl2br>
		</f:else>
</f:if>
```
