### ISSUE TITLE
[FEATURE] dayOfWeekStart must be configurable

### ISSUE THREAD

**Issue by echavaillaz** [einpraegsam/powermail#334]
Hi,

It would be great if the first day of a week can be configurable in the datetime picker.
The setting for this in the library is `dayOfWeekStart : 0`

As a spoken french company we need to override manually the javascript each time we use this function.

Thanks a lot.

**Comment by alexkue7911** [comment]
Added PR for frontend

**Comment by einpraegsam** [comment]
Thx for your work, but because this change needs a lot of work to initialize and to maintain and because more and more browsers have a native datepicker now (Chrome, Firefox, etc...) I tend to not merge this issue for now - sorry.
