### ISSUE TITLE
Cannot disable sender mail with leaving the subject field blank

### ISSUE THREAD

**Issue by JesperBom** [einpraegsam/powermail#336]
First of all, the default for the `plugin.tx_powermail.settings.setup.sender.enable` is 1 (true).
In the options of a form you have the field to enter the subject for the senders mail, which states: `Subject for Email to Sender (Empty subject disables mail)`
However if you leave this field blank it will not be disabled for that form. It will be filled in the mail repository, see:
```
if (empty($email)) {
            $email = $this->getSenderMailFromDefault($default);
        }
        return $email;
```
(line 367 - 370 in `powermail/Classes/Domain/Repository/MailRepository.php`)
Which fills the email with the language label for `error_no_sender_mail` followed by the `getIndpEnv.
Therefor you cannot disable the sender mail by leaving the field blank.

Is this a bug or do I mess up with my setup? (edited)

**Comment by einpraegsam** [comment]
I just tested on TYPO3 8.7 with powermail 6.1.0 and everything works as expected. I also double checked it. Pls ensure that you don't overwrite a configuration via TypoScript.
