### ISSUE TITLE
possible compatibility issues to version 9.5

### ISSUE THREAD

**Issue by DavidBruchmann** [einpraegsam/powermail#337]
List in screenshot shall just serve as impression and explanation for this post.
Running the test is the simplest way to see the details.
![image](https://user-images.githubusercontent.com/999146/46711523-dc5ba180-cc76-11e8-9b5b-ac0acefe2ba5.png)

**Comment by einpraegsam** [comment]
Thx for the feedback. I pushed some smaller fixes to develop branch. Others are not so easy to solve in my eyes. So I will close this issue for now because this does not effect the function of powermail. But feel free to do a pull request.
