### ISSUE TITLE
"Numbers Only" validation fails to validate zip codes "01234"

### ISSUE THREAD

**Issue by cweiske** [einpraegsam/powermail#34]
German postal codes consist of digits only, 5 of them. They may start with a zero `0`.

We wanted to use the "numbers only" field validator to verify that the user only inputs digits, but that fails with zip codes like `01234`.

This is because `StringValidator::validateNumbersOnly()` converts the input to int, which strips off the leading zero. You could instead use `is_numeric`.

**Comment by einpraegsam** [comment]
If you choose validation for numbers only and use HTML5 validation, the field is turned into <input type="number" ... />
With this, the leading zeros will be substituted by the browser (see http://stackoverflow.com/questions/8437529/html5-input-type-number-removes-leading-zero for details).
You have to use pattern for the field or an own validation.
