### ISSUE TITLE
Access Settings in initializeObjectSettings SignalSlot 

### ISSUE THREAD

**Issue by hahrens** [einpraegsam/powermail#340]
Hey there, 
i cannot find a method to view/edit the configuration in the initializeObjectSettings-SignalSlot as documented in [the docs](https://docs.typo3.org/typo3cms/extensions/powermail/ForDevelopers/SignalSlots/Index.html#signal-slots). The settings property is protected and therefore unaccessible in the signal slot. The settings property is defined protected in https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/extbase/Classes/Mvc/Controller/AbstractController.php#L52 and not accessible via getter in that or one of the extending classes.

Or maybe the Docs are wrong since it says 
> Change Settings from Flexform or TypoScript before Action is called

Is there any method or trick to access the settings array in a signal? I currently need to access the flexform-settings in createActionBeforeRenderView.

**Comment by einpraegsam** [comment]
Duplicated to https://github.com/einpraegsam/powermail/issues/335

**Comment by mhirdes** [comment]
In #335 there is only a getter.  There is no way to manipulate the settings. Please provice a reference to $this->settings or merge them afterwards.

**Comment by einpraegsam** [comment]
PR are welcome
