### ISSUE TITLE
Choose a Powermail Form will show existing forms twice under TYPO3 9

### ISSUE THREAD

**Issue by stephangrass** [einpraegsam/powermail#342]
The "Choose a Powermail Form" dialog will show existing forms twice in the main-settings of the powermail plugin. 

I discovered this issue in a multipage installation using Typo3 9.5.0, Powermail 6.10

![2018-10-18_09-32-20](https://user-images.githubusercontent.com/4489147/47138208-0e918280-d2b9-11e8-9464-d1b480970fc0.png)
![2018-10-18_09-43-32](https://user-images.githubusercontent.com/4489147/47138706-6bda0380-d2ba-11e8-9050-ee7661b1a9e4.png)

**Comment by einpraegsam** [comment]
Thx for the feedback. I pushed a fix to develop branch. Will be released with the next release.
