### ISSUE TITLE
Type HTML on powermail 4.4.0

### ISSUE THREAD

**Issue by creativeworkx** [einpraegsam/powermail#347]
I am using powermail 4.4.0 on Typo3 7.6.31, unfortunately #77 seems to be back in 4.4.0.
The content of the HTML powermail form element is passed through htmlspecialchars(), thus ignoring
`plugin.tx_powermail.settings.misc.htmlForHtmlFields = 1` which is set in the constants

**Comment by einpraegsam** [comment]
Are you using original HTML-Templates and -Partials of powermail? If not pls test with them and give me feedback pls.

**Comment by creativeworkx** [comment]
You were right,
the former developer still used `plugin.tx_powermail.settings.setup.misc.disableRemoveXss = 1` in his templates, i solved it now.

Thank you
