### ISSUE TITLE
Optin and powermail_all marker

### ISSUE THREAD

**Issue by zabinetta** [einpraegsam/powermail#349]
Hi everybody,
we have a very strange behavior with the powermail_all marker when we use Optin:
normally all the fields are well sorted, in the powermail_all marker as in the form.
when we use a form without the optin: sorting works perfectly.
when we use a form with optin: the fields are perfectly sorted in the optin-mail, but later, in the receiver- and the sendermail, the sorting in powermail_all is all mixed up, and we even don't have an idea about any system after which they are mixed.
we use: 
typo3 8.7.19
powermail 6.1.0 (just updated from 6.0.0)
powermail_cond 6.1.0 (also just updated)

The behavior is unstable, too. Today we tried to send the form from a second page for testing, without optin (worked), then we tried  to fill in without any errors (worked), after a computer and browser restart (worked), and suddenly the normal filling worked too.
 
Has anybody had this?

I hope the problem is gone now, because it costed us lots of nerves, in fact: it is driving me nuts...
so please: if you can confirm this is has been solved, feel free to let me know :)
with the best regards, Sabine

**Comment by einpraegsam** [comment]
Sorry for the build in dwarf but I have no clue at the moment about this issue. Feel free to do a pull request if you find the failure.

**Comment by kitzberger** [comment]
Probably the same issue as #966
