### ISSUE TITLE
Powermail 7.0 - Marker isn't shown in subject line

### ISSUE THREAD

**Issue by Hobokens** [einpraegsam/powermail#351]
Hi,
I use TYPO3 8.7.19 and powermail 7.0. 
My problem: In the powermail module in the backend the marker in the subject line isn't shown anymore. I just get {name} instead of the name.

Regards
Hobokens

**Comment by einpraegsam** [comment]
Thx. Sounds so that an older version handled this issue. Can you please give me a version where this worked?

**Comment by Hobokens** [comment]
With powermail 6.2. everything was fine.

**Comment by einpraegsam** [comment]
Thx, seems that you're right - I can confirm this behaviour

**Comment by einpraegsam** [comment]
Playing around turned out that 9699f4c38cd2ec64dceecd686c0356a07a048006 breaks the behaviour - will check this

**Comment by Hobokens** [comment]
Thank you so much for taking care of this so quickly.

**Comment by einpraegsam** [comment]
Thx for your feedback. I pushed a fix to develop branch. Ready for upcoming release.
