### ISSUE TITLE
SessionUtility and usage of TypoScriptService

### ISSUE THREAD

**Issue by lukaszuznanski** [einpraegsam/powermail#353]
Hi, 

Powermail version 4.4 up to 5.6.0 is supposed to support TYPO3 8.7, but in SessionUtility class, there is usage of non-existing class TYPO3\CMS\Extbase\Service\TypoScriptService, in TYPO3 8.7 this class namespace is renamed to TYPO3\CMS\Core\TypoScript\TypoScriptService.

Should I provide PR?

**Comment by einpraegsam** [comment]
No because it's already fixed: https://github.com/einpraegsam/powermail/blob/develop/Classes/Utility/SessionUtility.php
What about updating to the latest version of powermail?
