### ISSUE TITLE
 Powermail 7.0.0: Checkbox renders hidden field - breaks functionality in IE11

### ISSUE THREAD

**Issue by kerygmafabian** [einpraegsam/powermail#355]
When using checkboxes the first checkbox cannot be selected by the user when using Internet Explorer 11. I investigated the issue and I think it's because powermail adds an input type="hidden" field for the first checkbox of every checkbox group. So IE11 might not be able to asscociate the label with the correct input type="checkbox" field and therefor fails to check it.
![image](https://user-images.githubusercontent.com/9252509/48271339-647ec380-e43c-11e8-9e96-d2047a13c367.png)

**Comment by einpraegsam** [comment]
The Fluid viewhelper `f:form.checkbox` always adds a hidden field and this is not part of the powermail extension. So, if there are really problems with that checkbox, pls report to fluid.
