### ISSUE TITLE
Extending predefined receivers dynamic example

### ISSUE THREAD

**Issue by uocnma** [einpraegsam/powermail#357]
Hi,

this is rather a bug report than a question to the documentation. I tried to post it on TYPO3.net but the forum runs currently in a timeout when I submit my text.

So I refer to https://docs.typo3.org/typo3cms/extensions/powermail/4.4.0/ForAdministrators/BestPractice/DynamicReceiver/Index.html
... and tried to extend the TS code for setting not only the email address but also the subject. 

This is where I ended up, the second CASE is evaluated the first CASE seems to be ignored. As subject the value from the flexform is set. If I clear the flexform field the mail is not sent at all.

plugin.tx_powermail.settings.receiver.enable = 0

#dynamic example 1
plugin.tx_powermail.settings.setup.receiver.predefinedReceiver {

    receivers1.subject = CASE
    receivers1.subject {
    
            key.data = GP:tx_powermail_pi1|field|anfragegrund

                1 = TEXT
                1.value = Text A

                2 = TEXT
                2.value = Text B
    }

        receivers1.email = CASE
        receivers1.email {

                key.data = GP:tx_powermail_pi1|field|anfragegrund

                1 = TEXT
                1.value = receiver-a@domain.de

                2 = TEXT
                2.value = receiver-b@domain.de
        }
}

Two questions:
- how can I manage to set the subject as well as the email ?
- can I access to the field values as I can in the flexform, e.g. "Hello {name}"

It would be very kind if someone could help me.

Cheers,
Nelson.

**Comment by einpraegsam** [comment]
The only possibility is to set the receiver email address via predefinedReceiver functionality. If you need another logic for your subject, you have to find a different way (cObject Viewhelper in Subject, Manipulation via SignalSlot, etc...)
