### ISSUE TITLE
Deprecated keys in ext_emconf.php

### ISSUE THREAD

**Issue by chrisprog20** [einpraegsam/powermail#360]
Hi Alex, 
I just saw that you use some deprecated keys in ext_emconf.php in powermail 7.0.0.
They are 'shy','dependencies', 'conflicts', 'priority','loadOrder','modify_tables','lockType','CGLcompliance' and 'CGLcompliance_note' 

Maybe you remove them in the next version.

Cheers
Christian

**Comment by einpraegsam** [comment]
Thx, I removed those keys
