### ISSUE TITLE
[question] prefill fields from extension using section

### ISSUE THREAD

**Issue by olivermeckel** [einpraegsam/powermail#361]
Hi Alex,

i have a small extension providing events all over my site.
by clicking on a button you can register for an event.

the registration should be done by powermail.
the button should submit 2 informations (event_data and place) to prefill the form.
this is done by additional get parameters.
the form is placed in a section at the end of a page.
so additional by clicking on the button it should jump to the contact section

i tried the following code

`
{settings.formpid} = Page UID where the form is placed
{cUID} = ID of the section

<f:link.page pageUid="{settings.formpid}" section="{cUID}" additionalParams="{tx_powermail_p1: {formfield:'value'}}" class="btn btn-primary">Neu anmelden</f:link.page>`

typo3 is generating a wrong link:
"url/ofmycontactpage?tx_powermail_p1%5formfield%5D=value&cHash=178377ff12868941812e10afdcbd081d#c96"

the page is called and it jumps to section, but no parameters are submitted.
generating a manual link ist causing an error

is there any hint for solving my problem?
in one case the events and the contact form are on the same page

ThX

I'm using
typo3 9.5.1
powermail 7.0.0
powermail_condition 7.0.0

7.0.0
--

**Comment by einpraegsam** [comment]
Sorry, but this is an issuetracker and no support forum. Please use slack or stackoverflow for getting help from the community.

**Comment by olivermeckel** [comment]
Hi Alex, of course, you are right!
