### ISSUE TITLE
ViewHelper Be.Container doesn't load jQuery - export breaks

### ISSUE THREAD

**Issue by kiwi2101** [einpraegsam/powermail#362]
ViewHelper Be.Container doesn't seam to load jQuery correct even when parameter loadJQuery="true". This causes the export to break. I had to include jquery manually in ext/powermail/Resources/Private/Layouts/Backend.html to fix this.

Typo3 Version 9.5.1, powermail Version 7.0.0

**Comment by einpraegsam** [comment]
Thx, the option loadJQuery="true" is disabled in TYPO3 9.x because it was removed. I think we have to use require.js for this.

**Comment by einpraegsam** [comment]
I just created a fix in develop branch. Can someone pls test it and give me feedback?

**Comment by Raemy92** [comment]
Works for me, thank you!

**Comment by kiwi2101** [comment]
Works for me, thanks for the fix!

**Comment by einpraegsam** [comment]
Thx for your feedback. This issue will be fixed in the next release.
