### ISSUE TITLE
No mails send with plugin.tx_powermail.settings.db.enable = 0

### ISSUE THREAD

**Issue by wowawebdesign** [einpraegsam/powermail#364]
If I disable the saving of emails in the database with the constant, no mails will be send at all.

The tests out of the install tool and the powermail backend module are working as expected.

**Comment by koehlersimon** [comment]
I can confirm this behaviour with TYPO3 9.5.1 and Powermail 7.0.0

**Comment by agendartobias** [comment]
+1

**Comment by crizzdeeann** [comment]
I can confirm this behaviour too.
- No Mails will be sent, if saving is disabled
- The Mails are stored even though db.enable is set to 0 ("plugin.tx_powermail.settings.db.enable = 0")
Typo3 version: 8.7.22
Powermail  version: 7.0.0

**Comment by einpraegsam** [comment]
Thx for your feedback. I pushed a fix to develop branch. Will be released with the next version.
