### ISSUE TITLE
No mail are sent with powermail 7 if sender fields are filled out

### ISSUE THREAD

**Issue by matthaa** [einpraegsam/powermail#365]
if in plugin powermail / sender all fields (mail of sender, email of sender,  subject of the mail to sender) are filled out no mails are sent if using powermail 7 - after downgrade to powermail 6.2 everything works as expected (TYPO3 is 8.7.20).

**Comment by einpraegsam** [comment]
I just tested with pwoermail and TYPO3 8.7.22 and everything works as expected. Are you sure that the mail was not send (Junk or Spam folders checked? Can the server send emails to the given email? Is the sender email allowed on the server?)?.

**Comment by einpraegsam** [comment]
I think this could be related on some configuration settings to #364 and that should be fixed in the upcoming version.
