### ISSUE TITLE
Property Mapping exception using confirmation page and recaptcha

### ISSUE THREAD

**Issue by featdd** [einpraegsam/powermail#366]
Hi,

I'm using powermail 4.4.0 and rh_recaptcha 1.1.1

If I activate the confirmation page in the plugin settings while using the recaptcha field it throws a mapping exception

`#1297759968: Exception while property mapping at property path "": It is not allowed to map property "answers". You need to use $propertyMappingConfiguration->allowProperties('answers') to enable mapping of this property. `

I debugged the request processing and could'nt find the specific problem, but somehow the allowing of "answers" as property is gone in redirecting to the create/confirmation action

Greetings
Daniel

**Comment by einpraegsam** [comment]
I'm not sure, but this sounds like a bug in rh_recaptcha?
Did you test powermailrecaptcha or invisiblerecaptcha?

**Comment by featdd** [comment]
I tested powermailrecaptcha and that worked, didn't have seen the incompatibility of the rh_recaptcha version. but thanks for the alternatives.
