### ISSUE TITLE
[BUG] PrefillFieldViewHelper ignores default argument

### ISSUE THREAD

**Issue by dkd-kaehm** [einpraegsam/powermail#367]
Following construct: 

`{vh:Misc.PrefillField(field:field, mail:mail, default:'DEU')}` does not work if no overwrites are defined.

Expected behaviour: 
use the value of default argument if $this->value after buildValue() is empty:
```
        if (!$this->isCachedForm()) {
            $this->buildValue();
        }
```
for example:
```
        if (!$this->isCachedForm()) {
            $this->buildValue();
        }
        if (empty($this->value)) {
            $this->setValue($default);
        }
```

**Comment by einpraegsam** [comment]
Thx for the feedback. I pushed a fix to develop branch. Will be fixed in the next release.
