### ISSUE TITLE
Backend-Module: Uploads including amp in path get escaped although amp is used for splitting parameters

### ISSUE THREAD

**Issue by jpmschuler** [einpraegsam/powermail#368]
**Describe the bug**
Backend modules using a typolink to a secure folder create an not-working escaped link

**Expected behavior**
With TYPO3 v7, in2code/powermail:4.4.0 and bitmotion/typo3-secure-downloads:2.0.6 I was able to have the powermail backend module generate links to a  "secured" folder, thus instead of a local link `fileadmin/securefolder/file.pdf` I got e.g. `/index.php?eID=tx_securedownloads&p=&u=0&g=0&t=1543425964&hash=4f009617f5a76ffc0d1f570b0a62c098a4e291c4&file=fileadmin/securefolder/file.pdf` and it worked flawlessly.

**Errornous behaviour**
With TYPO3 v8, in2code/powermail:7.0.0 and bitmotion/typo3-secure-downloads:2.0.6 and bitmotion/typo3-secure-downloads:3.0.0 I get escaped URLs like `/index.php?eID=tx_securedownloads&amp;p=&amp;u=0&amp;g=0&amp;t=1543425964&amp;hash=4f009617f5a76ffc0d1f570b0a62c098a4e291c4&amp;file=fileadmin/securefolder/file.pdf` which result in a hash mismatch exception as the hash is not found at all.

**To Reproduce**
Have a backend module which creates typolinks, have a file in a secured folder with working config for EXT:secure_downloads. 
1. Configure secure_downloads for a folder
2. Configure powermail and have a form which uploads a file to above folder
3. Submit Form in Frontend
3. Start backend module of powermail, select Form entry, analyse/click link to uploaded file

I'm crossposting this to both extensions (at least for further reference even if this extension is not responsible), will update as soon as I find the exact reason.

**Comment by jpmschuler** [comment]
rels https://github.com/bitmotion/typo3-secure-downloads/issues/29

**Comment by jpmschuler** [comment]
currently debugging this. Powermails https://github.com/einpraegsam/powermail/blob/c674d29b274cc012431c6534d397ef38a4e1c108/Classes/ViewHelpers/Misc/GetFileWithPathViewHelper.php#L53 returns a correct unescaped link like ```index.php?eID=tx_securedownloads&p=&u=0&g=0&t=1550936330&hash=ad5a06b0168379bf66c26991b1e4e5ff68a570ae&file=fileadmin/fileupload/geschuetzt/myfile.pdf``` (I just did a php-die() on the value) so the error seems to be in the rendering of the link inside powermail, not inside secure-downloads

**Comment by jpmschuler** [comment]
Ok dug deeper. The problem is in the **GetFileWithPathViewHelper** which is `AbstractViewHelper` instead of `AbstractTagBasedViewHelper`

**Comment by einpraegsam** [comment]
Merged in current develop branch
