### ISSUE TITLE
Can't deactivate SPAM check completely

### ISSUE THREAD

**Issue by koehlersimon** [einpraegsam/powermail#369]
In a simple one page form, fields randomly get marked as SPAM and I can't send the form anymore. The settings "spamshield.enable = 0" in the constants are set, but seem to have no effect. I double checked, if the TypoScript setup is correctly set and it is set to "spamshield._enable = 0"". Even after clearing all caches several times, the form still shows SPAM messages.

What I simply want is: Switch off any spam detection. Seems to be impossible in this constellation or in TYPO3 9.5.1. ?

**Comment by einpraegsam** [comment]
Probably this is not related to spam check. What is your configuration?

**Comment by einpraegsam** [comment]
I'm going to close this issue because of missing feedback.
