### ISSUE TITLE
Documentation: Example uses removed RawAndRemoveXss-ViewHelper

### ISSUE THREAD

**Issue by julianhofmann** [einpraegsam/powermail#370]
In the example "Add new Field Properties", EXT:powermailextended/Resources/Private/Partials/Form/Field/Input.html uses the RawAndRemoveXss-ViewHelper which has been removed in version 5.0.

**Comment by einpraegsam** [comment]
The extension powermailextended is outdated in general and has to be updated. Feel free to add issues or PR here: https://github.com/einpraegsam/powermailextended :)

**Comment by einpraegsam** [comment]
oh, ok, you're right - Interested in doing a PR?
