### ISSUE TITLE
Wrong germen translation for Function-Test Section Extension Manager Updated

### ISSUE THREAD

**Issue by beath** [einpraegsam/powermail#374]
In the backend module Powermail Function-Test Section the test Extension Manager Updated has a contradicting german translation.

Extension Manager Updated
Extension is correct installed - all settings available from localconf.php

is translated with

Erweiterungsmanager aktualisiert
Erweiterung wurde **nicht** richtig installiert - alle verfügbaren Einstellungen der localconf.php

The "nicht" negates the meaning which is wrong. Also localconf.php is now called LocalConfiguration.php.

**Comment by einpraegsam** [comment]
The wrong translation is not part of the extension itself. It came from the translation server of TYPO3: translation.typo3.org. For whatever reason this type of software is very buggy in my eyes. So I'm not able to change the text for the key `BackendCheckExtMngConfigCorrect` (it's loading and loading). 
Nevertheless every person in the community can change those translations.
