### ISSUE TITLE
TYPO3 9.5 Double opt in: validation failed

### ISSUE THREAD

**Issue by jacques2017** [einpraegsam/powermail#376]
Powermail 7
The Page shown after clicking the confirmation-Link in the mail show an error:

> Validation failed while trying to call In2code\Powermail\Controller\FormController->createAction(). 

All requried fields where filled out before. 
In file FormController.php on line 300 the createAction is called. After this the validation failed.
Can anybody confirm this issue?

**Comment by jacques2017** [comment]
I find a bug-fix, but it's not the solution:
In File FormController.php
For createAction add the annotation:
* @ignorevalidation $mail

**Comment by einpraegsam** [comment]
Do you have a captcha in your form?

**Comment by jacques2017** [comment]
Yes, I have the powermail captcha in my form.

**Comment by DavidBruchmann** [comment]
I've the same issue without captcha

**Comment by McKoy61** [comment]
Can confirm this issue. 
Typo3 9.5.5/Powermail 7.30
Captcha activated
Database analyzation ok, rebuilt autoload information, reinstalled extension – nothing helps.
Captcha deactivated (delete captcha-field from form): everything works fine.

**Comment by Wahni69** [comment]
Same here. Typo3 9.5.5 Powermail 7.3.0
When I use the Captach field, the error appear. As soon as I delete the captcha field, every thing works fine. Is there a work around?

**Comment by baggyownz** [comment]
Same issue in TYPO3 9.5.5 and powermail 7.2.0.
Does anybody fixed it without changing the source code? Or does @einpraegsam has a solution or an update in planning?

**Comment by patrickdadzio** [comment]
I have the same problem. The function "findByUid" always returns an empty result although the uid passed as a parameter exists in the database. That's the query:

SELECT
   `tx_powermail_domain_model_mail`.* 
FROM
   `tx_powermail_domain_model_mail` `tx_powermail_domain_model_mail` 
WHERE
   (
(`tx_powermail_domain_model_mail`.`sys_language_uid` = - 1) 
      OR 
      (
(`tx_powermail_domain_model_mail`.`sys_language_uid` = 1) 
         AND 
         (
            `tx_powermail_domain_model_mail`.`l10n_parent` IN 
            (
               SELECT
                  `tx_powermail_domain_model_mail_dl`.`uid` 
               FROM
                  `tx_powermail_domain_model_mail` `tx_powermail_domain_model_mail_dl` 
               WHERE
                  (
                     `tx_powermail_domain_model_mail_dl`.`l10n_parent` = 0
                  )
                  AND 
                  (
                     `tx_powermail_domain_model_mail_dl`.`sys_language_uid` = 0
                  )
                  AND 
                  (
(`tx_powermail_domain_model_mail_dl`.`deleted` = 0) 
                     AND 
                     (
                        `tx_powermail_domain_model_mail_dl`.`hidden` = 0
                     )
                     AND 
                     (
                        `tx_powermail_domain_model_mail_dl`.`starttime` <= 1558604580
                     )
                     AND 
                     (
(`tx_powermail_domain_model_mail_dl`.`endtime` = 0) 
                        OR 
                        (
                           `tx_powermail_domain_model_mail_dl`.`endtime` > 1558604580
                        )
                     )
                  )
            )
         )
      )
   )
   AND 
   (
      tx_powermail_domain_model_mail.deleted = 0
   )

If I change `tx_powermail_domain_model_mail`.`sys_language_uid` = - 1 to `tx_powermail_domain_model_mail`.`sys_language_uid` = 0 I get all the rows in the table. The uid passed to the function never shows up in the query. I assume that  $query->equals('uid', $uid), doesn't work.

**Comment by msmolik** [comment]
I run into some kind of this error too. No captcha used but as soon as an mail created from a page with language not default = 0 the double opt in link fails. Mails are always persisted with sys language uid 0.

The controller uses the findByUid method of the mail repo.
The query settings are manipulated with $query->getQuerySettings()->setLanguageMode(null); to retrieve records even if they differ from the current language uid.
But this does not have any effect anymore. 
  
Looks like powermail is not fully compatible with the v9.5 changes to the language handling system.
https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.5/Important-82363-MakeExtBaseTranslationHandlingConsistentWithTyposcript.html

The only solution I found without changing the powermail source is to disable the new extbase language handling with the typoscript setting
config.tx_extbase.features.consistentTranslationOverlayHandling = 0

**Comment by peerlight** [comment]
Same issue in TYPO3 9.5.6 and powermail 7.3.1

**Comment by Wahni69** [comment]
I have the same problem. Installation Typo3 9.5.8 Powermail 7.3.1. Bootstrap Package 10.0.6 also. all others extentions are not realy relevant. 
Does config.tx_extbase.features.consistentTranslationOverlayHandling = 0 solve the problem?

**Comment by msmolik** [comment]
@Wahni69 It does. But as I had a lot of contents within the site and extensions I decided not to set it and did a fix of powermail by my own as long as this issue has not been resolved.

**Comment by Wahni69** [comment]
THX for your response. 
I could solve within my form by delete the captcha field… Now my form works, but without captcha. I hope that it will be fixed, some day… :-)

**Comment by limeboxIT** [comment]
I'm experiencing this error, when using double optin and unique validation. 
After optin confirmation the unique validator fails.

Additionally passing the mailUid to $mailRepository->findByMarkerValueForm and excluding that specific mails answers from the result, might solve this.

**Comment by fjaeker** [comment]
Are there any other solutions? 
We tried TYPO3 9.5.9 with powermail 7.4.0 and all the mentioned "fixes" . 
Double optin with captcha (tested also with powermailrecaptcha)  throws the "Validation failed" error :-(
Thanks for help.

**Comment by deanguis** [comment]
> 
> 
> @Wahni69 It does. But as I had a lot of contents within the site and extensions I decided not to set it and did a fix of powermail by my own as long as this issue has not been resolved.

May I ask how the fix looks like? We have the same problem and have no clue how to fix it.

**Comment by msmolik** [comment]
> > @Wahni69 It does. But as I had a lot of contents within the site and extensions I decided not to set it and did a fix of powermail by my own as long as this issue has not been resolved.
> 
> May I ask how the fix looks like? We have the same problem and have no clue how to fix it.

That was the fix I wrote back then


powermail/Classes/Domain/Model/Mail.php
L 717 

```
++
 /**
 * _languageUid
 * @var int
 * custom
 */
protected $_languageUid;

/**
 * @param int $_languageUid
 * @return void
 * custom
 */
public function set_languageUid($_languageUid)
{
    $this->_languageUid = $_languageUid;
}

/**
 * @return int
 * custom
 */
public function get_languageUid()
{
    return $this->_languageUid;
}
```


powermail/Classes/Domain/Factory/MailFactory.php
L51
-            ->setMarketingPageFunnel($marketingInfos['pageFunnel']);
+            ->setMarketingPageFunnel($marketingInfos['pageFunnel'])
+            ->set_languageUid(-1) //@custom as powermail can not deal with the new language handling of extbase we have to set the mails to global lang uid -1
+            ;

**Comment by Schwuuuuup** [comment]
> > > @Wahni69 It does. But as I had a lot of contents within the site and extensions I decided not to set it and did a fix of powermail by my own as long as this issue has not been resolved.
> > 
> > 
> > May I ask how the fix looks like? We have the same problem and have no clue how to fix it.
> 
> That was the fix I wrote back then
> 
> powermail/Classes/Domain/Model/Mail.php
> L 717
> 
> ```
> ++
>  /**
>  * _languageUid
>  * @var int
>  * custom
>  */
> protected $_languageUid;
> 
> /**
>  * @param int $_languageUid
>  * @return void
>  * custom
>  */
> public function set_languageUid($_languageUid)
> {
>     $this->_languageUid = $_languageUid;
> }
> 
> /**
>  * @return int
>  * custom
>  */
> public function get_languageUid()
> {
>     return $this->_languageUid;
> }
> ```
> 
> powermail/Classes/Domain/Factory/MailFactory.php
> L51
> 
> ```
> -            ->setMarketingPageFunnel($marketingInfos['pageFunnel']);
> +            ->setMarketingPageFunnel($marketingInfos['pageFunnel'])
> +            ->set_languageUid(-1) //@custom as powermail can not deal with the new language handling of extbase we have to set the mails to global lang uid -1
> +            ;
> ```

Hi, I tried this and it doesn't change the behavior, I still get
`Validation failed while trying to call In2code\Powermail\Controller\FormController->createAction().`

But looking at the Code, I think there is something missing, there is that new attribute in Mail.php and it gets set from MailFactory, but when is it read?

**Comment by msmolik** [comment]
> > > > @Wahni69 It does. But as I had a lot of contents within the site and extensions I decided not to set it and did a fix of powermail by my own as long as this issue has not been resolved.
> > > 
> > > 
> > > May I ask how the fix looks like? We have the same problem and have no clue how to fix it.
> > 
> > 
> > That was the fix I wrote back then
> > powermail/Classes/Domain/Model/Mail.php
> > L 717
> > ```
> > ++
> >  /**
> >  * _languageUid
> >  * @var int
> >  * custom
> >  */
> > protected $_languageUid;
> > 
> > /**
> >  * @param int $_languageUid
> >  * @return void
> >  * custom
> >  */
> > public function set_languageUid($_languageUid)
> > {
> >     $this->_languageUid = $_languageUid;
> > }
> > 
> > /**
> >  * @return int
> >  * custom
> >  */
> > public function get_languageUid()
> > {
> >     return $this->_languageUid;
> > }
> > ```
> > 
> > 
> > powermail/Classes/Domain/Factory/MailFactory.php
> > L51
> > ```
> > -            ->setMarketingPageFunnel($marketingInfos['pageFunnel']);
> > +            ->setMarketingPageFunnel($marketingInfos['pageFunnel'])
> > +            ->set_languageUid(-1) //@custom as powermail can not deal with the new language handling of extbase we have to set the mails to global lang uid -1
> > +            ;
> > ```
> 
> Hi, I tried this and it doesn't change the behavior, I still get
> `Validation failed while trying to call In2code\Powermail\Controller\FormController->createAction().`
> 
> But looking at the Code, I think there is something missing, there is that new attribute in Mail.php and it gets set from MailFactory, but when is it read?

This fix is for the double opt-in issue with validation in other languages then default one.
It does not fix any captcha validation errors.

The new setter and getter for the languid in the model are only added to be able to set the syslang uid to -1 as in general it would be set to 0 that equals the default lang uid. Syslang uid condition is added by default via the query builder.

**Comment by Schwuuuuup** [comment]
> This fix is for the double opt-in issue with validation in other languages then default one.
> It does not fix any captcha validation errors.

Oh, I see, I thought these problems were connected.

while having multiple languages configured, the Powermail forms here are usually not translated, but some do have Double-Opt-In activated AND include Captchas.
Is there a fix for this issue?

**Comment by sypets** [comment]
Hi @msmolik,

> @custom as powermail can not deal with the new language handling of extbase we have to set the mails to global lang uid -1

It looks like your fix is more a work-around because it does not really solve the underlying problem of  why "powermail can not deal with the new language handling of Extbase".

Anyhow, why is that? Is this a general problem of Extbase extensions or a powermail problem?

Personally, I would rather appreciate a real solution than a work-around, but I still think a work-around is - in the current situation - already a good first step, until a solution can be found.

So, can you create a PR with your fix? 

Just my 2c. 

If I can help I would also be willing to do this. Currently I think the most important task is to find out what the real underlying problem is with powermail / multiple languages.

**Comment by einpraegsam** [comment]
There is a change in the latest version of powermail that should fix this old issue with optin and strict mode by simply saving mails and answers with sys_language_uid=-1 (see https://github.com/einpraegsam/powermail/commit/6923ba22a75491d039173cd8eebe2e236de53ba4). Maybe this helps you in your case.

**Comment by Schwuuuuup** [comment]
> There is a change in the latest version of powermail that should fix this old issue with optin and strict mode by simply saving mails and answers with sys_language_uid=-1 (see [6923ba2](https://github.com/einpraegsam/powermail/commit/6923ba22a75491d039173cd8eebe2e236de53ba4)). Maybe this helps you in your case.

Ok, but do I understand correctly: this is only for the multi-language-problem not for the captcha+DoubleOptIn-Problem?

**Comment by deanguis** [comment]
> There is a change in the latest version of powermail that should fix this old issue with optin and strict mode by simply saving mails and answers with sys_language_uid=-1 (see [6923ba2](https://github.com/einpraegsam/powermail/commit/6923ba22a75491d039173cd8eebe2e236de53ba4)). Maybe this helps you in your case.

I guess the fix is only for version 8.x, isn't it? we are using typo3 9.5 and powermail 8.x is only supported for typo3 10... am I correct?

**Comment by Schwuuuuup** [comment]
> I guess the fix is only for version 8.x, isn't it? we are using typo3 9.5 and powermail 8.x is only supported for typo3 10... am I correct?

I also would like to have this answered.

**Comment by lorddoumer** [comment]
anyone figured it out how to get powermail optin to work when the buildin captcha is activated? (only one language)

**Comment by Schwuuuuup** [comment]
Unfortunately not yet, still waiting for a fix

**Comment by dkoehl** [comment]
Hi,
I got the same issue, with TYPO3 10.4+Powermail 8.x.
I have no captcha in my form, in my case it´s not working with password fields to. 
I excluded the password field from, mail etc. in TS, but nothing worked for me.

Any ideas to fix this issue?

**Comment by m-schmitz** [comment]
> > I guess the fix is only for version 8.x, isn't it? we are using typo3 9.5 and powermail 8.x is only supported for typo3 10... am I correct?
> 
> I also would like to have this answered.

Same here, I have the same problem in TYPO3 9.5.18, powermail 7.3.1 and the Double-Opt-In in other languages than 0. I would appreciate a fix for powermail 7.x.

**Comment by adudtkowski** [comment]
Hi, 

I am workin with TYPO3 10.4. + powermail 8.1.2 with multiple languages, double optin and the build in captcha field and I got 
"Validation failed while trying to call In2code\Powermail\Controller\FormController->createAction()" after click on the confirmation link, too.

Is here anything new? Removing the captcha is unfortunately not an option for me.

Thank you for the work and an answer.

**Comment by Schwuuuuup** [comment]
As far as I know nothing new: captcha+double opt-in doesn't work

**Comment by stephangrass** [comment]
Any solution for this issue? Typo3 9.5.22, Powermail 7.4.0
If sponsorship will help: Count me in!

**Comment by einpraegsam** [comment]
We focused on different things in the past becasue our direct clients which are using powermail do not have such problems for any reasons. If someone is interested in sponsoring failure analysis or bugfixes (for powermail 8 only), please contact us at service@in2code.de

**Comment by stephangrass** [comment]
I need the feature for powermail 7, i.e. for a version compatible with TYPO3 9. So this kind of sponsorship is out of the question for us.

**Comment by typo3-2020** [comment]
Hi,

We are using Typo3 Core 9.5.22 and Powermail 7.4.0 (latest version for Typo3 9 LTS)

Double Opt-In works correctly in the default language.
After clicking on the confirmation link, the e-mail is sent to the recipient.

When submitting a form in a translated language, the mail is sent with the confirmation link.
However, when the confirmation link is clicked, the message "The specified link is invalid" appears.

In our Typo3 site configuration the fallbackType is set to "strict" for all translations.
If you change the fallbackType from "strict" to "fallback", the Double Opt-In confirmation link will also work for translated languages.
However, we are dependent on having set the fallbackType to "strict".

Will there be a fix for Powermail 7?

Thanks and best regards,
Patrick

**Comment by dkoether** [comment]
Today I stumbled over this bug in TYPO3 9.5.22 with Powermail 7.4.0 in a TYPO3 project with only one language. After deactivating the captcha-field the form with double-opt in works as wanted.

**Comment by typo3-2020** [comment]
We have not included a captcha field in the form.

In the default language, the confirmation link and subsequent mail delivery is working.

However, the problem exists in all translated languages.

**Comment by doni32** [comment]
In Typo3 9.5.18 and Powermail 7.4.0 and reCaptcha V2 is not working too.
Anyone have a solution?

**Comment by wazum** [comment]
I fixed this issue with the following class (used in TYPO3 CMS 10 with powermail 8.2.2)

```php
<?php

defined('TYPO3_MODE') or die ('Access denied.');

(static function () {
    $GLOBALS['TYPO3_CONF_VARS']['SYS']['Objects'][\In2code\Powermail\Controller\FormController::class] = [
        'className' => \Plan2net\MyProject\Controller\FormController::class
    ];
})();
```

```php
<?php

declare(strict_types=1);

namespace Plan2net\MyProject\Controller;

use Exception;
use In2code\Powermail\Domain\Validator\CaptchaValidator;
use In2code\Powermail\Utility\HashUtility;
use TYPO3\CMS\Extbase\Validation\Validator\ConjunctionValidator;

/**
 * Class FormController
 *
 * @author Wolfgang Klinger <wk@plan2.net>
 */
final class FormController extends \In2code\Powermail\Controller\FormController
{
    public function initializeCreateAction(): void
    {
        parent::initializeCreateAction();

        if ($this->createActionIsForwardedFromDoubleOptInConfirmation()) {
            $this->removeCaptchaValidator();
        }
    }

    private function createActionIsForwardedFromDoubleOptInConfirmation(): bool
    {
        try {
            /** @noinspection PhpParamsInspection */
            return !empty($this->settings['main']['optin']) &&
                $this->request->hasArgument('hash') &&
                $this->request->hasArgument('mail') &&
                HashUtility::isHashValid(
                    $this->request->getArgument('hash'),
                    $this->request->getArgument('mail')
                );
        } catch (Exception $e) {
            return false;
        }
    }

    private function removeCaptchaValidator(): void
    {
        $validator = null;
        /** @var ConjunctionValidator $validator */
        try {
            $validator = $this->arguments->getArgument('mail')->getValidator();
        } catch (Exception $e) {
        }

        if (null !== $validator) {
            /** @var CaptchaValidator propertyValidator */
            foreach ($validator->getValidators() as $propertyValidator) {
                if ($propertyValidator instanceof CaptchaValidator) {
                    try {
                        $validator->removeValidator($propertyValidator);
                    } catch (Exception $e) {
                    }
                }
            }
        }
    }
}
```

hth anyone, especially @adudtkowski  ;-)

**Comment by dev-rke** [comment]
Hi @wazum ,

thank you for sharing, i confirm, the patch you provided works on latest TYPO3 v10 + latest Powermail.
Will you provide the patch as a pull request?

When i run powermail with captcha but without your patch, i just get a very non-self-explantory exception:
```
(1/1) Exception
Serialization of 'Closure' is not allowed
in /var/www/web/typo3/sysext/fluid/Classes/ViewHelpers/FormViewHelper.php line 291
```

As it seems you analyzed the issue, could you give us a short overview, what exactly is failing and why you solved it by removing the validator?
I can just assume the captcha validator runs when the results are displayed, so it runs also a second time on Double OptIn confirmation page. And there the compare value of the captcha validator is missing or a new generated one.
Am i right or is there another process step that causes the issue?

**Comment by eliasfernandez** [comment]
I have this problem with `EXT:jh_captcha` 3.0.3 and `EXT:powermail` 6.0.0.  It seems that the problem comes on the forward to createAction on the optinConfirmAction method. Trying to simply forward falls on an validation error of the captcha.   A simple workaround to avoid this error is to disable the validation when confirmAction is passed to the url:

~~~typoscript
[request.getQueryParams()['tx_powermail_pi1'] && request.getQueryParams()['tx_powermail_pi1']['action'] == 'optinConfirm']
plugin.tx_powermail.settings.setup.spamshield{
  _enable = 0
  methods.{$plugin.tx_jhcaptcha.settings.powermail.recaptchaId}._enable = 0
}
[end]
~~~

Hope it helps
