### ISSUE TITLE
Missing file MarketingEid.php

### ISSUE THREAD

**Issue by thomasscheuermann** [einpraegsam/powermail#377]
Typo3 tries to include the file powermail/Classes/Eid/MarketingEid.php. This fails, because the file no longer exsits.

**Comment by einpraegsam** [comment]
Which powermail version? Did you clean all caches (Install Tool)?

**Comment by thomasscheuermann** [comment]
Powermail Version 7.0.0, Yes, the cache has been deleted.

The wrong include is in the file ext_localconf.php on line 90/91.

**Comment by einpraegsam** [comment]
Thx for the note. I just removed the outdated lines. Will be released in the next version.
