### ISSUE TITLE
Can't overwrite senderEmail (TYPO3 9.5LTS)

### ISSUE THREAD

**Issue by Bufallo** [einpraegsam/powermail#378]
In powermail 6.2 and 7.0 i try to overwrite the senderEmail as described in https://docs.typo3.org/typo3cms/extensions/powermail/Faq/Index.html#how-to-solve-spf-defiance

But it is not working.
The email address from the form is always used.

(i tried with TS Options plugin.tx_powermail.settings.setup.receiver.overwrite.senderEmail and plugin.tx_powermail.settings.setup.receiver.default.senderEmail).

(When using the Setup-Check inside the mail-backend-Module, the email is sent from the value from my LocalConfiguration: 'MAIL' => ['defaultMailFromAddress' => ...], which is correct)

=> I couldnt find a way to overwrite the senderEmail, event the values are set in defaultMailFromAddress (LocalConfiguration) and Typoscript (default and overwrite).

(I will use the signalSlot 'sendTemplateEmailBeforeSend' as workaround for now, as our Mail Provider is not allowing to send emails using the Form-Users-Email (SPF))

**Comment by einpraegsam** [comment]
I just tested with powermail 7.0 and TYPO3 9.5 with exactly the four lines of the documentation:
```
plugin.tx_powermail.settings.setup.receiver.overwrite.senderEmail = TEXT
plugin.tx_powermail.settings.setup.receiver.overwrite.senderEmail.value = server@domain.org
plugin.tx_powermail.settings.setup.receiver.overwrite.senderName = TEXT
plugin.tx_powermail.settings.setup.receiver.overwrite.senderName.value = Server from domain.org
```

The result is as expected:
<img src="https://s.nimbusweb.me/attachment/2445857/qo854b8skbnd8sz9c6ri/sgE08Sz3G0rzCnYv/screen.png" />

What TYPO3 version do you use? Are you sure that you have inserted the TypoScript in the field setup? Are there any third party extensions which extend powermail?

**Comment by Bufallo** [comment]
Im using TYPO 9.5.3

I figured it out now:
If the Editor checks the "This field contains the Email of the sender"-Checkbox in the field config of the Email field, this field is always used.

![bildschirmfoto 2019-01-15 um 15 14 41](https://user-images.githubusercontent.com/8195551/51185843-7f583300-18d8-11e9-98c2-a85bc5205fa3.png)

If i uncheck the Checkbox, the overwrite TypoScript Configuration is working.
So the problem ist, that "overwrite" is not overwriting;-)
In my opinion "Overwrite" should always have priority over any other configuration option.

**Comment by einpraegsam** [comment]
Of course I also tested with this setting:
<img src="https://s.nimbusweb.me/attachment/2453926/xc9de124r4ndnrg5cyr7/n7RXipEJkOGDZqW6/screen.png" />

I double checked the behaviour again with powermail 7.1.0 and TYPO3 9.5.3:

WIth this setup:
```plugin.tx_powermail.settings.setup.receiver.overwrite.senderEmail = TEXT
plugin.tx_powermail.settings.setup.receiver.overwrite.senderEmail.value = server@domain.org
plugin.tx_powermail.settings.setup.receiver.overwrite.senderName = TEXT
plugin.tx_powermail.settings.setup.receiver.overwrite.senderName.value = Server from domain.org```

All works as expected and and now I'm running out of ideas. I don't believe in a bug but more in a failure in your configuration. If you already did the low hanging fruits while searching:
* Clean caches (Install Tool)
* Check if your TypoScript was added to setup and not to constants
* Check against typos
* Check if you don't mixed up configuration to receiver-mail with configuration to sender-mail
* Check in TypoScript object browser if your configuration was accepted

The only thing that you could do is debugging why the hell the extension ignores the configuration.

Is there anything more that I could do?

**Comment by Bufallo** [comment]
Hi Alex,

you are right, there was an error in my configuration.
I checked the Object Browser on the Root Page where i pasted the example configuration directly to the database (for test porposes).

Somewhere in the Rootline i found an extension template with an include of the powermail static template (which of course erases my settings to the defaults).

Now its working correcty.

Sorry for the inconvenience and thanks for your help.

**Comment by einpraegsam** [comment]
thx for the final feedback

**Comment by iunctim** [comment]
I just got stuck on this issue, triple-checked the configuaration for typos, everything correct but it just didn't run. 
Flushing TYPO3 and PHP Cache (including opcode cache) in the Maintenance backend module  did the trick.
