### ISSUE TITLE
Powermail Marketing Reporting issue

### ISSUE THREAD

**Issue by vmans** [einpraegsam/powermail#38]
There are no results appearing in Marketing Reporting. In several installations on diferent servers.

- I have not disabled marketing reporting.
- And I have added the static template.
- And Form Reporting statistics are working, for instance.

TYPO3 7.6.15 and PM 3.5.0.
TYPO3 8.5.1 and PM 3.11.2.

   - the cookie fe_typo_user is set (isn't that enough?)
   - typo3conf/ext/powermail/Resources/Public/JavaScripts/Powermail/Marketing.min.js
   is in the footer
   - no JS errors in console

But no marketing data gets written and stored (no cookie and/or session
data, also not in console).

So what do I miss out?

Thanks
Vincent

**Comment by einpraegsam** [comment]
Is there an AJAX request in the browser console? Something like /index.php?&eID=powermailEidMarketing&tx_powermail_pi1[language]=0&id=2&tx_powermail_pi1[pid]=2&tx_powermail_pi1[mobileDevice]=0&tx_powermail_pi1[referer]=&_=1486416591158

**Comment by vmans** [comment]
Yes, I find this in the console Network tab:

http://dev1.vibis.eu/index.php?&eID=powermailEidMarketing&tx_powermail_pi1[language]=0&id=3322&tx_powermail_pi1[pid]=3322&tx_powermail_pi1[mobileDevice]=0&tx_powermail_pi1[referer]=http%3A%2F%2Fdev1.vibis.eu%2F&_=1486453467411

Clicking it results in "Failed to load response data". Response headers location is a 404 Page Not Found.

**Comment by einpraegsam** [comment]
Request should somethink like
```
eID=powermailEidMarketing
tx_powermail_pi1[language]=0
id=2
tx_powermail_pi1[pid]=2
```

The anser should be empty but without errors. This should also be testable directly if you open the URI in your browser: yourdomain.org/index.php?&eID=powermailEidMarketing - if there is a 404 there is a misconfiguration.
Try to play a little bit with the URI (adding a page id, etc...)

**Comment by vmans** [comment]
Played around a bit, over 3 installations.

1- In TYPO3 7.6 it works as described. (I have to check if the referer goes well, though. But no errors.)
2- In TYPO3 8.5.1 on one server, it doesn't work. It goes as described.
3- In TYPO3 8.5.1 on another server, it doesn't work but I see a message now: 
Page Not Found
Reason: Request parameters could not be validated (&cHash empty)

So I've set [FE][pageNotFoundOnCHashError] = true to false. Now it works fine in 3, everything is saved (e.g. referer domain and URI).

Is this the right solution? I doubt it, but I'm no expert on this.

**Comment by vmans** [comment]
It's solved somehow. It just works differently now. On one server with 8.5.1 we need to set [FE][pageNotFoundOnCHashError] = true and on the other false. Guess that's weird.
