### ISSUE TITLE
Annotation Exception in powermail_frontend plugin in Typo3 9

### ISSUE THREAD

**Issue by ashupatel1990** [einpraegsam/powermail#380]
I am getting annotation exception in powermail extension, this errors comes from version 5.0.0. 
In Typo3 9 dontvalidate has been deprecated, so, you might have to replace that using IgnoreValidation namespace.
![typo3 exception](https://user-images.githubusercontent.com/31200232/51012377-cebdfc80-1582-11e9-9bcf-74c2ba0cb097.png)

I have fixed following way:
1) include namespace in top of the class.
use TYPO3\CMS\Extbase\Annotation\IgnoreValidation;
2) specify validation for particular variable.
/**
 * @IgnoreValidation("param")
 */

**Comment by einpraegsam** [comment]
Thx for the feedback. What steps do I have to make to reproduce this issue on my testsystem?

**Comment by ashupatel1990** [comment]
> Thx for the feedback. What steps do I have to make to reproduce this issue on my testsystem?

1. include namespace in top of the class.
use TYPO3\CMS\Extbase\Annotation\IgnoreValidation;

2. specify validation for particular variable.
-> replace dontvalidate $param to @IgnoreValidate("param")
/**
@IgnoreValidation("param")
*/

**Comment by kyros3** [comment]
I have the same Problem but i don't understand the solution. Can you explain me were the validation param is ? i try this below. But this is wrong.
Can someone help me ?


`/**
     * @param array $export Field Array with mails and format
	 * @IgnoreValidation("param")
	 * @dontvalidate $mails
     * @dontvalidate $fields
	 * 
     * @return void
     * @throws StopActionException
     */
    public function exportAction($export = [])
    {
        if (!$this->settings['list']['export']) {
            return;
        }
        $mails = $this->mailRepository->findByUidList($export['fields']);

        // get field array for output
        if ($this->settings['list']['fields']) {
            $fieldArray = GeneralUtility::trimExplode(',', $this->settings['list']['fields'], true);
        } else {
            $fieldArray = $this->formRepository->getFieldUidsFromForm($this->settings['main']['form']);
        }
        $fields = $this->fieldRepository->findByUids($fieldArray);

        if ($export['format'] === 'xls') {
            $this->forward('exportXls', null, null, ['mails' => $mails, 'fields' => $fields]);
        }
        $this->forward('exportCsv', null, null, ['mails' => $mails, 'fields' => $fields]);
    }

    /**
     * @param QueryResult $mails mails objects
     * @param array $fields uid field list
	 * @IgnoreValidation("param")

     * @return    void
     */
    public function exportXlsAction(QueryResult $mails = null, $fields = [])
    {
        $this->view->assign('mails', $mails);
        $this->view->assign('fields', $fields);
    }`

**Comment by ashupatel1990** [comment]
* @dontvalidate $mails
* @dontvalidate $fields

Please make @IgnoreValidation for both above fields as well.
and don't forget to include :
1. use TYPO3\CMS\Extbase\Annotation\IgnoreValidation;

**Comment by kyros3** [comment]
@ashupatel1990 Thank you very much. I am so stupid it was vor my eyes but i don't see it.
So it works.

**Comment by einpraegsam** [comment]
Fixed in develop branch by removing the old dontvalidate statements
