### ISSUE TITLE
Can't export mail list (Pwermail 7.0.0, Typo3 9.5.3)

### ISSUE THREAD

**Issue by Raemy92** [einpraegsam/powermail#381]
I created a form and filled in some test data. Now if I navigate to the mail list and click on the export buttons (doesn't matter if CVS or XLS) nothing happens.

There are no errors in the log.

I'm using Typo3 v.9.5.3 and Powermail v.7.0.0

- Tested it with Chrome and Firefox
- Cleared all cache, dumped autoload and deleted temp files

Thanks in advance for any help provided.

**Comment by einpraegsam** [comment]
Thx is related to #362 in my eyes
