### ISSUE TITLE
strange behavior with "required" aka "mandatory"

### ISSUE THREAD

**Issue by DavidBruchmann** [einpraegsam/powermail#383]
Having two fields where one is mandatory and the other one not in HTML they always have the attribute `required="required"`. I checked the debug of the field-objects and they are correct.  
**Now comes the funny but confusing part:**  
Changing the first line in `AbstractValidationViewHelper::addMandatoryAttributes` from
```
if ($field !== null && $field->isMandatory()) {
```
to
```
if ($field !== null && $field->isMandatory()===true) {
```
everything is working like expected.  
Without that change all fields are just mandatory.  
I checked it with input-fields and textarea.  
Is there any change in PHP I missed?

powermail: 7.0.0
TYPO3: 9.5.3
php: 7.2.13
OS: Linux 2.6.32-673.8.1.lve1.4.3.el6.x86_64
composer-mode: yes
webserver: Litespeed

**Comment by einpraegsam** [comment]
This is duplicated to #382

**Comment by benjaminpick** [comment]
Maybe the array reference survives for too long? I have seen such errors when using foreach with an array by reference, see https://bugs.php.net/bug.php?id=29992
