### ISSUE TITLE
Replacement in Mails

### ISSUE THREAD

**Issue by DavidBruchmann** [einpraegsam/powermail#384]
Some fields in mails are not replaced if the option "Add my own Variable Name[own_marker_select]" is not set. Currently it's about the fields `vorname`, `nachname` which are assigned 1:1 in TypoScript:
```
plugin.tx_powermail.settings.setup {
    dbEntry {
            vorname = TEXT
            vorname.field = vorname
            
            nachname = TEXT
            nachname.field = nachname
           ...
    }
}
```
Just enabling "Add my own Variable Name[own_marker_select]" without changing anything else solves the issue.

powermail: 7.0.0
TYPO3: 9.5.3
php: 7.2.13
OS: Linux 2.6.32-673.8.1.lve1.4.3.el6.x86_64
composer-mode: yes
webserver: Litespeed

**Comment by einpraegsam** [comment]
Which language? Can you pls post the HTML source of the related fields in the form. One without checking the checkbox and one with checking?
