### ISSUE TITLE
formatting of mails without RTE

### ISSUE THREAD

**Issue by DavidBruchmann** [einpraegsam/powermail#385]
Having disabled the RTE in FlexForm for the mail-texts (Bodytext for Email to Sender, Bodytext for Email to Receiver) I thought being able just to send text-mails without HTML.
The problem is that additional empty lines are inserted and the mails look weird therefore.
Stored in FF:
```
Guten Tag

Vielen Dank für Ihr ...
```
Text in Mail:
```
Guten Tag

 

Vielen Dank für Ihr ...
```
This is looking especially odd in the address-footer of the mails.

powermail: 7.0.0
TYPO3: 9.5.3
php: 7.2.13
OS: Linux 2.6.32-673.8.1.lve1.4.3.el6.x86_64
composer-mode: yes
webserver: Litespeed

**Comment by einpraegsam** [comment]
This would be more a support question then a bug reporting in my eyes. At the moment there is no support on github - sorry.
