### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by DavidBruchmann** [einpraegsam/powermail#386]
Installation with extension `secure-web`

tt_content:
![image](https://user-images.githubusercontent.com/999146/51246947-3ed2e500-19be-11e9-923b-0c585b67f085.png)

extension-manager:
![image](https://user-images.githubusercontent.com/999146/51247039-78a3eb80-19be-11e9-88e9-3924ba95be03.png)

In "Maintenance -> Manage Language Packs" I never get powermail shown in the moment but when I saw it, the icon was missing too, looking comparable with secure_downloads in the screenshot:
![image](https://user-images.githubusercontent.com/999146/51247489-d8e75d00-19bf-11e9-867c-647f4b0bf898.png)
Hope I don't mistake here, also strange that powermail is not shown there for some reason.

powermail: 7.0.0
TYPO3: 9.5.3
php: 7.2.13
OS: Linux 2.6.32-673.8.1.lve1.4.3.el6.x86_64
composer-mode: yes
webserver: Litespeed

**Comment by einpraegsam** [comment]
On my system everything works as expected (powermail 7.1.0 and TYPO3 9.5.3). I checked extension manager and plugin view.
Did you really clean all caches (Install Tool), etc...?

**Comment by DavidBruchmann** [comment]
You tried it also with the extension `secure-web`?

**Comment by einpraegsam** [comment]
No, I did not see that note.
Did you install it via composer package?

**Comment by DavidBruchmann** [comment]
yes

**Comment by einpraegsam** [comment]
Fixed with 1d8c79c9ae7537ce7eab38eae70396e806ad0f94
