### ISSUE TITLE
typos in docu

### ISSUE THREAD

**Issue by DavidBruchmann** [einpraegsam/powermail#387]
where: https://docs.typo3.org/typo3cms/extensions/powermail/ForAdministrators/BestPractice/SavingValuesToThirdPartyTables/Index.html#best-pracitce

`pracitce` => `practice`
`# Enabe function only` => `# Enable function only` (2x, in each code-box once)

Apart of that: **great option!**

**Comment by einpraegsam** [comment]
Thx, just do a pull request and I will merge it asap
