### ISSUE TITLE
Typo in Sass/js file: powermail_prog(r)ess_inner

### ISSUE THREAD

**Issue by npoggenburg** [einpraegsam/powermail#390]
There is a typo in the following files:
https://github.com/einpraegsam/powermail/blob/master/Resources/Private/Sass/_Pi1.scss
powermail/Resources/Private/Sass/_Pi1.scss
`powermail_progess_inner` should be 
`powermail_progress_inner`

https://github.com/einpraegsam/powermail/blob/master/Resources/Private/JavaScript/Powermail/Form.js
powermail/Resources/Private/JavaScripts/Powermail/Form.js
`$('<div />').addClass('powermail_progess_inner')` should be 
`$('<div />').addClass('powermail_progress_inner')`

**Comment by einpraegsam** [comment]
Thx for the hint
