### ISSUE TITLE
Form data ist not send and stored (Powermail 4.4.0)

### ISSUE THREAD

**Issue by MAnslinger** [einpraegsam/powermail#392]
I habe Powermail 4.4.0 with Typo3 7.6.18

When filling out the form and I click on the submit button I get redeirected to the form site not to the answer-site. (no error appears)
And the Mail is not send to sender and receiver, also the formdata ist not stored.

Can you help me ?

Thanks Markus

**Comment by einpraegsam** [comment]
This happens if the target url of the form is different to the current domain. E.g. if you have a redirect from https to http but you are using absRefPrefix with http instead of https. Pls check redirects in your browser console.
