### ISSUE TITLE
Email not sent but form email is stored

### ISSUE THREAD

**Issue by sypets** [einpraegsam/powermail#394]
I haven't been able to track down the reason for this problem just yet. Also, it is (not yet) reproducible on a test system. Is this a known problem? How can we narrow down the problem?

# System

* powermail 6.1.0
* TYPO3 8.7.23

# Problem description

We have a powermail form with quite a bit of traffic and for roughly a third of the entries the email is not being sent (this has been verified by checking the outgoing maillog, so it is not just a question of the email being sent and being blocked somewhere along the line). 

However, an entry is created in the list of mails (tx_powermail_domain_model_mail), so the problem is just the email not being sent.

# Tests / Analysis

* for the entries I checked where the email was not being sent, tx_powermail_domain_model_mail.spam_factor was 0%, so that can't be the problem
* the email adress can't be the problem either because in one case an applicant filled out the form 3 times (with the same email), but the email was only sent once.  
* sending out a form several times with the same email can't be the problem either, because for some of the entries that didn't get an email, the email address was only used once.

**Comment by einpraegsam** [comment]
There are no known bugs that would describe your problem. A small test does not show a problem on my test machine. 
Sorry, but I have no idea how to help you out at this moment.

**Comment by sypets** [comment]
Thanks. It was worth a try. I will add more information, once available. For now, it's ok with me, if you close this issue.

**Comment by einpraegsam** [comment]
Thx, if you find an issue pls reopen or let me know

**Comment by mmasmoudi** [comment]
I have same issue here, the email is stored but no emails arraive to my inbox.
Test email from installtool is working perfectly.
Typo3 7
Powermail 4.4
