### ISSUE TITLE
Add new transient property to model Mail

### ISSUE THREAD

**Issue by georgringer** [einpraegsam/powermail#395]
What do you think about adding a new property to the Model `\In2code\Powermail\Domain\Model\Mail`

```
    /**
     * @var array
     * @transient
     */
    protected $additionalData = ''; // I don't care about the name
```

which could be used to add some runtime data to the model? I could use that to add dynamic attachements to the mail? as an additional change `\In2code\Powermail\Domain\Service\Mail\SendMailService::prepareAndSend` would need also the argument `Mail`.

**Comment by einpraegsam** [comment]
Thx for the work. See my small notes.
