### ISSUE TITLE
sys_refindex exploding

### ISSUE THREAD

**Issue by MichiSpandl** [einpraegsam/powermail#399]
Hi, I'm not sure if this problem is about powermail but maybe you have a hint for me what I can do. We have a customer which has pretty much mails sent via powermail. Now we have seen that the database is kind of exploding. I checked the sys_refindex Table and I have seen that there are more than 3107596 entries for tx_powermail_domain_model_answer and over 1700380 entries for tx_powermail_domain_model_mail. We do have a scheduler task which cleans all mails after about 2 months (really deleting them in the DB, not just deleted=1) and I also check the sys_refindex and updated it, but there are still all the entries in the sys_refindex table. I guess it is because the mails and the answers refer to fields and forms which still exist... Is there a possibility for a clean up task of the sys_refindex table for powermail? Thanks, Michi

**Comment by einpraegsam** [comment]
Powermail does not create sys_refindex entries by itself and there is no such task in the extension.
