### ISSUE TITLE
Should Field:content_element be an int or varchar?

### ISSUE THREAD

**Issue by benjaminpick** [einpraegsam/powermail#402]
When creating a Field in my extension code (not in the backend via TCA), I have a fatal error in Typo3v9 with MySQL running in strict_mode:

Incorrect integer value: '' for column 'content_element' at row 1

ext_tables.sql defines content_element as int, but the Field class creates (and initializes) it as text field. Which one is correct? Do you try to take into account the case when several content elements are chosen at once (the TCA 'group') in the database, even if the TCA currently has maxitems = 1 ?

**Comment by einpraegsam** [comment]
Pls write me how to reproduce the issue.

**Comment by benjaminpick** [comment]
Typo3v9 9.5.4, powermail 7.2.0, MySQL 5.7.25 in Strict Mode

I am creating a Field/Answer pair dynamically during `manipulateMailObjectOnCreate`:

```php
$field =  $this->objectManager->get(Field::class);
$field->setType('custom_type');
$field->setTitle('custom');
$field->setMarker('custom');

$answer = $this->objectManager->get(Answer::class);
$answer->setField($field);
$this->addAnswer($answer);
```

Then I get the Exception:
```
TYPO3\CMS\Extbase\Persistence\Generic\Storage\Exception\SqlErrorException

Incorrect integer value: '' for column 'content_element' at row 1
```

The cause is that in the class Answer, the value is initialized with '' instead of '0' (see #403).
