### ISSUE TITLE
[Feature Request] make the limit of 5 entries in the form report variable

### ISSUE THREAD

**Issue by medarob** [einpraegsam/powermail#406]
Hi,
In the form reports, the "Get grouped mail answers for reporting" feature is limited to only 5 entries. Is it possible to make this variable, so that I can extend the number of entries to 10, 20 or any other number I like?

https://github.com/einpraegsam/powermail/blob/develop/Classes/Utility/ReportingUtility.php#L37

Thank you :)

**Comment by einpraegsam** [comment]
Pls feel free to do a PR
