### ISSUE TITLE
optionlist in PM Frontend uses text in values instead of using catalog ids

### ISSUE THREAD

**Issue by AEHluis** [einpraegsam/powermail#408]
FE-Users can manipulate a PM form optionlist with individual entries or manipulating data in value="plaintext".  

` Actual implementation:`
` <select ....>`
`   <option value="Brad">Brad</option>`
`   <option value="Angie">Angie</option>`
`   <option value="Jenny">Jenny</option>`
` </select>`
 
` Should be like this:`
` <select ....>`
`   <option value="1">Brad</option>`
`  <option value="2">Angie</option>`
`   <option value="3">Jenny</option>`
` </select>`

After den Form is submitted the real "values" are loaded from the DB regarding the selected option-Id. 
Then no manipulation of the data is possible.

**Comment by einpraegsam** [comment]
Yes, this is - at the moment - a missing feature. PR are welcome :)
