### ISSUE TITLE
empty e-mail after opt-in when "language_mode = strict" in multilanguage websites

### ISSUE THREAD

**Issue by medarob** [einpraegsam/powermail#410]
Hi,

I think I discovered an issue in multilanguage websites. I enabled the Double Opt-In functionality and the receiver gets an amail with no information. This happens in my French website but it's working on the English website and the standard German website.

I searched and found an entry from 2017 with the exact same issue:
https://github.com/einpraegsam/powermail/issues/187

Now I wonder why it's working on my English website but not on my French website. If I disable the "language_mode = strict; 0" it's working.. So it's seems the same issue like in the entry from 2017?

I use TYPO3 8.7.24 and Powermail 7.2.

**Comment by einpraegsam** [comment]
Yes, this is a known issue in TYPO3 together with language_mode=strict. The problem in short: Mail records should be saved with sys_language_uid=-1 instead of 0. But this isn't simple to solve. At the moment there is no solution for this.
