### ISSUE TITLE
Escape semicolon in answer to ensure proper csv

### ISSUE THREAD

**Issue by chrisprog20** [einpraegsam/powermail#414]
Hi Alex, 
when someone enters a semicolon (;) in the text this leads to false columns when importing generated csv into excel.
Maybe an idea would be to wrap each answer within double quotes. like explained
[here](https://bytes.com/topic/php/answers/840754-escaping-commas-csv-output) from User Gordon at Sep 24, 7:46*pm

```
If your aim is to write out data that would be compatible with
spreadsheet software, then the standard solution is to enclose any
field that's a string in quotes. For example, if your data was:

1,2,3,a,b,c,a man, a plan, a canal, panama

then rendering it as follows should produce the correct results when
you import into your CSV supporting spreadsheet application:

"1","2","3","a","b","c","a man, a plan, a canal, panama"

Of course, you then hit the problem of what to do if your string
contains a " character?

1,2,3,a,b,c,a man, a plan, a canal, "panama"

The answer is that you can escape the " character by doubling it up in
the output.

"1","2","3","a","b","c","a man, a plan, a canal, ""panama""

Data formatted like this should be imported correctly into most
software that supports with CSV. Do bear in mind, that Microsoft
Excel can have problems if any of your data contains a newline (the
general consensus is that if the newline is contained within quotes it
should be treated as part of the field instead of a line terminator,
but Excel seems to ignore that).
```
Thank you for your feedback.

Cheers
Christian

**Comment by einpraegsam** [comment]
I can't find a problem in Libre Office because I have no Excel to test. Nevertheless: Are you sure, that there was no misconfiguration in XLS?
![screenshot](https://user-images.githubusercontent.com/89055/55803178-1ef12000-5ada-11e9-9d2b-b9f618addda0.png)

**Comment by chrisprog20** [comment]
Hello Alex, 
I think that there was a misconfiguration.
So you can close the ticket.

Thank you for having had a look at it.

Cheers
Christian

**Comment by mschwemer** [comment]
Thanks for your feedback. 

I finally close it.
