### ISSUE TITLE
TYPO3 9.5 Exception in frontend on page with powermail pi2 plugin

### ISSUE THREAD

**Issue by Patta** [einpraegsam/powermail#417]
TYPO3 Exception in frontend on page with powermail pi2 plugin to output a list of mails.

```
Doctrine\Common\Annotations\AnnotationException
[Semantical Error] The annotation "@dontvalidate" in method In2code\Powermail\Controller\OutputController::exportAction() was never imported. Did you maybe forget to add a "use" statement for this annotation?
```

`in ...\typo3_9.5\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\AnnotationException.php line 54`

```
     * @return AnnotationException
     */
    public static function semanticalError($message)
    {
        return new self('[Semantical Error] ' . $message);
    }

    /**
     * Creates a new AnnotationException describing an error which occurred during
```

`at Doctrine\Common\Annotations\AnnotationException::semanticalError('The annotation "@dontvalidate" in method In2code\\Powermail\\Controller\\OutputController::exportAction() was never imported. Did you maybe forget to add a "use" statement for this annotation?')`

TYPO3 9.5.5
PHP 7.3.3
powermail 7.2.0
composer mode
win10 localhost

**Comment by einpraegsam** [comment]
Duplicated to #380
