### ISSUE TITLE
Marketing informations : Referer and referer domain not set

### ISSUE THREAD

**Issue by Gloumi** [einpraegsam/powermail#42]
I enabled the marketing reporting, added the static TS template, my informations are well stored (language, country, mobile...) except the referer. 

I did a debug here : https://github.com/einpraegsam/powermail/blob/develop/Classes/Utility/SessionUtility.php#L113 

The param `$referer` is well set, I can see that I come from http://www.facebook.com/ 
But the next step erase the information, because the array `$marketingInfo` is already set and does not contain the referer information.

**Comment by einpraegsam** [comment]
I tested on my local machine but I can't see a problem. When I follow a link from local1 to local2, the referrer will be transmitted via AJAX. If I surf a bit on local2 and end up on a powermail form and submit it, I will see the referrer in backend:
https://box.everhelper.me/attachment/776798/84725fb7-0b3e-4c40-b52e-29d7620777bb/262407-JkRbhqoH7eWWJz3I/screen.png

If you check your browser console, what kind of properties are transmitted to eID powermailEidMarketing?

**Comment by Gloumi** [comment]
Thanks Alex, I looked at the eID parameters : index.php?&eID=powermailEidMarketing&tx_powermail_pi1[language]=0&id=1&tx_powermail_pi1[pid]=1&tx_powermail_pi1[mobileDevice]=0&tx_powermail_pi1[referer]=https://www.facebook.com/&_=1487771140902 
Everything seems ok, as I said it looks like that the parameters are erased during the process, I can't understand why

**Comment by einpraegsam** [comment]
Sorry, I still can't find a problem on my testsystem. So I think it could be a problem with your instance or configuration.
