### ISSUE TITLE
Mail to receiver "Frontend User Group" does not work with large groups

### ISSUE THREAD

**Issue by seitenformate** [einpraegsam/powermail#424]
Hello, 
I'm trying to send a mail to a frontend user group. It works with one or two receivers. But not with 30. I have changed the size of receiver_mail in tx_powermail_domain_model_mail (from varchar(255) to text. But it still does not work. In the documentation I cannot find anything. Do you have an idea? 
Best regards,
Alex

**Comment by einpraegsam** [comment]
30 is a number that can lead to a timeout on sending mails. Powermail is only a simple contact form extension and not a newletter-system. I think it's not possible in the described use case.

**Comment by seitenformate** [comment]
Ok. Thank you!
