### ISSUE TITLE
Error message "Oops, an error occurred! Code: 2019041517290248c9e85a"

### ISSUE THREAD

**Issue by SwissFall** [einpraegsam/powermail#426]
Extension powermail; after submitting a mail, I get the error message "Oops, an error occurred! Code: 2019041517290248c9e85a" (Typo3 8.7.24 / Powermail V7.3.0)

**Comment by einpraegsam** [comment]
Seems like you have an error in your HTML-Template (or Partial). Try with original one again.

**Comment by SwissFall** [comment]
Extension deaktiviert, gelöscht und neu installiert. Gleicher Fehler. Captcha von powermailrecaptcha auf eingebautes gewechselt. Fehler weg.

--> irgendein Konflikt zwischen den beiden Extensions ...?

**Comment by einpraegsam** [comment]
Ok, one step back, the error points to a FLUID problem but the message is not helpful. Pls activate error messages with `config.contentObjectExceptionHandler = 0` in TypoScript setup and get a useful message.

**Comment by SwissFall** [comment]
Thanks for the helpful hint ... SecretKey was missing - mea culpa. Now - using "powermailrecaptcha" again - I get the message from "Spam in Nachricht vermutet: 90% Spam-Wahrscheinlichkeit in dieser Nachricht!" (and that after correctly solving the photo puzzle presented by Google).

**Comment by mschwemer** [comment]
Thanks for your feedback. 

I finally close this issue.
