### ISSUE TITLE
[Feature Request] : Secure uploads directory

### ISSUE THREAD

**Issue by phil64** [einpraegsam/powermail#427]
Hi,

One can anonymize uploaded files, which is great, but it would be much better to "access protect" the upload directory (through a mecanism as proposed by the "secure_downloads" extension, for example).

Thanks a lot for this great extension.

**Comment by einpraegsam** [comment]
There is no plan for this on the current roadmap

**Comment by Patta** [comment]
@phil64  if you already use ext:secure_downloads, you can configure your secured dirs. see https://github.com/bitmotion/typo3-secure-downloads/blob/master/Documentation/AdministratorManual/DetailsConfigurations/Index.rst

**Comment by phil64** [comment]
By using ext:secure_download, the concern is that if it allows to restrict the access to FE, the files are no longer accessible in BE.
