### ISSUE TITLE
Replacing receiver not working as expected

### ISSUE THREAD

**Issue by angeloprevitali** [einpraegsam/powermail#429]
If i want to add a receiver like

`plugin.tx_powermail.settings.setup.receiver.email = someone@somewhere.com`

then it works perfect. If i do this it wont work anymore and there is NO mail sent.

`plugin.tx_powermail.settings.setup.receiver.email < lib.emailadress`

If i check the output of the lib.emailadress it gets me the correct e-mail adress as I should have. 
Normally TS works like this and it should be replaced.

Any hint?

Best regards,
Angelo

**Comment by einpraegsam** [comment]
lib.emailadress is maybe a cObject while your first line is simply a string - so this will not work.

Pls note that this is not a support forum for questions but for bugs.

**Comment by angeloprevitali** [comment]
Dear Alex

**if** it it a bug i have to write it here on GitHub, right? ;-)

Have a look to that. **This works:**
`plugin.tx_powermail.settings.setup.receiver.email = someone@somewhere.com`

This will **NOT** work, why?

`lib.emailadress = TEXT  
lib.emailadress.value = someone@somewhere.com
plugin.tx_powermail.settings.setup.receiver.email < lib.emailadress`

**Comment by einpraegsam** [comment]
This is not a bug - as I already wrote, right?
Pls use `plugin.tx_powermail.settings.setup.receiver.email < lib.emailadress.value` or write it as string

**Comment by angeloprevitali** [comment]
i do not get it what you want to tell me.. Anyway... no problem.
