### ISSUE TITLE
Wrong mail text parsing if static template files from extensions include before all static templates

### ISSUE THREAD

**Issue by Patta** [einpraegsam/powermail#43]
TYPO3 v7.6.15 and powermail 3.11.2

My typoscript is include static from custom extension. To avoid problems with some system extensions (felogin ...) the option "Static Template Files from TYPO3 Extensions" is set to "Include before all static templates if root flag is set".

My powermail receiver mail textfields contain paragraphs. 
With the above configuration, p tags are removed in sent and stored mails.

I temporary fixed this issue, by adding the `lib.parseFunc_powermail < lib.parseFunc_RTE` setup from powermails ext_typoscript_setup.txt to my powermail typoscript setup file.

**Comment by einpraegsam** [comment]
All configuration from ext_typoscript_setup.txt is mandatory and needs to be included. If you change the sorting of the included TypoScript, this can lead to many problems. Nevertheless you can copy the two lines to your TypoScript if needed.
