### ISSUE TITLE
upload field breaks double-opt-in 

### ISSUE THREAD

**Issue by lilu82** [einpraegsam/powermail#431]
Hi (I apologize in advance for my bad english ^^),
I use TYPO3 7.6 and powermail 4.4.0.
Using a form with upload field and double-opt-in, the opt-in confirmation is send but the confirmation link in mail is redirecting me to an error:

Oops, an error occurred!
Argument 7 passed to In2code\Powermail\Domain\Factory\FileFactory::makeFileInstance() must be an instance of In2code\Powermail\Domain\Model\Form, instance of TYPO3\CMS\Extbase\Persistence\Generic\LazyLoadingProxy given, called in /var/www/htdocs/typo3conf/ext/powermail/Classes/Domain/Factory/FileFactory.php on line 81

Without double-opt-in everything is fine. 
Double-opt-in wihout an upload field is also fine.
Only both together do not seem to work.

**Comment by einpraegsam** [comment]
Hi, I'm sorry but there is no bugfix support for the old 4.4.0 version any more.
