### ISSUE TITLE
Error while submit a form ERR_BLOCKED_BY_XSS_AUDITOR

### ISSUE THREAD

**Issue by xQuai** [einpraegsam/powermail#433]
Hello,

I've got a Problem with powermail. We activated the Header `X-XSS-Protection: 1;mode=block` and now we have got the following error in Chrome and Chrome Mobile if we submit a form `ERR_BLOCKED_BY_XSS_AUDITOR`. The data will be submitted, but the user experience is not really well, because they see an Chrome error page. 

Do you know the problem?
Is there a fix for that problem?

My Versions are:
- powermail 7.3.0
- TYPO3 8.7.24

**Comment by einpraegsam** [comment]
Do you have HTML anywhere in your field values? Maybe for a checkbox AGB-Link or so?

**Comment by xQuai** [comment]
That is correct. There are checkbox fields with AGB-Links. Is it a problem?

**Comment by einpraegsam** [comment]
Yes it is, just use a different value and label. Label with link and value without link. After that your chrome is happy.

**Comment by xQuai** [comment]
Can you give me an example? I don't know how i can realize your idea.
I used Type 'Checkboxes' and put into Options Text plus a a-tag with a link to the AGB.

**Comment by einpraegsam** [comment]
Look at the documentation how to use a different label then a value for checkboxes: https://docs.typo3.org/typo3cms/extensions/powermail/ForEditors/AddANewForm/FieldCheck/Index.html#option-examples-for-checkbox
