### ISSUE TITLE
Powermail: Don't shows multiple receiver in the records

### ISSUE THREAD

**Issue by MarkusGehrig** [einpraegsam/powermail#440]
Hey
We found a display bug in the powermail module, showing the filled forms. 
We want to send the form to 3 email addresses, which works absolutely perfectly but in the created mail record only the last set address is shown. 

As an example in the plugin, we set as receivers:
a@example.com
b@example.com
c@example.com

In the record (powermail module edit record) only the last receiver is shown: 
c@example.com

As we have seen now only the backend records are broken and all emails get delivered as expected.

**Comment by einpraegsam** [comment]
That's correct. At the moment only one email address is stored. There is no plan to change it at the moment.
