### ISSUE TITLE
disclaimer link triggered

### ISSUE THREAD

**Issue by markushowald** [einpraegsam/powermail#446]
If the disclaimer link is sent, it seems to get triggered on our customers email client. That means, the fill out a form, receive it and it get's automatically deleted/withdrawn.

They use this configuration:

Windows: 2016 @citrix
Outlook: 2016 @citrix

As a workaround, I just deactivated the disclaimer link via typoscript:
sender.addDisclaimerLink = 0

**Comment by einpraegsam** [comment]
There are some mail providers that follows every link in an email. Even if this is more a gdpr question why the provider does it, there is no possibility for powermail to find out if the click is correct or if it's an automatism.
