### ISSUE TITLE
Confirmation Link with Double Opt-in and Attachment leads to Error Message "Illegal string offset 'form'"

### ISSUE THREAD

**Issue by mschmitz89** [einpraegsam/powermail#447]
Using the latest TYPO3 9.5.7 and Powermail 7.3.1 with a form with active Double Opt-In and Attachment leads to the following error, when clicking the confirmation link in the mail:

`PHP Warning: Illegal string offset 'form' in /usr/www/users/kundexy/web/typo3conf/ext/powermail/Classes/Domain/Validator/UploadValidator.php line 56`

typo3*.log:

`Wed, 05 Jun 2019 10:41:39 +0200 [CRITICAL] request="" component="TYPO3.CMS.Core.Error.DebugExceptionHandler": Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1476107295: PHP Warning: Illegal string offset 'form' in /usr/www/users/kundexy/web/typo3conf/ext/powermail/Classes/Domain/Validator/UploadValidator.php line 56 | TYPO3\CMS\Core\Error\Exception thrown in file /usr/www/users/kundexy/web/typo3/sysext/core/Classes/Error/ErrorHandler.php in line 124. Requested URL: http://www.domain.de/karriere/online-bewerbung?tx_powermail_pi1%5Baction%5D=optinConfirm&tx_powermail_pi1%5Bcontroller%5D=Form&tx_powermail_pi1%5Bhash%5D=bb7b793ffcae021d19b44480f48df92a2cdbeb5ffebaa5dba23759b9c1fbf94c&tx_powermail_pi1%5Bmail%5D=40&cHash=827cbe0fd18e6e82fe1738102fe1aecc - {"TYPO3_MODE":"FE","exception":"TYPO3\\CMS\\Core\\Error\\Exception: PHP Warning: Illegal string offset 'form' in \/usr\/www\/users\/kundexy\/web\/typo3conf\/ext\/powermail\/Classes\/Domain\/Validator\/UploadValidator.php line 56 in \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/core\/Classes\/Error\/ErrorHandler.php:124\nStack trace:\n#0 \/usr\/www\/users\/kundexy\/web\/typo3conf\/ext\/powermail\/Classes\/Domain\/Validator\/UploadValidator.php(56): TYPO3\\CMS\\Core\\Error\\ErrorHandler->handleError(2, 'Illegal string ...', '\/usr\/www\/users\/...', 56, Array)\n#1 \/usr\/www\/users\/kundexy\/web\/typo3conf\/ext\/powermail\/Classes\/Domain\/Validator\/UploadValidator.php(29): In2code\\Powermail\\Domain\\Validator\\UploadValidator->formHasUploadFields()\n#2 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/extbase\/Classes\/Validation\/Validator\/AbstractValidator.php(99): In2code\\Powermail\\Domain\\Validator\\UploadValidator->isValid(Object(In2code\\Powermail\\Domain\\Model\\Mail))\n#3 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/extbase\/Classes\/Validation\/Validator\/ConjunctionValidator.php(40): TYPO3\\CMS\\Extbase\\Validation\\Validator\\AbstractValidator->validate(Object(In2code\\Powermail\\Domain\\Model\\Mail))\n#4 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/extbase\/Classes\/Mvc\/Controller\/Argument.php(341): TYPO3\\CMS\\Extbase\\Validation\\Validator\\ConjunctionValidator->validate(Object(In2code\\Powermail\\Domain\\Model\\Mail))\n#5 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/extbase\/Classes\/Mvc\/Controller\/Arguments.php(299): TYPO3\\CMS\\Extbase\\Mvc\\Controller\\Argument->validate()\n#6 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/extbase\/Classes\/Mvc\/Controller\/ActionController.php(315): TYPO3\\CMS\\Extbase\\Mvc\\Controller\\Arguments->validate()\n#7 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/extbase\/Classes\/Mvc\/Controller\/ActionController.php(167): TYPO3\\CMS\\Extbase\\Mvc\\Controller\\ActionController->callActionMethod()\n#8 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/extbase\/Classes\/Mvc\/Dispatcher.php(73): TYPO3\\CMS\\Extbase\\Mvc\\Controller\\ActionController->processRequest(Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Request), Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Response))\n#9 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/extbase\/Classes\/Mvc\/Web\/FrontendRequestHandler.php(92): TYPO3\\CMS\\Extbase\\Mvc\\Dispatcher->dispatch(Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Request), Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Response))\n#10 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/extbase\/Classes\/Core\/Bootstrap.php(172): TYPO3\\CMS\\Extbase\\Mvc\\Web\\FrontendRequestHandler->handleRequest()\n#11 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/extbase\/Classes\/Core\/Bootstrap.php(159): TYPO3\\CMS\\Extbase\\Core\\Bootstrap->handleRequest()\n#12 [internal function]: TYPO3\\CMS\\Extbase\\Core\\Bootstrap->run('', Array)\n#13 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(5971): call_user_func_array(Array, Array)\n#14 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/frontend\/Classes\/ContentObject\/UserContentObject.php(41): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->callUserFunction('TYPO3\\\\CMS\\\\Extba...', Array, '')\n#15 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(815): TYPO3\\CMS\\Frontend\\ContentObject\\UserContentObject->render(Array)\n#16 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(731): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render(Object(TYPO3\\CMS\\Frontend\\ContentObject\\UserContentObject), Array)\n#17 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/frontend\/Classes\/Controller\/TypoScriptFrontendController.php(3813): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('USER', Array)\n#18 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/frontend\/Classes\/Controller\/TypoScriptFrontendController.php(3774): TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController->INTincScript_process(Array)\n#19 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/frontend\/Classes\/Controller\/TypoScriptFrontendController.php(3741): TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController->recursivelyReplaceIntPlaceholdersInContent()\n#20 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/frontend\/Classes\/Http\/RequestHandler.php(187): TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController->INTincScript()\n#21 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/frontend\/Classes\/Middleware\/OutputCompression.php(46): TYPO3\\CMS\\Frontend\\Http\\RequestHandler->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#22 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\OutputCompression->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(TYPO3\\CMS\\Frontend\\Http\\RequestHandler))\n#23 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/adminpanel\/Classes\/Middleware\/AdminPanelDataPersister.php(44): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#24 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Adminpanel\\Middleware\\AdminPanelDataPersister->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#25 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/adminpanel\/Classes\/Middleware\/AdminPanelRenderer.php(46): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#26 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Adminpanel\\Middleware\\AdminPanelRenderer->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#27 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/frontend\/Classes\/Middleware\/ContentLengthResponseHeader.php(45): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#28 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\ContentLengthResponseHeader->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#29 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/frontend\/Classes\/Middleware\/ShortcutAndMountPointRedirect.php(65): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#30 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\ShortcutAndMountPointRedirect->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#31 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/frontend\/Classes\/Middleware\/PrepareTypoScriptFrontendRendering.php(118): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#32 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\PrepareTypoScriptFrontendRendering->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#33 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/frontend\/Classes\/Middleware\/PageArgumentValidator.php(87): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#34 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\PageArgumentValidator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#35 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/frontend\/Classes\/Middleware\/MaintenanceMode.php(53): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#36 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\MaintenanceMode->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#37 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/frontend\/Classes\/Middleware\/PageResolver.php(162): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#38 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\PageResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#39 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/workspaces\/Classes\/Middleware\/WorkspacePreview.php(106): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#40 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Workspaces\\Middleware\\WorkspacePreview->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#41 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/redirects\/Classes\/Http\/Middleware\/RedirectHandler.php(70): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#42 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Redirects\\Http\\Middleware\\RedirectHandler->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#43 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/frontend\/Classes\/Middleware\/StaticRouteResolver.php(66): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#44 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\StaticRouteResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#45 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/frontend\/Classes\/Middleware\/SiteBaseRedirectResolver.php(75): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#46 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\SiteBaseRedirectResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#47 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/adminpanel\/Classes\/Middleware\/AdminPanelInitiator.php(58): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#48 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Adminpanel\\Middleware\\AdminPanelInitiator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#49 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/frontend\/Classes\/Middleware\/SiteResolver.php(68): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#50 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\SiteResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#51 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/adminpanel\/Classes\/Middleware\/SqlLogging.php(49): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#52 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Adminpanel\\Middleware\\SqlLogging->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#53 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/frontend\/Classes\/Middleware\/BackendUserAuthenticator.php(95): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#54 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\BackendUserAuthenticator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#55 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/frontend\/Classes\/Middleware\/FrontendUserAuthenticator.php(79): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#56 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\FrontendUserAuthenticator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#57 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/frontend\/Classes\/Middleware\/TypoScriptFrontendInitialization.php(90): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#58 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\TypoScriptFrontendInitialization->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#59 \/usr\/www\/users\/kundexy\/web\/typo3conf\/ext\/staticfilecache\/Classes\/Middleware\/StaticFileCacheMiddleware.php(33): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#60 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): SFC\\Staticfilecache\\Middleware\\StaticFileCacheMiddleware->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#61 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/frontend\/Classes\/Middleware\/EidHandler.php(50): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#62 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\EidHandler->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#63 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/frontend\/Classes\/Middleware\/PreprocessRequestHook.php(57): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#64 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\PreprocessRequestHook->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#65 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/core\/Classes\/Middleware\/NormalizedParamsAttribute.php(58): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#66 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Core\\Middleware\\NormalizedParamsAttribute->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#67 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/frontend\/Classes\/Middleware\/TimeTrackerInitialization.php(49): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#68 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\TimeTrackerInitialization->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#69 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/core\/Classes\/Http\/MiddlewareDispatcher.php(67): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#70 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/core\/Classes\/Http\/AbstractApplication.php(98): TYPO3\\CMS\\Core\\Http\\MiddlewareDispatcher->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#71 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/frontend\/Classes\/Http\/Application.php(69): TYPO3\\CMS\\Core\\Http\\AbstractApplication->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#72 \/usr\/www\/users\/kundexy\/web\/typo3\/sysext\/core\/Classes\/Http\/AbstractApplication.php(110): TYPO3\\CMS\\Frontend\\Http\\Application->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#73 \/usr\/www\/users\/kundexy\/web\/index.php(24): TYPO3\\CMS\\Core\\Http\\AbstractApplication->run()\n#74 \/usr\/www\/users\/kundexy\/web\/index.php(25): {closure}()\n#75 {main}"}
`

The URL in the mail is this:
http://www.domain.de/karriere/online-bewerbung?tx_powermail_pi1%5Baction%5D=optinConfirm&tx_powermail_pi1%5Bcontroller%5D=Form&tx_powermail_pi1%5Bhash%5D=e43cd31d5878e7c866d314ba41c73eab91a84b3a6d9b58db20ea012b0a04785d&tx_powermail_pi1%5Bmail%5D=39&cHash=53182f8709d94fb9eade07b5c69ca500

**Comment by mschmitz89** [comment]
Any news or hints to fix this?

**Comment by mschmitz89** [comment]
Found a hotfix for this:

In typo3conf\ext\powermail\Classes\Controller\FormController.php

Remove line 88 with the following code:

` * @validate $mail In2code\Powermail\Domain\Validator\UploadValidator`

**Comment by mschwemer** [comment]
Hi @mschmitz89 

thanks for the report.

I am currently going through all the issues and try to reproduce them.

With TYPO3 V10 and the current develop branch, I cannot reproduce the issue.

Are you still hit by the problem. If yes, can you provide more information?

TIA

**Comment by mschwemer** [comment]
Closed due to inactivity

**Comment by mschmitz89** [comment]
Hi @mschwemer,

sorry for not responding more to the query. Unfortunately, the mail has gone down with me.

I have now come across this ticket again, because I have the same problem now with the latest TYPO3 11.5.23 and Powermail 10.7.2 again in another installation.

As soon as an upload field is present and the double opt-in is active, no more mails arrive. Neither for the sender nor for the form recipient.

Do you need more information here? If so, what exactly?
