### ISSUE TITLE
After Submit -> Scroll Offset if error in a field

### ISSUE THREAD

**Issue by chequille** [einpraegsam/powermail#448]
Hi,
my page does have a fixed header.
Therefore, when there is a wrong entry in a field of the form or a mandatory field not filled, page scrolls to the first field with an error.
Unfortunately, this field is covered by my fixed header and therefore not visible.
Is there a way to change this with some kind of offset to this scroll function?

Please let me know if you have any idea.
BR
Jürgen

**Comment by mschwemer** [comment]
The scrolling functionality on errors come from the third party library. You might want to look there, how to configure it. 

https://parsleyjs.org/
