### ISSUE TITLE
Marker is set incorrectly on translated fields

### ISSUE THREAD

**Issue by elmarputz** [einpraegsam/powermail#45]
On our TYPO3 8.6, we face the problem, that every time, we add or update a translated field, the marker of the translated fields is set to the translated title - the marker from the original language gets overriden. 

Example: 

- original field name "Firstname" -> marker name "firstname" 
- adding translation "Vorname" -> marker name (in translated field): "vorname" 

This leads to incorrect frontend markup. All labels are translated correctly.
We checked all language settings and tested different language settings - no success at all.

TYPO3 Version: 8.6
PHP Version 7.0.13

**Comment by einpraegsam** [comment]
I digged a bit into this issue and I think this is a core issue. I created a redmine ticket to it: https://forge.typo3.org/issues/79983
I will let this ticket open as long as there is no final solution.

**Comment by einpraegsam** [comment]
I commited a patch to develop branch. Ready for upcoming release.
