### ISSUE TITLE
Limit number of form submissions

### ISSUE THREAD

**Issue by starryprabin** [einpraegsam/powermail#450]
Is there a way to limit the number of submissions for particular form? For example, I want to display the form until 10 number of submissions are made. After that there is a message like `The limit of submission has reached. It is not possible to submit again`, or `The maximum number of limit has reached.` or any other message.

Regards

**Comment by einpraegsam** [comment]
Look at the default TypoScript https://github.com/einpraegsam/powermail/blob/develop/Configuration/TypoScript/Main/setup.txt#L56
