### ISSUE TITLE
typo @ DE

### ISSUE THREAD

**Issue by xerc** [einpraegsam/powermail#452]
<target state="translated">Handelt es sich bei dieser E-Mail um ein versehen
->
<target state="translated">Handelt es sich bei dieser E-Mail um ein Versehen

**Comment by xerc** [comment]
verständlicher/ "Haben Sie diese E-Mail nicht angefordert und Sie möchten Ihre Daten löschen?"

**Comment by einpraegsam** [comment]
Pls feel free to to a pull request

**Comment by xerc** [comment]
Duplicate of #453

**Comment by mschwemer** [comment]
Can be closed. 

Mentioned PR #453 is already merged
