### ISSUE TITLE
GP: values in Typoscript when using double opt-in

### ISSUE THREAD

**Issue by fabrikatur** [einpraegsam/powermail#455]
Hi.
Thanks for the versatile plugin.

I'm using an adaption of your doc's example for multiple predefined receivers.
(Dynamic example 2, https://docs.typo3.org/typo3cms/extensions/powermail/stable/ForAdministrators/BestPractice/DynamicReceiver/Index.html)

As soon as I activate the Double Opt-in, which is mandatory due to GDPR reasons I don't seem to able to access the Get/Post-Values in Typoscript (typo3 8.7.26, powermail 7.3.1)

Is this an error or is there another way to pass the value of a form field to the cObjectViewHelper for the receiver mail when using Double Opt-in?

Cheers.

**Comment by einpraegsam** [comment]
Of course, double opt in is an extra process and there are no GP veriables
