### ISSUE TITLE
Multifile attachment limit not working

### ISSUE THREAD

**Issue by cybergwei** [einpraegsam/powermail#456]
if you use the multifile upload field the file size limit doesn't work when you a choose a second file. if only one file is selected it is working.

**Comment by mschwemer** [comment]
Dear @cybergwei 

I am currently going through all the old issues and try to reproduce them with the TYPO3 10.4 and branch:develop of powermail.

I cannot reproduce the mentioned behavior. I tested client side and server side validation

If your are still hit by the issue, feel free to re-open it.

**Comment by z-spondoms** [comment]
I am currently utilizing Typo3 version 11.5.25 along with Powermail version 10.7.0. Unfortunately, the issue persists despite these versions. The upload limit is configured to 10485760 bytes (approximately 10MB). However, users can get around the validation when uploading two or more files, such as two 7MB files. In this scenario, the email fails to send, but no error is displayed in the frontend.
