### ISSUE TITLE
Mail getUid() in Finisher

### ISSUE THREAD

**Issue by rafu1987** [einpraegsam/powermail#457]
Hello there,

I am writing a custom finisher and am wondering how to get the uid of the already persisted mail. When I debug, the uid is NULL.

Any hints?

Thanks :-)

**Comment by rafu1987** [comment]
Okay, I'm not saving the mail actually, but to a custom table. So is there any way to get the uid in the finisher of the record, that was created?

**Comment by einpraegsam** [comment]
`$this->getMail()->getUid()` would be the correct line. See https://docs.typo3.org/typo3cms/extensions/powermail/7.3.1/ForDevelopers/AddFinisherClasses/Index.html for a bigger example of how to implement finishers.
