### ISSUE TITLE
When reloading [F5] the submit page the form will be sent again

### ISSUE THREAD

**Issue by epxfrho** [einpraegsam/powermail#458]
When reloading [pressing F5] the submit page the form will be sent again. Wenn you using a redirect to any other Page after submit, it's ok. But using the submit page of the powermail plugin, you can send form as often as you want by pressing F5. 

I know this issue from different projects with different powermail versions. Actually we use powermail 7.3.1 with Typo3 8.7.27. I've always wondered why I can not find an issue for this, but maybe I've searched for the wrong terms?

I think you should never be able to resend the form / email multiple times by reloading the page. Regardless of whether you use a captcha or which spam shield settings you use.

best regards
Frank

**Comment by einpraegsam** [comment]
Please look at https://docs.typo3.org/typo3cms/extensions/powermail/7.3.1/ForAdministrators/BestPractice/PreventDuplicates/Index.html for some details on your task

**Comment by epxfrho** [comment]
Thanks for the answer.

But the server side solution, with the unique field, will not work if no mails will be stored in the database. And in case of GDPR (General Data Protection Regulation or DSGVO in Germany) it might become the standard not to store mails in the database.

And the client side solution based on js, which prevents clicking on the submit button more than once, will not work either, if the user is already on the submit page.

I think their should be a build in solution. Or do I overlook something? Perhaps the spam shield's session method might be a solution, if the session entry would be deleted after sending the mail.

bets regards
Frank
