### ISSUE TITLE
lib.parseFunc_powermail is empty because of wrong loading order

### ISSUE THREAD

**Issue by franzkugelmann** [einpraegsam/powermail#46]
`lib.parseFunc_powermail` is set in ext_typoscript_setup.txt. My understanding is that stuff in this file is by default loaded BEFORE stuff from static templates like fluid_styled_content. This has the effect that
`lib.parseFunc_powermail < lib.parseFunc_RTE`
does not work, because `lib.parseFunc_RTE` is empty at this point.
This results in **wrong or missing formatting in sent mails**.
I think we use the default settings in our project, so this should be relevant to most installations, independant of TYPO3 version.
You can check if you suffer the same problem in every specific installation via the Template Module in  TypoScript-Object-Browser or Template Analyse.

We solved this issue by dupicating
`lib.parseFunc_powermail < lib.parseFunc_RTE
lib.parseFunc_powermail.tags.link.typolink.forceAbsoluteUrl = 1`
into our project TypoScript, which is loaded after all other TypoScript was loaded.

**Comment by franzkugelmann** [comment]
Ah sorry, should have checked before. This is duplicate of #43.
But i have default setting `(default) include before if root flag is set`.

**Comment by einpraegsam** [comment]
Hi Franz,

it seems that you're right. And of course that must be fixed.
Nevertheless I did not bring it to work in TYPO3 8.6, even if I added something like
```

# ParseFunc Configuration for using FAL links in receiver and sender mail
<INCLUDE_TYPOSCRIPT: source="FILE:EXT:fluid_styled_content/Configuration/TypoScript/Helper/ParseFunc.txt">
lib.parseFunc_powermail < lib.parseFunc_RTE
lib.parseFunc_powermail.tags.link.typolink.forceAbsoluteUrl = 1
```
At the very end of my setup. Where did you place the code? Do you use CSC or only FSC? Which TYPO3 version?

**Comment by maechler** [comment]
Hi all,

We face the same issue using CSC and TYPO3 7.6.15. It would actually work if we moved the settings to `TypoScript/Main/setup.txt`. 
The `lib.parseFunc_powermail` is only relevant for the front end (or am I missing something?) and in order for the front end to work properly I guess we need the `TypoScript/Main/setup.txt` anyways.

What do you think?

**Comment by franzkugelmann** [comment]
Hi Alex,
we had TYPO3 7.6.15 with FSC and just added the two lines into our project specific TS settings, which is loaded after all the default and static templates.
`lib.parseFunc_powermail < lib.parseFunc_RTE lib.parseFunc_powermail.tags.link.typolink.forceAbsoluteUrl = 1
`
@maechler is right, putting it into `TypoScript/Main/setup.txt` should work, too. Not sure if mails are sent from backend somewhere, though.

**Comment by einpraegsam** [comment]
Moving to setup.txt could be a solution but that does not help in TYPO3 8.6 (on my testsystem) and I would like to also solve this issue. :/

**Comment by franzkugelmann** [comment]
I will test on 8.6 next week with another project.

**Comment by franzkugelmann** [comment]
I did some analysis and have to apologize for the confusion i created. We had a hook in place which modfied the `(default) include before if root flag is set` setting on runtime. 
The current structure in powermail is perfectly fine IF you stick to the default setting in field sys_template::static_file_mode, because the settings in ext_typoscript_setup.txt are loaded after the static FSC template (as expected by @einpraegsam) In both 7LTS and 8.7.0-dev! 
If you need a different setting just readd the two lines as described above. 

Now for @einpraegsam and those who updated from 8.5 recently: Your project probably missing the lib.parseFunc_RTE altogether currently. With the rework of EXT:fluid_styled_content they seem to have changed the keys for the static templates. In my instance i needed to readd the static template for fluid_styled_content, there was only the template "Fluid Content Elements CSS (optional)" selected, but i am sure we had the correct static template added back then. Now the `lib.parseFunc_powermail` looks just fine.
I close this issue. If there are still problems they have probably nothing to do with loading order of TypoScript.

**Comment by maechler** [comment]
@einpraegsam @franzkugelmann 

Even though it works with the default settings of TYPO3, I think it would still be an improvement to move it to `TypoScript/Main/setup.txt` in order to avoid that error if someone does not use the default settings (as we do).
The `lib.parseFunc_powermail` so far is only used in the templates `Mail/ReceiverMail.html` and `Mail/SenderMail.html`. Thus I think it should be save to move it.

**Comment by franzkugelmann** [comment]
I guess the reason to put it to the current location is to be independent of the inclusion order of the static templates. If someone includes powermail before Fluid Styled Content it would not work.
But thats up to @einpraegsam  :)
Thanks anyway for all the feedback and the great work in powermail!

**Comment by mueller-sebastian** [comment]
We just got the problem that links in RTE lists (ul / ol) were still relative.

This comes because of the stdWrap.parseFunc defined for this external blocks, where lib.parseFunc is defined.
Removing stdWrap (was not rendered as html anymore) or setting stdWrap.parseFunc to lib.parseFunc_powermail (generating infinite loop) did not work.

We could fix it by adding the following typoscript:
`
lib.parseFunc_powermail.externalBlocks.ul.stdWrap.parseFunc.tags.link.typolink.forceAbsoluteUrl = 1
lib.parseFunc_powermail.externalBlocks.ol.stdWrap.parseFunc.tags.link.typolink.forceAbsoluteUrl = 1`
