### ISSUE TITLE
Translated record not respected by Powermail

### ISSUE THREAD

**Issue by MrMooky** [einpraegsam/powermail#467]
We're currently referencing multiple elements from an English translation into the Polish one. Every element works fine, but the Powermail Form outputs the Default Form in German instead of the translated one.

![powermail_reference](https://user-images.githubusercontent.com/3603346/64231745-ba9f8480-cef0-11e9-8e1e-60078bcb53e0.jpg)

It is being referenced correctly, yet the output is this:

<img width="829" alt="Screen Shot 2019-09-04 at 08 42 34" src="https://user-images.githubusercontent.com/3603346/64231798-d2770880-cef0-11e9-82f1-6fc3ee83bb0d.png">

How could we fix this?

**Comment by einpraegsam** [comment]
Referencing maybe not supported at the moment - sorry
