### ISSUE TITLE
Fix sys_language_uid labels for TYPO3 9.5

### ISSUE THREAD

**Issue by IndyIndyIndy** [einpraegsam/powermail#470]
See also: https://github.com/einpraegsam/powermail/issues/267

Language labels are not working for TYPO3 9.5.

**Comment by einpraegsam** [comment]
Thx for the PR - what about TYPO3 8.7?

**Comment by mschwemer** [comment]
Thanks for your PR. Merged into develop and the associated one of @sypets to 7.x
