### ISSUE TITLE
IRRE records not visible in BE, within form records

### ISSUE THREAD

**Issue by AnuBN** [einpraegsam/powermail#472]
**Environment :** 
TYPO3 : v8.7.27
Powermail : v3.22.1

**Issue :** 
When a new powermail form/powermail page is created in a folder/page from backend, every process appears normal until saving the form. Once saved and reopened, the IRRE records (pages in case of forms and fields in case of pages) are not rendered completely. But with a checkbox and an input field.
There are no error messages or warnings. The same scenario triggers when forms are opened from 'Mails' module too.
Please see the screenshot.

![Screenshot 2019-09-25 at 11 57 21](https://user-images.githubusercontent.com/18255272/65591301-87e72a00-df8c-11e9-9b01-bd271d6b5393.png)

**Comment by einpraegsam** [comment]
Powermail 3.x is not supported any more
