### ISSUE TITLE
Powermail Frontend and Powermail Conditions

### ISSUE THREAD

**Issue by chequille** [einpraegsam/powermail#474]
Hi Alex,
I want to use pwoermail_frontend plugin to be able to change mail records.
Generally it is working.
But my form is using powermail conditions and these are not active in the frontend plugin. Meaning, all fields of the form are shown in the frontend editing, as well those which are hidden and not active caused by powermail conditions.

Is there any chance to get this working?
Does it maybe depend on the template for frontend editing?

Would be great to hear something from you about this issue.

Best regards,

Chequille

**Comment by einpraegsam** [comment]
Conditions are not compatible with _frontend at the moment
