### ISSUE TITLE
Add LICENSE.txt

### ISSUE THREAD

**Issue by pquerner** [einpraegsam/powermail#475]
It is noted that you use GNU 2+ for this extension, however I think the GNU LICENSE fill should be an actual file.

Currently we have the situation that we have a customer where we have to say which software was used or is going to be used and give a linkback to the LICENSE file. I don't know if a line in composer.json is enough for that at this time.

**Comment by einpraegsam** [comment]
Hi, I don't see the need but if it would help you, feel free to make a PR

**Comment by pquerner** [comment]
I explained the need, I think.
Think of a company. You, as an agency want to do work for them. The company has a OSS devision which must give its OK to all parts of your application (before you even begin). In this document you need to give details (not fully, but partial) which software you intend to use, and which LICENSE is attached to it.
This extension came up and I had to give the full URL to the LICENSE file (can be named whatever, but the contents must be the used license). In your case I had to give something alike 

https://github.com/einpraegsam/powermail/blob/develop/composer.json#L18

Which is not ideal.

I don't know yet how it will impact the situation, but I am guessing there is some possability that it will raise questions. Which could easily be fixed with a simple LICENSE file.
