### ISSUE TITLE
TypoScript documentation uses wrong keys

### ISSUE THREAD

**Issue by Abdull** [einpraegsam/powermail#477]
[The powermail 7.3.1 documentation writes on the _Main TyposScript_ page](https://docs.typo3.org/typo3cms/extensions/powermail/stable/ForAdministrators/BestPractice/MainTypoScript/Index.html):

```
Constants (should be prefixed with plugin.tx_powermail.settings.)
...
misc.htmlForHtmlFields
...
```
For above example and other keys in the `misc.*` `main.*` (and possibly other prefixes), this is wrong.

Correct is:

```
Constants (should be prefixed with plugin.tx_powermail.settings.setup.)
```

Notice the additional `setup.`.

**Comment by einpraegsam** [comment]
Thx, feel free to do a PR - I will accept it asap.

**Comment by mschwemer** [comment]
This is wrong. 

The `setup` typoscript path segment is only valid for typoscript setup and not for the constants. 

I checked it within the TypoScript Object Browser. 

So nothing to do here.
