### ISSUE TITLE
DisclaimerLink

### ISSUE THREAD

**Issue by ursbraem** [einpraegsam/powermail#480]
Please, please set 

`plugin.tx_powermail.settings.sender.addDisclaimerLink = 0`

as default value instead of 1.

This has caused some confusion for our clients. We introduced the feature unnoticedly (composer update). The users didn't understand the wording and clicked the link, causing their entries to be deleted.

**Comment by mgrundkoetter** [comment]
Also: When the user does explicitly NOT want to send his/her data to the receiver, the default mail template should not contain the `{powermail_all}` marker as this kind of contradicts the whole thing, right?

**Comment by ursbraem** [comment]
@mgrundkoetter I agree, but that's another topic, isn't it?

**Comment by mschwemer** [comment]
On the one hand I basically agree, 

But the feature was introduced in October 2018, your report is of October 2019, and now it is March 2021. 

We leave it as is, because for many others, this will be breaking, if they do not set the value manually.
