### ISSUE TITLE
localization problems with fields and pages after upgrade (typo3 9.5.10, powermail 7.4.0)

### ISSUE THREAD

**Issue by zabinetta** [einpraegsam/powermail#481]
Dear Alex,

I had a very strange localization behavior and I would like to tell the story in case I'm not the only one:
last week I upgraded a site with many powermail-forms from 8.7 to 9.5, and powermail 7.3.1 to 7.4.0, too.
Afterwards, all my mailforms were corrupted: the base language form had all fields in all languages mixed, and localized record Language 1 had no fields at all. In Backend, list module, the forms, form-pages and fields looked well in Localization view.

Later I found out: the problem was, that the localized fields were pointing to the base-language form-pages, not to the translated page. I am quite sure my editor had localized them by the backend-list-module, directly, as this is possible in backend.
If you want to have a look in your database:
`SELECT f.*,p.uid,p.title,p1.uid,p1.title FROM `tx_powermail_domain_model_field` f 
join `tx_powermail_domain_model_page` p on f.pages=p.uid 
join `tx_powermail_domain_model_page` p1 on p1.l10n_parent=p.uid
where f.`sys_language_uid`=1 and p.`sys_language_uid` = 0`

So I did the folowing things: 

1. in Backend I am now hiding the powermail fields and pages in the list-module in order to force my editor to localize from inside the form-record:
mod.web_list.table.tx_powermail_domain_model_field.hideTable = 1
mod.web_list.table.tx_powermail_domain_model_page.hideTable = 1
2. in the database this helps to tix the corrupted fields:
`Update `tx_powermail_domain_model_field` f 
join `tx_powermail_domain_model_page` p on f.pages=p.uid 
join `tx_powermail_domain_model_page` p1 on p1.l10n_parent=p.uid
set f.pages=p1.uid
where f.`sys_language_uid`=1 and p.`sys_language_uid` = 0`

Generally, it could be an Idea to hide the fields and pages in list-module..

With the best regards,
Sabine

**Comment by npoggenburg** [comment]
we have the same problem!

**Comment by j4k3** [comment]
Same here. Thanks for taking the time to document the insight on this, Sabine.

**Comment by mschwemer** [comment]
Thanks for your report. 

Sorry for the hassle. Manually translating the each single field is not meant to be done. Additionally this might be an upgrade issue, as the language handling changed between V8 and V9. 

I think, there is nothing to to here right now. 

If you still think, hiding the single fields in the list view is a good idea, please open a feature request (and in best case a pull request ;-) )
