### ISSUE TITLE
Ready only for a single field possible?

### ISSUE THREAD

**Issue by kalinka2103** [einpraegsam/powermail#484]
Hello, I'm new in T3 and even newer in working with powermail. I try to set up a form with several fields but with one field that cannot be edited from the user (ready only).

I have frontend users and some forms that are visible after login. The "name" field shall be pre filled with the name saved in the user account (I figured out how this works). But I need an option to set just this field to read only, so the user can't edit the name.

I've found some solutions in the web, but that didn't work for me or would not work for my intention (like simply hiding the name field, but that would cause that it's not seen in the received mail too).

Does anyone have an idea how to solve this problem?

**Comment by einpraegsam** [comment]
Please ask for support on slack or stackoverflow. This area is for collecting bugs and features.
