### ISSUE TITLE
[BUGFIX] add eval => 'int' for starttime and endtime in tca

### ISSUE THREAD

**Issue by axelp94** [einpraegsam/powermail#489]
Add eval => 'datetime,int' for starttime and endtime in tca because an SQL error

"SQL error: 'Incorrect integer value: '' for column 'starttime' at row 1' (tx_powermail_domain_model_field:)"
 
occurs when you use "Strict SQL Mode" for mysql and you delete the datetime field and save the record.

**Comment by einpraegsam** [comment]
Fixed in powermail 8.0.0
