### ISSUE TITLE
Mail to Sender does not work

### ISSUE THREAD

**Issue by kalinka2103** [einpraegsam/powermail#492]
Hello einpraegsam,

I have a problem with Powermail 7.4 (Typo3 9.5). Whatever I try, the sender gets no copy of the mail he sent. My test account (frontend user) has a mail address in his user settings, that's shown in a powermail text field (get from frontend database). I've already checked the field that it contains the mail address of the sender. In the powermail backend I also have content in the formulars field for subject and content of the mail to the sender.

a) If I don't use TS, but write a mail address (mail@provider.tld) into the field mail address of the sender in the formular backend, the sender don't get a mail anyways.

b) I also tried follow TS setup / constant:
`plugin.tx_powermail.settings.setup.sender.enable = 0`
`[globalString = GP:tx_powermail_pi1|field|FIELDID|0 = *Kopie*]`
`plugin.tx_powermail.settings.setup.sender.enable = 1`
`[end]`

My checkbox contains "Kopie" ("Kopie an mich"). I tried using the ID of the checkbox or the name of the marker of it (with and without {}) in FIELDID, but it did not work.

c) In the internet I found a possible solution with "value=yes" for the code above, but sadly it did not work too.

By the way if I use the settings above, the receiver does not get any mail too. I'm not sure if this "error" occured at each of the settings or just on some specific, but if that's important, I could reconstruct it.

I hope you or someone else can help me with that problem. I have no idea what I could try or do to make it work.

**Comment by einpraegsam** [comment]
When there is a problem with sending mails in powermail it's mostly because of SPF defiance. Did you read and respect https://docs.typo3.org/typo3cms/extensions/powermail/stable/Faq/Index.html#how-to-solve-spf-defiance ?

**Comment by mschwemer** [comment]
Closing it due to inactivity.
