### ISSUE TITLE
checked=checked only if "*" is really set by editor

### ISSUE THREAD

**Issue by josefglatz** [einpraegsam/powermail#493]
I found out that in the actuall powermail version 7.4 `checked=checked` for e.g. radio buttons is set each of them when the editor uses a pipe at the end without a `*` in the TYPO3 backend.

### In this example, both of them have `checked=checked` and the last one is effectively checked for the website visitor of the form

![image](https://user-images.githubusercontent.com/2861556/73152331-ceca6500-40cf-11ea-9b29-63001be377a0.png)

### As an editor I assume, that the shown example above behaves like:

![image](https://user-images.githubusercontent.com/2861556/73152413-1e109580-40d0-11ea-9bcb-6b1d3dce6b03.png)

---

* What do you think about?
* Is this a usability improvement for editors of the powermail form?
* I think that this worked before in any previous version of powermail?

**Comment by einpraegsam** [comment]
Fixed in develop branch. Will be released with the next version.
