### ISSUE TITLE
Backlink to form-page

### ISSUE THREAD

**Issue by emhmf** [einpraegsam/powermail#494]
Hello everybody 

I have a powermail form that is included on several pages. After submit I would like to redirect to another page. On this forwarding page I need a backlink to the page where the form was submitted.
I have tried it in several ways, but none of them worked so far.

I use powermail v7.4.0 and TYPO3 9.5.13

Does anyone have any tips on how I could do this?

Thanks for any hint
Martin

**Comment by einpraegsam** [comment]
Just add a button with a JavaScript back to the form.
BTW: This is not a support-place but more an issue board. Stackoverflow or Slack would be the best place for such questions.
