### ISSUE TITLE
Support for crowdin

### ISSUE THREAD

**Issue by georgringer** [einpraegsam/powermail#497]
It would be nice to have crowdin localized in more languages by using Crowdin

**Comment by comradekingu** [comment]
@georgringer Crowdin has less activity, fewer projects, doesn't promote small projects, and spies on the user https://support.crowdin.com/cookies/

https://weblate.org/hosting/ is a much better alternative.

**Comment by georgringer** [comment]
We are using crowdin for complete typo3 project

**Comment by comradekingu** [comment]
Or Crowdin is using TYPO3 translators to sell tracked advertising and populate its translation memory for the entire project. If you want more languages, and better quality translations in those langauges, go to where the libre software translators and libre software projects are.

**Comment by comradekingu** [comment]
8 languages reaching coverage in 4 months is not good.

**Comment by mschwemer** [comment]
Hi @georgringer, 

I am wondering, why Crowdin shows that only 2% of the labels are translated to german. We have probably 100% translated. 
https://crowdin.com/project/typo3-extension-powermail/de#

Can you tell me, what I am doing wrong?

TIA

**Comment by georgringer** [comment]
Will try to check this week

**Comment by georgringer** [comment]
@mschwemer I imported the translations now, 96% finished you can add any other translation from pootle by doing the following:

1.) Fetch it e.g. with `wget 'https://extensions.typo3.org/fileadmin/ter/p/o/powermail-l10n/powermail-l10n-el.zip'` Use any locale you know
2.) extract the tar.gz
3.) Go to the directory `Resources/Private/Language/`
4.) Open the xlf files and replace `original="messages"` with `original="EXT:powermail/Resources/Private/Language/locallang.xlf"` ( of course it needs to fit the opened  file path) - it must match the one from default files, see https://github.com/einpraegsam/powermail/blob/develop/Resources/Private/Language/locallang.xlf#L3
5.) you can upload the xlf files at https://crowdin.com/project/typo3-extension-powermail/settings#translations

If you got any questions, please don't hesitate to contact me via slack

**Comment by mschwemer** [comment]
Thanks for your explanation. It worked like a charm. 
 Been there, done that. 
I copied all available translations from pootle to crowdin.

**Comment by georgringer** [comment]
Awesome
