### ISSUE TITLE
Use of captcha with Typo3 8.2 

### ISSUE THREAD

**Issue by mepoe** [einpraegsam/powermail#5]
Hi, 

When adding a captcha field to a form with a typo3 8.2 installation, the following error message shows on the frontend: 
Uncaught TYPO3 Exception
#1256475113: The argument "field" was registered with type "In2code\Powermail\Domain\Model\Field", but is of type "string" in view helper "In2code\Powermail\ViewHelpers\Validation\ErrorClassViewHelper". (More information)

InvalidArgumentException thrown in file
/Applications/MAMP/typo3_src-8.2.1/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php in line 318.

powermail 3.7 is being used.

**Comment by einpraegsam** [comment]
Do you use a confirmation page?
What kind of captcha? An external extension or the build-in calculating captcha?

**Comment by mepoe** [comment]
Hi, no I dont use a confirmation page. And it is the build-in calculating captcha.

**Comment by einpraegsam** [comment]
This was fixed in current develop branch. Should be resolved in 3.9.0
