### ISSUE TITLE
SPF-Issue with yahoo-mails and replytoEmail for receiver

### ISSUE THREAD

**Issue by olivermeckel** [einpraegsam/powermail#502]
We have several issues with the SPF from yahoo.

Regarding to your FAQ **How to solve SPF defiance?** we can report that receiver mails get blocked when powermail uses automatic reply email address from the sender.

We are currently testing whether it is a hoster specific problem.
Site is hosted at Mittwald. Mittwald reported general problems with mail delivery to and from yahoo.

We could fix the problem by also overwriting the replyToEmail for receiver.

TYPO3 8.7.30 and Powermail 7.4.0

**Comment by einpraegsam** [comment]
So, what should I do with your information now?

**Comment by olivermeckel** [comment]
Hi Alex,

unfortunately, we don't know that either. We just wanted to inform the users of Powermail. 
The only solution: not to use the transmitted mail address of contact forms as sender address in confirmation mails.

**Comment by mschwemer** [comment]
Will close this isse, because, overwriting the email addresses is the way to go.
