### ISSUE TITLE
Not possible to create new forms/pages with 8.0.0 and 8.0.1

### ISSUE THREAD

**Issue by nebrot** [einpraegsam/powermail#503]
There are still more changes needed than in #501 for forms/pages => form/page. We can't create completly new forms with pages and fields with 8.0.1. Have you tested it? I think at least these files are still wrong and probably some more. Search for "forms" and "pages" in:
- Classes\Hook\CreateMarker.php ('p.form = fo.uid' and 'f.page = p.uid')
- Classes\Tca\ShowFormNoteEditForm.php ('p.form = fo.uid' and 'f.page = p.uid')
- Configuration\TCA\tx_powermail_domain_model_form.php ('foreign_field' => 'form')
- Configuration\TCA\tx_powermail_domain_model_page.php ('foreign_field' => 'page')

After manually fixing this it's possible for us to save a new form with one page and some fields.

![powermail-error](https://user-images.githubusercontent.com/6941112/74841552-22c01680-5329-11ea-81fb-7de34bac6e8a.png)

**Comment by nebrot** [comment]
Next error after trying to include the powermail-plugin:
![powermail-error](https://user-images.githubusercontent.com/6941112/74844344-9cf29a00-532d-11ea-919d-d51b945bb97b.png)

**Comment by einpraegsam** [comment]
https://github.com/einpraegsam/powermail/pull/504

**Comment by einpraegsam** [comment]
Thx for leading me into that direction. I created some forms and plugins and I do not see any more errors. Nevertheless it is still possible to run into some issues because of totally switching to a more typesave code in 8.x.
I will release a 8.0.2 in a few minutes. Hope for your feedback.

**Comment by nebrot** [comment]
Seems to work now, thank you for your great work! We only have now problems with redirect-field after form-submit. I'll open a new issue.
