### ISSUE TITLE
Redirect after submit doesn't work with 8.0.2

### ISSUE THREAD

**Issue by nebrot** [einpraegsam/powermail#506]
The thx-redirect after form-submit doesn't seem to work with 8.0.2. The link browser is missing too, see at top 8.0.2 and at bottom 7.4.0.

![powermail-thx-redirect](https://user-images.githubusercontent.com/6941112/75140306-e4db3d80-56ee-11ea-9d12-53f33a46d445.png)

**Comment by einpraegsam** [comment]
Thx for the feedback. Will be released in the upcoming version.
