### ISSUE TITLE
Double Opt-In

### ISSUE THREAD

**Issue by ekarakas** [einpraegsam/powermail#507]
Hi all,
i have a bug with Double Opt-In. 
after clicking the link in mail. Became following error msg:
Validation failed while trying to call In2code\Powermail\Controller\FormController->createAction()

My system
Powermail 7.4.0
Typo3 9.5.13

In Formular is no capture. Simple contactform with a finisher configuration to send data to an crm.

Best regards, ekarakas

**Comment by markussuess** [comment]
Maybe this helps:

https://github.com/einpraegsam/powermail/issues/376#issuecomment-519076454

**Comment by einpraegsam** [comment]
Duplicated to #376
