### ISSUE TITLE
"Reporting (Form)" doesn't work with 8.0.2

### ISSUE THREAD

**Issue by nebrot** [einpraegsam/powermail#508]
The module-function "Reporting (Form)" throws an error after clicking on it. We are using TYPO3 10.3.0 and have 0 mails saved.

![powermail-report-form](https://user-images.githubusercontent.com/6941112/75358704-9fb43880-58b3-11ea-8dab-26c0a036beef.png)

**Comment by einpraegsam** [comment]
Thx, I pushed a fix to develop branch
