### ISSUE TITLE
upload multiple not possible ??

### ISSUE THREAD

**Issue by xbouillet** [einpraegsam/powermail#512]
Hello,
I have a problem with multiple file uploads. Indeed, the "multiselect" option does not work.
In front, it is impossible to load multiple files.
Someone would have any idea?
PS: I have a typo3 v9.5 and powermail 7.4.0 

Thanks

**Comment by einpraegsam** [comment]
I can't see a problem. What browser did you use? What if you select more then only one file (by clicking strg+select)?

**Comment by mschwemer** [comment]
Closed due to missing response for one and a half year
