### ISSUE TITLE
ajaxSubmit does not work with 2 forms on the same page

### ISSUE THREAD

**Issue by schrob3000** [einpraegsam/powermail#516]
TYPO3: 8.7.29
Powermail: 7.4.0

Hello,

i have a contact box on every page which used ajaxSubmit=1 (Typoscript USER object). If there is another powermail form (CE) on the page, both forms work with ajax or without ajax. It depends on the sequence in the template.

Only the contactBox should use ajax.

###### Both forms normal:
```
<f:render section="content" />
<f:cObject typoscriptObjectPath="lib.contactBox" />
```

###### Both forms ajax:
```
<f:cObject typoscriptObjectPath="lib.contactBox" />
<f:render section="content" />
```

```
lib.contactBox = USER
lib.contactBox {
    userFunc = TYPO3\CMS\Extbase\Core\Bootstrap->run
    extensionName = Powermail
    pluginName = Pi1
    vendorName = In2code
    view < plugin.tx_powermail.view
    persistence < plugin.tx_powermail.persistence
    settings < plugin.tx_powermail.settings
    settings.setup.main.form = 10
    settings.setup.main.pid = 20
    settings.setup.misc.ajaxSubmit = 1
    
}
```

**Comment by einpraegsam** [comment]
No, that is not supported at the moment. Nevertheless you could build your own AJAX submit via JavaScript.
