### ISSUE TITLE
Limit subscriptions for a form

### ISSUE THREAD

**Issue by mathias-noethiger** [einpraegsam/powermail#519]
Imagine you want to create a form for an event with a limited number of seats.

It would be nice if one could set a limit (eg. 100 seats). 
When the limit is reached (100 forms sent)
then instead of the form, powermail shows a default page (e.g. "event booked out")

**Comment by einpraegsam** [comment]
Please don't ask for support on github. There is a slackchannel or stackoverflow, where everyone could help you.

For your question: https://github.com/einpraegsam/powermail/blob/develop/Configuration/TypoScript/Main/setup.typoscript#L56
