### ISSUE TITLE
german translation: uppercase letter instead of lowercase in label=disclaimer_mailmessage

### ISSUE THREAD

**Issue by medarob** [einpraegsam/powermail#520]
Hi,

the word "versehen" is wrong in `de.locallang.xml`
```
<label index="disclaimer_mailmessage">Handelt es sich bei dieser E-Mail um ein versehen und Sie wollen diese löschen?</label>
```

The correct spelling is "**V**ersehen" with an uppercase letter at the beginning.

**Comment by mschwemer** [comment]
Thanks for your hint. 

The sentence got rephrased in #f913aecef56b75d71b324686c7126544646896d3, so the word "versehen" is not there any more.
