### ISSUE TITLE
[FEATURE] reset file upload field

### ISSUE THREAD

**Issue by franzkugelmann** [einpraegsam/powermail#522]
Especially with big forms it would be convenient if a user could easily reset a file upload field, if she choose a file but then does not want to send it (without resetting the whole form).
For example like shown here: https://jsfiddle.net/gyrocode/yfeo529g/
We are willing to sponsor that little feature.

**Comment by fxp66** [comment]
I managed this by placing javascript into a html-field.
You may use the example snippet from fiddle or some other code
without jquery. It's quite simple

**Comment by einpraegsam** [comment]
Thx for the possible solution. No further investigations here.
