### ISSUE TITLE
"Form Overview" doesn't work for non-admins with 8.1.0

### ISSUE THREAD

**Issue by nebrot** [einpraegsam/powermail#523]
The module-function "Form Overview" throws an error after clicking on it with non-admin users. We are using TYPO3 10.4.0. There seems to be a type-casting needed or?
![powermail-error](https://user-images.githubusercontent.com/6941112/80077757-374da480-854e-11ea-8993-ef0f1b033ac9.png)

**Comment by einpraegsam** [comment]
Fixed in develop branch and ready for the upcoming release
