### ISSUE TITLE
Adding custom validators result in a TypeError

### ISSUE THREAD

**Issue by cdaecke** [einpraegsam/powermail#532]
Adding a new validator fails with the following error:

> Argument 1 passed to In2code\Powermail\Tca\AddOptionsToSelection::addOption() must be of the type string, integer given, called in...

The validator is added via TsConfig:
`tx_powermail.flexForm.validation.addFieldOptions.120 = My Validator`

The field `validation` in `tx_powermail_domain_model_field` is of type `int`, so it is not possible to add an validator with the following line:
`tx_powermail.flexForm.validation.addFieldOptions.myValidator = My Validator`

I think, this error was introduced with this commit:
https://github.com/einpraegsam/powermail/commit/a453eeffc5a7c5883d79a6f2c9de06b268c04e6b#diff-5faafaaf041418f92db152e2b294de68

The type definition for `$value` in `protected function addOption(string $value, string $label = null): void` should be changed to `int`.
https://github.com/einpraegsam/powermail/blob/c7eeb59b9949e0bd06542e331a73baf6a7230214/Classes/Tca/AddOptionsToSelection.php#L147

After changing the above, the `$fallback` in `protected function getLabel(string $label, string $fallback): string` needs to be change to an `int` as well.
https://github.com/einpraegsam/powermail/blob/c7eeb59b9949e0bd06542e331a73baf6a7230214/Classes/Tca/AddOptionsToSelection.php#L164

**Comment by akoenig-clickstorm** [comment]
You could also just add a typecast to string for the  value in the addOptions function in AddOptionsToSelection.php to make custom validators work again:

    /**
     * Add options to FlexForm Selection
     *
     * @return void
     */
    protected function addOptions(): void
    {
        foreach ($this->getFieldOptionsFromTsConfig() as $value => $label) {
            if (StringUtility::endsWith((string)$value, '.') === false) {
                $this->addOption((string)$value, $label);
            }
        }
    }

**Comment by einpraegsam** [comment]
I just pushed a fix to develop branch. Ready for the upcoming release.
