### ISSUE TITLE
Saving Values to Third Party Table (fe_users) for luxletters

### ISSUE THREAD

**Issue by bergdani** [einpraegsam/powermail#534]
typo3 10.4.0 powermail 8.1.0:
i'm trying to write to the table fe_users and it works as long i don't check if an email is already in database with the folowing TYPOScript:

# Write only if any field is not yet filled with current value (e.g. test if an email is already in database)
                # default: always add new records (don't care about existing values)
                # update: update record if there is an existing entry (e.g. if email is already there)
                # none: no entry if field is filled (do nothing if record already exists)
			_ifUnique.email = update

            # optional: add additional where clause (only in mode "update") for search if a record still exists. You could use a plain string (see example below) or a cObject if needed
			_ifUniqueWhereClause = AND pid = 147

it comes a the folowing Error (Oops, an error occurred!):

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Return value of In2code\Powermail\Domain\Service\SaveToAnyTableService::getExistingEntry() must be of the type array, bool returned | TypeError thrown in file /home/httpd/vhosts/suiza.me/aselmaria.com/public/typo3conf/ext/powermail/Classes/Domain/Service/SaveToAnyTableService.php in line 354. Requested URL: https://www.aselmaria.com/es/boletin-informativo?tx_powermail_pi1%%5Baction%%5D=optinConfirm&tx_powermail_pi1%%5Bcontroller%%5D=Form&tx_powermail_pi1%%5Bhash%%5D=6edcf87db0db2e624c9d56e0c7c44312503f3545146a5ec750192c73419dee51&tx_powermail_pi1%%5Bmail%%5D=59&cHash=b4208770b0f2dcda8145bbefefd42ee8

Is this an error or can't use it that way?

**Comment by mmirsch** [comment]
I have the same issue and can explain it.
In line 348 the querybuilder is called:
$queryBuilder
            ->select($this->getUniqueIdentifier())
            ->from($this->getTable())
            ->where($where)
            ->setMaxResults(1)
            ->execute()
            ->fetch();
If there is no entry in database querybuilder will return false which leads to this exception.

One solution would be too drop return type in function declaration:
    protected function getExistingEntry()  {

Another might be to test the querybuilder result before returning it.

Greetings,
Manfred

**Comment by einpraegsam** [comment]
Thx for the investigation. I pushed a fix to develop branch.
