### ISSUE TITLE
[Feature] Select recipient

### ISSUE THREAD

**Issue by UNI49** [einpraegsam/powermail#537]
Hi

I've not find how to do that, so I ask for this here. Is there a possibility to have a frontend form, with a select, and the select is in fact the field to select the recipient of the mail.

Example : I want to build a form to send a message to "customer service, webmaster or legal department", I just choose that on front (send a message to…) and powermail send it to the right email address.

Is there a possibility in Powermail for doing that ?

Thanks for help.

**Comment by einpraegsam** [comment]
Please look into the documentation - see https://github.com/einpraegsam/powermail/blob/develop/Documentation/ForAdministrators/BestPractice/DynamicReceiver.md

Note: This is only a bugtracker. If you have support questions, please use the slack channel or stackoverflow
