### ISSUE TITLE
PGP encryption

### ISSUE THREAD

**Issue by bilalovic986** [einpraegsam/powermail#538]
Hello,

Does powermail support the use of PGP encryption? 
Any extension that provides such functionality or a possibility to add such functionality?

Typo3 version 8.7.32
Powermail version 7.4.0

Thanks and best regards

**Comment by einpraegsam** [comment]
No, not as far as I know.

BTW: Please use Github for Bug issues. Support questions should be asked in Slack or Stackoverflow.
