### ISSUE TITLE
InputValidator validation is not executed if value is "0"

### ISSUE THREAD

**Issue by simare** [einpraegsam/powermail#544]
The validation of the InputValidator is only executed when the value is not empty (https://github.com/einpraegsam/powermail/blob/develop/Classes/Domain/Validator/InputValidator.php#L116) but the php `empty` function regards the following  as empty:

* "" (an empty string)
* 0 (0 as an integer)
* 0.0 (0 as a float)
* "0" (0 as a string)
* NULL
* FALSE
* array() (an empty array) 

So basically when no client side checks are enabled one can skip all mandatory input validations by using one of the above values.

Steps to reproduce:
1. Disable client side and native validation
2. Create a form with one mandatory field and use validateMinNumber > 1 
3. fill the field with 0 and submit

Expected result: Form should be rejected with validation error
Actual result: No validation error

**Comment by einpraegsam** [comment]
This behaviour is expected with the current framework.
