### ISSUE TITLE
Ajax submit not working with 9.5.19

### ISSUE THREAD

**Issue by exotec** [einpraegsam/powermail#545]
After upgrading TYPO3 from 9.5.9 to 9.5.19 the ajax form submit do not work anymore with powermail 7.4.0 ?

**Comment by Patta** [comment]
@exotec I can not confirm that. Maybe a missing route enhancer?

**Comment by exotec** [comment]
Sorry, it was my mistake. Powermail with ajax works well.

**Comment by mschwemer** [comment]
Closed issue because of the last comment by the issue author.
