### ISSUE TITLE
Double-Opt-In fails when confirmed on other device

### ISSUE THREAD

**Issue by m-schmitz** [einpraegsam/powermail#553]
_Using: TYPO3 9.5.19, powermail 7.4.0 and powermail_cond 7.0.0. Issue occurs on different systems_

When I fill out a form with DOI on one device and click the confirmation link on an other device, the following error occurs: `Validation failed while trying to call In2code\Powermail\Controller\FormController->createAction()`.

At first I assumed this to be related with the spamshield "Session check", but it is disabled.

Any hint where this might be located?

Thanks in advance,
Marco

**Comment by einpraegsam** [comment]
Powermail 7.x support dropped because we want to focus on 8.x development - sorry
