### ISSUE TITLE
[BUG] Save values to a session is not working

### ISSUE THREAD

**Issue by KreativeKrise** [einpraegsam/powermail#559]
If I enable the function to [save values to a session ](https://github.com/einpraegsam/powermail/blob/master/Documentation/ForAdministrators/BestPractice/SaveSession.md), then it throws the error `Return value of In2code\Powermail\Utility\SessionUtility::getSessionValuesForPrefill() must be of the type array, string returned`.

To solve the error, there is already the pull request #541 available.

Unfortunately the session data are not saved or loaded into the form with that fix.

Tested with TYPO3 10.4.3 and powermail 8.1.1.

**Comment by einpraegsam** [comment]
1) PR is already merged
2) This feature doesn't load values into form (as far as I remember)

**Comment by KreativeKrise** [comment]
> 2. This feature doesn't load values into form (as far as I remember)

? The values are stored in the session and can be read from the session to prefill an input field. That's not working anymore, even with the PR.

**Comment by KreativeKrise** [comment]
It's written on https://github.com/einpraegsam/powermail/blob/develop/Documentation/ForAdministrators/BestPractice/SaveSession.md

> You can save values after a submit to a session. This could be helpful if a user should not fill out a form field twice. So a form could be prefilled with values that a user submitted before.

And that's not working anymore.
