### ISSUE TITLE
Powermail and PowermailCondition Error in Administration log

### ISSUE THREAD

**Issue by olivermeckel** [einpraegsam/powermail#561]
i am using 
- powermail 8.1.1 
- powermail_cond 8.0.1 
- TYPO3 10.4.4

Calling the form in frontend – which works pretty fine – throws the following error in backend admin log

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Argument 1 passed to In2code\Powermail\Domain\Model\Field::setText() must be of the type string, array given, called in /html/typo3/typo3conf/ext/powermail_cond/Classes/Controller/ConditionController.php on line 78 | TypeError thrown in file /html/typo3/typo3conf/ext/powermail/Classes/Domain/Model/Field.php in line 345. Requested URL: https://www.domain.de/contact?type=3132`

**Comment by einpraegsam** [comment]
So what about making an update to powermail_cond 8.0.3? https://packagist.org/packages/in2code/powermail_cond

**Comment by olivermeckel** [comment]
Sorry, we are not using composer for this project. In the extension repository 8.0.1 is the latest version.
The version 8.0.3 als solves the issue with multilanguage forms and conditions! Great!

Thanks for the quick response

**Comment by einpraegsam** [comment]
Ok good :)

Fyi: Not all versions are published to TER

**Comment by olivermeckel** [comment]
Sorry, but powermail_cond is still not working for translated forms?

https://github.com/einpraegsam/powermail_cond/issues/36
