### ISSUE TITLE
ConditionMatcher problem in setup.typoscript

### ISSUE THREAD

**Issue by taurec76** [einpraegsam/powermail#564]
Hello
With typo3 10 there are log messages which occurs at every call:

component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed. - {"expression":"getTSFE().type == 31311] || [getTSFE().type == 31312] || [getTSFE().type == 31319"}

I found the error in setup.typoscript in line 97.
The condition should be:
[getTSFE().type == 31311 || getTSFE().type == 31312 || getTSFE().type == 31319]

After this change the error doesn't occur any more

**Comment by einpraegsam** [comment]
That is already fixed: https://github.com/einpraegsam/powermail/blob/develop/Configuration/TypoScript/Powermail_Frontend/setup.typoscript#L97
Now a release is needed
