### ISSUE TITLE
Allow form file upload without adding suffix on file name collision

### ISSUE THREAD

**Issue by Abdull** [einpraegsam/powermail#566]
I deactivated file upload name randomization by setting `plugin.tx_powermail.settings.misc.randomizeFileName = 0` (side question: why is file name randomization on by default?).

I noticed that when there already exist Powermail file uploads with the same file name, then Powermail attaches an suffix:

* `registration.pdf`
* `registration_01.pdf`
* `registration_02.pdf`

This is confusing, especially for form users, as during the final form confirmation steps, their uploaded file suddenly has another name than what they initially provided, increasing form submission cancellations.

Files land by default in directory `public/uploads/tx_powermail`. A solution to _this_ issue could be to create a subdirectory with the submitted form's ID, then put the file with unchanged name there.

**Comment by einpraegsam** [comment]
This is the default function since a long and we will keep the settings to not lose old stuff and to keep the new filename similar to the old one.
Randomized is set by default, because uploaded files should not be downloadable when someone tries to search on your website for domain.org/uploads/tx_powermail/cv.pdf or /privatedate.pdf or so. Nevertheless the folder tx_powermail should be inaccessable per default for default websites by a .htaccess file.

**Comment by Abdull** [comment]
> This is the default function since a long and we will keep the settings to not lose old stuff and to keep the new filename similar to the old one.

Isn't that what a wizard migration step could take care of automatically?

> Randomized is set by default, because uploaded files should not be downloadable when someone tries to search on your website for domain.org/uploads/tx_powermail/cv.pdf or /privatedate.pdf or so. Nevertheless the folder tx_powermail should be inaccessable per default for default websites by a .htaccess file.

Why is the Powermail upload folder located within `public` in the first place? As much as I understand, [by default, `public/upload/*` IS publicly accessible](https://github.com/TYPO3/TYPO3.CMS/blame/fcbfb04588e6dcf162b9afc730e1a0f49c665dce/typo3/sysext/install/Resources/Private/FolderStructureTemplateFiles/root-htaccess#L310).

What would be a correct `.htaccess` configuration then?

But in general, using 32 randomized characters to hide possibly sensitive data feels like the wrong approach.

**Comment by Abdull** [comment]
Related to #427.
