### ISSUE TITLE
How to set default language to german?

### ISSUE THREAD

**Issue by fxp66** [einpraegsam/powermail#569]
I'm using Typo3 9.15 with powermail 7.4.0 and have difficulties to set up validation messages and buttons to german language.
Do you have a snippet Typoscript?

This seems to be a problem of the javascript validation, php validation shows the german mandatory messages.

thx

**Comment by einpraegsam** [comment]
There is no support for the old version of powermail. BTW: There is also no support here - this is the issue tracker. Please ask in Slack or on Stackoverflow.
