### ISSUE TITLE
Undeclared arguments passed to ViewHelper TYPO3\CMS\Fluid\ViewHelpers\FlashMessagesViewHelper: class 

### ISSUE THREAD

**Issue by Hobokens** [einpraegsam/powermail#57]
Hi,
on al local machine XAMPP with PHP 7.0.9, TYP03 8.6.1 and the newest Powermail I get the error above when calling a page with a powermail form. Please take a look at the attached file.

Regards
Hobokens
[TYPO3 Exception.pdf](https://github.com/einpraegsam/powermail/files/857938/TYPO3.Exception.pdf)

**Comment by einpraegsam** [comment]
Did you took the original HTML-Templates (and Partials) of Powermail? If not please do for testing. Did you clean the caches?

**Comment by Hobokens** [comment]
Thanks for your quick reply. I tested it again with the original HTML-Templates (and Partials) of Powermail and the error is gone.
Sorry for not getting the idea to test by myself.
