### ISSUE TITLE
TYPO3 9 condition syntax

### ISSUE THREAD

**Issue by foobar13372** [einpraegsam/powermail#575]
#338 was wrongly closed.

TYPO3 9 with strict syntax + latest compatible Powermail spams the logs.

The correct way to handle this is mentioned in https://github.com/einpraegsam/powermail/issues/338#issuecomment-568418223
Just provide both templates. Alternative way: provide a v9-exclusive Powermail version which is just the same but with replaced condition syntax.

TYPO3 9 is still LTS. LTS = **Loooong** Term **Support**.

We can't "simply upgrade to v10" yet.

**Comment by einpraegsam** [comment]
There is no further bugfix upgrade planned for the old version as long as it is not security relevant.
