### ISSUE TITLE
If you set multiple receiver email addresses, only the last one is saved in the tx_powermail_domain_model_mail record.

### ISSUE THREAD

**Issue by weber-ebusiness** [einpraegsam/powermail#577]
`In2code\Powermail\Domain\Service\Mail\SendReceiverMailPreflight->sendReceiverMail` iterates over the receiver email addresses to send one email to each address. Every time, the function call `$this->sendMailService->sendMail` sets the receiver email address on the mail object to the one of the current iteration (`SendMailService->updateMail`).

Because of that, only the last receiver address is set in the mail object after sending the emails.

I think the easiest solution would be to add another `$mail->setReceiverMail($receiverService->getReceiverEmailsString());` before `return $isSent;` in `In2code\Powermail\Domain\Service\Mail\SendReceiverMailPreflight->sendReceiverMail`.

**Comment by einpraegsam** [comment]
That is correct and should not be changed at the moment
