### ISSUE TITLE
Ajax Submit may strip content from response

### ISSUE THREAD

**Issue by marcelbusch** [einpraegsam/powermail#578]
As far as I understood the powermail javascript file, whenever a form is submitted via ajax, the response-html gets selected by `[data-powermail-form="n"]:first`. If there is markup in the template which is not inside the `<f:form>` it will be stripped from the page. My current solution is to wrap the form around everything I want to display but that's not quite how form-tags should be used, right?

**Comment by einpraegsam** [comment]
So what would be your suggestion here?

**Comment by einpraegsam** [comment]
I will close this issue for now. Can be reopened if needed.
