### ISSUE TITLE
addMandatoryAttributesForMultipleFields should use validationerror_mandatory for single checkboxes

### ISSUE THREAD

**Issue by georgringer** [einpraegsam/powermail#58]
If checkboxes are required but there is actually only one checkbox, `ValidationDataAttributeViewHelper::addMandatoryAttributesForMultipleFields` should use the error message `validationerror_mandatory` instead of `validationerror_mandatory_multi`.

**Comment by einpraegsam** [comment]
Thx Georg, I pushed a fix to develop branch. Ready for upcoming release
