### ISSUE TITLE
Marketings "no_cache"creates log warnings

### ISSUE THREAD

**Issue by Schweriner** [einpraegsam/powermail#583]
The call of the marketing page which contains no_cache = 1 creates warnings in the typo3temp log:
_Mon, 07 Sep 2020 09:08:34 +0200 [WARNING] request="ff68a9b0387c2" component="TYPO3.CMS.Frontend.Controller.TypoScriptFrontendController": $TSFE->set_no_cache() was triggered. Reason: no_cache has been set before the page was generated - safety check. Caching is disabled!_

System: TYPO3 9 LTS

The responsible line: https://github.com/einpraegsam/powermail/blob/4681fb5be22d9c57e1bbc208ec0037be1b55aa08/Configuration/TypoScript/Marketing/setup.typoscript#L46

**Comment by einpraegsam** [comment]
This is a normal setting as described here: https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/Setup/Config/Index.html#no-cache

If this is a problem, it is not related to the extension but to TYPO3 itself.
