### ISSUE TITLE
cleanUnusedUploads create Output in Cronjob

### ISSUE THREAD

**Issue by nbiwki** [einpraegsam/powermail#584]
https://github.com/einpraegsam/powermail/blob/master/Classes/Command/CleanupUnusedUploadsCommand.php#L51

Hello, i have create an "Powermail Task: cleanUnusedUploads" Task in the Scheduler and i  get a E-Mail from the cronjob every time, because its generatet an Output: 

```
Overall Files: 0
Removed Files: 0
```
It has become common that an output in a cronjob is only generated if there is an error or if you want to send an e-mail for example for statistics.

I think for this case it is not necessary to create this output.

Is it possible to optionally put this into a log file? 

Thank you.

**Comment by einpraegsam** [comment]
Thx for the feedback, but at the moment it is not planned.
Explanation: If I start a command via CLI I want to have an output if everything works as expected.
