### ISSUE TITLE
No labels in access tab (TYPO3 10.4)

### ISSUE THREAD

**Issue by marcelmarty** [einpraegsam/powermail#585]
When installing powermail 8.1.4 (latest from Github) with TYPO3 10.4.6, I have no labels in access tab.

![Screenshot 2020-09-12 014614](https://user-images.githubusercontent.com/1627210/92981368-caee2600-f499-11ea-86cd-40b15496b2c7.jpg)

**Comment by einpraegsam** [comment]
Strange, I pushed a fix to develop branch
