### ISSUE TITLE
Deleting Mails at Mail-List module is not possible

### ISSUE THREAD

**Issue by mathias-noethiger** [einpraegsam/powermail#586]
I want to delete several e-mails over powermail module and tab "Mail List". It is not possible to delete single entries nor all entries per page. Reloading the list shows just deleted items again. 

We run powermail version 8.1.1 with TYPO3 10.4.7.

**Comment by dmnkj** [comment]
We have the same Problem.
When i want to hide or delete a Mail i get in the Browser Console a Error Message "Uncaught ReferenceError: T3_THIS_LOCATION is not defined" in the Powermails "Backend.min.js" File.

We run Powermail version 8.1.2 with TYPO3 10.4.6

**Comment by einpraegsam** [comment]
I can confirm this behaviour. Same with hidding mails. It seems that $.ajax stopped working.

**Comment by einpraegsam** [comment]
I just pushed a fix to develop branch. Ready for upcoming release.
