### ISSUE TITLE
[BUG] In2code\Powermail\Tca\FormSelectorUserFunc::getPidListFromStartingPoint() must be of the type string, integer returned

### ISSUE THREAD

**Issue by bribbelbum** [einpraegsam/powermail#588]
Hi,

we use the page ts configuration "tx_powermail.flexForm.formSelection" to set id where powermail records are saved. We got the following error:
In2code\Powermail\Tca\FormSelectorUserFunc::getPidListFromStartingPoint() must be of the type string, integer returned
`/**
     * Get commaseparated list of PID under a starting Page
     *
     * @param int $startPid
     * @return string
     * @throws Exception
     */
    protected function getPidListFromStartingPoint(int $startPid = 0): string
    {
        $queryGenerator = ObjectUtility::getObjectManager()->get(QueryGenerator::class);
        return $queryGenerator->getTreeList($startPid, 10, 0, 1);
    }`
$queryGenerator->getTreeList returns an integer instead of a string which stand in the description of function getTreeList. I don't now if there more checks needed for correct functionality or only it is enough `to` switch return type to int.

We use:
TYPO3 10.4.8
powermail 8.1.4

Thanks for fixing

**Comment by einpraegsam** [comment]
Thx, I fixed it in develop branch
