### ISSUE TITLE
Composer and doctrine/dbal SQL Error

### ISSUE THREAD

**Issue by dennismetz** [einpraegsam/powermail#590]
When i'm updating my TYPO3 instance via composer and it updated "doctrine/dbal" from 2.10.4 to 2.11.0 i'm getting the following error when i'm submitting a form:

You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AND ((`tx_powermail_domain_model_field`.`marker` = ?) AND (`tx_powermail_do...' at line 1

TYPO3 Version 10.4.8
PHP Version 7.4.7 (local machine, xampp) 
PHP Version 7.2.x to 7.4.x on the DEV/Prod Server

**Comment by bh-teufels** [comment]
same Error on Typo3 9.5.21 
PHP 7.3 and PHP 7.4
Powermail 7.4.0

critical!

**Comment by kralos** [comment]
This doesn't sound related to doctrine/dbal#4295 to me

**Comment by derhansen** [comment]
See https://forge.typo3.org/issues/92376

dbal/doctrine 2.11 seem to have some breaking changes. Temporary workaround is to add `"doctrine/dbal": "^2.11"` to composer conflicts. Pretty sure TYPO3 core will include a solution soon.

**Comment by einpraegsam** [comment]
Thx for clarification @derhansen
