### ISSUE TITLE
Powermail Frontend Plugin error

### ISSUE THREAD

**Issue by webdesign-k** [einpraegsam/powermail#600]
I have an error message in the backend and don't know what to do now:

Argument 2 passed to In2code \ Powermail \ Utility \ BackendUtility :: createEditUri () must be of the type int, string given

The message comes as soon as I have integrated a Powermail frontend plugin. Display in the front end works.

Typo3 10.4.9

Powermail 8.2.0

**Comment by einpraegsam** [comment]
Fixed in develop branch. Ready for upcoming release.
