### ISSUE TITLE
PSR-14 based EventDispatcher

### ISSUE THREAD

**Issue by devtroll** [einpraegsam/powermail#602]
With TYPO10 the PSR-14 Event Dispatchers were changed. 
Is it planned to use this functionality?

[https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Feature-88770-PSR-14BasedEventDispatcher.html](url)

**Comment by einpraegsam** [comment]
Yes it is planned in general. But it is not an easy task to rewrite all signals to events because all variables must be changed to objects.
So no timeplan yet and I will close this issue for now.
