### ISSUE TITLE
Update mm-Table via dbEntry

### ISSUE THREAD

**Issue by carmah1** [einpraegsam/powermail#606]
Hello,
I have created a form with which the data is stored in a third party table with three MM relations. It all works as described without any problems.

https://docs.typo3.org/typo3cms/extensions/powermail/stable/ForAdministrators/BestPractice/SavingValuesToThirdPartyTables/Index.html

Now I have created a form for editing this data, which is read out from the database with prefill.

The update also works for the standard table, but there is a problem with the mm relations.

"exception": "exception 'Exception' with message 'Field uid in table tx_jobfair_job_discipline_mm does not exist, but it's needed for _ifUnique functionality' in \ / ... \ / ... \ / typo3conf \ / ext \ / powermail \ / Classes \ / Domain \ / Service \ /SaveToAnyTableService.php: 406 \ nStack trace: \ n # 0

There is no field uid in the mm table, there are of course only the fields uid_local and uid_foreign.

If I omit the _ifUnique parameter, a new entry is created in the mm table. With the _ifUnique parameter set to the uid_local field, the error message occurs.

Is there a way to update a mm table with dbEntry?

plugin.tx_powermail.settings.setup {
  dbEntry {
    1 {
      _enable = TEXT
      _enable.value = 1
  
      _table = TEXT
      _table.value = tx_jobfair_domain_model_job
      
      _ifUnique.uid = update
      
       uid = TEXT
      uid.field = uid
      
      ...
    }
    2 {
      _enable = TEXT
      _enable.value = 1

      _table = TEXT
      _table.value = tx_jobfair_job_discipline_mm
      
      _ifUnique.uid_local = update

      uid_local = TEXT
      uid_local.field = uid
      # uid_local.field = uid_1

      uid_foreign = TEXT
      uid_foreign.field = sport
    }
}

TYPO3: 7.6.10
Powermail: 3.4.0

Thanks in advance

**Comment by einpraegsam** [comment]
No there is no function for this

BTW: Support dropped for the very old version of powermail

**Comment by carmah1** [comment]
Wow, that was a quick answer! But that is also very bad. Does this feature exist in the current version?

_BTW: Support dropped for the very old version of powermail_
I thought so. But I have no control over which version is used. From which version is there support?

**Comment by einpraegsam** [comment]
No that feature does not exist and is not planned. You can develop something by your own with a finisher (if this stuff is existing in the old version)

Look at to see which version is still supported: https://github.com/einpraegsam/powermail
