### ISSUE TITLE
Excpetion while opening Powermail Frontend Plugin as non-admin editor

### ISSUE THREAD

**Issue by ffh-webadmin** [einpraegsam/powermail#607]
When a normal editor tries to open a powermail frontend plugin in page or list module, the following exception is thrown:

Oops, an error occurred!
Return value of In2code\Powermail\Domain\Repository\PageRepository::getPropertiesFromUid() must be of the type array, null returned

Typo3 LTS 10 and Powermail 8.2.1.

**Comment by einpraegsam** [comment]
Please update to the latest powermail version. If it still exists, please reopen.

**Comment by ffh-webadmin** [comment]
Installation was already updated to 8.2.1, which is the latest version?

**Comment by einpraegsam** [comment]
Sorry, 8.2.1 is the latest version. So no action is required here. Nevertheless I can't reproduce the issue with a default editor on my testsystem. Any specific settings?

**Comment by ffh-webadmin** [comment]
We checked all exclude fields. User has access to all the Typo3 Pages/Content and Powermail columns. 

For debugging we returned an empty array in getPropertiesFromUid(), then the form will render but with an empty list od powermail forms.

**Comment by siwa-pparzer** [comment]
Can reproduce on my system.
Some Fields have the pid -1 (upgraded from 6.2 to 10.4) and therefore the Query fails because the Backend Editor cannot access Page -1.
Why some Fields have the pid -1, i cant't tell.

**Comment by einpraegsam** [comment]
Is this the same problem as described from @ffh-webadmin?

**Comment by siwa-pparzer** [comment]
Yes, the Action `PageRepository->getPropertiesFromUid` returns null and is called because of this check in the `BackendUtility->filterPagesForAccess`:
`if (!self::isBackendAdmin()) {`
Therefore only editors get this error - not admins

**Comment by einpraegsam** [comment]
So, it feels like it is not a code-problem but more a migration problem of record elements.

**Comment by ffh-webadmin** [comment]
Just tested with a new form. There _form, _page and _field records does have a valid pid but the error persists. 

![image](https://user-images.githubusercontent.com/4989581/97142674-634a1c80-1761-11eb-8479-8b303fbf1702.png)

![image](https://user-images.githubusercontent.com/4989581/97142709-765cec80-1761-11eb-8ec9-97f6b04635bf.png)

![image](https://user-images.githubusercontent.com/4989581/97142735-88d72600-1761-11eb-8421-0181fe53c483.png)

Return value of In2code\Powermail\Domain\Repository\PageRepository::getPropertiesFromUid() must be of the type array, null returned

**Comment by siwa-pparzer** [comment]
Are this the only records in the DB?
Did you make sure, that there is not a single record of Fields/Pages/Forms with pid -1 in the DB?

**Comment by ffh-webadmin** [comment]
Ahh, ok. These are the only ones which DO NOT have -1 as they are created after the update. So I will first fix the other ones and try again

**Comment by ffh-webadmin** [comment]
Even after deleting all the -1 forms/pages/fields still the same error. 

Could it be caused also by pids which do not exist anymore in pages table?

**Comment by ffh-webadmin** [comment]
Issue solved by deleting all records with invalid pids:

DELETE FROM tx_powermail_domain_model_form WHERE pid NOT IN (SELECT uid FROM pages);
DELETE FROM tx_powermail_domain_model_page WHERE pid NOT IN (SELECT uid FROM pages);
DELETE FROM tx_powermail_domain_model_field WHERE pid NOT IN (SELECT uid FROM pages);
