### ISSUE TITLE
[BUG] FE User is not set for mail

### ISSUE THREAD

**Issue by semasimo** [einpraegsam/powermail#608]
Hello,

I am using TYPO3 LTS10 and powermail 8.2.1.

I found out that the id of the feuser is not set in the table 'tx_powermail_domain_model_mail'.

I found out it has to do with this commit 'https://github.com/einpraegsam/powermail/commit/9b37a8c63c96836a9160d2c9c439e6bc6d7b150a'

there is an instanceof check agains 'User', but at the beginning of the file the namespace is not included.
So the User is never set.

semasimo

**Comment by einpraegsam** [comment]
I can confirm this issue

**Comment by einpraegsam** [comment]
Fixed in develop branch
