### ISSUE TITLE
[BUG] IsPluginOnCurrentPageCondition not working if plugin is inserted via records

### ISSUE THREAD

**Issue by Patta** [einpraegsam/powermail#61]
Nice to see this [feature](https://github.com/einpraegsam/powermail/commit/48513aff17a6e3f3c68624e8610a7c573b43f63b) back in powermail!

But it doesn't work if the plugin is inserted via records content element.

**Comment by einpraegsam** [comment]
This is correct, 
and if the plugin was inserted via TypoScript. And also hidden, fe_user authentication and so on is not yet implemented.
It was just a quick implementation.
If you want to add a pull request, feel free.
