### ISSUE TITLE
Marketing information causes permanent flash message

### ISSUE THREAD

**Issue by nhovratov** [einpraegsam/powermail#610]
If powermail marketing is included and you visit a page with a form plugin, The flash message `No TypoScript settings given. Admin, did you already include the "Main" static template?` is shown. This happens because marketing information has no flexform and thus the settings array (settings.setup) is not flattened. The check `if (!isset($this->settings['staticTemplate']))` in FormController becomes always true.

TYPO3 Version 10.4.9 and Powermail Version 8.2.1

**Comment by einpraegsam** [comment]
I just pushed a fix into develop branch. Can somebody test please?

**Comment by nhovratov** [comment]
Looks good! The flashmessage is gone. Thank you for fixing!

**Comment by einpraegsam** [comment]
Thx for the check. I'm going to release a new version asap.
