### ISSUE TITLE
powermail error displayed TYPO3 10 no Typoscript setting found did you insert the Main template!

### ISSUE THREAD

**Issue by hocomadvies** [einpraegsam/powermail#615]
In TYPO3 10.4.9 I have the latest version form TER installed. It displays an erro powermail error displayed TYPO3 10 no Typoscript setting found did you insert the Main template Admin!  The answer is YES id did there are no other TYPOscript settings given for teh fresh installed powermail 8.2 version. I Am able to create a form. I get this on different T3 systems and different servers. 

Any idea hwo to solve this? Otherwise powermail is not usable in TYPO3 10.

**Comment by einpraegsam** [comment]
Can you please check in TypoScript Object Browser if this setting is available on the page with the failure: https://github.com/einpraegsam/powermail/blob/develop/Configuration/TypoScript/Main/setup.typoscript#L969

**Comment by einpraegsam** [comment]
Duplicated to https://github.com/einpraegsam/powermail/issues/610
