### ISSUE TITLE
Creating individual error messages for validation

### ISSUE THREAD

**Issue by uocnma** [einpraegsam/powermail#617]
Hi,
this is more a question than a bug report. I aplogize for any inconvenience!

In my powermail form I use validation via regExp for a certain scenario. I modified the error message via TS so now it contains a conrete hint how to solve the error:

plugin.tx_powermail {
    _LOCAL_LANG.default.validationerror_validation.10 = ...
    _LOCAL_LANG.de.validationerror_validation.10 = ...
}

Up to this everything is fine.  But what if I want to use validation via a different regExp in another input field ? The same validation error message would appear ?!?

a) How can I add my own labels / error message via Typoscript ?
b) How can I assign my error message to a unique field in my form ? Is this possible at all ?

Kind regards,
Nelson.

**Comment by einpraegsam** [comment]
Please note that this is only an issue board and to keep the open issues as small as possible, all support questions should asked in StackOverflow or Slack.
