### ISSUE TITLE
Option for disabling storage has no effect.

### ISSUE THREAD

**Issue by Schwuuuuup** [einpraegsam/powermail#619]
Hi,
I host a TYPO3 for many institutes of a university. The editors oftentimes have not much knowledge about the internet. Therefore to avoid conflicts with the GDPR(DSGVO) we tried to deactivate storing of powermail form data as a default and only reactivate it on special selected sub-pages.
I thought that worked, but now it doesn't ... maybe I was wrong that it worked in the past, maybe there was an update or something else.

Nevertheless I have a page, where I did both:
I set `plugin.tx_powermail.settings.setup.db.enable = 0` in the `setup` part of the template and
I set `plugin.tx_powermail.settings.db.enable = 0` in the `constants` part of the template
But to no avail, there are still new answers stored in `tx_powermail_domain_model_answer`
Is there an option that can override the settings of the constants?
- The confirmation page ist NOT activated,
- Double-Opt-In IS activated.

The data persists even after the link from the confirmation mail is used.
The data is deleted when the delete-link from the confirmation-mail is clicked.
**BUT**: The uploaded file (hashed filename) still is there (in /uploads/tx_powermail ) after that, even after
`Extbase-CommandController-Task (extbase) powermail:task:cleanunuseduploads` is run in the scheduler

What am I doing wrong how can I achieve that after the mail is confirmed, no trace of the answers/mail remains in TYPO3 and on the Webserver?

TYPO3: 9.5.22
Powemail: 7.4.0 from TER

Sorry for posting this on Slack and here, but I will not regularly online on Slack and do not want to miss an answer.

Best regards TOM

**Comment by einpraegsam** [comment]
As written before (I think on slack). When optin is anabled, at the moment powermail needs to store records (of course). A function that deletes mail records on confirmation is a missing feature at the moment.
Nevertheless it is not planned. With some garbage tasks in the scheduler everyone is able to clean old records (even if they are still not confirmed) to fit GDPR requirements.
