### ISSUE TITLE
error messages in the field partial

### ISSUE THREAD

**Issue by pixelplant** [einpraegsam/powermail#62]
Hello

This is not necessarily an issue but more of a question/request.

How would one display the error messages directly in the field's partial? In my custom template each field has 2 columns, the left one holds the label and field(input), while the right one displays the error message/s, if any are present during validation.

I do not want to display them before all the form fields (so have removed the Misc/FormError partial), but to the right side, next to each field.

I can call vh:Validation.ErrorClass to see if an error is present and update the CSS class, but how would I go about showing the actual error message?

I tried calling this in the Partials/Form/Field/Input.html for example, but no error message is displayed:
```
<f:form.validationResults for="{field.marker}">
	<f:if condition="{validationResults.flattenedErrors}">
		<f:for each="{validationResults.errors}" as="error">
			<p class="error">{error.code}: {error}</p>
		</f:for>
	</f:if>
</f:form.validationResults>
```

I'm out of ideas so far so any help is more than welcomed.

Thank you

**Comment by pixelplant** [comment]
I got it working like this, but seems stupid to have to go through ALL the error messages for every field and then display the error messages for the current field only...
```
<f:form.validationResults>
	<f:if condition="{validationResults.flattenedErrors}">
			<f:for each="{validationResults.flattenedErrors}" as="errors">
				<f:for each="{errors}" as="singleError">
					<f:if condition="{field.marker} == {singleError.code}">
						<p class="error">
							<f:translate key="validationerror_{singleError.message}">{singleError.message}</f:translate>
						</p>
					</f:if>
				</f:for>
			</f:for>
	</f:if>
</f:form.validationResults>
```

**Comment by einpraegsam** [comment]
I think the best way would be to create a simple error message viewhelper. Something like <vh:validation.getErrorMessage field="{field}" />

**Comment by einpraegsam** [comment]
Nevertheless at the moment this would be a feature request.
