### ISSUE TITLE
Use no form rendering with DB, file form instead like FLUID form or *.yaml file

### ISSUE THREAD

**Issue by olegkarun** [einpraegsam/powermail#621]
Often we use powermail as part of custom extensions. Carts, order forms, registrations, etc. Powermail is awesome with Finishers and lots of cool things. But create in DB form for that and after keep not touched are really difficult. Also the big problem with multiplying. When you need the same from with small changes that required copy big from several times in DB. Would be much better to have a form configurator in the file, just to push in git with your extension and join you live.

Ask for developers. Could we do that?
Ask for other developers we need that can we donate and support?

**Comment by einpraegsam** [comment]
Yes, a nice idea and I also thought about this issue. Nevertheless there are no plans for such a massive new feature at the moment. Sorry
