### ISSUE TITLE
Extend flexform with new properties

### ISSUE THREAD

**Issue by p380** [einpraegsam/powermail#625]
The documentation provides an example for an input field.

But I need an example with an optional field.
tx_powermail.flexForm.addField.settings \ .flexform \ .main \ .finisher {
     _sheet = main
     label = Label
     config {
         type = select
         renderType = selectSingle
...
     }
}

Regards

**Comment by einpraegsam** [comment]
This is not provided. Pls use the default way to extend FlexForm of any plugin in TYPO3 https://docs.typo3.org/p/georgringer/news/master/en-us/DeveloperManual/ExtendNews/ExtendFlexforms/Index.html
