### ISSUE TITLE
Unique Validation with Opt-in not validating correctly

### ISSUE THREAD

**Issue by SoundstormVFX** [einpraegsam/powermail#626]
Hello all!

I use Typo3 10.4.9 and Powermail 8.2.2 with Double Optin-In and UniqueValidation for the e-mail field.

Beside the problem everyone is having I also have another one which I didn't saw mentioned here:
If I do not confirm/click the opt-in link, I should be able to send another form with the same e-mail, as I didn't confirmed the first one. Unfortunatly this does not work anymore. Powermail blocks the second try because there is already an e-mail stored (but not activated!). The Validation should only validate against confirmed/activated e-mails. 

Has this behaviour changed in recent versions? This used to work in Typo3 7 (I'm updating to v10). 
Somebody has an idea/bugfix?

Thanks!

**Comment by einpraegsam** [comment]
Yes, this is true. This was introduced with https://github.com/einpraegsam/powermail/issues/509.
