### ISSUE TITLE
Sometimes the captcha field is unsolvable because the exercise is out of image

### ISSUE THREAD

**Issue by dkoether** [einpraegsam/powermail#627]
Hello,

we face the problem that from time to time the generated captcha image is unsolvable because the math exercise is partly out of the image like shown below:
![Captcha](https://user-images.githubusercontent.com/7765498/98525955-7a1c6300-2279-11eb-960f-7d428bf293fb.png)
<img width="238" alt="Captcha 2" src="https://user-images.githubusercontent.com/7765498/98527272-1b57e900-227b-11eb-920c-93d6e11cc106.png">

Even if you can conclude that the second number would be a 10 you can't keep apart numbers like 8 and 6 if they are placed to high or as seen in the second image.

I only changed the background image and font-color. No changes were made in default text size and also the default powermail settings are used. Powermail is installed with version 7.4.0 in TYPO3 9.0.22

Possibly solution:
1. Reload-Button to get a new captcha image
2. Make sure that the exercise is not unreadable

Did anyone face the same problem or can provide a solution for this?

Thanks in advance!

Update:
Added one more example and more explanation

**Comment by einpraegsam** [comment]
You can adjust the settings via TypoScript to your needs - see https://github.com/einpraegsam/powermail/blob/develop/Configuration/TypoScript/Main/setup.typoscript#L329 for details

**Comment by dkoether** [comment]
Thank you for answering but shouldn't it be working correctly by default?

**Comment by einpraegsam** [comment]
It's not so easy to fix as you may be think. To increase barrier for machines it's relevant to use different angles and space on the one hand. On the other hand it should be "solveable". But finding a good solution that fits both requirements is not that easy.
