### ISSUE TITLE
Set a fixed sender address for mail to receiver instead of spoofing?

### ISSUE THREAD

**Issue by j4k3** [einpraegsam/powermail#628]
I've been trying to get Powermail to work with an external smtp server. Over the past years, many mail servers have set up SPF as a means of spam prevention, where the receiving server asks the specified sending server for the authenticity of all received mails. If a mail is not authenicated as sent by this address, the mail is silently discarded. The server in question is one of those. The TYPO3 installation has it's own mail account with login data. 
Basically, mails must only ever be sent with this specific address.

I've set up a Powermail Form where the user enters their mail address into a specified field.
The mails to the sender are delivered as they get sent from the address set up as the default sender address in the installations configuration.
The mails to the receiver however are sent with the users address as sender and therefor discarded.

What is even the idea here? Why does Powermail spoof the address instead of just setting it as the replyto address in the mail header? If I remove the checkmark on the field that states that it contains the mail address of the user, then, the "receiver" mail is delivered, but no longer the "sender" one.
After hours of debugging I've pretty much tested all of the configuration options I could find, none of them work as described in the documentation, they all seem to get overwritten with the email address given in the form.

//plugin.tx_powermail.settings.setup.receiver.overwrite.senderEmail = noreply@REDACTED.de
//plugin.tx_powermail.settings.setup.receiver.overwrite.senderEmail.value = noreply@REDACTED.de

How can I supress this behaviour?

**Comment by j4k3** [comment]
So yesterday I've had the time to look into this issue, turns out my suspicion was right. Powermail uses the e-mail address given in the the form to spoof the sender address. I've modified the code in question to verify. 

ReceiverMailSenderPropertiesService.php

```
    /**
     * Get sender email from configuration in fields and params. If empty, take default from TypoScript
     *
     * @return string
     * @throws InvalidSlotException
     * @throws InvalidSlotReturnException
     */
    public function getSenderEmail()
    {
        TypoScriptUtility::overwriteValueFromTypoScript(
            $defaultSenderEmail,
            $this->configuration['receiver.']['default.'],
            'senderEmail'
        );

        $senderEmail = $this->mailRepository->getSenderMailFromArguments($this->mail, $defaultSenderEmail);

        $signalArguments = [&$senderEmail, $this];
        $this->signalDispatch(__CLASS__, __FUNCTION__, $signalArguments);
        return $senderEmail;
    }

```

I have been, to say the least, completely baffled to read this code. Does none of the devs realize that it's not possible to couterfeit mails and spoof someone elses sender address? Have none of the devs ever heard of SPF? Was any of this ever tested in a real world scenario? How often do you get bug reports about emails erratically dropped out of existence? Am I the first one to report this bug?

Other than the signal dispatched here, is there an easier way to set the sender adress so that it isn't overwirtten, and is there a configuration option to set the email address given in the form as the replyto-address, where it actually belongs?

**Comment by einpraegsam** [comment]
Wow, finally a dev who knows how to develop :100: 
Read the docs: https://docs.typo3.org/typo3cms/extensions/powermail/stable/Faq/Index.html#how-to-solve-spf-defiance or don't use this extension if you don't like it.
Very simple
