### ISSUE TITLE
TYPO3 command cleanup:lostfiles deletes files uploaded from powermail forms

### ISSUE THREAD

**Issue by Abdull** [einpraegsam/powermail#629]
Using
* TYPO3 9.5.23
* powermail 7.4.0

Running TYPO3 command 
`./public/typo3/sysext/core/bin/typo3 cleanup:lostfiles` will delete all files from powermail's file upload directory.

`cleanup:lostfiles` is described as follows: "Looking for files in the uploads/ folder **which does not have a reference in TYPO3 managed records**."

Can it be that powermail uploaded files don't use TYPO3 managed records concept?

**Comment by j4k3** [comment]
The life of a TYPO3 integrator. A constant "I can't be the first one to encounter this, right?". Thanks for making me aware of that.

**Comment by mschwemer** [comment]
I can confirm this behaviour. 

For the time being, you can use the option `--exclude "uploads/tx_powermail"`. Then all assets in this folder will be kept. 

I will look into it.

**Comment by mschwemer** [comment]
Another solution is to move the upload folder away from `uploads/tx_powermail`

If you use for example `plugin.tx_powermail.settings.setup.misc.file.folder = my_powermail_folder` the files remain untouched, while executing the task. 

(Don't forget to protect the folder with an `.htaccess`.)

**Comment by mschwemer** [comment]
Solution accepted via a :+1: by the user ... so I will close the issue.

**Comment by sypets** [comment]
All the suggestions above seem more like a workaround.

Is it possible to make a change in TCA or elsewhere (reference index?) so that TYPO3 understands the relations? I have not fully looked into it, but looking in the core source, there is a description how the` cleanup:lostfiles` command works:

> Assumptions:
> - a perfect integrity of the reference index table (always update the reference index table before using this tool!)
> - that all contents in the uploads folder are files attached to TCA records and exclusively managed by DataHandler through group" type fields

https://github.com/TYPO3/typo3/blob/master/typo3/sysext/lowlevel/Classes/Command/LostFilesCommand.php
