### ISSUE TITLE
List View: Uncaught TYPO3 Exception: NAMEPREP: Prohibited input U+00000026 [Typo3 8 LTS]

### ISSUE THREAD

**Issue by mfvetter** [einpraegsam/powermail#63]
On Typo3 8 LTS when I click on List View and there's a powermail plugin (Content Element) in the page I get this error:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: NAMEPREP: Prohibited input U+00000026 | InvalidArgumentException thrown in file /var/www/typo3_src-8.7.1/vendor/mso/idna-convert/src/Punycode.php in line 335.`

If I delete the powermail plugin from the page and click on List View again, the error goes away and I can then see the responses stored in the page.

Tested in several pages and the only way to have the List View working is deleting the powermail plugin from the page.

I [linked the complete exception output](https://forge.typo3.org/attachments/download/32348/TYPO3%20Exception.html) just in case. It seems to be a problem with parsing of the powermail Flexform.

I'm under a development subdomain. E.g.: dev.mydomain.com
Powermail version: 3.17.0

PS: Powermail is an excellent extension! Thanks for looking into this.

[Typo3 Exception.html](https://forge.typo3.org/attachments/download/32348/TYPO3%20Exception.html)

**Comment by einpraegsam** [comment]
I did some testing but I can't reproduce this error on my test engine. Any hints what I can do to see your exception on my system?

**Comment by mfvetter** [comment]
I noticed it only happens when I fill out the Receivers Email and/or the Sender's Email address. After I add the receiver's or sender's email address and click on the View Module, I get the exception error. It seems that the symbol @ is causing the error as the exception message says on line 16: TYPO3\CMS\Core\Utility\GeneralUtility::idnaEncode

**Comment by mfvetter** [comment]
Actually if there's a symbol @ in any field, the error occurs for me.

**Comment by einpraegsam** [comment]
I added a ticket in the core section of TYPO3: https://forge.typo3.org/issues/80969
