### ISSUE TITLE
[FEATURE] parsley step by step validation.

### ISSUE THREAD

**Issue by Megafry** [einpraegsam/powermail#631]
One of my customer needed a step by step validation:
based on the official [parsley-doc](https://parsleyjs.org/doc/examples/multisteps.html) i came up with this solution:
can this be added as a feature?

```js
$('.powermail_form fieldset').each(function(index, section) {
  $(this).attr('data-parsley-group-index',index)
  $(this).find(':input').attr('data-parsley-group', 'block-' + (index + 1));
});
function curIndex() {
  return $('.powermail_form fieldset:visible').attr('data-parsley-group-index');
}
$('body').on('click','.powermail_tab_navigation a',function(e) {
  e.preventDefault();
console.log(['->',curIndex()])
  $('.powermail_form').parsley().whenValidate({
    group: 'block-' + curIndex()
  }).done(function() {
    //return 1
  });
});
```

Megafry

**Comment by bytesinmotion** [comment]
Hi, I have a client with the same problem and tried to implement your code. It kind of works my only problem is that when the error occurs on tab 2 or 3 the validation jumps back to the first step even tough that one is completed. It doesn't stay on the tab on error but jumps back. Any idea why this is happening?

**Comment by einpraegsam** [comment]
Parsley.js is not used any more with powermail 10.
