### ISSUE TITLE
Backend Module Mail List: Uploaded images show "File does not exist" instead of preview image if upload folder is forbidden and EXT:secure_downloads used

### ISSUE THREAD

**Issue by jpmschuler** [einpraegsam/powermail#636]
Installation Details:
TYPO3 v9.5.23
EXT:powermail 7.4.1
EXT:secure_downloads 3.0.3

Szenario:
1. Have Powermail form with two file uploads
2. define a upload folder which is HTTP-forbidden and configure EXT:secure_downloads for that folder
3. make an example submit upload a image and a pdf
4. Open Powermail backend module mail view, select folder, uncollapse the example submit

Output with error:
![exampleerror](https://user-images.githubusercontent.com/12411176/101754458-0bc6fc80-3ad4-11eb-8e9b-c03aca3aedd3.png)
For PDFs and other files filename is shown, for image files links work with an secure_downloads eID link, but the preview for the images is not shown, instead an irritating label is shown.

Expected output:
![exampleworl](https://user-images.githubusercontent.com/12411176/101754468-0f5a8380-3ad4-11eb-9f7a-5dc2436a9a9d.png)

For PDFs and other files filename should be shown, for images a preview is shown.

Debugging:
Disabling EXT:secure_downloads and still having the folder HTTP-forbidden results in image previews shown (although the links now point to the file, which results in a 403 obviously.
For me it seems the the preview function used in powermail uses a specific variant of the filename and some specific tests which result in this irritating label. As PDF filenames are output without a hassle it might be a good thing to fallback to default output if preview can't be generated, instead of having this irritating label and a working link.

(Edit notes: fixed screenshots)

**Comment by einpraegsam** [comment]
Thx for the note. Nevertheless this feature is not yet planned - sorry
