### ISSUE TITLE
File Upload mandatory

### ISSUE THREAD

**Issue by plojewski** [einpraegsam/powermail#638]
Hi, I use Typo3 10.4.9 and Powermail 8.2.1. All types of fields has a Mandatory checkbox in Extended tab expect File Upload.
Could you check this please?
 
<img width="771" alt="Zrzut ekranu 2020-12-21 o 20 44 26" src="https://user-images.githubusercontent.com/7590893/102816323-22236100-43ce-11eb-828f-55ff6b7bd3e7.png">

**Comment by peerlight** [comment]
I can see it in TYPO3 10.4.18 and Powermail 8.3.x

**Comment by einpraegsam** [comment]
Mandatory is also available for uploads - no changes in the shorter past related to this feature.
If the field is not visible, check your local configuration (TSconfig or TCA).
