### ISSUE TITLE
deprecated use of ExtensionUtility::configurePlugin

### ISSUE THREAD

**Issue by SteffenKluetsch** [einpraegsam/powermail#639]
You still use the deprecated dot notation in the extension name for "VENDOR.EXT_NAME"

This changes in Typo3 11

`Error handler (BE): TYPO3 Deprecation Notice: Calling method TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin with argument $extensionName ("WE.WeCookieConsent") containing the vendor name ("WE") is deprecated and will stop working in TYPO3 11.0. in /html/production/typo3_src-10.4.10/typo3/sysext/extbase/Classes/Utility/ExtensionUtility.php line 63 `

**Comment by einpraegsam** [comment]
Powermail does not yet support Version 11
