### ISSUE TITLE
TYPO3 V10 Powermail in Lightbox

### ISSUE THREAD

**Issue by archyart** [einpraegsam/powermail#643]
Hello,
i want to use powermail in a lightbox. Is there any solution? Which lightbox is recommend?

Greetings from DE

**Comment by Patta** [comment]
@archyart you can e.q. use fancybox (jquery lightbox). The powermail form could be placed on a blank page and added to a page with the iframe media type of fancybox. But this is not a powermail related "issue". Maybe ask that type of stuff on slack.

**Comment by archyart** [comment]
Thx very much...

Greetings

**Comment by einpraegsam** [comment]
Please do not use github issues for support questions. It's hard enough to keep an overview over the open issues.
If you need help/support, you can use stackoverflow or slack.
