### ISSUE TITLE
 [WARNING] request="7c87d5277516e" bläht die Log-Datei auf.

### ISSUE THREAD

**Issue by kurtkk** [einpraegsam/powermail#645]
In der akt. Version für TYPO3 V9 stehen in 3 setup.txt noch die veralteten Conditions drin.
Die erzeigen folgenden Output im Log:

Mon, 01 Feb 2021 13:27:30 +0100 [WARNING] request="7c87d5277516e" component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed, fallback kicks in. It looks like an old condition with only one equal sign. - {"expression":"globalVar = LIT:0 < 0"}
Mon, 01 Feb 2021 13:27:30 +0100 [WARNING] request="7c87d5277516e" component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed, fallback kicks in. It looks like an old condition with only one equal sign. - {"expression":"globalVar = LIT:0 < 1"}

Ich hatte das in der vorigel Powermail-Version schon mal "korrigiert":
//[globalVar = LIT:0 < {$plugin.tx_powermail.settings.styles.bootstrap.addBootstrap}]
[{$plugin.tx_powermail.settings.styles.bootstrap.addBootstrap} > 0]
	page.includeCSS.powermailBootstrapPath = {$plugin.tx_powermail.settings.styles.bootstrap.bootstrapPath}
[end]

Aber beim Update auf die V.7.4.1 waren die 3 setup.txt wieder mit der Abfrage "[globalVar = LIT:0 < ...." versehen.

Vielleicht könntet Ihr das bei Gelegenheit auch ändern!?

Gruß aus Jülich
Kurt Kunig

**Comment by einpraegsam** [comment]
Hi Kurt,

we already focussed on the powermail 8 and older versions are not supported any more with bugfixes (only with security updates). Look at https://github.com/einpraegsam/powermail#21-versions-and-support for an overview.

Greetings from Rosenheim, Alex

**Comment by kurtkk** [comment]
Sorry, I didn't know that we have to "speak" English here!  ;-)
