### ISSUE TITLE
Documentation for powermail v8 missing form docs.typo3.org

### ISSUE THREAD

**Issue by cweiske** [einpraegsam/powermail#662]
The extension documentation on docs.typo3.org is stuck at powermail 7.3 (go to https://docs.typo3.org/Home/Extensions.html, type "powermail" and see that the last version is 7.3).

It would be nice if the documentation for powermail version 8 would be there, too.

(Maybe this is because documentation has been converted to markdown in commit 5256bb9559ff2ae9ed5f2609e0ff961b54367268?)

**Comment by einpraegsam** [comment]
Exactly, I changed RST to a much more easier way to write documenation: Markdown.
As long as docs.typo3.org don't render md, there is no way to have it there.
Link to external documentation is up to date in TER.
