### ISSUE TITLE
Outdated documentation rendered on docs server

### ISSUE THREAD

**Issue by sypets** [einpraegsam/powermail#667]
**Summary**: would recommend to either

a) convert current markdown files to .rst (you can still leave the top level Readme.md for GitHub as Markdown but GitHub supports both)
b) get old documentation removed on docs server and only use files on GitHub as documentation - ask in Slack channel `typo-documentation` and only use docs on GitHub
c) ask in Slack `#typo3-documentation` channel for advice how to handle Markdown files with menus

---

Currently, an older version is rendered: https://docs.typo3.org/typo3cms/extensions/powermail/7.3.1/Index.html

The documentation is currently not rerendered. This may be a problem that the webhook was not generated in this repo after docs server migration, see https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingDocForExtension/Webhook.html

But, I also tested this locally (with the Docker container), and there was an error on rendering. 

```
ATTENTION:

   No documentation found! No documentation rendered!

   Reason: None of the possible starting files (called 
   "masterdoc") could not be found. Please provide at
   least one of the following. They will be taken into
   account in this order of preference:

      1. Documentation/Index.rst
      2. Documentation/index.rst
      3. Documentation/Index.md
      4. Documentation/index.md
      5. README.rst
      6. README.md

```

The reason is that the startfile is named Readme.md / Documentation/Readme.md and not README.md or Documentation/Index.md https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/DirectoryFilenames.html#supported-filenames-and-formats

If Documentation/Readme.md is renamed to Documentation/README.md (or if Readme.md is renamed to README.md) it can be rendered but **I would not recommend to do this**. You will not get good results. Only what is in this file will be rendered and the links from the startpage will not work. If you work with .rst and toctree you can get better results with an automatically generated menu.

**Comment by einpraegsam** [comment]
I will go for markdown only in future because this is much easier to handle and a common thing in the PHP world.
Yes, I would also like that the old RST documentation is not rendered any more on docs.typo3.org. 
I'm wondering if you are part of the documentation team? Can you please turn this stuff off?

**Comment by sypets** [comment]
I used to be in documentation team.

It is possible to remove existing documentation. Just notify someone on Slack : #typo3-documentation channel.

One thing to consider: Sometimes old documentation may still be relevant for older extension versions. But if you want to get it removed, it's just a click of a button.

---

While the markdown may be easier to handle, .rst is the recommended format for rendering docs on docs.typo3.org. 

I realize .rst ist sometimes considered as complicated and I had some problems too at the beginning with things being rendered differently (or not rendered at all) and not immediately obvious why. 

But some of these can be easily circumvented by using good editing tools with .rst support. There is a docker container for local rendering which can also be integrated into GitHub CI.

There are also some advantages (in using reStructuredText + sphinx), such as:

* automatic menu building (currently menu is maintained manually)
* more visibility of documentation (search results on docs.typo3.org, appears in new global search - "Search in TYPO3 documentation", which is live for a couple of days now)
* syntax highlighting of code snippets
* automatic screenshot building (currently used for official docs in combination with styleguide extension, currently not available for extensions AFAIK, but may be available in future)
 
---

Sorry about long post. Don't want to bother you. Just think it's a pity if TYPO3 offers the documentation rendering and some very popular, well-known extensions do not use it. A lot of work has been done lately and there may even be new solutions for some problems you did encounter or new ways of doing things which are easier and better, which I am not aware of.

---

P.S. Symfony (PHP) uses reStructuredText and sphinx too (similar to our solution).

**Comment by einpraegsam** [comment]
In my eyes it's an easy situation: Nearly no developer wants to write documentation. So writing should as less complicated as possible. And because github, gitlab, etc... are supporting MD by default and because it's very easy to understand, I would not think of any other language. In addition I don't have to run docker images with sphinx or stuff, but just open my IDE to have a good preview.
Even if RST would be a good decision for core documentation (and I'm not totally convinced here), it is the wrong decision for TYPO3 extensions. 
Don't make developers live more complicated then it must be :)

We can have a short phone call if my intention is not clear if you want.
