### ISSUE TITLE
[QUESTION] Export of all fields misses fields with type typoscript

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [einpraegsam/powermail#671]
Hi there,

I have created a form with several normal fields and 5 typoscript fields. These typoscript libs render hidden input fields where the value attribute gets filled with values from the database. After sending the form everything is fine. The frontend report shows all fields (normal and typoscript), the email renders all fields and they are stored correctly in the database.

Now the problem: If I use the powermail: export scheduler task afterwards and leave "Argument: fieldList" empty (to export all fields), all fields except these 5 typsocript fields are exported to CSV! Now the curious thing is that they get exported if I explicitly fill "fieldList" with the UIDs of the typoscript fields (and the others). This is of course not convenient because I'd have to add the UIDs to the scheduler task whenever I extend the form.

What's wrong here? Am I missing something? There is no difference between normal and typoscript fields in the table `tx_powermail_domain_model_answer`. Might it be that fields with type "typoscript" are not exported by default? How can I force this for a special form?

Thanks in advance.

Cheers

**Comment by einpraegsam** [comment]
This is a missing feature at the moment. Only default fields are within normal exports.
At the moment we don't want to change this behaviour, but maybe in a later version.

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Okay, thanks for the fast reply! Could you maybe give me a hint where (not how) in the code I would have to make changes for a different behaviour? Only typoscript fields needed...
