### ISSUE TITLE
Issue with spamshield (even without methods) and fe session cookie

### ISSUE THREAD

**Issue by TBschen** [einpraegsam/powermail#673]
(yes I have read the documentation part about the session cookie :) )

When I submit a form, it will create a session cookie (fe_typo_user) even though I think I've disabled everything I should.
The critical part that causes it seems to be the spamshield.
Wenn I add the following to my setup (all methods disabled), it will create a cookie nonetheless:
```
plugin.tx_powermail.settings.setup.spamshield.methods.1._enable = 0
plugin.tx_powermail.settings.setup.spamshield.methods.2._enable = 0
plugin.tx_powermail.settings.setup.spamshield.methods.3._enable = 0
plugin.tx_powermail.settings.setup.spamshield.methods.4._enable = 0
plugin.tx_powermail.settings.setup.spamshield.methods.5._enable = 0
plugin.tx_powermail.settings.setup.spamshield.methods.6._enable = 0
plugin.tx_powermail.settings.setup.spamshield.methods.7._enable = 0
```

When I only write this in my setup, it won't create a cookie:
```
plugin.tx_powermail.settings.setup.spamshield._enable = 0
```

Strange, huh?
I have jquery included and it submits via AJAX. It works well otherwise.
Not much else has been configured in my TYPO3 installation.

Some more information:
```
TYPO3 10.4.15
powermail 8.3.2
```

ext Config checked:
```
basic.disableIpLog (boolean)
basic.disableMarketingInformation (boolean)
basic.disableBackendModule (boolean)
basic.disablePluginInformationMailPreview (boolean)
```

static template included:
`Main Template`

constants:
```
plugin.tx_powermail.settings.main.confirmation = 0
plugin.tx_powermail.settings.main.optin = 0
plugin.tx_powermail.settings.main.moresteps = 0
plugin.tx_powermail.settings.misc.ajaxSubmit = 1
plugin.tx_powermail.settings.db.enable = 0
```

setup:
```
plugin.tx_powermail.settings.setup.receiver.overwrite.senderEmail = TEXT
plugin.tx_powermail.settings.setup.receiver.overwrite.senderEmail.value = some@ema.il
plugin.tx_powermail.settings.setup.receiver.overwrite.senderName = TEXT
plugin.tx_powermail.settings.setup.receiver.overwrite.senderName.value = Some Name
```

**Comment by TBschen** [comment]
Ok, so I've checked the code a little

`saveSpamFactorInSession `** (Save Spam Factor in session for db storage)** in SpamShieldValidator.php is causing the creation of a session cookie.

I feel like this should only execute if db storage is wanted (I've set db.enable to 0), if it's only used for that.

**Comment by einpraegsam** [comment]
I would have to dig into it but at the moment I'm quite busy, but the last time when I checked, everything works like described in documentaion.
BTW: Db storage has nothing to do with a session check in my eyes. A session check needs a cookie to prevent spam.

**Comment by TBschen** [comment]
@einpraegsam 
No need to hurry really, I feel like I've understood the documentation correctly and that the issue is within the code (I might be wrong ofc), so closing this issue could be too soon.


class **SpamShieldValidator** includes the function **saveSpamFactorInSession()** , which is only called in function **isValid** of the same class.
So as long as spamshield is enabled, **saveSpamFactorInSession()** is executed no matter what spamshield methods are enabled:

```
    public function isValid($mail)
    {
        if ($this->isSpamShieldEnabled($mail)) {
            $this->runAllSpamMethods($mail);
            $this->calculateMailSpamFactor();
            $this->saveSpamFactorInSession(); //<-- if spamshield is enabled, it executes no matter what
            $this->saveSpamPropertiesInDevelopmentLog();
            if ($this->isSpamToleranceLimitReached()) { // <-- doesn't use spamfactor session cookie
                $this->addError('spam_details', 1580681599, ['spamfactor' => $this->getCalculatedSpamFactor(true)]);
                $this->setValidState(false);
                $this->sendSpamNotificationMail($mail);
                $this->logSpamNotification($mail);
            }
        }
        return $this->isValidState();
    }
```

However, the session cookie created by saveSpamFactorInSession() is checked (with getSpamFactorFromSession() ) in prepareMailForPersistence() (class MailFactory).
prepareMailForPersistence() is called in saveMail() (class FormController)
saveMail() is called in createAction() (same class)

createAction() includes:
```
        if ($this->isMailPersistActive($hash)) {
            $this->saveMail($mail);
            $this->signalDispatch(__CLASS__, __FUNCTION__ . 'AfterMailDbSaved', [$mail, $this]);
        }
```

isMailPersistActive() (same class) loos like this:

```
    /**
     * Decide if the mail object should be persisted or not
     *        persist if
     *            - enabled with TypoScript AND hash is not set OR
     *            - optin is enabled AND hash is not set (even if disabled in TS)
     *
     * @param string $hash
     * @return bool
     */
    protected function isMailPersistActive(string $hash = ''): bool
    {
        return ($this->isPersistActive() || !empty($this->settings['main']['optin'])) && $hash === '';
    }
```



So saveSpamFactorInSession() needs an if-statement with something like isMailPersistActive?

**Comment by cehret** [comment]
I can confirm this. Marketing disabled and also the Session Check. But as soon as you enable Spamshield a fe_user Cookie is set.

by removing
$this->saveSpamFactorInSession();

in

function isValid($mail)

in SpamShieldValidator.php no cookie is set anymore and the function is still there as far as I could see...

TYPO3 10.4.21
Powermail 8.4.1
