### ISSUE TITLE
Send email with defined values on conditions

### ISSUE THREAD

**Issue by amirmoschref** [einpraegsam/powermail#674]
I'm currently working on a form which is used to request a membership in a non-profit organization. People need to choose their subsidiary organization based on the state they live in. I'm already using the "predefined receiver" feature, so the request will find the correct subsidiary. 

Now I need another feature which allows me to send the user input to a third party based on a condition. The problem is that the email the third party is not allowed to have sensitive data like the banking information. 

Thank you very much for your help!

Best Regards 

Amir

**Comment by mschwemer** [comment]
Hi @amirmoschref 

thanks for your request. 

I consider these conditions for fields as "business logic", that is very specific and IMHO out of scope for a generic mail form extension. 

If you still need this feature, please ask us for an offer to find and develop a proper solution. 

Best regards
Marcus
