### ISSUE TITLE
BUG: broken marketingPageFunnel return

### ISSUE THREAD

**Issue by helsner** [einpraegsam/powermail#678]
https://github.com/einpraegsam/powermail/blob/5f9ec097cade6f0c967cf638c750a01284d71482/Classes/Domain/Model/Mail.php#L530

Here the json_decode does not always return an array but an object, which then causes an exception as the type does not fit anymore.
Adding true as second argument for the json_decode should solve this

**Comment by einpraegsam** [comment]
Thx, fixed in develop branch and ready for upcoming release

**Comment by helsner** [comment]
oh, you're too fast, would've added the fix, but got stopped by a meeting 😅 
thx a lot!
