### ISSUE TITLE
Remove spaces in multi seleckt checkbox mail body

### ISSUE THREAD

**Issue by RonLeh** [einpraegsam/powermail#680]
If I use a multi select checkbox there are spaces after each comma in the e-mail body.
Can I remove this spaces to get a comma separated list of values, if the user selects more than one value?

Best regards.
Ron

**Comment by einpraegsam** [comment]
I think it's hardcoded here: https://github.com/einpraegsam/powermail/blob/develop/Classes/Domain/Model/Answer.php#L105

Please don't use the issue tracker for general questions. Slack or Stackoverflow would be the better choice.

**Comment by RonLeh** [comment]
Thank you very much! Next time I'll use Stackoverflow.
Best regards
Ron
