### ISSUE TITLE
File upload to additional fal storage

### ISSUE THREAD

**Issue by deflektor-de** [einpraegsam/powermail#682]
Hi there,

I try to point the upload folder for file upload to a target other than first and default storage by setting plugin.tx_powermail.settings.misc.uploadFolder.
I thought, that "2:/testfolder" might work for file storage with uid 2, but it doesn't.

Instead there is only a folder named "2:" generated.

Any hints?

**Comment by einpraegsam** [comment]
Did you search for "fileadmin" in TypoScript and replaced all code with your new folder? 
BTW: FAL is not yet implemented. So using a FAL-driver with external source would not work at the moment.
