### ISSUE TITLE
Powermail 8.3.1 - eigene Fehlermeldung bei Mehrschrittformular

### ISSUE THREAD

**Issue by archyart** [einpraegsam/powermail#685]
Hallo,
ich benötige einen Tipp wie ich nach dem Absende Button eine allgemeine Fehlermeldung generieren kann das in dem Mehrschrittformular ein Pflichtfeld nicht ausgefüllt wurde.

FG

**Comment by einpraegsam** [comment]
Please use Slack or Stackoverview for free support questions. This place is for issues (bugs, features, etc...) only.
