### ISSUE TITLE
Huge memory consumption of mail export

### ISSUE THREAD

**Issue by Micha-sus** [einpraegsam/powermail#686]
I tried to export roughly 2000 mails from the TYPO3 Backend but the export failed due to the php memory limit. I had to increase the limit to 512Mb in order to make the export work (CSV and Excel). Could you please check if this is a bug and whether you can optimize the export code to use less memory?

TYPO3 9.5.27 (non-composer)
PHP 7.3
MySQL 5.7
Powermail 7.0.3

Kind regards,

Micha

**Comment by einpraegsam** [comment]
Yes, we know that. You could do an export via CLI instead of using the web-interface (via Apache, etc...).
Nevertheless we already dropped support for powermail 7.x
