### ISSUE TITLE
AddFinischerClass and the AddDataProcessor - can not add html tags... 

### ISSUE THREAD

**Issue by docmcfly** [einpraegsam/powermail#687]
Hello, 

I tried with the AddFinischerClass and the AddDataProcessor to modify the mail just from sending. 

I would like to parse for URLs before sending and replace them with hyperlinks.

For example: 
Input: https://www.wikipedia.de/ 

Then it should become <a href="https://www.wikipedia.de/">www.wikipedia.de/</a>. 

But when I use the AddDataProcessor and change the value in the field, the tags are in the mail. :( 

And if I use the finisher and edit the body.... nothing happens. :((

When I save the mail again.... is then reliably with this data (this body) the mail sent?

Thanks for the help... 
Clemens 

Translated with www.DeepL.com/Translator (free version)

**Comment by einpraegsam** [comment]
There is a signal called `sendTemplateEmailBeforeSend` that can be used for manipulating mail settings just before it will be sent.
