### ISSUE TITLE
Doctrine\DBAL\Exception\InvalidFieldNameException

### ISSUE THREAD

**Issue by typo3rel** [einpraegsam/powermail#688]
Hi,

Typo3 9.5 and powermail 7.4

this exception occurs when a normal user tries to display all forms in a workspace environment.
```An exception occurred while executing 'SELECT `uid`, `pid`, `t3ver_oid`, `t3ver_id`, `t3ver_wsid`, `t3ver_label`, `t3ver_state`, `t3ver_stage`, `t3ver_count`, `t3ver_tstamp`, `t3ver_move_id`, `t3_origuid`, `tstamp`, `sorting`, `deleted`, `perms_userid`, `perms_groupid`, `perms_user`, `perms_group`, `perms_everybody`, `editlock`, `crdate`, `cruser_id`, `hidden`, `title`, `doktype`, `TSconfig`, `is_siteroot`, `php_tree_stop`, ..........  FROM `tx_powermail_domain_model_page` WHERE (`pid` = ?) AND (`t3ver_oid` = ?) AND (`t3ver_wsid` = ?) AND (`tx_powermail_domain_model_page`.`deleted` = 0) LIMIT 1' with params [-1, 3, 1]: Unknown column 'perms_userid' in 'field list'```

it seems as if the statement in the In2code\Powermail\Domain\Repository\PageRepository (getPageNameFromUid & getPropertiesFromUid) is not sent raw to the database ??

i changed it to 
```
    /**
     * @param int $uid
     * @return string
     */
    public function getPageNameFromUid($uid): string
    {
//        $pageName = '';
//        $query = $this->createQuery();
//        $sql = 'select uid,title from pages where uid = ' . (int)$uid . ' limit 1';
//        $result = $query->statement($sql)->execute(true);
//        if (!empty($result[0]['title'])) {
//            $pageName = $result[0]['title'];
//        }
//        return $pageName;

	    $querybuilder = DatabaseUtility::getQueryBuilderForTable('pages', false); // false to keep workspace restrictions?
	    return $querybuilder
		    ->select('title')
		    ->from('pages')
		    ->where('uid = ' . (int)$uid)
		    ->execute()
		    ->fetchColumn(0);
    }

    /**
     * Get properties from table "pages"
     *
     * @param int $uid
     * @return array
     */
    public function getPropertiesFromUid($uid)
    {
//        $query = $this->createQuery();
//        $sql = 'select * from pages where uid = ' . (int)$uid . ' limit 1';
//        $result = $query->statement($sql)->execute(true);
//        return $result[0];
	    $querybuilder = DatabaseUtility::getQueryBuilderForTable('pages', false); // false to keep workspace restrictions?
	    return $querybuilder
		    ->select('*')
		    ->from('pages')
		    ->where('uid = ' . (int)$uid)
		    ->execute()
		    ->fetchAll()[0];
    }
```
And it works
THX

**Comment by einpraegsam** [comment]
Thx for the note. Workspaces are not supported in powermail. I'll be sure that there are a lot more spots in the code that have to be updated.
In addition support for powermail 7 was dropped when 8 was released.

Greetings, Alex
