### ISSUE TITLE
[Feature] Duplicate and/or Copy-Button

### ISSUE THREAD

**Issue by kludikovsky** [einpraegsam/powermail#69]
Sometime when powermail is used for bigger forms, it would be advantagous to be able to copy/duplicate fields. Sometimes there are questionaires with same answer options, or input with similar spec's.

A button like the "Add new record" button on the right, e.g. "Duplicate record" would do the job.

The main advantage would be the option to edit the fields in bulk in the list view (as the associations are untouched.

**Comment by einpraegsam** [comment]
This is not planned at the moment. Feel free to bring in a pull request.
