### ISSUE TITLE
Unable to set redirect page after first submit

### ISSUE THREAD

**Issue by malbezem** [einpraegsam/powermail#697]
With the double opt-in feature enabled, I can't set any redirect after the first submit to a confirmation page. 
This has been an issue on my Website for a very long time and I couldn't solve it.

First I implemented a redirect inside **\typo3conf\ext\powermail\Resources\Private\Templates\Form\Create.html**
which looks like this:

```HTML
<f:section name="main">
	<f:alias map="{flashMessageClass:'powermail_message_error'}">
		<f:render partial="Misc/FlashMessages" arguments="{_all}" />
	</f:alias>


	<div class="{settings.styles.framework.createClasses}" data-powermail-form="{mail.form.uid}">
		<f:if condition="{optinActive}">
			<f:else>
				<vh:misc.variables mail="{mail}">
					<f:format.html parseFuncTSPath="lib.parseFunc_RTE">{powermail_rte}</f:format.html>
				</vh:misc.variables>

				<f:render partial="Misc/GoogleAdwordsConversion" />
			</f:else>
			<f:then>
				<strong>processing...</strong>
				<script type="text/javascript">
					window.location = "https://example.com/";
				</script>
			</f:then>
		</f:if>
	</div>
</f:section>
```

But this redirect doesn't work as desired, because the page would be loading first, and then the script runs afterward, which causes a small delay.
The second issue with this redirect is that the implementation is changing the files from the Powermail extension that can be easily overwritten.

Is there any possibility to do the redirect better? 
Thank you.

**Comment by einpraegsam** [comment]
Please do not use the issue tracker for your support questions, to keep the issues manageable. Slack or Stackoverflow would be a better place.

**Comment by malbezem** [comment]
This is a huge issue with Powermail you just closed. Thanks anyway
