### ISSUE TITLE
Changing checkbox in powermail-frontend - without database field - creates an error

### ISSUE THREAD

**Issue by schokomeldra** [einpraegsam/powermail#700]
We show our mails in the frontend and the admin can change the fields of the form. Now the system is moving from an old Typo3v9 to the newest 10. Powermail is Version 8.3.3

Not all fields must be filled by the user, when it is initially sent. There are normal inputs and a checkbox. When the normal inputs are empty, they create an empty field in the database. The checkbox doesn't do this, it creates no field. 

So now, when the admin tries to change the mail, an error occurs:
<img width="499" alt="2021-08-04 12_22_16-Oops, an error occurred! - Brave" src="https://user-images.githubusercontent.com/88444710/128202855-ebf1f2f6-a6c5-46ea-a53e-39891e858133.png">

In Backend:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: Return value of In2code\Powermail\Domain\Repository\AnswerRepository::findByFieldAndMail() must be an instance of In2code\Powermail\Domain\Model\Answer, null returned \| TypeError thrown in file /ext/powermail/Classes/Domain/Repository/AnswerRepository.php in line 36. 

The function needs a field in the database, otherwise this error shows up. However, in our Typo3v9 there is no error message. 
When we remove the ": Answer" from the function, the error doesn't occur and the field for the checkbox is added in the database as before in 9. 
The problem is (in 9 and 10): The answer field for the checkbox is not created on the same page as the mail, but on the root page 0. That is also not optimal :( 

We need this option:
send empty checkbox -> change the empty checkbox to a checked one

Is there a possibility to make this working? Like it works for normal input fields :)

**Comment by einpraegsam** [comment]
There are no plans to create empty values anywhere sorry. 
Nevertheless we can have a look to fix the exception that is shown if the would help you.

**Comment by einpraegsam** [comment]
Please tell me step by step how to reproduce the error.

**Comment by schokomeldra** [comment]
1. create a form with text input fields and a checkbox (with more than one option)
2. fill the form, but not the checkbox, and send it (when you look in the database, the inputs make an empty field, the checkbox not)
3. now look at the email with powermail-frontend and create a frontend-user which can edit the mail
4. try to change the input of the empty checkbox with this frontend user -> error occurs

when you fill the checkbox in the second step, you can change it in the fourth step
