### ISSUE TITLE
powermail success but missing mail

### ISSUE THREAD

**Issue by xbouillet** [einpraegsam/powermail#701]
Hey, We have a strange problem with powermail, some emails (4 out of 95) are not sent on the server (the email is missing from the maillog file) despite the fact that the process has been completed (insertion in database).
Has anyone ever encountered this problem?

TYPO3: 9.5.23
POWERMAIL : 7.3.0
Thanks in advance.

**Comment by einpraegsam** [comment]
Please check email settings especially SPF-defiance with sender email: https://github.com/einpraegsam/powermail/tree/develop/Documentation/FAQ#how-to-solve-spf-defiance
I would ask the hoster or serverteam what mails are dropped and why.
