### ISSUE TITLE
Removal of wrapper div in export files are not working anymore

### ISSUE THREAD

**Issue by Patta** [einpraegsam/powermail#706]
The code in this condition is not working anymore (since fluid_styled_content ?):

```
file: Configuration/TypoScript/Powermail_Frontend/setup.typoscript

[getTSFE().type == 31311 || getTSFE().type == 31312 || getTSFE().type == 31319]
# we don't want the wrapper div in our export files
tt_content.stdWrap.innerWrap >
[end]
```

A overwrite of the default content element layout is in my opinion the fastest way to get rid of the content element wrapper div in the export files.

**Comment by einpraegsam** [comment]
Please don't use github for support questions but Slack or Stackoverview. Otherwise the issues are flooded with such stuff :)

**Comment by Patta** [comment]
@einpraegsam this is not a support question. I found a not working configuration. I created a PR with a fix for this issue. See #707
