### ISSUE TITLE
[FEATURE] Add possibility to choose the value of an autocomplete attribute

### ISSUE THREAD

**Issue by phil64** [einpraegsam/powermail#708]
Hi,

As an important improvement for accessibility (see https://www.w3.org/TR/WCAG21/#identify-input-purpose), it would be great to add this feature in the backend input form for a field, either with a free entry field or with a list of choices (see https://developer.mozilla.org/fr/docs/Web/HTML/Attributes/autocomplete), and then add automaticaly this attribute in the rendering of the field.

Best regards,

**Comment by einpraegsam** [comment]
This is not yet planned and to keep the number of open tickets small, I'm going to close this issue for now. Thx anyways
