### ISSUE TITLE
links in the email RTE are not processed anymore

### ISSUE THREAD

**Issue by xerc** [einpraegsam/powermail#709]
ref. https://typo3.org/article/typo3-10420-9530-and-1133-maintenance-releases-published
reg. [settings.flexform.receiver.body],[settings.flexform.sender.body]
expl. `href="t3://file?uid=1"`

**Comment by chrisprog20** [comment]
I think you want to say that the output is "href="t3://file?uid=1", right?
try to do the following,: 
`{settings.flexform.receiver.body -> f:format.html()} `and {`settings.flexform.sender.body -> f:format.html()}`.
That should render the url in the href attribute as required.
See also: [https://github.com/TYPO3/html-sanitizer/issues/23](https://github.com/TYPO3/html-sanitizer/issues/23)

**Comment by mschwemer** [comment]
@chrisprog20 Thanks for your solution.
