### ISSUE TITLE
BE: fieldname seem not to be set

### ISSUE THREAD

**Issue by kludikovsky** [einpraegsam/powermail#71]
The Fieldname seem not to be set when the standard is used.

![image](https://cloud.githubusercontent.com/assets/6077916/25661981/0bf12f70-3013-11e7-9a1e-8872b6d52df2.png)

**Comment by einpraegsam** [comment]
Do you mean, that the markername is not set? If so, please write me some more information (T3 version, powermail version, how to reproduce, which language).

**Comment by kludikovsky** [comment]
Sry,
The markername is not listed in the backend, It's shown as `0` as in the image above.
Versions:
T3: 7.6.18 and 
powermail:  3.17
BE language is english

Reproduce:
`List module` -> `Fields`-> `Set Fields` -> `	
Individual Fieldname to use as Variable (automaticly wrapped with {}) [auto_marker]`
`
It's just a minor issue, unless somebody needs this for further processing.

Let me know if I can be of further help.

**Comment by einpraegsam** [comment]
ok, english is an additional language or the default language?

**Comment by kludikovsky** [comment]
Again sry. Its the default english. I haven't seen an english in the languages

**Comment by einpraegsam** [comment]
I added a new field in TYPO3 7.6 in default language. When I save the form, the maker is set correct - see 
<img src="https://box.everhelper.me/attachment/897109/84725fb7-0b3e-4c40-b52e-29d7620777bb/262407-IdtTyfyWhgbCOQAT/screen.png" />
Do I misunderstand the problem?

**Comment by kludikovsky** [comment]
Ok, I'm maybe not clear enough.
In the listing view the `Individual Fieldname to use as Variable (automaticly wrapped with {})` lists all `0`

![_screen_shot_2017-05-04_082210b](https://cloud.githubusercontent.com/assets/6077916/25692539/b4b29794-30a3-11e7-850c-477eee5980de.jpg)


instead of the set name.

![_screen_shot_2017-05-04_082225b](https://cloud.githubusercontent.com/assets/6077916/25692522/8cae22b8-30a3-11e7-84ff-37ecefcf8718.jpg)

Most probably it's just a little typo in the variable name in the listing part.

**Comment by einpraegsam** [comment]
No, it's correct that this field is empty. The field is just a placeholder in TCA for tx_powermail_domain_model_field.marker and can be ignored.
