### ISSUE TITLE
Feature request: Make it possible to set storage time frame for powermail answers per form (privacy)

### ISSUE THREAD

**Issue by sypets** [einpraegsam/powermail#711]
Currently, it is possible to setup scheduler tasks to regularly deleted old mails (tx_powermail_domain_model_answer and tx_powermail_domain_model_mail). You can delete anything older than x days, as described on the scheduler page: https://github.com/einpraegsam/powermail/edit/develop/Documentation/ForAdministrators/SchedulerTasks.md

However, due to GDPR it is required to delete personal data as soon as this data is no longer required, see also #710.

This is difficult to do if you have several forms. You can

* not store the answers at all (which is possible and is described on the "[privacy](https://github.com/einpraegsam/powermail/blob/develop/Documentation/ForAdministrators/Privacy.md)" page).
* delete the mails after a certain period. But what should the period be? This is a one size fits all solution. 

I think if editors must define how long the answers are stored when the form is created (or changed), there will more control to manage the deletion of old answers.

There could be a maximum value so it will not be possible to set unreasonable time lengths.

**Comment by einpraegsam** [comment]
Thx, but this feature is not planned at the moment
