### ISSUE TITLE
The ex_tables.sql file is missing a comma on version 3.3.0

### ISSUE THREAD

**Issue by joniroutypo3** [einpraegsam/powermail#712]
CREATE TABLE tx_powermail_domain_model_answer (
...
...
KEY starttime (starttime),
KEY endtime (endtime) **HERE**
KEY t3ver_oid (t3ver_oid,t3ver_wsid),

**Comment by joniroutypo3** [comment]
I know this is an old version but it could be usefull in case of old site upgrade : https://github.com/joniroutypo3/powermail/commit/63a4c5cb85daf8b01c709cabd621a07705043462#commitcomment-56329978

**Comment by mschwemer** [comment]
Hi,

thanks for your report. Indeed the comma is missing. But this was fixed in the next version 3.4.0. If you update to a later 3.x version prior to the upgrade, your upgrade would run fine. 

3.4.0 does not have any breaking changes (AFAIK), so an update should be OK.

Best regards
Marcus

**Comment by joniroutypo3** [comment]
Hi,
ok, thank you Marcus

Best regards
Jonathan
