### ISSUE TITLE
[QUESTION] Using Powermail as survey/poll solution

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [einpraegsam/powermail#713]
Hi there,

we need a survey/poll solution. As we already use Powermail for mails, we think of using it also for surveys, because of its great possibilities and because the available survey-extensions don't provide all of our requirements, which are:

1. At least TYPO3 10, better 11 ready
2. FE-User will be saved
3. Mandatory fields on/off
4. **Prevent multiple voting for the same survey via cookies OR fe-user (both is needed) on/off**
5. Evaluation/Charts in backend (possible with an own solution if not available)

Powermail has it all, but I'm not sure about 4). I saw some TS setting possibilities like session checks but I'm not sure if that can be used.

Question: How can I (optionally!) prevent multiple form-submits with powermail? Ideally adjustable in backend, so editors can decide on their own for each form. It is important to have two options for the check: via cookies or fe-user because of different Typo-Environments.

Thanks and Cheers

TYPO3 10.4.20
Powermail 8.4.1

**Comment by einpraegsam** [comment]
Please use slack or stackoverflow for questions, otherwise we cannot track open bugs any more.

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Ok, done.
