### ISSUE TITLE
TYPO3 V11 Comptibility

### ISSUE THREAD

**Issue by mschwemer** [einpraegsam/powermail#717]
Goal is to create a TYPO3 V11 compatible version. 

There is already a branch to work on.

This issue is there to collect all existing issues / problems  ...

**Comment by mschwemer** [comment]
## Development environment

The current composer based selenium test are not working due to filing composer dependencies. 

At least one package breaks the installation. There ist already a ticket for that since January 2020

https://github.com/minkphp/MinkGoutteDriver/pull/80

**Comment by Physikbuddha** [comment]
I created PR #714 two weeks ago, which at least allows me to run a fairly simple Powermail form with double opt-in on TYPO3 v11 and PHP 8.0

**Comment by sbusemann** [comment]
in2code will release an Early Access Version of Powermail soon for Sponsors. You can get a sponsor here: https://www.in2code.de/en/agency/typo3-extensions/#c3643

**Comment by mhirdes** [comment]
@sbusemann When? How much does we have to pay? On the one hand I can understand why you would like to get paid for your efforts. On the other hand there are so much free extensions which you maybe also use for free. On top Early Access is also a little bit funny. We can not update our projects until powermail is ready for v11.  Until now powermail was well supported and always up to date. If this is not the case anymore, we may have to look for alternatives. That would be sad.

If you need help, there are a lot of developers who can help, me included.

**Comment by sbusemann** [comment]
@mhirdes I tried to explain some reasons here: https://www.in2code.de/en/recent/typo3-extension-development-not-a-sustainable-business-model

We want to find a balanced way to provide free open source extensions, but also try to cover our costs. Introducing an Early Access for sponsors is our current approach. You can choose any amount, but at least you consider 100 € net as a minimum, to cover all overhead.

**Comment by sbusemann** [comment]
@mhirdes and besides, we have also the hen egg problem, as we rely on components which are not ready or compatible (f.e. https://github.com/minkphp/MinkGoutteDriver - which blocks Behat testing, ...)

**Comment by sypets** [comment]
@mhirdes I am just also a user of third party extensions, so not authorized to reply. But would just like to give my perspective: I think it is reasonable that some ask for funding and make early versions available.

You also have other examples, e.g. typo3-solr. They also provide(d) early access versions.

Developing an extension like this - even managing issues and maintaining is a lot of work.

If more people funded extensions, it would not be necessary, but many people use extensions, and few fund them. (And yes, I would also like to have everything open source and be able to contribute. But we are talking about an early access version here, if I understand correctly).

Apart from that: Support more open source projects

**Comment by sbusemann** [comment]
@mhirdes The Beta version of Powermail 9 for TYPO3 11 is finished. We are working on some last smaller bugs and will have the EAP Release this week.

**Comment by mhirdes** [comment]
Thanks for your replies. IMO an early access would be ok, if TYPO3 v11 would not have been released already a month ago. Now the EA is the only way to get it. That was my point. I also have some extensions released in TER and understand you.

**Comment by sbusemann** [comment]
@mhirdes you can take a look at https://www.in2code.de/en/recent/extension-support-fuer-typo3-version-11 - released in June

**Comment by SimonWpt** [comment]
It would be nice, if you announce an approximate release date for the normale 11-version (not the EAV).

**Comment by sbusemann** [comment]
Q1 - 2022

**Comment by SimonWpt** [comment]
Thank you for the fast info.

**Comment by balasch** [comment]
Will you keep the release date Q1/22 or are there still problems?

**Comment by einpraegsam** [comment]
Free version release is planned for the current week for TYPO3 11

**Comment by mschwemer** [comment]
Release 9.0, which is compatible with TYPO3 V11 is officially released.  :tada:
