### ISSUE TITLE
SQL error on backend module using workspaces

### ISSUE THREAD

**Issue by CIMEOS** [einpraegsam/powermail#720]
Hi team,
We're experiencing an issue on the Powermail backend module when a non-admin user is trying to access the "Form overview" action from a workspace.
Here's the SQL exception:
``
An exception occurred while executing 'SELECT `uid`, `pid`, `tstamp`, `crdate`, `cruser_id`, `deleted`, `hidden`, `starttime`, `endtime`, `fe_group`, `sorting`, `rowDescription`, `editlock`, `sys_language_uid`, `l10n_parent`, `l10n_source`, `l10n_state`, `t3_origuid`, `l10n_diffsource`, `t3ver_oid`, `t3ver_wsid`, `t3ver_state`, `t3ver_stage`, `t3ver_count`, `t3ver_tstamp`, `t3ver_move_id`, `perms_userid`, `perms_groupid`, `perms_user`, `perms_group`, `perms_everybody`, `title`, `slug`, `doktype`, `TSconfig`, `is_siteroot`, `php_tree_stop`, `url`, `shortcut`, `shortcut_mode`, `subtitle`, `layout`, `target`, `media`, `lastUpdated`, `keywords`, `cache_timeout`, `cache_tags`, `newUntil`, `description`, `no_search`, `SYS_LASTCHANGED`, `abstract`, `module`, `extendToSubpages`, `author`, `author_email`, `nav_title`, `nav_hide`, `content_from_pid`, `mount_pid`, `mount_pid_ol`, `l18n_cfg`, `fe_login_mode`, `backend_layout`, `backend_layout_next_level`, `tsconfig_includes`, `legacy_overlay_uid`, `tx_impexp_origuid`, `seo_title`, `no_index`, `no_follow`, `og_title`, `og_description`, `og_image`, `twitter_title`, `twitter_description`, `twitter_image`, `canonical_link`, `categories`,  `tsedit` FROM `tx_powermail_domain_model_page` WHERE (`t3ver_oid` = ?) AND (`t3ver_wsid` = ?) AND (`tx_powermail_domain_model_page`.`deleted` = 0) LIMIT 1' with params [322, 1]: Unknown column 'fe_group' in 'field list'
``

The above SQL query is trying to retrieve all fields from the TYPO3 pages table columns from the tx_powermail_domain_model page table which does not make any sense.
This issue does not occur when an admin user is trying to access this action within a workspace. It seems to be an access-level-related issue. However, even with a full granted non-admin user, the exception still occurs.

We figured out a workaround by editing the getPropertiesFromUid action from PageRepository by doing so:
``` PHP
/**
 * @param int $uid
 * @return array
 */
public function getPropertiesFromUid(int $uid): array
{
    $result = \TYPO3\CMS\Backend\Utility\BackendUtility::getRecordWSOL('pages', $uid);
    return $result;
}
```

Does anyone have any idea about what could trigger such an exception?

Step to reproduce:

1.  Activate Workspace on your TYPO3 instance;
2. Create a non-admin backend user with access to Powermail extension and forms;
3. Add a new Workspace with the newly created user in;
4. Log with the non-admin account and switch to the new Workspace;
5. Use the Mail backend module on a page and try to access the "Form overview" action;

Instance information:
TYPO3 version 10.4.21 & 10.4.18
Powermail 8.3.2 and 8.1.2

**Comment by einpraegsam** [comment]
Workspaces are not supported in powermail since ever - sorry
