### ISSUE TITLE
can't change powermail form inside plugin in a none-live workspace

### ISSUE THREAD

**Issue by medarob** [einpraegsam/powermail#723]
An editor wanted to edit and change a powermail plugin in the workspace but the form list is empty. There is no form available.

![grafik](https://user-images.githubusercontent.com/33951787/141189104-68df86cc-8691-4adc-96e0-0530996594f5.png)

The same editors sees the complete powermail form list in the Live Workspace. Switching to another workspace leads to this error.
Admins see the complete powermail form list in Live Workspace AND other Workspaces.

I tested this with a non-admin dummy user who has all access rights (in case I missed something) but it's the same error.
Should this work and is there a configuration missing or is this a powermail or TYPO3 bug?

TYPO3 10.4.21, powermail 8.4.1

**Comment by einpraegsam** [comment]
Workspaces is not supported in no powermail version.
