### ISSUE TITLE
Scheduler export: sender name is hardcoded

### ISSUE THREAD

**Issue by tkasper** [einpraegsam/powermail#724]
Hey, 

if I get it correctly, then the email sender in the export command is not configurable. The name „Sender“ is hardcoded in the ExportService:getSenderEmails().
What do you think if we either add support for Thomas Kasper <tk@becklyn.com> or we add another field for the names? 

Please give me a short feedback about that. 

Thx & cheers
Thomas

**Comment by einpraegsam** [comment]
Yes, that's true and at the moment we do not plan to change this - sorry
