### ISSUE TITLE
How to receive flesh message from `ext:powermail`?

### ISSUE THREAD

**Issue by typo3ua** [einpraegsam/powermail#725]
Can anyone help me...? I use ... `{f:flashMessages(queueIdentifier:'extbase.flashmessages.tx_powermail_pi1')}` for receive flesh message from `ext:powermail` but I get nothing... what is wrong I did..?

**Comment by einpraegsam** [comment]
Please don't use github issues for support questions but Slack or Stackoverflow.

**Comment by typo3ua** [comment]
Sorry! I did it on Slack
