### ISSUE TITLE
Set Email address at Receiver Mail Reply Mail

### ISSUE THREAD

**Issue by nitsan-technologies** [einpraegsam/powermail#727]
Hi team,

We have one query related Mail configuration. My typo3 Version is 10.4.17 and Powermail version is 8.3.2 .

**Query**: _Set Contact Form_ User mail address at   `Receiver Mail Reply Mail`  Constant. Our requirement is Set User email address at reply-to in mail popup see here: http://i.imgur.com/CjkbuxA.png  Right Now, I have set here one email http://i.imgur.com/mfiJCx6.png and I got this email in reply-to field. But I Want to add Sender mail address at reply to input.

Can you please help us?
 
Waiting for your response..
 
Thanks!
Nitsan

**Comment by einpraegsam** [comment]
Please don't use github for support questions but Slack or Stackoverflow.
