### ISSUE TITLE
Power mail form fields are not showing in the forms after upgrading to typo310

### ISSUE THREAD

**Issue by shilpajh** [einpraegsam/powermail#728]
Hi ..
while upgrading to typo310 , powermail  forms are listings under form list but no fields are there. Do i need to create fields again ?
Can anybody help me please

**Comment by twestner** [comment]
If I remember correctly, there is an update script for this... But these two queries will do the job, too:

`UPDATE `tx_powermail_domain_model_page` set form = forms;`

`UPDATE `tx_powermail_domain_model_field` set page = pages;`

**Comment by shilpajh** [comment]
Thanks a lot. it works for me
