### ISSUE TITLE
Documentation: word outputted is wrong

### ISSUE THREAD

**Issue by DavidBruchmann** [einpraegsam/powermail#729]
The word outputted doesn't exist as 'put' is irregular and has the three timeforms put put, put, which are all the same.  

![image](https://user-images.githubusercontent.com/999146/144768514-1aa49915-57a5-4ded-a170-79ef4a53633d.png)

I discovered 'outputted' on the page [ForDevelopers/AddNewFieldProperties.md](https://github.com/einpraegsam/powermail/blob/develop/Documentation/ForDevelopers/AddNewFieldProperties.md) and it shoud be changed to 'output' or 'put out'. Alternatively another word could be chosen instead.  
In that context the sentence could be 'If there is text stored, this should be available before the Input field is rendered.'

**Comment by einpraegsam** [comment]
Thx for the short english lesson 😀️
But what about a pull request to update the documentation. That would be a nice Open Source reaction.

**Comment by DavidBruchmann** [comment]
I wasn't sure about the best sentence, which one you'd prefer?

**Comment by einpraegsam** [comment]
Pick the one that you want - I'm not an english expert
