### ISSUE TITLE
Lib.test and userfuncs in Edit-mode (_pi2)

### ISSUE THREAD

**Issue by bendoo** [einpraegsam/powermail#731]
Hello,
I have used ts-objects in PM-forms (either calling a userfunc or ts). However, is it right that these features are not available when in "edit-mode" (_pi2), only in (_pi1)? Also got the impression that this also counts for JS-validation of fields: if I set a field to "numeric" it only validates correctly with (_pi1) and not when editing after having saved the form.
Am I missing something, is this a bug or a missing feature?

Thanks!

**Comment by einpraegsam** [comment]
Yes, that is correct.
