### ISSUE TITLE
CSV / EXCEL Export not working with UID

### ISSUE THREAD

**Issue by ohm-meter** [einpraegsam/powermail#732]
Hi,

If i want to export a CSV or XLS with the UID of the entry i got this error:

`Argument 1 passed to In2code\Powermail\Utility\CsvUtility::sanitizeCell() must be of the type string, int given, called in /public/typo3conf/ext/powermail/Classes/ViewHelpers/String/SanitizeCsvCellViewHelper.php on line 21`

I found the Problem in the Templates:
https://github.com/einpraegsam/powermail/blob/f0ba8a8eab0d62c6393925122e82def1024020b8/Resources/Private/Templates/Module/ExportCsv.html#L82
and
https://github.com/einpraegsam/powermail/blob/f0ba8a8eab0d62c6393925122e82def1024020b8/Resources/Private/Templates/Module/ExportXls.html#L84

The Problem is that the UID is from type Integer and that will raise an error.  I found this Note at the csvValues Function
https://typo3.org/security/advisory/typo3-psa-2021-002
As quick hack i changed the Fluid template like this:

`<f:variable name="maildata"><vh:misc.variableInVariable obj="{mail}" prop="{fieldUid}" /></f:variable>
    <f:if condition="{vh:condition.isNumber(val:maildata)}">
    <f:then>
        {maildata}
    </f:then>
    <f:else>
        <vh:string.sanitizeCsvCell>{maildata}</vh:string.sanitizeCsvCell>
    </f:else>
</f:if>`

Instance information:
TYPO3 version 10.4.21 
Powermail 8.4.1

Cheers

**Comment by peterkraume** [comment]
I experienced a different but similar issue:

```
Uncaught TYPO3 Exception: Argument 1 passed to In2code\Powermail\Utility\CsvUtility::sanitizeCell() must be of the type string, bool given, called in typo3conf/ext/powermail/Classes/ViewHelpers/String/SanitizeCsvCellViewHelper.php on line 22 | TypeError thrown in file typo3conf/ext/powermail/Classes/Utility/CsvUtility.php in line 20.
```

The patch from @jpmschuler didn't work out for me. I solved the problem now  by casting the cell value to string before passing it to `CsvUtility::sanitizeCell()`.
