### ISSUE TITLE
Error sending mail is invisible to user with page redirect

### ISSUE THREAD

**Issue by christophlehmann** [einpraegsam/powermail#733]
Hey Alex,

i had a problem in sending a receiver mail. The error was on our site, but a question came up to me.

Due to catching the exception in https://github.com/einpraegsam/powermail/blob/develop/Classes/Controller/FormController.php#L255 and a configured redirect page (powermail plugin option "redirect to page") nobody noticed it and no mail was send.

What is your intention to 'just' log the exception?

**Comment by einpraegsam** [comment]
At the moment we don't plan to add such a feature but focussing on existing bugs
