### ISSUE TITLE
Finishers in _pi2

### ISSUE THREAD

**Issue by bendoo** [einpraegsam/powermail#734]
Hello,

I am working on a project where I heavenly depend on the _pi2 (edit-module).
If am not mistaken, finishers are not available for _pi2 as these are available for _pi1.
I tried to make them available for _pi2 by this line:
plugin.tx_powermail.settings.Pi2.finishers < plugin.tx_powermail.settings.setup.finishersThis way I hoped to have the standard finishers available in _pi2 but it does not work though.
What would be the right approach to do this?
Any ideas/suggestions are highly appreciated.

**Comment by einpraegsam** [comment]
Please don't use github issues for support questions. I already saw that you've posted on slack, what's correct. Another channel would be stackoverflow.
