### ISSUE TITLE
Scheduler task clean file 

### ISSUE THREAD

**Issue by xbouillet** [einpraegsam/powermail#735]
Hello,

We have updated powermail 7.3.1 to 8.4.1 in order to update TYPO3 to V10.
The cleanuploadsfiles powermail task to clean up old files does not appear in scheduler task.

It is no longer compatible ?

Thanks

**Comment by xbouillet** [comment]
[](url
![task powermail V10](https://user-images.githubusercontent.com/46443870/148416341-16a7be37-6cff-423d-89a0-968edaf7c0bb.PNG)
![task powermail V9](https://user-images.githubusercontent.com/46443870/148416357-74c34616-04ff-4e62-964c-3706feea6af2.PNG)
)

**Comment by xbouillet** [comment]
The samed task in v10
![task powermail V10](https://user-images.githubusercontent.com/46443870/148416552-98fed92d-dcb3-42a5-a183-e5c8e03c79c9.PNG)

**Comment by einpraegsam** [comment]
Please use "Execute console commands (scheduler)" and then choose the comand that you need from powermail.
