### ISSUE TITLE
Advertisement of <vh:string.RawAndRemoveXss> is wrong in documentation

### ISSUE THREAD

**Issue by xperseguers** [einpraegsam/powermail#738]
Documentation:

https://github.com/einpraegsam/powermail/blob/develop/Documentation/ForDevelopers/WriteOwnValidators.md?plain=1#L410

Having a look at the git history to figure when this file was "touched", I came to commit e1a54429ac7e6633064d9b8287b73fc2ccc37426 where VH got renamed to `EscapeLabelsViewHelper`.

=> Please adapt documentation

**Comment by einpraegsam** [comment]
Thx, I just pushed a fix to develop branch
