### ISSUE TITLE
Undefined array key 0 with PHP 8.0.17

### ISSUE THREAD

**Issue by spiegel** [einpraegsam/powermail#747]
When I try to insert the plugin I keep getting the following error message:

(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Undefined array key 0 in /mnt/web106/a0/47/58186647/htdocs/website/2022/typo3conf/ext/powermail/Classes/Tca/ShowFormNoteEditForm.php line 221

TYPO3 11.5.7
Powermail 9.0.2
PHP 8.0.17

**Comment by spiegel** [comment]
Same error message on PHP version 8.1.4

**Comment by mschwemer** [comment]
Thanks for your report. 

Will be fixed in the next release.

**Comment by spiegel** [comment]
Sorry, but the error message continues to appear

PHP Version 8.1.4
TYPO3 11.5.7

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/1771409/165357569-e2bb5a64-78cd-4e01-b134-feeb87c48fe8.png">

**Comment by spiegel** [comment]
Same error message with PHP 8.0.17
TYPO3 11.5.7
powermail 10.1.0

**Comment by chriskrj** [comment]
Same with php 8.1.1
TYPO3 11.5.9
powermail 10.1.0
