### ISSUE TITLE
Don't save attachment

### ISSUE THREAD

**Issue by melaniemedialight** [einpraegsam/powermail#748]
Hi !

I have to make a form on a website and I have a constraint : do no save attachment in the web folder (don't save at all).
Is it possible to disable upload or remove the file juste after sending mail (such as in version 1 of powermail with upload.delete = 0) ?

I know that a task exists in scheduler but I need to remove it immediately.

Is there someone who already did this or has an idea please ?

**Comment by einpraegsam** [comment]
Please don't ask support questions in github. Pls use Slack or Stackoverflow for this. Otherwise the issue list is even more flooded with tasks for us.
