### ISSUE TITLE
RTE is gone in TYPO3 7.6 in flexforms

### ISSUE THREAD

**Issue by schi** [einpraegsam/powermail#75]
In EXT:powermail 3.18.1 in TYPO3 7.6 RTE is missing for example in settings.flexform.receiver.body.

If I revert https://github.com/einpraegsam/powermail/commit/e8c145553ddea1159dcf23a8bdb2e7450d25b9dd RTE in flexforms is available in TYPO3 7.6.

**Comment by einpraegsam** [comment]
Thx for the feedback, I will do some more tests with it.

**Comment by einpraegsam** [comment]
It seems that we can't remove the line `<defaultExtras>richtext[]:rte_transform[mode=ts_css]</defaultExtras>` for TYPO3 7.6
I tested in 7.6 and 8.7 and now all seems to work as expected.

**Comment by einpraegsam** [comment]
Will be release asap
