### ISSUE TITLE
Scroll to error in version 10

### ISSUE THREAD

**Issue by Patta** [einpraegsam/powermail#754]
Thanks for version 10. Great release!

For UX reasons it would be cool, if the "scroll to error" functionality would be implemented.
It seems that parsley did that in version < 10.
For large forms or on mobile devices, a user doesn't know if there is a form error or an empty field if the view stays on the submit button.

**Comment by einpraegsam** [comment]
Thx for the feedback. Are you interested in implementing the missing feature as PR?

**Comment by Patta** [comment]
no, at the moment i have no concrete idea about this

**Comment by einpraegsam** [comment]
Feature will be released with powermail 10.1.0
