### ISSUE TITLE
Validation on multistep forms

### ISSUE THREAD

**Issue by cdominpxp** [einpraegsam/powermail#759]
Thanks for the version 10.
We noticed something that is problematic from a user perspective that still worked in version < 10:
In multistep forms, parsley had probably taken care of "jumping" to the appropriate error when a validation error occurred. Unfortunately, this is no longer the case. Are there any plans to implement this feature again?

**Comment by einpraegsam** [comment]
Not yet, but you can support the missing feature if it's relevant for you.

**Comment by cdominpxp** [comment]
My colleague wrote a quick patch, so we can use it in a project. Maybe someone else can use it:
#763

**Comment by einpraegsam** [comment]
Thx for your time, I just pushed a different solution to develop branch :)
