### ISSUE TITLE
typoscript - changing the reuqired status of field at runtime

### ISSUE THREAD

**Issue by derBoogie** [einpraegsam/powermail#766]
In earlier versions of powermail it was possible to use
`plugin.tx_powermail_pi1.validate.uid#.required = 0`
to change the required status of a field at runtime.
With powermail version 8 it does not work anymore.
Has the syntax changed or can it be done in another way?

**Comment by einpraegsam** [comment]
I have no clue that this has worked on any time in the past. 
In addition, please don't use the issues in powermail for asking support questions. Please use Slack or Stackoverflow instead.
Thx
