### ISSUE TITLE
Feature request: Make it possible to set a "form administrator" within the form plugin flexform

### ISSUE THREAD

**Issue by sypets** [einpraegsam/powermail#768]
I would like to enable editors to define a person responsible for the form in the TYPO3 backend. Either by supplying email adress or BE user. This will the person who will get notifications if there are issues with the form or the powermail answers.

I checked and it does not look like this is currently possible.

The reason is that for data protection reasons, older form answers are being deleted on a regular basis. I would like to notify users when their answers will get deleted. Could use the` tx_powermail_domain_model_mail.receiver_mail field`, but that will usually not be the person setting up the form. Also, look at who created the form or last edited the page, but again that will not be correct in a few cases and may be quite some time ago where the BE user is no longer available.

I would prefer to not have a TypoScript setting but something within the flexform which editors can set themselves.

This might also be used for other notifications as well.

**Comment by einpraegsam** [comment]
Thx for your idea, but there are no plans to build something as you have described in powermail core. Nevertheless it's possible to extend powermail to your needs (look at the documentation in the develop section).
