### ISSUE TITLE
Backend-Module: Pagination broken

### ISSUE THREAD

**Issue by tobikummer** [einpraegsam/powermail#769]
**TYPO3 11 LTS
Powermail 9.0.x
PHP 7.4.29**

In the backend module of powermail, there is a list view of all the sent mails. If there are lot of mails, there is a pagination at the bottom. But it doesn't work...
If I copy the link of the second page and paste it into the browser address line, it works well.

<img width="1320" alt="Bildschirmfoto 2022-05-19 um 10 53 18" src="https://user-images.githubusercontent.com/19902193/169255059-6ff31e1d-55cf-4ee8-bbc1-6c897672496d.png">

Tested in several TYPO3 11 instances with powermail 9.0.x.

**Comment by LimeUwe** [comment]
+1

**Comment by georgringer** [comment]
the problem is the RequireJS module which does 
```js
		$('.powermail_list .pagination a').click(function(event) {
			event.preventDefault();
```

**Comment by einpraegsam** [comment]
Thx for noting about the issue and thx for the workarround Georg. I just pushed a fix to develop branch.
