### ISSUE TITLE
Type HTML didn't work since 3.17.0

### ISSUE THREAD

**Issue by BFallert** [einpraegsam/powermail#77]
In my pages i use sometimes fields with type "Show HTML". 
Since Powermail 3.17.0 they didn't work anymore, they work only as text.

**For example:**
I like to have a headline, so i insert
`<h4>TEST</h4>` 
but i didn't get a Headline, i get instead 
`&lt;h4&gt;TEST&lt;/h4&gt;`

I use Typo3 7.6.16 or 7.6.18
I test Powermail in Version 

- 3.17.0
- 3.18.0
- 3.18.1
- 3.18.2

live example: [http://www-test.bib.uni-mannheim.de/anschaffungsvorschlag/](url)

**Comment by einpraegsam** [comment]
As written some times before, there was a small breaking change to be more on the secure site not using GeneralUtility:removeXSS() any more by default.
See the notes in https://github.com/einpraegsam/powermail/commit/1c5af7effa19031c45e28912dfe4872ed6e7283a 
Adding `plugin.tx_powermail.settings.misc.htmlForHtmlFields = 1` to the constants should fix the issue.
Sorry for the breaking change.

**Comment by BFallert** [comment]
It would be a good idea to document this in the changelog :-)
Finding information in Slack is the horror ;-)
Thanks for your answer! it works!

**Comment by BFallert** [comment]
It would be a good idea to document this in the changelog :-)
Finding information in Slack is the horror ;-)
Thanks for your answer! it works!
