### ISSUE TITLE
TS overwrite not working anymore

### ISSUE THREAD

**Issue by derghostface** [einpraegsam/powermail#772]
Since v10.2.0 the TS settings with overwrite are not working anymore, i.e. "plugin.tx_powermail.settings.setup.sender.overwrite.senderEmail"

This is related to 988a1623d73e6503a4497bfe586bbf1c0d1c7a55

The correct check in SendMailService.php:510 should be:
`if (\TYPO3\CMS\Core\Utility\ArrayUtility::isValidPath($this->configuration, $type . './overwrite.')) {`

**Comment by swisschocolate** [comment]
I can confirm this fix. (TYPO3 11.5.10, Powermail 10.2.0)

**Comment by einpraegsam** [comment]
Thx for your feedback, I pushed a fix into develop branch
