### ISSUE TITLE
getContentObject() on null in Finisher

### ISSUE THREAD

**Issue by siwa-jhainz** [einpraegsam/powermail#773]
typo3conf/ext/powermail/Classes/Finisher/SendParametersFinisher.php:133
$this->configurationManager is null
therefore getContentObject() fails
it seems that configurationManager doesn't get injected

do we need this line, because contentObject is set via parent constructor?

**Comment by einpraegsam** [comment]
Please give us some more information about your powermail and TYPO3 versions

**Comment by cdominpxp** [comment]
Same error here when submitting a form.
Typo3 11.5.9, powermail 10.3.0

**Comment by siwa-jhainz** [comment]
TYPO3 version: 11.5.10
Powermail: 10.3.0
