### ISSUE TITLE
Delete attached files when comming back from confirmation page ?

### ISSUE THREAD

**Issue by baden32** [einpraegsam/powermail#775]
Hello,
I created a PowerMail with a confirmation page (form is not submitted immediately). This form included files fields to upload documents.

Everything is fine if I send and confirm the form in a single process, I receive the attached file with the original name.

Unfortunately, if I want to upload a file nammed "test.pdf", submit the form and press back on the confirmation page (because one of the sent data is wrong), then upload another file nammed "sample.pdf", the initial file "test.pdf" is still present in the upload directory and it will never be deleted.

So my question: is it possible to make Powermail to remove the uploaded file(s) if I press the "back" button of the confirmation page?

Thank you in advance for your tips.
Regards
Bads.

**Comment by einpraegsam** [comment]
Please don't use github for support questions. It's very hard to keep an overview over the bunch of bugs and feature requests. If there are also support questions, the backlog is flooded.
Please ask on Slack or Stackoverview in general.

To your question: At the moment it is exactly as you described above.
