### ISSUE TITLE
Redirect to Thx-Page after submit is not working

### ISSUE THREAD

**Issue by nebrot** [einpraegsam/powermail#776]
For the most forms we use the function to redirect to a specific page after submit. This redirect doesn't work anymore, instead the page with the answers is shown.

I think the error is somewhere here, $this->contentObject->data['pi_flexform'] seems to be empty here: https://github.com/einpraegsam/powermail/blob/25536540e9e1f799a1def74f4ebd4f54b7098d51/Classes/Domain/Service/RedirectUriService.php#L95-L99

![powermail-thx-redirect](https://user-images.githubusercontent.com/6941112/172578437-3eae2d3e-21a8-45a3-adcd-1490d4530fd2.png)

Powermail 10.3.1
TYPO3 11.5.10
PHP 7.4

**Comment by einpraegsam** [comment]
Thank you for your contribution

**Comment by Konafets** [comment]
I encounter the exact same issue with Powermail 10.7.3 and TYPO3 11.5.30. Neither the Flexform setting is respected because `pi_flexform` is not in `data` nor the TS setting `plugin.tx_powermail.settings.setup.thx.redirect` is used. Finally I got it working with 

```
plugin.tx_powermail.settings.setup.thx.overwrite {
    redirect = TEXT
    redirect.value = 42
}
```
