### ISSUE TITLE
Error message Undefined array key "config" in

### ISSUE THREAD

**Issue by spiegel** [einpraegsam/powermail#778]
After submitting a form, the following error message appears

![PastedGraphic-2](https://user-images.githubusercontent.com/1771409/173040175-aba772a1-8ea9-4934-988b-0fc1f822a9ff.png)

Environment:
TYPO3 11.5.7
PHP 8.0.18

**Comment by einpraegsam** [comment]
Can you please tell me your powermail version?

**Comment by spiegel** [comment]
Sorry, I forgot to refer to. It is powermail version 10.3.2.

**Comment by einpraegsam** [comment]
I just checked in TYPO3 11.5.9 with PHP 8.0.14 in powermail 10.3.2 - there is no such error on my testmachine. I'm wondering what's the difference between our both instances.

**Comment by einpraegsam** [comment]
Strange, I tested on a different instance with docker and I could finally reproduce this issue

**Comment by einpraegsam** [comment]
Pushed a fix to develop branch, will be fixed in the upcoming release

**Comment by einpraegsam** [comment]
10.3.3 just released - thx for your time

**Comment by spiegel** [comment]
Great, now it works well!
Thx for fixing it in time.

**Comment by jacques2017** [comment]
> Great, now it works well! Thx for fixing it in time.

Many thx for fixing it.
