### ISSUE TITLE
receiver mail: no line breaks in textarea fields

### ISSUE THREAD

**Issue by blueamerican** [einpraegsam/powermail#779]
TYPO3 10.4.23
powermail 8.4.1

Plugin > Mail to receiver > settings.flexform.receiver.body

If i set concrete markers (e.g. {nachricht}) instead of {powermail_all}, the content in the mail hast no linebreaks.

{nachricht} is a form textarea field

**Comment by einpraegsam** [comment]
What about using a nl2br ViewHelper?

**Comment by blueamerican** [comment]
yes, i can use special ViewHelpers. I thought, it would be a powermail issue, according to the documentation.

Bodytext > Add some text for the mail to the receiver:

- Add {powermail_all} to get all values from the form in one table (with labels)
- Add a variable like {firstname}

**Comment by einpraegsam** [comment]
No, would be something like `{variable -> f:format.nl2br()}
