### ISSUE TITLE
Empty fields after wrong captcha

### ISSUE THREAD

**Issue by devxpoint** [einpraegsam/powermail#780]
TYPO3 9.5
powermail 7.4.3

After filling out the form with a wrong captcha solution and submit (AJAX)
I get the error above "Rechenaufgabe: Falscher Captcha-Code eingegeben - bitte probieren Sie es nochmal! "
and all fields are empty :(

What could I do to prevent this?

**Comment by einpraegsam** [comment]
Sorry, support for powermail 7 dropped long ago now
