### ISSUE TITLE
PropertyMapping: Fatal error when creating new fields

### ISSUE THREAD

**Issue by cepheiVV** [einpraegsam/powermail#781]
Powermail: 10.4
TYPO3: 11.5.2

1. Create a new form
2. Create a new Page in the form
3. Create a new Field in the page <<< error

> Cannot assign string to property In2code\Powermail\Domain\Model\Field::$senderEmail of type bool

**Comment by DavidR93** [comment]
I get the same error message when I try to create a field.

 TYPO3: 11.5.12
 Powermail: 10.4
 PHP: 8.1.0

**Comment by Nefiji** [comment]
Typo3: 11.5.12
Powermail: 10.4.0
PHP: 7.4.28

Can confirm that creating new fields is not possible. The bug prevents you from setting up Powermail and therefore renders the whole plugin unusable.

Typed property In2code\Powermail\Domain\Model\Field::$senderEmail must be bool, string used
in [...]/public/typo3/sysext/extbase/Classes/DomainObject/AbstractDomainObject.php line 116

    public function _setProperty(string $propertyName, $propertyValue)
    {
        if ($this->_hasProperty($propertyName)) {
            $this->{$propertyName} = $propertyValue; /* Line 116 */
            return true;
        }
        return false;
    }

**Comment by EvilBMP** [comment]
TYPO3 11.5.12
PHP 7.4

Can confirm this as well - after the upgrade from 10.2.0 to 10.4.0 I get

`In2code\Powermail\Domain\Model\Field::$page must be an instance of In2code\Powermail\Domain\Model\Page or null, int used`

in the backend when I want to safe a form.

**Comment by stephanreinecke** [comment]
Same here, errror when I try to create a field.

TYPO3 11.5.8
Powermail 10.4.0
PHP 8.0.16

**Comment by einpraegsam** [comment]
I just pushed a fix to develop branch. Can someone test the change and give me feedback please?

**Comment by stephanreinecke** [comment]
I just tested the change and it seems to work now. I can create new fields without any error.

Thanks for the quick fix!

**Comment by einpraegsam** [comment]
Thx @DavidR93 - I could reproduce this issue in PHP 8 and pushed another fix. 
To all: Please test again and give me feedback

**Comment by cepheiVV** [comment]
Works for me on develop branch with TYPO3 11.5.12 (ddev)

**Comment by einpraegsam** [comment]
Thx for the feedback, I just release 10.4.1 - sorry for the trouble guys
