### ISSUE TITLE
Typed property In2code\Powermail\Domain\Model\Field::$multiselect must be bool, int used

### ISSUE THREAD

**Issue by dennismetz** [einpraegsam/powermail#784]
PHP 7.4
TYPO3 11.5.12
Powermail 10.4

I use a checkbox with multiselect.
When I save I get the error message: Typed property In2code\Powermail\Domain\Model\Field::$multiselect must be bool, int used

Content of the field is approximately that:
"Here is a Text|Field was accepted"

**Comment by einpraegsam** [comment]
Duplicate to #781
