### ISSUE TITLE
Error when using a custom validator (PHP 8)

### ISSUE THREAD

**Issue by DavidR93** [einpraegsam/powermail#786]
I added my own validator to Powermail and I noticed that when I submit the form in the frontend, the following error occurs:

PHP Warning: Undefined array key "type." in /var/www/html/public/typo3conf/ext/powermail/Classes/Domain/Model/Field.php line 785

TYPO3: 11.5.12
PHP: 8.1.0
Powermail: 10.4.1

**Comment by einpraegsam** [comment]
Thx for your info - I just pushed a fix to develop branch

**Comment by DavidR93** [comment]
I have tested the fix. Works fine :)
