### ISSUE TITLE
Missing label in powermail backend module

### ISSUE THREAD

**Issue by vertexvaar** [einpraegsam/powermail#79]
The german translation for the "Reduce to one form" label is missing.

![bildschirmfoto 2017-05-12 um 13 18 21](https://cloud.githubusercontent.com/assets/5594393/25996067/95d88eaa-3715-11e7-9c42-3c2a016c955e.png)

**Comment by einpraegsam** [comment]
The localization is existing in powermail. I think that the translation is missing on the typo3 translation server (see translation.typo3.org).
```
			<trans-unit id="BackendListFilterFulltextSearchFormFilter">
				<source>Reduce to one form:</source>
				<target state="translated">Auf ein Formular begrenzen:</target>
			</trans-unit>
```
