### ISSUE TITLE
ForeignValidator::loadFile() must be of the type string, null given

### ISSUE THREAD

**Issue by linkpool** [einpraegsam/powermail#791]
Dear Powermail-Team,

Powermail: 10.4.1
PHP: 7.4
ForeignValidator.php

```
    /**
     * @param string $pathAndFile
     * @return void
     */
    protected function loadFile(string $pathAndFile): void
    {
        if (!empty($pathAndFile) && file_exists($pathAndFile)) {
            require_once($pathAndFile);
        }
    }

```

Within PHP 7.4 $pathAndFile won't access a null value, so you'll get:

`Argument 1 passed to In2code\Powermail\Domain\Validator\ForeignValidator::loadFile() 
must be of the type string, null given, called in ...typo3conf/ext/powermail/Classes/Domain/Validator/ForeignValidator.php on line 35#
`

Solution:

```
    /**
     * @param string $pathAndFile
     * @return void
     */
    protected function loadFile(string $pathAndFile = null): void
    {
        if (!empty($pathAndFile) && file_exists($pathAndFile)) {
            require_once($pathAndFile);
        }
    }
```

THX

Ralph

**Comment by einpraegsam** [comment]
Thx, I pushed a fix to develop branch
