### ISSUE TITLE
Mandatory upload field fails after returning from confirmation page

### ISSUE THREAD

**Issue by github1maxserv** [einpraegsam/powermail#796]
TYPO3: 10.4.31, Powermail: 8.4.1

A form with a mandatory upload field functions if you proceed to the confirmation page and then submit the form.

However, if you go back from the confirmation page to the form itself the selected file is listed below the upload field and the upload field itself is empty. The upload field itself is still mandatory and will produce an error if you submit the form

**Comment by einpraegsam** [comment]
Please upgrade to the latest powermail version and test again. Powermail 7 and 8 are not supported any more with regulare bugfixes.
