### ISSUE TITLE
automatic field repair does not finish

### ISSUE THREAD

**Issue by vertexvaar** [einpraegsam/powermail#80]
The Powermail backend module offers a possibility to fix localizations of forms, pages and fields.
After udpating Powermail from v2 to v3 i ran the update wizard in the extension manager and clicked all of the "solve problem" buttons, but the last one keeps showing up, even after multiple tries.

![bildschirmfoto 2017-05-12 um 13 22 43](https://cloud.githubusercontent.com/assets/5594393/25996185/40017fb8-3716-11e7-8565-65b08e5f6f99.png)

If you need a dump of the affected powermail tables you can come over.

**Comment by einpraegsam** [comment]
Thx, I removed this function completely. Reasons are documented in the commit message.
