### ISSUE TITLE
TypeError: Saving fields of type "Content Element" results in error

### ISSUE THREAD

**Issue by DavidR93** [einpraegsam/powermail#801]
If a field of type "Content Element" was created inside a form this error occurs when saving:

TypeError
Cannot assign string to property ln2code\Powermail\Domain\Model\Field::$contentElement of type int
in /var/www/html/public/typo3/sysext/extbase/Classes/DomainObject/AbstractDomainObject.php line 116
in /var/www/html/public/typo3/typo3conf/ext/powermail/Classes/Hook/CreateMarker.php line 250

TYPO3: 11.5.12
PHP: 8.1.0
Powermail: 10.4.2

**Comment by dhoffmann1979** [comment]
I have done a fix in Pull Request https://github.com/einpraegsam/powermail/pull/804

**Comment by einpraegsam** [comment]
Thx, I just merged the change
