### ISSUE TITLE
Backport PHP8.0 fixes to v9

### ISSUE THREAD

**Issue by revoltek-daniel** [einpraegsam/powermail#802]
Hello,

it looks like PHP8.0 fixes are not backported to v9 releases. But for v11 compatibility, PHP8.0 compatibility should be a must.

https://github.com/einpraegsam/powermail/blob/9.0.2/Classes/Tca/ShowFormNoteEditForm.php#L221 <- thorws an undefined index, in v10 it is fixed
https://github.com/einpraegsam/powermail/blob/10.4.2/Classes/Tca/ShowFormNoteEditForm.php#L224

any chance to get this fixed?

**Comment by einpraegsam** [comment]
No sorry, but we don't want to fix old stuff. Please use powermail v10 instead of 9.
