### ISSUE TITLE
PHP Warning: Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by dennismetz** [einpraegsam/powermail#803]
When creating a new plugin, selecting Powermail but not yet selecting a form and exiting the "Create Plugin" window, the following error is thrown:

PHP Warning: Trying to access array offset on value of type null in .../typo3conf/ext/powermail/Classes/Hook/PluginPreview.php line 159

PHP 8.1.9
TYPO3 11.5.15
Powermail: 10.4.2

**Comment by dhoffmann1979** [comment]
I fixed this issue with PR https://github.com/einpraegsam/powermail/pull/805

**Comment by einpraegsam** [comment]
Is fixed in develop branch and ready for the upcoming release
