### ISSUE TITLE
Empty fields despite definition of required fields

### ISSUE THREAD

**Issue by alexingo** [einpraegsam/powermail#807]
Hi! 
I'm using powermail 8.4.1 in typo3 10.4.30 installation with php 7.4. I received yesterday empty emails or emails with only one filled field like that "Sonstiges, Anmerkungen, Fragen | 1zqjmo'"(){}<x>:/1zqjmo;9". 
But the form includes several required fields!?
Best regards!

**Comment by einpraegsam** [comment]
I'm not sure how to help you here without any further information of the request log (e.g.).
In addition powermail 8 is not supported any more.
