### ISSUE TITLE
manipulateVariablesInPowermailAllMarker not working

### ISSUE THREAD

**Issue by Subjekt2Change** [einpraegsam/powermail#808]
The value replacements are no longer working. The original values are being displayed both in the mails and in the backend.

The bug seems to originate here: https://github.com/einpraegsam/powermail/blob/04b198d7a55c7e23418729692fcdcf4e5543c9e9/Classes/ViewHelpers/Misc/ManipulateValueWithTypoScriptViewHelper.php#L62

The variable `$this->typeToTypoScriptType` is not set in this particular class. Thus the statement resolves to false and the value is never replaced. Changing the condition to `$this->typeToTsType` like in the condition directly below fixes the bug.

**Comment by einpraegsam** [comment]
Thx for digging into this issue and also delivering the fix. I just pushed the fix to develop branch.
