### ISSUE TITLE
"Email address already confirmed" with Microsoft Office365 safe-link-feature

### ISSUE THREAD

**Issue by twestner** [einpraegsam/powermail#809]
Microsoft Office 365 has an feature called "[safelink](https://docs.microsoft.com/de-de/microsoft-365/security/office-365-security/safe-links?view=o365-worldwide)", it is enabled by default. With this features all links will be pre-checked for security issues, when the email is opened by the user. This feature has been existing for a while, but last days the problems got bigger as more and more users run into this issue:

When the doi-link is pre-checked, it is DONE. If the user clicks the link for the first time, the message "the emailaddress has been confirmed already" appears.

In best case, the user gets the wrong message and is wondering, but everything runs as expected. In worst case, there is a process after DOI via signals, which will not start at the user-click (the signal is not touched, as the mail-object is already unhidden).

We could not find a 100% fitting solution to block those requests before getting to optinConfirmAction, so we had to handle those requests. We decided to open optinConfirmAction for more than one call and check our process behind, but we are unsure, if this is the best solution for all.

(at our b2b-project 7% of all users run into this issue last days)

**Comment by einpraegsam** [comment]
Hi Tina,

thx for reporting this issue. I already heard about such a thing together with Microsoft some years ago. At the moment I would tend to not change the behavior in powermail. At this point I don't get if the request is done by the client (so by the Office365 Outlook program installed on the clients device) or by the mailserver itself?

At first glance, there are some options for you and your customer:
- Turn off the security feature in Office365
- Any other hints from Microsoft how to handle this situation?
- Catch the request in Middleware if it is possible (probably a different UserAgent for this "security" request) and deliver a 404 or something else
- Building an own plugin or content element on a fix page. Then manipulating the Link in the OptIn Mail template to link to this page (but still deliver hash and mail parameters). The page will just show a button "Yes, pls confirm the Optin". By clicking the button, the original link (see OptIn Mail template) is called.

We can also talk about the issue next time when playing cards or just have a good time :100: 

CU, Alex

**Comment by twestner** [comment]
Hi Alex,

thanks for your reply. This is ok for me at the moment as we solved the issue by opening the doi for more requests (via patch).

Probably some other users will have that problem, so I provide some more last infos:

The additional request comes from the mail client and is sent, when the email is opened for the first time.

> Turn off the security feature in Office365

of course, I can do this... But I cannot tell all my users before ;)

> Any other hints from Microsoft how to handle this situation?

not yet.

> Catch the request in Middleware if it is possible (probably a different UserAgent for this "security" request) and deliver a 404 or something else

Not as easy as it seems. Catching the requests as HEAD-requests instead of GET does not work in any case, also the user-agent-filter does not match all requests (many of them have NO user_agent, but some are completely regular requests). An IP-filter could be an option, as the requests are sent with an Microsoft-IP (but also not in any case, when using a CDN for example).

An own plugin to handle these things is an option for sure.

But of course, let's talk, when we meet next time :) Looking forward to this.

**Comment by MR-DTR** [comment]
Hello all, exactly the same problem. The confirmation emails do not go out like this either. But in the database the mails are marked as confirmed. The issue is closed. But any tips, settings or workflows to handle it?

**Comment by twestner** [comment]
Hey, 
as we could not find any criteria to catch all of these calls for blocking them, we decided to open the confirmation-call for multiple clicks. In our use case it doesn't make any difference, if the link has been clicked once or twice or more often.
If you need any code, tell me and I will do a little research in my project to find it.

**Comment by MR-DTR** [comment]
@twestner that would be nice to see the code how you solved it.

**Comment by RMSsysteme** [comment]
We would also like to see this implementation of the workaround!

**Comment by twestner** [comment]
I'm sorry for the delay, the notification mail got somewhere lost in my inbox...

You only have to put away the if-clause which checks the hidden-state in FormController->optinConfirmAction. That's all.
We decided to patch and not to override the controller - that would also be a good way.

https://pastebin.com/mGHs9has
