### ISSUE TITLE
Feature Request: Test Mail to receiver button

### ISSUE THREAD

**Issue by vertexvaar** [einpraegsam/powermail#81]
The Powermail Plugin offers the possibility to define a custom message sent to both the receiver and the sender of a form. Testing and validating these settings is possible by filling the form in the frontend. As an Integrator i always have to overwrite the customers receiver e-mail address and check if there's also no additional TypoScript that overrules these settings again and revert my changes after successful testing.
A field to enter my e-mail address with a button beneath it to send a test mail with the defined contents would be nice!

**Comment by einpraegsam** [comment]
I've thinked a lot about that issue but I think I have too less time at the moment to implement something like this, even if I think it would be a good idea. Probably a bit later.
