### ISSUE TITLE
[BUG] Undefined array key 'marker'

### ISSUE THREAD

**Issue by PKuhlmay** [einpraegsam/powermail#813]
Hi I tried to add a submit button to a form, and I get the following error:
`PHP Warning: Undefined array key "marker" in /var/www/html/public/typo3conf/ext/powermail/Classes/Hook/CreateMarker.php line 374`
All other fields are working, only the submit button doesn't.

PHP 8.0
TYPO3 11.5.16
powermail 9.0.2
powermail_cond 9.0.3
composer mode

**Comment by PKuhlmay** [comment]
Changing the line to 
`return !empty($markers[$this->uid]) && $markers[$this->uid] !== ($this->properties['marker'] ?? null);
`worked for me.

**Comment by einpraegsam** [comment]
I just looked into the code and as far as I see, the change should not be needed with the existing lines of code:
```
return !empty($markers[$this->uid]) && isset($this->properties['marker']) && $markers[$this->uid] !== $this->properties['marker'];
```
because there is an isset($this->properties['marker']). 
Can you please use the latest powermail versions and test again?
