### ISSUE TITLE
[BUG] Undefined array key 0 in ShowFormNoteEditForm.php

### ISSUE THREAD

**Issue by PKuhlmay** [einpraegsam/powermail#814]
I tried to add a plugin 'Powermail' to a page, but after selecting the plugin in the wizard, I got the following error:
`PHP Warning: Undefined array key 0 in /var/www/html/public/typo3conf/ext/powermail/Classes/Tca/ShowFormNoteEditForm.php line 221`

PHP 8.0
TYPO3 11.5.16
powermail 9.0.2
powermail_cond 9.0.3
composer mode

**Comment by einpraegsam** [comment]
Please use the latest powermail versions. We dropped support for powermail 9.

**Comment by PKuhlmay** [comment]
I cannot use the latest version as the EXT:powermail_cond is not yet working with powermail 10. But if you release a new version for powermail_cond, I will change to the new one.

**Comment by einpraegsam** [comment]
There is already a new version of powermail_cond available for EAP members (as far as I remember). But back to topic: Powermail 9 is not supported any more with bugfixes and in addition there is a good chance, that this problem is already fixed.
