### ISSUE TITLE
Error when trying to localize a form field

### ISSUE THREAD

**Issue by olek07** [einpraegsam/powermail#82]
When trying to localize a form field I get en error message:
	
2: SQL error: 'Incorrect integer value: '' for column 'content_element' at row 1' (tx_powermail_domain_model_field:NEW5916b787d0685799405051)

Powermail: 3.18.0
TYPO3: 7.6.18

![powermail-error](https://cloud.githubusercontent.com/assets/16425375/26023604/3907645c-37c0-11e7-9e11-908346ba3858.png)

**Comment by einpraegsam** [comment]
What is the result if you run `SHOW VARIABLES LIKE 'sql_mode';` as sql query in your database?

**Comment by olek07** [comment]
`| sql_mode      | ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
`

**Comment by einpraegsam** [comment]
Thx, I changed my sql mode from `NO_ENGINE_SUBSTITUTION` on my local testsystem to your mode and could reproduce the issue. A fix was pushed to develop branch and will be released asap.

**Comment by einpraegsam** [comment]
Additional note: There is a bug in TYPO3 8.7.1 - it's not possible to store answers to database together with `STRICT_TRANS_TABLES` (see https://forge.typo3.org/issues/81043)
