### ISSUE TITLE
No array conversion of FlexForm data required in AbstractValidator

### ISSUE THREAD

**Issue by tbsschmdt** [einpraegsam/powermail#823]
In method `injectTypoScript` of class `AbstractValidator` the FlexForm data is converted to array via [$flexFormService->convertFlexFormContentToArray](https://github.com/einpraegsam/powermail/blob/ca958460d4cfd48277ad6a90bfbdf8a8b0c920a3/Classes/Domain/Validator/AbstractValidator.php#L144). This is not neccessary because `$configurationManager->getContentObject()->data['pi_flexform']` already returns the FlexForm data as array.

Calling `convertFlexFormContentToArray` with an array leads to an PHP warning in `GeneralUtiliy::xml2arrayProcess`: *Warning: trim() expects parameter 1 to be string, array given*.

The property `flexform` of `AbstractValidator` is empty after the conversion.

Is there any case where FlexForm data in this method is a string that needs conversion? Or could the conversion just be omitted?

**Comment by einpraegsam** [comment]
The function `injectTypoScript` was removed more then one year ago. I think you're using an outdated version of powermail?

**Comment by tbsschmdt** [comment]
I'm using version 8.4.2. It's the latest version that runs with TYPO3 10. Therefore I wouldn't call it completely outdated. But I guess that upgrading TYPO3 and using Powermail version 10 is the way to go.
