### ISSUE TITLE
[BUG] No linebreaks in answer for textarea fields with confirmation page active

### ISSUE THREAD

**Issue by cdominpxp** [einpraegsam/powermail#825]
We ran into an issue with missing line breaks in the answer of textarea fields.
The mail with powermail_all and also the export has no line breaks for answers with the textarea field type.

I've checked the database and if the confirmation page is active, the line breaks are missing in the database.
First entry is with confirmation page, second is without confirmation page:

![image](https://user-images.githubusercontent.com/14347480/200621508-1a0a5d09-91a7-44c1-94db-4b874ee04f8e.png)

powermail Versions: 10.4.2 and 10.6.0
Typo3 Version: 11.5.16

**Comment by einpraegsam** [comment]
Are you manipulating the HTML output somehow on the page? Maybe a html compressor or so? Can you please disable it and test again.

**Comment by cdominpxp** [comment]
That's true. We use sourceopt and if we disable it, the line breaks are there. Thanks for the hint, sourceopt removes the linebreaks from the hidden field on confirmation page:

![image](https://user-images.githubusercontent.com/14347480/205027535-2f5b033f-cc07-4f4b-b832-7bdfd479dd46.png)

So, we have to disable sourceopt on our form pages. Thank you very much for the support.
