### ISSUE TITLE
Overwrite sender-email (of sender and receiver mails) ends up in a "email address not valid" error

### ISSUE THREAD

**Issue by tobikummer** [einpraegsam/powermail#829]
TYPO3 11.5.18
Powermail: 10.6.0

If I overwrite the senderEmail and senderName via Typoscript globally like this 
```
plugin.tx_powermail {
    settings {
        setup {
            receiver {
                overwrite.senderEmail = TEXT
                overwrite.senderEmail.value = info@customer.ch

                overwrite.senderName = TEXT
                overwrite.senderName.value = Customer AG
            }

            sender {
                overwrite.senderEmail = TEXT
                overwrite.senderEmail.value = info@customer.ch

                overwrite.senderName = TEXT
                overwrite.senderName.value = Customer AG
            }
        }
    }
}
```

and I submit the form, the following error is shown in the log-file
```
Mail could not be sent - ["Email \"\" does not comply with addr-spec of RFC 2822."]
``` 

Our customers can create & update powermail plugins for themselves. So they left the fields `settings.flexform.sender.email` and `settings.flexform.sender.name` blank. THEN, the overwriting does not work like expected.
It the fill out these two fields, all works like expected.

**Comment by einpraegsam** [comment]
Yes, that is the current behaviour. Fields in FlexForm must be filled even if they may get overwritten later by TypoScript. At the moment we keep this behaviour.
