### ISSUE TITLE
loadEditId() is removed from T3v11 in Backend.js

### ISSUE THREAD

**Issue by OnrHng** [einpraegsam/powermail#836]
Hi,
loadEditId() is removed from T3v11 in Backend.js. Therefore it is throw an error. I personally fixed it in our extended extension like in OverviewBe.html partial

```
<td nowrap="nowrap">
	<a title="id={form.pid}" href="{f:be.uri(route: 'web_layout', parameters: '{id: form.pid}')}">
		<vh:getter.getPageNameFromUid uid="{form.pid}" />
	</a>
</td>
```

in origin extension it is so

```
<td nowrap="nowrap">
	<a title="id={form.pid}" onclick="top.loadEditId({form.pid},&quot;&amp;SET[language]=0&quot;); return false;" href="#">
		<vh:getter.getPageNameFromUid uid="{form.pid}" />
	</a>
</td>
```

it is quick fix with above help.

cheers
Onur

**Comment by einpraegsam** [comment]
Thx for the hint, I just pushed a fix to develpo branch. Ready for upcoming release.
