### ISSUE TITLE
settings.setup.sender.enable.if

### ISSUE THREAD

**Issue by krischanskide** [einpraegsam/powermail#837]
Maybe that's not the right place to ask, but:

I tried different ways (enable with if.isTrue, conditions with queryParams, enable as CASE, enable as field) to set sender mail enabled only if a checkbox in the form is activated, but always failed. Is it possible? What's the right way to do it?

Thank you very much.

**Comment by einpraegsam** [comment]
Please don't use github issues for your questions. This area is already too full. 
I would set on slack or stackoverflow - thx.
