### ISSUE TITLE
[globalString = GP:tx_powermail_pi1|field|anschaffungsvorschlag_fach = Allgemeines] didn't work

### ISSUE THREAD

**Issue by BFallert** [einpraegsam/powermail#84]
`[globalString = GP:tx_powermail_pi1|field|anschaffungsvorschlag_fach = Allgemeines]`
`    lib.anschaff_mail = TEXT`
`    lib.anschaff_mail.value = bernd.fallert@bib.uni-mannheim.de`
`    lib.anschaff_fach_name = TEXT`
`    lib.anschaff_fach_name.value = Fachreferat Allgemeines`
`[global]`

If i set the options without 
`[globalString = GP:tx_powermail_pi1|field|anschaffungsvorschlag_fach = Allgemeines]`
the mails will send, but with this option i get no mails.

With this statement i will change mail-Adresses and subject in the mail if the field "anschaffungsvorschlag_fach" has diffrent subjects.

I have no idea whats wrong? I find this example on other sides as well. 
Have someone any help?

Bernd

**Comment by BFallert** [comment]
I think i find my error. All fields are renamed???? instead of `anschaffungsvorschlag_fach` the called now `anschaffungsvorschlagfach`. 
If i changed this in my code, all is ok!

**Comment by BFallert** [comment]
if i stored a page the fied variables are changed. 
Can you dokument this?
Thanks

**Comment by einpraegsam** [comment]
Of course not every character is allowed. If you set your own marker, not allowed chars are substituted. If you want, you can make a pull request to improve documentation.
