### ISSUE TITLE
Receiver emails separated by space in flexform does not work but no warning displayed in BE form.

### ISSUE THREAD

**Issue by sypets** [einpraegsam/powermail#841]
If flexform `settings.flexform.receiver.email` contains several email addresses **separated by space** sending the email does not work but no warning is displayed in the backend form.

It is possible to enter several email addresses. [Documented](https://github.com/einpraegsam/powermail/blob/develop/Documentation/ForEditors/AddNewPlugins.md) is to separate them with newline. Other delimeters also work, such as comma or semicolon (this is later converted into semicolon).

However using space as delimeter does not work, but an error is not displayed when entering this in the form or when saving the form.

Later, the receiver email will not be sent, an error is displayed in the form.

Also, there is no validation done at all in the BE so it is possible to save the form with an invalid email (such as without `@`)

----

**works:**

```
adress1.example.org
adress2.example.org
```

`adress1.example.org;adress2.example.org`

----

**Does not work:**

`adress1.example.org adress2.example.org`

----

Can use SQL query to show the email addresses:

MariaDB:

`SELECT uid,pid,REGEXP_REPLACE(REPLACE(pi_flexform,'\n', 'NL'),'.*settings.flexform.receiver.email">NL *<value index="vDEF">([^<]*)<.*', '\\1') FROM tt_content WHERE NOT deleted AND ctype='list' AND list_type='powermail_pi1';`

MySQL:

`SELECT uid,pid,REGEXP_REPLACE(REPLACE(pi_flexform,'\n', 'NL'),'.*settings.flexform.receiver.email">NL *<value index="vDEF">([^<]*)<.*', '$1') FROM tt_content WHERE NOT deleted AND ctype='list' AND list_type='powermail_pi1';
`

---

source code to parse mails:

**ReceiverMailReceiverPropertiesService**

```
protected function parseEmailsFromString(string $string): array
    {
        $array = [];
        $string = str_replace(
            [
                PHP_EOL,
                '|',
                ','
            ],
            ';',
            $string
        );
        $arr = GeneralUtility::trimExplode(';', $string, true);

```

**Comment by einpraegsam** [comment]
While I tended to close this request at first glance because we still use too much separators, I now think one more isn't a problem. 
Pushed a fix to develop branch. 
Ready for upcoming release.
