### ISSUE TITLE
TypoScript condition error

### ISSUE THREAD

**Issue by Teisi** [einpraegsam/powermail#844]
TYPO3 10.4.32
powermail 8.4.2

### powermail/Configuration/TypoScript/Powermail_Frontend/setup.typoscript (127 | 138)
[ERROR] request="70a40e247738e" component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed. - {"expression":"{$plugin.tx_powermail.settings.styles.bootstrap.important} == 1"}

and
### powermail/Configuration/TypoScript/BootstrapClassesAndLayout/setup.typoscript (4 | 9)
[ERROR] request="70a40e247738e" component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed. - {"expression":"{$plugin.tx_powermail.settings.javascript.addJQueryFromGoogle} == 1"}

### I think for example the "value" should be in quote's like:
```diff
- [{$plugin.tx_powermail.settings.styles.bootstrap.addBootstrap} == 1]
+ ["{$plugin.tx_powermail.settings.styles.bootstrap.addBootstrap}" == "1"]
```

**Comment by einpraegsam** [comment]
Powermail 8 is not yet supported any more with bugfixes. Nevertheless the same code is still used in latest powermail version. But I can't see such an error in log. Furthermore a comparison with an integer value should be possible without quotes.

**Comment by Teisi** [comment]
ah so all right :)

anyway, I can only say that the error was gone after I have now changed the lines in the installed powermail version manually as written above.

**Comment by einpraegsam** [comment]
Thx, for your final feedback
