### ISSUE TITLE
unencrypted Passwords

### ISSUE THREAD

**Issue by emhl** [einpraegsam/powermail#846]
I know that it is a nieche feature, but currently the Password field only obscures the password when typing it in. The input is saved and sent unencrypted.
additionally, it's not possible to set any requirements (like password length)

Would it be possible to store and share hashed passwords instead?

Another option would be to remove password fields entirely.

in its current form it just encourages bad security practices and has less features than the normal text field.

**Comment by einpraegsam** [comment]
That's correct we should remove the field type in future.
As a quick solution, you can disable the field type in your instance.
