### ISSUE TITLE
Missing use statement in In2code\Powermail\Command\CleanupUploadsCommand

### ISSUE THREAD

**Issue by chrissonntag** [einpraegsam/powermail#847]
Powermail-Version: 9.0.2
The class `In2code\Powermail\Command\CleanupUploadsCommand` is missing a use statemtn to `Symfony\Component\Console\Command\Command`. Therefore the following error is thrown when executing the cleanupUploadsCommand
```
Uncaught TYPO3 Exception Class "In2code\Powermail\Command\Command" not found
thrown in file /app/public/typo3conf/ext/powermail/Classes/Command/CleanupUploadsCommand.php
in line 40
```

The bug is already [fixed in the most recent version of powermail](https://github.com/einpraegsam/powermail/blob/develop/Classes/Command/CleanupUploadsCommand.php#L6). But due to the requirements of powermail_cond we have to stick with v9 for now.

Thx for your effort in advance

**Comment by einpraegsam** [comment]
Sorry to hear that, but as you may already know, powermail 9 is not supported any more with regulare bugfixes.
