### ISSUE TITLE
Warning when saving fields

### ISSUE THREAD

**Issue by lucmuller** [einpraegsam/powermail#854]
When saving a field (textbox in y case) I get this warning
```
(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Undefined array key "marker" in /var/www/esiee.dev15.ameos.info/public/typo3conf/ext/powermail/Classes/Hook/CreateMarker.php line 374
```
![image](https://user-images.githubusercontent.com/1927963/214582455-1c07a70f-4eb8-45d8-bf72-ea66b2cdf72f.png)

**Comment by lucmuller** [comment]
Sorry, should have done that in the first place.
TYPO3 11 PHP 8.1 Powermail has been installed with composer.

**Comment by einpraegsam** [comment]
Powermail 9 support was dropped. Please use version 10. I'm pretty sure that this issue is already fixed in 10.

**Comment by lucmuller** [comment]
My Bad ! Thanks for pointing this out !

It's because we're using powermail_cond who seems to not be compatible with the latest powermail version.
