### ISSUE TITLE
symfony condition syntax for on/off mail to sender by checkbox in frontend

### ISSUE THREAD

**Issue by derBoogie** [einpraegsam/powermail#855]
Before the update to TYPO3 9.5 I used the following condition syntax in setup.typoscript to enable sending an email to the sender using a checkbox in the frontend form:
 
```
[globalString = GP:tx_powermail_pi1|field|emailanansender|0 = ]
    plugin.tx_powermail.settings.setup.sender.enable = 0
[else]
    plugin.tx_powermail.settings.setup.sender.enable = 1
[global]
```

What should the symfony condition syntax look like for this purpose?

According to my logic, the following should work, but it does not:

```
[traverse(request.getParsedBody(), 'tx_powermail_pi1/field/emailanansender/0')]
	plugin.tx_powermail.settings.setup.sender.enable = 1
[else]
	plugin.tx_powermail.settings.setup.sender.enable = 0
[global]
```

Can anyone help me with this?

**Comment by einpraegsam** [comment]
Please don't use github issues for support questions. Stackoverflow or Slack would be an opinion.

**Comment by derBoogie** [comment]
In case someone should need it, the syntax for TYPO3 >= 9 is:

```
[traverse(request.getParsedBody(), 'tx_powermail_pi1/field/emailanabsender/0') == '']
	plugin.tx_powermail.settings.setup.sender.enable = 0
[else]
	plugin.tx_powermail.settings.setup.sender.enable = 1
[global]
```
