### ISSUE TITLE
PageRepository works on wrong table

### ISSUE THREAD

**Issue by rvock** [einpraegsam/powermail#857]
The PageRepository works on the wrong database table in TYPO3 v11.5.22:

[PageRepository.php#L35](https://github.com/einpraegsam/powermail/blob/79242316bec50e92ed79b5c4a2db4250d90c4984/Classes/Domain/Repository/PageRepository.php#L35)

```php
public function getPropertiesFromUid(int $uid): array
{
    $query = $this->createQuery();
    $sql = 'select * from pages where uid = ' . (int)$uid . ' limit 1';
    $result = $query->statement($sql)->execute(true);
    return $result[0];
}
```

Even though the query specifies the `pages` table, the generated query uses `tx_powermail_domain_model_page`.

You can easily reproduce this bug, if you call `getPropertiesFromUid()` with a valid PageUid:
```php
$pageRepository = GeneralUtility::makeInstance(PageRepository::class);
$pageRepository->getPropertiesFromUid(1); // Throws exception
```

I believe this is a regression, because TYPO3 might have changed Query-Handling or query-generation in the `statement()` method. The current code does not need an extbase query and should be refactored to use Doctrine DBAL (as is the case with `getAllPages()` in the same class).

**Comment by einpraegsam** [comment]
Hello,

even if you're basically right with the idea to replace the old function with a queryBuilder, I was not able to reproduce this issue.
I updated to the latest TYPO3 11 and the latest powermail version. After that I just vardumped `$pageRepository->getPropertiesFromUid(1)` in FormController->formAction and the result is the expected result from table `pages.*`.
How to reproduce this issue?

**Comment by rvock** [comment]
You're right. You need to install the workspace extension.

I know, that powermail does not work with workspaces. But the error occurs in the live-workspace and it was working in TYPO3 v9.

**Comment by einpraegsam** [comment]
Even if this problem is related to workspaces or to extbase in relation with workspaces, I updated the function.

**Comment by rvock** [comment]
Great, thanks a lot 👍 

I can confirm, it's working in our installation.
