### ISSUE TITLE
Wrong value type in Reporting ViewHelper

### ISSUE THREAD

**Issue by dennislizarzaburu** [einpraegsam/powermail#861]
Problem: When having only numbers in an answers value field, the GetLabelsForChartsViewHelper returns an error. It appears in the "Reporting (Form)" view in the backend module. 

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: str_replace(): Argument #3 ($subject) must be of type array|string, int given | TypeError thrown in file /public/typo3conf/ext/powermail/Classes/ViewHelpers/Reporting/GetLabelsForChartsViewHelper.php in line 50. `

- TYPO3 11.5.24
- PHP 8.0 / 8.1
- Powermail 10.7

**Comment by einpraegsam** [comment]
Thx, I just fixed it in develop branch.
