### ISSUE TITLE
Function check under PHP >= 8.0: PHP Warning: Undefined variable $_EXTKEY 

### ISSUE THREAD

**Issue by obusch14v** [einpraegsam/powermail#864]
Hi,
if we click on "Function check" in the "Mails" module in the backend, we get the error message
`PHP Warning: Undefined variable $_EXTKEY in /xxxxxxxx/typo3conf/ext/powermail/ext_emconf.php line 13`

The error occurs from PHP version 8.0 (tested 8.0, 8.1 and 8.2).
There is no error message under PHP version 7.4.

Can anyone confirm this error?

TYPO3: 11.5.24
Powermail: 10.7.0

**Comment by einpraegsam** [comment]
As you can see here: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/FileStructure/ExtEmconf.html
It's still needed that ext_emconf.php needs the (meanwhile outdated) variable $_EXTKEY. Se we have to use it. Please create a new issue under forge.typo3.org for this.
