### ISSUE TITLE
Add CMS v12 compatibility

### ISSUE THREAD

**Issue by grempa** [einpraegsam/powermail#867]
It would be great to have a version, which is compatible with the upcoming TYPO3 CMS v12.
Alternatively, if it is already compatible, please add the version in composer etc.

**Comment by einpraegsam** [comment]
Powermail for version 12 is nearly ready to use. Availability is only possible via EAP for this year (see https://www.in2code.de/agentur/typo3-extensions/early-access-programm/ or https://www.in2code.de/en/agency/typo3-extensions/early-access-program/). 
At the beginning of 2024 powermail for TYPO3 12 will be available for everyone for free.

Hope that helps you for your plans
