### ISSUE TITLE
How to get the same DateTime Picker as before v10 update ?

### ISSUE THREAD

**Issue by Seranno** [einpraegsam/powermail#885]
As mentionned in the [UpgradeInstructions ](https://github.com/einpraegsam/powermail/blob/10.0.0/Documentation/Changelog/UpgradeInstructions.md) the library Parsley.js has been removed.
This is what we used to show a DateTime Picker with Time displayed in the Picker.

### BEFORE (Typo3 10.4 - Powermail 8.4.1): 
![DateTimePicker_before_v10](https://github.com/einpraegsam/powermail/assets/86281894/69f01e2a-1ae1-47c3-b424-c39ebc05884b)

`<input data-datepicker-force="1" data-datepicker-settings="datetime" data-datepicker-months="Janvier,Février,Mars,Avril,Mai,Juin,Juillet,Août,Septembre,Octobre,Novembre,Décembre" data-datepicker-days="Di,Lun,Ma,Me,Je,Ve,Sa" data-datepicker-format="Y-m-d H:i" required="required" aria-required="true" data-parsley-required-message="Ce champ doit être rempli !" data-parsley-trigger="change" class="powermail_date parsley-error" id="powermail_field_date_start" type="text" name="tx_powermail_pi1[field][date_start]" value="" data-parsley-id="5">`

### AFTER (Typo3 11.5 - Powermail 10.7.0):
![DateTimePicker_after_v10](https://github.com/einpraegsam/powermail/assets/86281894/a596f9a0-aded-43ee-870c-d6f79175395c)

`<input data-datepicker-format="YYYY-MM-DD HH:mm" required="required" aria-required="true" data-powermail-required-message="Ce champ doit être rempli !" class="powermail_date powermail_field_error" id="powermail_field_date_start" type="datetime-local" name="tx_powermail_pi1[field][date_start]" value="" aria-describedby="tx_powermail_pi1fielddate_start-errormessage">`

Additional info :
- We display the Powermail form on Firefox 102.11.0esr (64-bit)
- We used `misc.forceJavaScriptDatePicker = 1`

Right now I don't know how to : 
- Change the time format of the placeholder in Y-m-d H:i -> no PM/AM  (blocking)
- Display the Time in the picker, so the user can choose it (blocking)
- Show the DateTime Picker in French (not blocking)

**Comment by einpraegsam** [comment]
Datetimepicker was removed together with parsley.js as the need of jQuery. As far as I remember we go for native datepicker solution from browsers. There is no way back in powermail to jQuery. Nevertheless, feel free to add any JS framework or helper class that you need.

**Comment by Seranno** [comment]
Thanks for the prompt answer !
