### ISSUE TITLE
File name for attachment from variables

### ISSUE THREAD

**Issue by qween90** [einpraegsam/powermail#889]
Hi,

I have used the extension: pdfviewhelpers to create a PDF from my Powermail form for download. The name of the PDF is generated from 2 variables {name} and {firstname} and stored in the TYPO3 backend in a folder fileadmin/PDF/xxx{name}_{firstname}.pdf.

Now I'm trying to send this PDF via email attachment to the user, but I can't get it to work. Is there a solution for this?

**Comment by einpraegsam** [comment]
Please don't use github issues for support questions. Free support could be possible via Slack or Stackoverflow. Thx, Alex
