### ISSUE TITLE
Exception while refreshing the submit page

### ISSUE THREAD

**Issue by pixelplant** [einpraegsam/powermail#89]
Refreshing the "submit page" generates this error. I am using the latest release of powermail and TYPO3 8.7.1

_Exception while property mapping at property path "": It is not allowed to map property "answers". You need to use $propertyMappingConfiguration->allowProperties('answers') to enable mapping of this property._

How to reproduce? Create a simple form with several fields, and make sure you also add a captcha. Activate the confirmation page then proceed to the "submit page". Once the page is loaded and you have all the data displayed, make sure you refresh it. You should now get the error.

**Comment by einpraegsam** [comment]
If I reload a submit page (form contained a captcha field), my browser (firefox) ask me if I want to resend the values. If I click yes, this is the (wanted) result:
<img src="https://box.everhelper.me/attachment/924349/84725fb7-0b3e-4c40-b52e-29d7620777bb/262407-r64ZurwHbicVJt2V/screen.png" />

**Comment by Sonezi** [comment]
same error for me, except i am using reCAPTCHA for Powermail, i tried both version and 1.0.0 and 1.1.1 same error... everything works just fine until you need to confirm form on submit button...

query string:

id=23
tx_powermail_pi1[action]=create
tx_powermail_pi1[controller]=Form
cHash=88d66d30a0ee90eb3f810b3441e22f9f

request body: 
-----------------------------832481986668778497230790681
Content-Disposition: form-data; name="tx_powermail_pi1[__referrer][@extension]"

Powermail
-----------------------------832481986668778497230790681
Content-Disposition: form-data; name="tx_powermail_pi1[__referrer][@vendor]"

In2code
-----------------------------832481986668778497230790681
Content-Disposition: form-data; name="tx_powermail_pi1[__referrer][@controller]"

Form
-----------------------------832481986668778497230790681
Content-Disposition: form-data; name="tx_powermail_pi1[__referrer][@action]"

confirmation
-----------------------------832481986668778497230790681
Content-Disposition: form-data; name="tx_powermail_pi1[__referrer][arguments]"

YToyOntzOjQ6Im1haWwiO2E6Mjp7czo0OiJmb3JtIjtzOjE6IjEiO3M6NzoiYW5zd2VycyI7YTo4OntpOjA7YTozOntzOjU6ImZpZWxkIjtzOjI6IjEzIjtzOjU6InZhbHVlIjtzOjU6InZhbGlkIjtzOjk6InZhbHVlVHlwZSI7aTowO31pOjE7YTozOntzOjU6ImZpZWxkIjtzOjE6IjEiO3M6NToidmFsdWUiO3M6NToibmVuYWQiO3M6OToidmFsdWVUeXBlIjtpOjA7fWk6MjthOjM6e3M6NToiZmllbGQiO3M6MToiMiI7czo1OiJ2YWx1ZSI7czoxMToiamtsamtsdWl1aXUiO3M6OToidmFsdWVUeXBlIjtpOjA7fWk6MzthOjM6e3M6NToiZmllbGQiO3M6MToiMyI7czo1OiJ2YWx1ZSI7czo2OiIxMjE5ODQiO3M6OToidmFsdWVUeXBlIjtpOjA7fWk6NDthOjM6e3M6NToiZmllbGQiO3M6MToiNCI7czo1OiJ2YWx1ZSI7czo2OiIzMzQyNTIiO3M6OToidmFsdWVUeXBlIjtpOjA7fWk6NTthOjM6e3M6NToiZmllbGQiO3M6MToiOSI7czo1OiJ2YWx1ZSI7czoxMDoiMzQyMzQyMzQyMyI7czo5OiJ2YWx1ZVR5cGUiO2k6MDt9aTo2O2E6Mzp7czo1OiJmaWVsZCI7czoxOiI1IjtzOjU6InZhbHVlIjtzOjE1OiJuZXpuYW1AZ21haS5jb20iO3M6OToidmFsdWVUeXBlIjtpOjA7fWk6NzthOjM6e3M6NToiZmllbGQiO3M6MToiNiI7czo1OiJ2YWx1ZSI7czowOiIiO3M6OToidmFsdWVUeXBlIjtpOjA7fX19czo1OiJmaWVsZCI7Tjt91efcab61ecdb9736259c59d5a2f4a35d6510d756
-----------------------------832481986668778497230790681
Content-Disposition: form-data; name="tx_powermail_pi1[__referrer][@request]"

a:4:{s:10:"@extension";s:9:"Powermail";s:11:"@controller";s:4:"Form";s:7:"@action";s:12:"confirmation";s:7:"@vendor";s:7:"In2code";}869ad6c7cecbb76c694c1ea16e374da47aecf475
-----------------------------832481986668778497230790681
Content-Disposition: form-data; name="tx_powermail_pi1[__trustedProperties]"

a:2:{s:5:"field";a:8:{s:6:"marker";i:1;s:4:"name";i:1;s:7:"vorname";i:1;s:3:"plz";i:1;s:3:"ort";i:1;s:6:"mobile";i:1;s:5:"email";i:1;s:4:"text";i:1;}s:4:"mail";a:1:{s:4:"form";i:1;}}7f165948d5c4b8134ee293ab13790a4d8a40a7ec
-----------------------------832481986668778497230790681
Content-Disposition: form-data; name="tx_powermail_pi1[field][marker]"

valid
-----------------------------832481986668778497230790681
Content-Disposition: form-data; name="tx_powermail_pi1[field][name]"

nenad
-----------------------------832481986668778497230790681
Content-Disposition: form-data; name="tx_powermail_pi1[field][vorname]"

jkljkluiuiu
-----------------------------832481986668778497230790681
Content-Disposition: form-data; name="tx_powermail_pi1[field][plz]"

121984
-----------------------------832481986668778497230790681
Content-Disposition: form-data; name="tx_powermail_pi1[field][ort]"

334252
-----------------------------832481986668778497230790681
Content-Disposition: form-data; name="tx_powermail_pi1[field][mobile]"

3423423423
-----------------------------832481986668778497230790681
Content-Disposition: form-data; name="tx_powermail_pi1[field][email]"

neznam@gmai.com
-----------------------------832481986668778497230790681
Content-Disposition: form-data; name="tx_powermail_pi1[field][text]"


-----------------------------832481986668778497230790681
Content-Disposition: form-data; name="tx_powermail_pi1[mail][form]"

1
-----------------------------832481986668778497230790681--

any hint? :) tnx

**Comment by Sonezi** [comment]
if i turn off (Do you want a confirmation page? ) recaptcha passes without error!! and mail shows up in backend? but what about client request to have confirmation page?? Any help? tnx

**Comment by einpraegsam** [comment]
Sorry, I still can't reproduce this issue, even with https://github.com/einpraegsam/powermailrecaptcha and activated confirmation page (Firefox and resend values on reload). 
* Reloading of the confirmation page without problems
* Reloading of the final submit page without problems

**Comment by bsolano** [comment]
I am seeing the same error with TYPO3 7.6.9, the latest powermail and the extension rh_recaptcha.  Maybe it is a recaptcha issue?

![4b9e1d5d5dc28773dd3961203010c829d0d370966b5184aa3c pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/11201077/27360557-119d5d62-55df-11e7-9187-90e34b52f950.png)

**Comment by Kitzberger** [comment]
I can confirm this issue with TYPO3 7.6.21, powermail 2.25.2 and jh_captcha 1.3.1. As soon as there's a form with a captcha and I try to submit the confirmation page -> Bam!

**Comment by kiwi2101** [comment]
I can confirm this is still a issue with powermail 4.* and Typo3 8.7.10
The mentioned workaround in #19 didn't solve my problem.
