### ISSUE TITLE
Undefined array key "tt_content" in vendor/in2code/powermail/Classes/EventListener/FlexFormParsingModifyEventListener.php line 78

### ISSUE THREAD

**Issue by format-gmbh** [einpraegsam/powermail#891]
An error occurred trying to process items for field "Allowed excludefields" (PHP Warning: Undefined array key "tt_content" in vendor/in2code/powermail/Classes/EventListener/FlexFormParsingModifyEventListener.php line 78).

The error occurs when editing a backend user group.

TYPO3 12.4.2
PHP 8.2.1
powermail 11.0.0

**Comment by format-gmbh** [comment]
Now I have a slightly different error message in the same place:

Uncaught TYPO3 Exception: array_keys(): Argument #1 ($array) must be of type array, null given | TypeError thrown in file vendor/in2code/powermail/Classes/EventListener/FlexFormParsingModifyEventListener.php in line 78

**Comment by kanow** [comment]
I can confirm this issue. 

TYPO3 12.4.5
PHP 8.2.4
powermail 11.0.0 

I patched this line with

`$uid = isset($queryParams['edit']['tt_content']) ? array_keys($queryParams['edit']['tt_content'])[0] : 0;`

but I don't know why is it necessary. Why this FlexFormParsingModifyEventListener is used on editing `be_groups` and building selects for the `non_exclude_fields`?

**Comment by mschwemer** [comment]
Thanks for the report. 

The fix is available in the latest release 11.0.1 via the eap program.
