### ISSUE TITLE
 New form JS validation documentation?

### ISSUE THREAD

**Issue by alsodenn** [einpraegsam/powermail#893]
Is there any documentation for the new JS validation?

Previously with Parsley.js you had various callback events available. 
We now need a callback as soon as the form has no errors, i.e. shortly before it is sent, i.e. an "isValid" event.

Is there such a thing or how could it be implemented?

**Comment by einpraegsam** [comment]
Please look into the documentation for some help: https://github.com/einpraegsam/powermail/blob/develop/Documentation/ForDevelopers/WriteOwnValidators.md
