### ISSUE TITLE
Undefined array key "edit" on activate/deactivate powermail plugin

### ISSUE THREAD

**Issue by kanow** [einpraegsam/powermail#894]
PHP E_Warning if I change hidden state of the content element plugin in backend.

`Undefined array key "edit" in powermail/Classes/EventListener/FlexFormParsingModifyEventListener.php in line 78 `

TYPO3 12.4.3
PHP 8.2.4

**Comment by mschwemer** [comment]
Thanks for the report. 

The fix is available in the latest release 11.0.1 via the eap program.
