### ISSUE TITLE
powermail_frontend backend checkboxes dont get saved

### ISSUE THREAD

**Issue by wolfgang007** [einpraegsam/powermail#895]
Hello guys, 

if the powermail version is greather than v9, the backend checkboxes of the modul powermail_frontend "Own entries" and "Link to detail view" dont get saved, if checked. 

In lower versions of powermail it worked correctly. 

I use Typo3 11.5 and powermail 10.7

Anyone have an idea?
![checkbox1](https://github.com/einpraegsam/powermail/assets/17067590/308d867d-4389-4173-b220-b1026a1366b8)
![checkbox2](https://github.com/einpraegsam/powermail/assets/17067590/0c1db0b0-2e6d-4a8e-a37e-6d1071c15e50)

**Comment by mschwemer** [comment]
Thanks for the report. 

The fix is available in the latest releases: V 11.0.1 for TYPO3 12 and V 10.7.3 for TYPO3 11
