### ISSUE TITLE
Undefined array key "type" in powermail/Classes/Hook/PluginPreviewRenderer.php

### ISSUE THREAD

**Issue by kanow** [einpraegsam/powermail#898]
Hi,

TYPO3 12.4
PHP 8.2.4
Powermail 11.0.0

if I go to pages in pagetree (backend) with powermail plugins I have this error.

`Undefined array key "type" in powermail/Classes/Hook/PluginPreviewRenderer.php`
That points to the line 129:
`    if ((int)$this->flexFormData['settings']['flexform']['receiver']['type'] === 1) {`

I'm updating an older site from TYPO3 9.5 to TYPO3 12 with powermail 11.0.0. (EAP with TYPO3 12 compatibility).
The error is shown if I try to show the content elements in page module. In List module I can see all content elements and can edit the powermail plugin.

After saving the plugin (no changes, just saving), the error is gone. It sems like that the receiver type is not set in the flexform settings in old content element which is set after saving the element. I'm not sure whats the proper solution. Adapt migration for such cases or check if type is set or not :wink: 

The old powermail version was 7.4.0.

Upgrade wizards in 10.4 executed:
* powermailRelationUpdateWizard
* powermailLanguageUpdateWizard

UpgradeWizard in 12.4 executed:
* "Powermail: Migrate list types and switchable controller actions to CTypes"
* "EXT:powermail: Migrate plugin permissions"

**Comment by mschwemer** [comment]
Thanks for the report. 

The fix is available in the latest release 11.0.1 via the eap program.
