### ISSUE TITLE
PluginUpdater wizard ignores CType in migration

### ISSUE THREAD

**Issue by kanow** [einpraegsam/powermail#899]
I'm updating powermail to 11.0.0 with EAP.

UpgradeWizard for plugins, only checks `list_type` and ignores the `CType` of content elements in `getMigrationRecords` function.
In my instance we have content elements where the CType was changed from `list` to `textmedia` after the powermail form was not longer needed. In those elements the `list_type` is still `powermail_pi1` and the `pi_flexform` is also filled with powermail data. But those elements are now used as normal textmedia element. The migration wizard changed the the `CType` back to a Powermail plugin and the form is now back on the page :wink: .

Checking the CType additionally will help on such issues.

For now I will check the database and changing the `list_type` of those content elements before excuting the wizard.

**Comment by mschwemer** [comment]
Thanks for the report. 

The fix is available in the latest release 11.0.1 via the eap program.
