### ISSUE TITLE
Mail layout styling

### ISSUE THREAD

**Issue by pixelplant** [einpraegsam/powermail#90]
Hello

Is there any way to style the overall template sent by emails? I'm talking about the Mail.html file in the "Layouts" folder. How would one go about adding inline images (think logo, header, etc) that would be sent along with the text supplied in the bodytext?

I don't think I've seen this explained in the docs so I was wondering if it was possible at all. I could link them to an external domain no problem, I was just wondering if inline attachments are a possibility, maybe with some of your viewhelpers?

Thank you

**Comment by einpraegsam** [comment]
Yes, you could/should set your own Layout- and Template-Files. In with this you can add your own inline styles. 
How to set own Templates/Layouts/Partials: https://docs.typo3.org/typo3cms/extensions/powermail/ForAdministrators/BestPractice/Templates/Index.html

**Comment by pixelplant** [comment]
Yes, I was aware of the documentation and I managed to customise the layout and add my own images, etc. The question was mostly related to inline images, let's say you have a logo and you want it to be attached (integrated) with the email sent, and not just an absolute url and thus avoiding you to "confirm" the display of images in the email client.
So instead of a call like this in your layout
```
<f:image src="EXT:hdv/Resources/Public/Images/logo_hdv.jpg" alt="" absolute="true"/>
```
imagine having maybe a dedicated viewhelper in powermail with an option "inline" or "attach" that displays the image and also integrates it in the email

**Comment by einpraegsam** [comment]
No, there is no such viewhelper. Nevertheless you can add attachments easily via TypoScript: https://github.com/einpraegsam/powermail/blob/develop/Configuration/TypoScript/Main/setup.txt#L171
