### ISSUE TITLE
Allow same value for option in select field

### ISSUE THREAD

**Issue by echavaillaz** [einpraegsam/powermail#900]
Actually if I configure a select field like this:
```
mango | fruit
rose | flower
pineapple | fruit
lotus | flower
lily | flower
```
Only pineapple and lily will be displayed.
The right thing to do would be to display them all.

The problem is in the "SelectFieldViewHelper", the method "setOptions" rewrite the options based on the value.

**Comment by einpraegsam** [comment]
Following the documentation on https://github.com/einpraegsam/powermail/blob/develop/Documentation/ForEditors/FieldSelect.md#option-examples-for-selectbox the part right of the pipe is used as value. So the pipe-symbol is used for a split.

**Comment by echavaillaz** [comment]
Thanks for the answer, I must be missing something, how can I render something like:
```
<select>
  <option value="fruit">mango</option>
  <option value="flower">rose</option>
  <option value="fruit">pineapple</option>
  <option value="flower">lotus</option>
  <option value="flower">lily</option>
</select>
```
It seems to be not possible also according the doc.

**Comment by einpraegsam** [comment]
That is not possible per default. Powermail is designed that values in (e.g.) select fields must be unique. 
So, yes, this is not possible at the moment.

**Comment by BokuNoMaxi** [comment]
@echavaillaz you can output your options by overwriting the select field: 
`<f:form.select
      property="{field.marker}"
      class="powermail_select {settings.styles.framework.fieldClasses} {vh:validation.errorClass(field:field, class:'powermail_field_error')}"
      id="powermail_field_{field.marker}"
      additionalAttributes="{vh:validation.validationDataAttribute(field:field)}"
      multiple="{field.multiselectForField}"
      value="{vh:misc.prefillField(field:field, mail:mail)}"
    >
      <f:for each="{field.modifiedSettings}" as="option" iteration="i">
        <f:form.select.option value="{option.value}"> {option.label}</f:form.select.option>
      </f:for>
    </f:form.select>`

@einpraegsam is there a possibility to access the label of the option? currently I can only access the value or the label of the select, but not the option. Sometimes it is a nice feature to select the receiver mail by a select box instead of some hacky typoscript overwrite if a field on uid 1486 is set. Or is there a better way?
