### ISSUE TITLE
emconf and composer.json: suggest static_info_tables extension

### ISSUE THREAD

**Issue by zabinetta** [einpraegsam/powermail#901]
Hi,
could you please require or suggest the static_info_tables Extension in ext_emconf.php and composer.json , to make sure the static country properties are available for the CountriesFromStaticInfoTablesService.php
(I had the issue when updating to v11.5)
with the best regards,
Sabine

**Comment by mschwemer** [comment]
Sorry, I forgot to cherry-pick the change from the eap program into the public repo. 

Will be included in the next release.
