### ISSUE TITLE
Date fields are not stored

### ISSUE THREAD

**Issue by pixelplant** [einpraegsam/powermail#91]
When using date fields, either with our without DatePicker activated, the date is not displayed on the confirmation page and on the submit page, and it is also not available in the finishers.
It is present during the first submit though, so if the validation fails you can still see your old value in the textfield, but it's not passed on to the other pages.

**Comment by einpraegsam** [comment]
That sound very strange to me. There is a huge testparcour that have to be run through for some automatic tests and that would be a major issue.
See http://powermail.in2code.ws/index.php?id=28 for a testpage with datefields and confirmation page. Please check if the marker of the datefield is empty.
BTW: What powermail and what TYPO3-Version?

**Comment by pixelplant** [comment]
TYPO3 v8.7.1 and latest powermail version 3.18.2

**Comment by pixelplant** [comment]
ok, fixed the issue.
The default language on my installation is French, and the datetime format was always set to "j-m-A" for some reason. It comes from a standard powermail installation so I did not modify the format somewhere else.

What I had to do to fix it was to specify the format for each language, including french
```
    plugin.tx_powermail_pi1._LOCAL_LANG {
        default {
            datepicker_format_date = d/m/Y
            datepicker_format_time = d/m/Y H:i:s
            datepicker_format_datetime = H:i:s
        }
        fr {
            datepicker_format_date = d.m.Y
            datepicker_format_time = d.m.Y H:i:s
            datepicker_format_datetime = H:i:s
        }
    }
```
It now works and the date is displayed on the confirmation page and stored in the database.

Maybe one of the reasons would be that I overwrote the partials location (added them to my extension) and so it does not find the translations defined in powermail as it runs in the context of my extension? but if that were the case it should not work even if I define the translations in typoscript, since they're still defined for powermail

```
plugin.tx_powermail {
    view {
        partialRootPaths {
            0 = EXT:powermail/Resources/Private/Partials/
            20 = EXT:hdv/Resources/Private/Partials/Ext/Powermail/
        }
...
```

**Comment by einpraegsam** [comment]
Probably you load translations from translation.typo3.org into typo3/l10n/powermail and maybe there is a problem with the french localization. Nevertheless, you're right to set the format via TypoScript. This is needed for the datepicker on one hand and on the other hand for the date-converting after a form submit.

**Comment by pixelplant** [comment]
Ah yes, indeed. it was in the translations fetched from the translation server. Someone translated directly "d-m-Y" to french, as in "j-m-A" (jour, mois année) and this breaks the date handling if you use the french translation.

**Comment by einpraegsam** [comment]
Yes, search on translation server (after) login just shows the problem https://translation.typo3.org/fr/TYPO3.ext.powermail/translate/Resources/Private/Language/locallang.xlf#search=Y-m-d&sfields=source,target
I think I could replace it on the server for the future (hopefully - because I'm not a pootle-expert)
