### ISSUE TITLE
Autofill in Google Chrome

### ISSUE THREAD

**Issue by DTM-TYPO3** [einpraegsam/powermail#94]
In a contact form with just a few fields (name, lastname, mail, message) the autofill function from Google Chrome always puts an e-mail address into the input field. If the form has more fields (zip, city etc.) autofill puts in the "correct" values.
Could that be fixed by renaming labels / input field names?
Thanks for any advice in advance.
Best regards,
Stefanie

TYPO3 7.6.18
powermail 3.18.0
Google Chrome Version 58.0.3029.110 (64-bit)

**Comment by einpraegsam** [comment]
You can change the labels as you want, but the field names must have a name like `tx_powermail_pi1[field][something]`.
Probably chrome sees a name like ...mail... and "thinks" it must be a mail field. Nevertheless I can't simply change the name of the extension.

**Comment by DTM-TYPO3** [comment]
Thanks for your answer.
For future releases could you overthink the naming of the form fields to avoid this bug with chrome´s autofill?

**Comment by einpraegsam** [comment]
No, because I think the name of the extension (something with *mail*) could be the problem. And I don't want to rename the complete extension because chrome is buggy on this function.
