### ISSUE TITLE
Error in parsley.min.js

### ISSUE THREAD

**Issue by ronnyboenisch** [einpraegsam/powermail#95]
The current used version of parsley.min.js causes an error: "TypeError: t.options.classHandler is not a function". This affects others JS which is used on the page.

Using the latest version (2.7.2) of parsley.js will fix this.

**Comment by einpraegsam** [comment]
There was a bu in parsley.js 2.3 with blur events, but it seems that is fixed now. I updated to 2.7.2 in develop branch.
