### ISSUE TITLE
Field sorting ignored on frontend

### ISSUE THREAD

**Issue by nidema** [einpraegsam/powermail#96]
I'm working on TYPO3 8.7.1 and Powermail 3.19.0.
I added two fields (City and Province) to an existing form, the backend shows the fields with the correct order
![screen_backend](https://cloud.githubusercontent.com/assets/28921562/26398671/7b74a224-407a-11e7-8788-90fb0e006ba6.png)
But on frontend they are placed as last inside the page
![screen_frontend](https://cloud.githubusercontent.com/assets/28921562/26398712/97ef14f2-407a-11e7-85bb-29a51654f705.png)
Looks like the frontend is ignoring the sorting value.

**Comment by einpraegsam** [comment]
Pls open the related form and open the related pages inline in within the page inline the fields. What about the field sorting in this view?

**Comment by einpraegsam** [comment]
No reaction, so I will close this issue for now.
