### ISSUE TITLE
Sorting of export fields get lost after page reload 

### ISSUE THREAD

**Issue by mediaessenz** [einpraegsam/powermail#97]
If you sort, remove or add fields in the extended export settings and reload the backend module (or only change e.g. to reporting view of the same module), all export setting are lost.

At least the possibility (e.g. by tsconfig) to define the initial order of the fields would be fantastic.
A little budget (100 EUR) would be available.

**Comment by einpraegsam** [comment]
The focus at the moment is to increase main stability. Maybe in future...

**Comment by mediaessenz** [comment]
Wouldn't it be better to change this issue to feature (request) instead of closing it?
Doing this it would be possible to me (or others) to contribute this function by a pull request with an reference to the issue number.
