### ISSUE TITLE
export to csv file

### ISSUE THREAD

**Issue by format-gmbh** [einpraegsam/powermail#98]
I would like to export the mails to a csv file. But this file is empty. I have tried the planner and the backend module. The export to xls file runs correctly.
I use the default templates and partials.
TYPO3 8.7.1 / powermail 3.19.0

**Comment by einpraegsam** [comment]
I don't know why but the Utf8ToUtf16ViewHelper seems to break the export. Removing this from the View in EXT:powermail/Resources/Private/Templates/Module/ExportCsv.html fix the issue. 
The viewhelper was introduced somewhere in the past to support German umlauts for Excel. Can you remoe it for testing and give me feedback pls?

**Comment by format-gmbh** [comment]
Yes, that solved the problem. But the output looks as follows:
&quot;Firma&quot;;&quot;Name&quot;;&quot;E-Mail&quot;;&quot;Telefon&quot;;&quot;Ihre Nachricht&quot;;

**Comment by format-gmbh** [comment]
Sorry:
`&quot;Firma&quot;;&quot;Name&quot;;&quot;E-Mail&quot;;&quot;Telefon&quot;;&quot;Ihre Nachricht&quot;;`

**Comment by einpraegsam** [comment]
It's getting more strange now. In 7.6 the export works as expected...

**Comment by einpraegsam** [comment]
I think a found a solution. Thx for your report.
