### ISSUE TITLE
Nach Update auf TYPO3 7.6.18 HTML-Form-Elemente funktionieren nicht mehr

### ISSUE THREAD

**Issue by jhamecher** [einpraegsam/powermail#99]
Hallo werte Entwickler,

wir haben das Problem, das nach dem Update nur noch der HTML-Code, des HTML-Formular-Elementes, auf der Seite zu sehen ist.

Was können wir machen?

Viele Grüße
Johannes

**Comment by einpraegsam** [comment]
Pls write in english to be helpful for the community.
Try to use original HTML-Templates, Partials and Layouts.

**Comment by Patta** [comment]
@jhamecher read the changelog before upadeting.

**Comment by einpraegsam** [comment]
Changelog: https://docs.typo3.org/typo3cms/extensions/powermail/Changelog/Index.html
See breaking changes in 3.18.0
